### ISSUE TITLE
model and parameters' bootstrapping

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#1]
vignettes idea: 

1) comparison of bootstrapped and freq point-estimates parameters
2)  boostrapped and bayesian parameters

**Comment by DominiqueMakowski** [comment]
@mattansb About bootstrapping in general, since you recently wrote a post on it. Maybe you'd like to take a look at the `model_bootstrap` function that we plan to include in this package :)

**Comment by mattansb** [comment]
A vignette about why and when you'd want to use bootstrapping methods?

**Comment by DominiqueMakowski** [comment]
For instance, but first, we would need to improve the `model_bootstrap` function, which is a wrapper to easily get bootstrapped parameters for different kinds of models

**Comment by DominiqueMakowski** [comment]
Closing for now, though the documentation needs improvement
