### ISSUE TITLE
model_parameters(), mixed models and new models

### ISSUE THREAD

**Issue by strengejacke** [easystats/parameters#101]
I have re-organized the code a bit and added support for a lot more models, i.e. many more models now work with `p_value()`, `ci()`, `standard_error()`, `standardize()` and `model_parameters()`.

I have also tried to find some generic approaches. These mainly evolve around `model_parmaters.polr()` for models that do not have a proper `update()` method (so standardizing won't work), or `model_parameters.lme()` (for models that can be standardized).

The `model_parameters.xxx()` then calls `.extract_parameter_generic()`, which in turn just calls p_value(), standard_error() and ci(). So once we have these three working, we can simply add model_parameters for any other model.

**One thing we might implement in the future**: Information about random effects from mixed models (coefficients, standard errors / ci). I think this is less important for now, but nice to have in the future. For `model_parameters()`, we could at least provide some core-information like SD of random effects or so, similar to what is provided in the related `summary()`.

**Comment by strengejacke** [comment]
@DominiqueMakowski in particular pinging you here...

**Comment by strengejacke** [comment]
Ok, now we have already a lot of models supported here. Following models / packages I'm trying to add in the near or far future:

- [ ] biglm / bigglm
- [ ] censReg
- [ ] coxme
- [ ] crch
- [ ] Gam (pkg gam)
- [ ] gamm / gamm4 (not sure if this already works?)
- [ ] gbm
- [ ] gee / geeglm
- [ ] lmRob / glmRob
- [ ] lmrob / glmrob
- [ ] iv_robust
- [ ] ivreg
- [ ] lm_robust
- [ ] logistf
- [ ] multgee
- [ ] quantreg
- [ ] speedlm / speedglm
- [ ] tobit
- [ ] vgam / vglm

**Comment by DominiqueMakowski** [comment]
I have missed this, great job 🥇  a true challenger to broom in the making 😏 On my side I'll first try (tomorrow) to write the announcement blogpost for the initial CRAN release, then I'll slowly get back to every issue. Let me know if there's anything in particular I can help for the extension of support!

**Comment by strengejacke** [comment]
It would be great if you can figure out https://github.com/easystats/parameters/issues/102 and https://github.com/easystats/parameters/issues/103.

I was always focussing on following methods when implementing a new model:
- `p_value()`
- `standard_error()`
- `ci()`
- `.get_statistic()` (which I also mirrored to `insight::get_statistic()` for future use)
- `model_parameters()`
- `standardize()`
- `model_simulate()`
- (and `parameters_simulate()` works automatically once `model_simulate()` is working)

I _think_ the bootstrapping option will fail for some models. Not sure how we can deal with this, as some models simply don't provide a working `update()` function. So, functions I did not touch (and where support for more model classes is not yet added) are:
- `model_bootstrap()`
- `parameters_bootstrap()`
- partly, `standardize.model()` / `parameters_standardize()` will not work
- `parameters_selection()`

So, all the "Parameters Engineering" stuff is not yet fully supported.

**Comment by strengejacke** [comment]
@DominiqueMakowski What do you think about setting `standardize` to `FALSE` by default for `model_parameters()`? Especially for mixed models, refitting may take some time, which may result in "unexpected" behaviour or confusion ("will the method response, or is it frozen?").

**Comment by DominiqueMakowski** [comment]
To FALSE or maybe to "smart" (posthoc algorithm)?
