### ISSUE TITLE
print for model_parameters from gam(m)-models

### ISSUE THREAD

**Issue by strengejacke** [easystats/parameters#103]
@DominiqueMakowski Parameter names are missing for gam-objects...

``` r
library("parameters")
library("mgcv")
#> Loading required package: nlme
#> This is mgcv 1.8-28. For overview type 'help("mgcv-package")'.
    
set.seed(123)
dat <- gamSim(1, n = 400, dist = "normal", scale = 2)
#> Gu & Wahba 4 term additive model
model <- gam(y ~ s(x0) + s(x1) + s(x2) + s(x3), data = dat)
    
model_parameters(model)
#> # Conditional component
#> 
#> Parameter   | Coefficient |   SE |     95% CI |      p
#> ------------------------------------------------------
#> (Intercept) |        7.97 | 0.10 | 7.77, 8.17 | < .001
#> 
#> # Smooth Terms component
#> 
#> Parameter | Coefficient |      p
#> --------------------------------
#>           |        3.63 | < .001
#>           |        2.97 | < .001
#>           |        8.30 | < .001
#>           |        1.05 | < .01
```

<sup>Created on 2019-09-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DominiqueMakowski** [comment]
I do remember seeing the discussion somewhere related to the fact that the statistic is either t or F. Is there a way to find that and label it accordingly instead of `t / F`?

Will take a look at the parameter issue

**Comment by strengejacke** [comment]
>  Is there a way to find that and label it accordingly instead of t / F?

I think it relates in particular to gam models, where the fixed effects have a t-statistic, while the smooth terms have an F-statistic.

**Comment by DominiqueMakowski** [comment]
I understand, but since the printing method splits the two dataframes, couldn't we adjust the names?

**Comment by strengejacke** [comment]
Yes, I just thought it would be a hassle work and had no motivation doing it ;-)
The statistic is saved as attribute, so you have to check especially for smooth terms, and then fix the print-stuff...

**Comment by DominiqueMakowski** [comment]
Okay I'll give it a go later!

**Comment by strengejacke** [comment]
I think parameters is in a really good shape. Actually, I think for the next update we can concentrate on supporting more models and making existing functions more robust if we detect any issues. There is already a lot of this work done. So, once bayestestR is updated on CRAN we can indeed ship another update for parameters as well, or do you think there are essential features missing for the next update?

**Comment by DominiqueMakowski** [comment]
Totally agree with you. Once basic functionalities are there (i.e., `model_parameters`), we can then slowly work on improving the more exploratory/novel ones for features engineering, reduction etc.

**Comment by DominiqueMakowski** [comment]
Looking into the implementation, I understand now why the the `t / F` is problematic ^^

**Comment by DominiqueMakowski** [comment]
Fixed it, but wondering about the case of logistic gams... Will it still be a t? or a z?

``` r
library(parameters)
library(mgcv)

dat <- gamSim(1, n = 400, dist = "normal", scale = 2)
#> Gu & Wahba 4 term additive model
model <- gam(y ~ s(x0) + s(x1) + s(x2) + s(x3), data = dat)
model_parameters(model)
#> # Conditional component
#> 
#> Parameter   | Coefficient |   SE |     95% CI |     t |      p
#> --------------------------------------------------------------
#> (Intercept) |        7.61 | 0.10 | 7.40, 7.81 | 73.95 | < .001
#> 
#> # Smooth Terms component
#> 
#> Parameter        | Coefficient |     F |      p
#> -----------------------------------------------
#> Smooth term (x0) |        7.46 |  5.99 | < .001
#> Smooth term (x1) |        2.70 | 91.65 | < .001
#> Smooth term (x2) |        7.53 | 70.62 | < .001
#> Smooth term (x3) |        1.57 |  0.54 | > .1
```

<sup>Created on 2019-09-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
``` r
library(mgcv)
#> Loading required package: nlme
#> This is mgcv 1.8-28. For overview type 'help("mgcv-package")'.
## now simulate poisson data...
set.seed(6)
dat <- gamSim(1,n=2000,dist="poisson",scale=.1)
#> Gu & Wahba 4 term additive model

## use "cr" basis to save time, with 2000 data...
b2<-gam(y~s(x0,bs="cr")+s(x1,bs="cr")+s(x2,bs="cr")+
          s(x3,bs="cr"),family=poisson,data=dat,method="REML")
summary(b2)
#> 
#> Family: poisson 
#> Link function: log 
#> 
#> Formula:
#> y ~ s(x0, bs = "cr") + s(x1, bs = "cr") + s(x2, bs = "cr") + 
#>     s(x3, bs = "cr")
#> 
#> Parametric coefficients:
#>             Estimate Std. Error z value Pr(>|z|)    
#> (Intercept)  0.78784    0.01545   50.99   <2e-16 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> Approximate significance of smooth terms:
#>         edf Ref.df  Chi.sq p-value    
#> s(x0) 1.705  2.123   1.550   0.462    
#> s(x1) 2.534  3.152 178.691  <2e-16 ***
#> s(x2) 7.458  8.403 383.732  <2e-16 ***
#> s(x3) 1.002  1.004   0.029   0.865    
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> R-sq.(adj) =  0.228   Deviance explained = 19.9%
#> -REML = 3538.4  Scale est. = 1         n = 2000
```

<sup>Created on 2019-09-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
z and chisq, obviously? At least for poisson... :-)

And, just checked, same for binomial

``` r
library(mgcv)
#> Loading required package: nlme
#> This is mgcv 1.8-28. For overview type 'help("mgcv-package")'.
## now simulate poisson data...
set.seed(6)
dat <- gamSim(1,n=2000,dist="binary",scale=.1)
#> Gu & Wahba 4 term additive model

## use "cr" basis to save time, with 2000 data...
b2<-gam(y~s(x0,bs="cr")+s(x1,bs="cr")+s(x2,bs="cr")+
          s(x3,bs="cr"),family=binomial(),data=dat,method="REML")
summary(b2)
#> 
#> Family: binomial 
#> Link function: logit 
#> 
#> Formula:
#> y ~ s(x0, bs = "cr") + s(x1, bs = "cr") + s(x2, bs = "cr") + 
#>     s(x3, bs = "cr")
#> 
#> Parametric coefficients:
#>             Estimate Std. Error z value Pr(>|z|)    
#> (Intercept)  0.27039    0.04572   5.914 3.35e-09 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> Approximate significance of smooth terms:
#>         edf Ref.df Chi.sq p-value    
#> s(x0) 2.660  3.308  8.360  0.0519 .  
#> s(x1) 1.883  2.352  6.846  0.0436 *  
#> s(x2) 3.856  4.752 36.812 7.2e-07 ***
#> s(x3) 1.001  1.002  2.577  0.1087    
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> R-sq.(adj) =  0.0253   Deviance explained = 2.23%
#> -REML = 1352.5  Scale est. = 1         n = 2000
```

<sup>Created on 2019-09-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DominiqueMakowski** [comment]
Should we deal with this at insight's level (get_statistic) to come up with some generic solution?

**Comment by strengejacke** [comment]
How could this look like? Since `insight::get_statistic()` is just a copy what we currently have in parameters, it returns the statistic as attribute. We _could_ add another column, that simply would contain the "statistic" for each parameter (which is in most cases always the same, except for gams).

**Comment by DominiqueMakowski** [comment]
or a named list as attribute, similar to how pretty_names are stored?

**Comment by strengejacke** [comment]
Haven't looked into the pretty_names implementation, but that sounds good!

**Comment by strengejacke** [comment]
The main issue is resolved. We can fix remaining labelling of the statistic column once we have it more detailled in _insight_.
