### ISSUE TITLE
parameters_standardize for logistic models

### ISSUE THREAD

**Issue by mattansb** [easystats/parameters#107]
Looking at the code for `parameters_standardize`, it looks like when a non-linear model is used, the coefs are standardized (in the post-hoc method/s) only on x. Is this correct? If so, I couldn't find this explanation anywhere in the docs...

**Comment by DominiqueMakowski** [comment]
That is correct, as log-odds are already "scaled", so basically they just need to be scaled in regards to x. In other words, as y is, for instance, a binary vector, doesn't make really sense to scale it.

This functioning is based on logistic models, but not sure if they are exceptions to other non-linear models...

**Comment by strengejacke** [comment]
There are some type of response variables that cannot be standardized:
- logistic (binary outcome)
- count models (poisson, ...)
- ratios (beta-reg)
- survival-models
- probably some more...

Maybe most regression models except models with continuous outcome (linear alike).

Or wasn't that the question?

**Comment by mattansb** [comment]
(Answering as I pack)
I just meant that if this is the case, this should be made explicit in  the
docs (:

--
Mattan S. Ben-Shachar, PhD student
Department of Psychology & Zlotowski Center for Neuroscience
Ben-Gurion University of the Negev
The Developmental ERP Lab

**Comment by DominiqueMakowski** [comment]
So I think the default behaviour not to scale by y in non-linear models is safe. I'll add this to the docs

@mattansb stop githubing and enjoy your easyvacations already! :)

**Comment by mattansb** [comment]
That's so weird, that's what my wife said!
Alright, byyyyeeeee

--
Mattan S. Ben-Shachar, PhD student
Department of Psychology & Zlotowski Center for Neuroscience
Ben-Gurion University of the Negev
The Developmental ERP Lab

**Comment by DominiqueMakowski** [comment]
aktchually it is mentioned is `standardize`'s help for models:

> @param include_response Logical, if \code{TRUE} (default), the response value
#'   will also be standardized. For certain models (logistic regression,
#'   count models, ...), the response value will never be standardized, to make
#'   re-fitting the model work.

And it's also mentioned throughout the methods in parameters_standardize that most of them do not change binary variables (and thus the outcome)... Closing this, feel free to add this information more explicitly somewhere if you have an idea how 😉
