### ISSUE TITLE
reorganize documentation

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#118]
example structure:

- Parameters description
  - model_parameters()
- Variables reduction
  - parameters_reduction()
  - PCA
  - Factor analysis (EFA / CFA)
- Parameters selection
  - parameters_selection()
- Parameters Engineering
  - Bootstrapping
  - Standardization

**Comment by strengejacke** [comment]
you mean the website?

**Comment by DominiqueMakowski** [comment]
yup (mainly a note to myself to not forget  ^^)

**Comment by strengejacke** [comment]
What's the status of this issue, can we close it?

**Comment by DominiqueMakowski** [comment]
I'd still like to streamline the README

**Comment by strengejacke** [comment]
ok. I have checked sjPlot with the new _parameters_ and everything works fine. Was quite easy to replace broom::tidy() by parameters::model_parameters(). I _think_ that there's not much more to do (beside fixing check issues), or do you see any critical points left?

**Comment by DominiqueMakowski** [comment]
Yup, I think it's already a thick update ☺️

**Comment by strengejacke** [comment]
Indeed, though many of the updates are rather "invisible" to users. ;-)

**Comment by strengejacke** [comment]
From `?p_value`:

> Description
This function attempts to return, or compute, p-values of a model's parameters. The nature of the p-values is different depending on the model:

> Mixed models (lme4): TO BE IMPROVED.

What did you intend to write?

**Comment by DominiqueMakowski** [comment]
I don't know, I suppose more info about the methods for estimating p-values for mixed models...
