### ISSUE TITLE
CRAN 0.2

### ISSUE THREAD

**Issue by strengejacke** [easystats/parameters#119]
What should be addressed for the next update?

- [x] #114 
- [x] #118 
- [x] ~#110~
- [x] ~#92~
- [x] #121 
- [x] #123 
- [x] #124

**Comment by strengejacke** [comment]
I would leave #92 for later. It's not critical, and I have to look into it in more detail. #110 is something I would like to see someelse to address, as I'm not good at ANOVA stuff.

**Comment by DominiqueMakowski** [comment]
We could make a call on twitter or something, seeking for someone, and not necessarily an R expert, with some better understanding of ANOVAs and DFs and stuff? Or directly contact some authors of papers on the subject?

**Comment by strengejacke** [comment]
the `method`-argument in `standarize()` needs a better description, @DominiqueMakowski can you address this?

**Comment by strengejacke** [comment]
Do you think we can submit an update in the next days, probably within this week? I need to update sjPlot, and would like to use the updated _parameters_ in sjPlot instead of broom.

**Comment by DominiqueMakowski** [comment]
Yes, especially since the CRAN version errors due to latest bayestestR:

"Please correct before 2019-10-08 to safely retain your package on CRAN."

**Comment by strengejacke** [comment]
Ok, got the same email.

**Comment by strengejacke** [comment]
Fixed some check issues, some typos and updated website... Let's see if Travis values our effort.

**Comment by strengejacke** [comment]
Can codecov be the reason why Travis fails?

```
$ travis_wait 30 Rscript -e 'covr::codecov()'
Still running (1 of 30): Rscript -e covr::codecov()
The job exceeded the maximum time limit for jobs, and has been terminated.
```

**Comment by strengejacke** [comment]
I uploaded to win-builder, let's see if there are any critical check issues left (I don't think so...)

**Comment by DominiqueMakowski** [comment]
https://win-builder.r-project.org/ZMIUn5VCv86P
The files will be removed after roughly 72 hours.
Installation time in seconds: 12
Check time in seconds: 366
Status: 2 ERRORs, 1 WARNING

https://win-builder.r-project.org/1e6Ww6J1542A
The files will be removed after roughly 72 hours.
Installation time in seconds: 2
Check time in seconds: 21
Status: 1 ERROR

**Comment by DominiqueMakowski** [comment]
-- 1. Failure: ci (@test-MCMCglmm.R#17)  ---------------------------------------
  ci(m1)$CI_low not equal to c(0.976294, 0.034227).
  2/2 mismatches (average diff: 0.00159)
  [1] 0.9793 - 0.9763 ==  0.002999
  [2] 0.0341 - 0.0342 == -0.000173
  
  -- 2. Failure: se (@test-MCMCglmm.R#25)  ---------------------------------------
  standard_error(m1)$SE not equal to c(0.024089, 0.005111).
  2/2 mismatches (average diff: 0.000554)
  [1] 0.02312 - 0.02409 == -0.000964
  [2] 0.00497 - 0.00511 == -0.000144
  
  -- 3. Failure: model_parameters (@test-MCMCglmm.R#41)  -------------------------
  model_parameters(m1)$Median not equal to c(1.013152, 0.042433).
  2/2 mismatches (average diff: 0.00137)
  [1] 1.0152 - 1.0132 ==  0.002025
  [2] 0.0417 - 0.0424 == -0.000713
  == testthat results  ===========================================================
  [ OK: 254 | SKIPPED: 1 | WARNINGS: 9 | FAILED: 3 ]
  1. Failure: ci (@test-MCMCglmm.R#17) 
  2. Failure: se (@test-MCMCglmm.R#25) 
  3. Failure: model_parameters (@test-MCMCglmm.R#41) 
  
  Error: testthat unit tests failed
  Execution halted
* checking PDF version of manual ... OK
* DONE
Status: 2 ERRORs, 1 WARNING

Increased tol should fix it

**Comment by strengejacke** [comment]
Or skip mcmcglmm tests on CRAN.

**Comment by DominiqueMakowski** [comment]
I think we're pretty much set

**Comment by strengejacke** [comment]
Ok, submit? ✔️ from me

**Comment by strengejacke** [comment]
Do we want to increase the version to 0.2.0?

**Comment by DominiqueMakowski** [comment]
Yes, I'll make a PR with 0.2.0, that I will submit and that we will merge ***once*** it is accepted ^^, so I can tag a release :)

**Comment by strengejacke** [comment]
very nice work on the new documentation, btw!

**Comment by DominiqueMakowski** [comment]
Meh I didn't see you bumped the version on master 😠 okay, nevermind, I am submitting ☺️ 

> very nice work on the new documentation, btw!

Can be further improved, but at least we have a basis :)

**Comment by strengejacke** [comment]
> Meh I didn't see you bumped the version on master

🚀

**Comment by DominiqueMakowski** [comment]
submitted

**Comment by DominiqueMakowski** [comment]
"On its way to CRAN" 🎉  Should we write a small blogpost advertising the extension of support?

**Comment by strengejacke** [comment]
replacing broom by parameters really reduced the code by some lines...
https://github.com/strengejacke/sjPlot/commit/c747994862f7097f013d7a1cbf09041b473731e4 :-)
