### ISSUE TITLE
plot method for n_factors

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#121]
Something like that:

```r
library(tidyverse)
nfactors <- parameters::n_factors(mtcars)

x <- data.frame(n_Factors = 1:max(nfactors$n_Factors),
                n_Methods = 0)

nfactors %>%
  summary() %>%
  rbind(x[!x$n_Factors %in% summary(nfactors)$n_Factors, ]) %>%
  mutate(n_Methods = n_Methods / sum(n_Methods) * 100) %>%
  ggplot(aes(x = n_Factors, y = n_Methods, group = 1)) +
  geom_area(fill = "#2196F3") +
  see::theme_modern() +
  ylab("Aggreement between methods (%)") +
  xlab("Number of Factors") +
  scale_x_continuous(breaks = 1:max(nfactors$n_Factors))
```

![image](https://user-images.githubusercontent.com/8875533/65474055-f5238e00-deac-11e9-89fd-c825aee4ff72.png)

**Comment by strengejacke** [comment]
```r
library(ggplot2)
library(parameters)

data(mtcars)
nfactors <- n_factors(mtcars)

s <- summary(nfactors)
x <- data.frame(n_Factors = factor(1:max(nfactors$n_Factors)), n_Methods = 0)
s <- rbind(s, x[!x$n_Factors %in% s$n_Factors, ])

s$n_Factors <- factor(s$n_Factors, levels = rev(sort(levels(s$n_Factors))))
s$n_Methods <- s$n_Methods / sum(s$n_Methods)
s$group <- "0"
s$group[which.max(s$n_Methods)] <- "1"

ggplot(s, aes(x = n_Factors, y = n_Methods, colour = group)) + 
  geom_segment(aes(y = 0, xend = n_Factors, yend = n_Methods)) +
  geom_point() +
  labs(
    x = "Number of Factors",
    y = "Agreement between methods (%)", 
    title = "Number of factors supported by most Methods"
  ) +
  coord_flip() +
  guides(colour = FALSE) +
  scale_y_continuous(labels = scales::percent) +
  see::theme_modern() +
  see::scale_color_material()
```

![image](https://user-images.githubusercontent.com/26301769/65510821-1e0c4900-ded6-11e9-9036-0318c9dacc54.png)

**Comment by DominiqueMakowski** [comment]
```r
nfactors <- parameters::n_factors(mtcars, package = "all")
plot(nfactors) +
  theme_modern()
```
![image](https://user-images.githubusercontent.com/8875533/65563671-f1f7d300-df7c-11e9-87a8-164d457bb7f9.png)


I've refactored it a bit to make it horizontal with the area. The idea is that it mimics some sort of "distribution" of values. I.e., with even more methods I believe they would nicely converge toward a particular number of factors in a probabilistic way.

**Comment by strengejacke** [comment]
😱 

so why do you prefer an "area" for something that is discrete and much easier to grasp with a simpler line plot I suggested?

**Comment by strengejacke** [comment]
> with even more methods

But we don't have "1.15326 methods suggest that...". That always reminds me of the election battle in, I think 2002?, where Schröder mocked about his opponents talking about the "1.27 children a family has" or something like that ;-)

**Comment by DominiqueMakowski** [comment]
😠

**Comment by DominiqueMakowski** [comment]
The middle ground would be a thick bar chart (vertical) that would accurately represent the discrete nature, but also looking a bit like a histogram (which would satisfy my probabilistic perspective)

**Comment by strengejacke** [comment]
Or we add a "style" argument, which lets the user decide which style to plot?

**Comment by strengejacke** [comment]
> Minimalist is the new maximalist

(https://github.com/easystats/see/issues/39#issuecomment-515471399)

**Comment by strengejacke** [comment]
Added a `type`-option, like we have for some other plot-methods already...

https://easystats.github.io/see/articles/parameters.html#number-of-componentsfactors-to-retain

ok?

**Comment by DominiqueMakowski** [comment]
that looks like an overshot haha but okay, I suggest to make area default tho :grin:

**Comment by strengejacke** [comment]
> I suggest to make area default tho

:suspect:

**Comment by DominiqueMakowski** [comment]
![image](https://user-images.githubusercontent.com/8875533/66017457-80380000-e50d-11e9-8751-51686fb4d4a2.png)

**Comment by strengejacke** [comment]
I still think that lollipop plots are the best way to plot this...

**Comment by DominiqueMakowski** [comment]
😠 😠

**Comment by strengejacke** [comment]
``` r
library(easystats)
#> # Attaching packages
#> <U+2714> insight     0.5.0.9000   <U+2714> bayestestR  0.3.0     
#> <U+2714> performance 0.3.0.9000   <U+2714> parameters  0.2.0.1   
#> <U+2714> see         0.2.1.9000   <U+2714> correlation 0.1.0     
#> <U+2714> estimate    0.1.0        <U+2714> report      0.1.0

nfactors <- n_factors(mtcars, package = "all")
#> Registered S3 methods overwritten by 'huge':
#>   method    from   
#>   plot.sim  BDgraph
#>   print.sim BDgraph
plot(nfactors) + theme_modern()
```

![](https://i.imgur.com/ZT62SJw.png)

``` r
plot(nfactors, type = "line") + theme_modern()
```

![](https://i.imgur.com/6uPW7Q1.png)

``` r
plot(nfactors, type = "area") + theme_modern()
```

![](https://i.imgur.com/46sph68.png)

<sup>Created on 2019-10-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


🥂

**Comment by DominiqueMakowski** [comment]
overcomplexification but okay ^^

**Comment by strengejacke** [comment]
Yes, but a "hidden gem" in a package is ok. ;-)

**Comment by DominiqueMakowski** [comment]
haha true
