### ISSUE TITLE
robust standard errors

### ISSUE THREAD

**Issue by strengejacke** [easystats/parameters#122]
currently implemented in `sjstats::robust()`, we could implement robust SE in _parameters_ as well, as it's an often requested feature.

Downside: limited to some models (supported by the _sandwich_ package), and increased number of arguments (unless we add a new, separate method, but including in `standard_error()` would be more generic).

**Comment by DominiqueMakowski** [comment]
I agree that having that as an argument in `standard_error` is probably better
