### ISSUE TITLE
`method`-argument in `standarize()` needs a better description

### ISSUE THREAD

**Issue by strengejacke** [easystats/parameters#124]
the `method`-argument in `standarize()` needs a better description, @DominiqueMakowski can you address this?

_Originally posted by @strengejacke in https://github.com/easystats/parameters/issues/119#issuecomment-534620403_

**Comment by strengejacke** [comment]
What I _actually_ thought was explaining the different available options for `method`, which I'm not 100% certain what they all do in detail...

We have 

``` r
method <- match.arg(method, choices = c("default", "refit", "2sd", "smart", "partial", "classic"))
```

But refit, smart, partial and classic are not explained nor mentioned?

**Comment by DominiqueMakowski** [comment]
cause it's only in `parameters_standardize`... not sure why in this match.arg list

**Comment by strengejacke** [comment]
ah, got it! And there is comprehensive description in details... thanks for addressing this anyway, though there was not much to address. 🤣
