### ISSUE TITLE
n_clusters

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#130]
since we have n_factors we might as well think about the possibility for n_clusters

and possibly check_clusterstructure (similar to check_factorstructure) if such thing makes sense

useful links:
https://towardsdatascience.com/10-tips-for-choosing-the-optimal-number-of-clusters-277e93d72d92

**Comment by strengejacke** [comment]
see https://strengejacke.github.io/sjPlot/reference/sjc.elbow.html and https://strengejacke.github.io/sjPlot/reference/sjc.kgap.html

**Comment by DominiqueMakowski** [comment]
And for univariate distributions: https://stats.stackexchange.com/questions/138223/how-to-test-if-my-distribution-is-multimodal

**Comment by DominiqueMakowski** [comment]
`check_multimodal` might also be a possibility

**Comment by strengejacke** [comment]
Can we close this?

**Comment by DominiqueMakowski** [comment]
yes!
