### ISSUE TITLE
vignette standardization

### ISSUE THREAD

**Issue by strengejacke** [easystats/parameters#131]
> 2sd: Scaling by two 2 SDs
> Same as method = "refit", however, standardization is done by dividing by two times the SD or MAD (depending on robust). This method is useful to obtain coefficients of continuous parameters comparable to coefficients related to binary predictors (Gelman 2008).

Shouldn't it be _Same as method = **"smart"**_?

**Comment by DominiqueMakowski** [comment]
I *think* it currently does a "refit" as it runs `standardize(get_data(model), method = "2sd")`

**Comment by strengejacke** [comment]
Ah, ok. Haven't checked the code yet. I can look into detail when I'm in office in a few minutes

**Comment by strengejacke** [comment]
Yep, it uses refit.
