### ISSUE TITLE
print() style for t-test

### ISSUE THREAD

**Issue by strengejacke** [easystats/parameters#133]
We could have one row per group, not all results in one row. The STATA output looks ok, I think:
https://github.com/strengejacke/sjPlot/issues/189#issuecomment-283346562

**Comment by DominiqueMakowski** [comment]
The only limit I see is that it's hard to retrieve this information from the R's default t.test object... 

(That being said, if we implemented the rstan/brms-based t-test and correlation test in bayestestR (cf. https://github.com/bayesstuff/bfrms/ @mattansb), it would potentially give us more freedom for the results. Although that's probably a longterm idea)

**Comment by strengejacke** [comment]
Yes, but the information we have could be printed row-wise, and missing information like se/ci per group can be calculated using `parameters::standard_error()`. I think it's easier than expected.

**Comment by DominiqueMakowski** [comment]
while the printing could eventually be changed to the multiple lines indeed, I think we should keep the underlying dataframe as 1 row, because it's consistent with tidystuff and easystats stuff (one row per parameter, and a ttest estimates one parameter). 

would this formatted output have its place in report rather than parameters?

**Comment by strengejacke** [comment]
> while the printing could eventually be changed to the multiple lines indeed, I think we should keep the underlying dataframe as 1 row, because it's consistent with tidystuff and easystats stuff (one row per parameter, and a ttest estimates one parameter).

Agree.

> would this formatted output have its place in report rather than parameters?

I would expect the formatted output from `model_parameters()` print-method.

**Comment by strengejacke** [comment]
I think there is too little information to achieve this.
