### ISSUE TITLE
Effect size package?

### ISSUE THREAD

**Issue by strengejacke** [easystats/parameters#138]
We have quite some stuff dealing with effect sizes, conversion and ANOVA stuff. What do you think, does it make sense to separate these functions from _parameters_ and put them into an own package?

**Comment by DominiqueMakowski** [comment]
IMO effect sizes for models are closely related to parameters (being just scaleless parameters), so, for now, I'd say we can keep the handful of conversion functions here (as they are quite straightforward to maintain) and are a core aspect of the parameters engineering scope of the package. That being said, if we start to extend this aspect (for instance metaanalysis tools etc.) then that might become necessary indeed...

(but let's get the 3 remaining packages on CRAN before adding more 😅)

**Comment by DominiqueMakowski** [comment]
Mmh after spending my morning overthinking standardized parameters and all, I think you might be right. We could create a separate package containing methods for standardizing, converting and interpreting parameters (mainly move functions from here and from report). That would ease their subsequent inclusion in parameters and report. It would also be easier to document it there.

I'll create the new package, and copy the relevant functions *without* removing them from parameters and report until the package in on CRAN. We'll see how it works having this package separate.

This could go fast, as most functions work already. @strengejacke are you okay to take over parameters and be the one listed as maintainer?

**Comment by strengejacke** [comment]
I would probably leave standardization in parameters? Making effectsize a similar small package like correlation?

**Comment by DominiqueMakowski** [comment]
standardization is needed for effet sizes, but not needed for parameters. And it better fits there IMO. But as `effectsize` would be super light (no dependencies (not even suggested) aside from insight and (?) bayestestR), it's not a problem to import it in the others

**Comment by strengejacke** [comment]
True.

**Comment by strengejacke** [comment]
Although standardization is something I often use in modelling, while I actually never use effect size (conversion).
