### ISSUE TITLE
Remove dplyr deps

### ISSUE THREAD

**Issue by strengejacke** [easystats/parameters#14]
Why would we need `standardize.grouped_df()`? I think the results of standardizing won't differ, no matter if the df is grouped or not. Or do you have any counter-examples?

**Comment by DominiqueMakowski** [comment]
Yes, standardizing groupwise standardize the data within the groups so the mean and deviation is the same in each group, whereas general standardization preserves the deviation and mean differences between groups. (I wrote a small [post](https://neuropsychology.github.io/psycho.R/2018/07/14/standardize_grouped_df.html) about it 😄 )

**Comment by DominiqueMakowski** [comment]
And I think we won't be able to get rid off dplyr that easily, especially in the high-level packages, as it used at many places... but we can live with it now, and in the future, when the bulk of the work will be done (if ever haha), we will have time for polishing and optimizing :)

**Comment by strengejacke** [comment]
> Yes, standardizing groupwise standardize the data within the groups so the mean and deviation is the same in each group, whereas general standardization preserves the deviation and mean differences between groups. (I wrote a small [post](https://neuropsychology.github.io/psycho.R/2018/07/14/standardize_grouped_df.html) about it 😄 )

True; I just did this for computing mean, median and sd for subgroups in a data frame... :-/

Since the group-information is stored as attribute in the grouped data frame, we can write a small wrapper that replaces `dplyr::do()` here. For high level packages, we can keep the package dependency, but if possible, we should avoid this in our low level packages, unless we heavily rely on a certain package (which I don't see for dplyr in this particular case).

I'll draft a function and propose a PR later.
