### ISSUE TITLE
df_residual -> df_error

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#140]
``` r
as.data.frame(parameters::model_parameters(lm(Sepal.Length ~ Species, data = iris)))
#>           Parameter Coefficient         SE    CI_low  CI_high         t
#> 1       (Intercept)       5.006 0.07280222 4.8621258 5.149874 68.761639
#> 2 Speciesversicolor       0.930 0.10295789 0.7265312 1.133469  9.032819
#> 3  Speciesvirginica       1.582 0.10295789 1.3785312 1.785469 15.365506
#>   df_residual             p
#> 1         147 1.134286e-113
#> 2         147  8.770194e-16
#> 3         147  2.214821e-32
```

<sup>Created on 2019-10-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Currently the column is named `df_residual`. @mattansb, about the name of an argument in effectsize, said:

> because the df aren't of the residual, they are of the estimate error - in a linear model these are the same, but in any mixed effects model this isn't strictly true (you can argue that are random effects are themselves a kind of "residual", I guess...)

Should we rename the column to df_error? Or both to something else? (for mathematical accuracy, but foremost for consistency across the easyverse)?

**Comment by strengejacke** [comment]
Do we have other cases (functions) where this is relevant?

Let's do some brainstorming on what kind of different "df" types we have... df_residual, df_error, ...?

**Comment by mattansb** [comment]
`df_effect` and `df_error` (the error is sometimes based on the residuals, but not always)
Or `df1` and `df2`
Or `df_num` and `df_den`

z-tests have none.
Chi-square tests only have the first.
t-tests only have the second one.
F-tests have both.

**Comment by DominiqueMakowski** [comment]
df_error seems the most generic
