### ISSUE TITLE
adjusted p-values for multiple comparison

### ISSUE THREAD

**Issue by strengejacke** [easystats/parameters#141]
I think it's not that hard to implement adjusted p-values, since we have all the methods for different models. Below the code for the simple lm case, from the multcomp vignette.

```r
betahat <- coef(lm.cars)
Vbetahat <- vcov(lm.cars)
```
At first, we are interested in the hypothesis β1 = 0 and β2 = 0. This is equivalent to the linear hypothesis Kβ = 0 where K = diag(2), i.e.,

```r
K <- diag(2) # length of nrow(get_parameters())
Sigma <- diag(1 / sqrt(diag(K %*% Vbetahat %*% t(K))))
z <- Sigma %*% K %*% betahat
Cor <- Sigma %*% (K %*% Vbetahat %*% t(K)) %*% t(Sigma)
```

Note that z = (−2.6011, 9.464) is equal to the t statistics. The multiplicityadjusted p values can now be computed by means of the multivariate t distribution utilizing the pmvt function available in package mvtnorm:

```r
library("mvtnorm")
df.cars <- nrow(cars) - length(betahat)
sapply(abs(z), function(x) 1 - pmvt(-rep(x, 2), rep(x, 2), corr = Cor, df = df.cars))
#> [1] 1.661e-02 2.458e-12
```

(from: https://cran.r-project.org/web/packages/multcomp/vignettes/multcomp-examples.pdf)

**Comment by DominiqueMakowski** [comment]
What do you mean adjusting the p values? You mean supporting the multcomp package?

**Comment by strengejacke** [comment]
Yes, an own implementation for multiplicity adjustment

**Comment by DominiqueMakowski** [comment]
how would it be different from `stats::p.adjust`?

**Comment by strengejacke** [comment]
good question! Maybe just for more models working? Or testing different hypotheses (not only A = 0, but also A > B or so?)

Maybe this can wait a bit, I was just curious if I can use this approach in ggpredict for multiple comparison adjustments.

**Comment by DominiqueMakowski** [comment]
Wouldn't it be more in `estimate`, which does some recombination, specific tests etc?

**Comment by mattansb** [comment]
Its seems (but I might be completely wrong) that this method accounts for the covariance between the parameters, resulting in a multi-variate p-value, whereas `stats::p.adjust` preforms some adjustment on the p-value.

**Comment by DominiqueMakowski** [comment]
p.adjust is definitely different from multcomp (the former is very agnostic to what is provided and just adjust numbers based on some formulas) , hence I was not sure if the issue was about supporting multcomp or something else. From what I see, multcomp would be rather closer in spirit to emmeans? Mattan you're now the expert of emmeans it seems so you can tell 😁

**Comment by strengejacke** [comment]
I think it might be useful for both parameters and estimate. We have different type of results, coefficients and fitted values.

**Comment by mattansb** [comment]
It seems `emmeans` has some functions that call `multcomp` (`emmeans::as.glht`), but I've never used it...

**Comment by Generalized** [comment]
The **_emmeans_** package (for **E**stimated **M**arginal Means) reproduces the LS-Means (Least Squares Means) capabilities of SAS. Honestly, in the pharmaceutical industry it's **mandatory** to report LS-means every single time we do any kind of statistical modelling. Except for fully balanced designs, where the raw means = LS-means. **_emmeans_** handles both the Tukey contrast (all-pairwise comparisons) along with the Tukey's correction (via the Monte Carlo approximation of the multivariate t distribution, AFAIR) and Dunnett contrast (all-vs.-baseline) along with appropriate correction (the traditional one, using the MC multivariate t and own - faster, but less precise and not widely known approximation). **_multcomp_** also offers a lot in terms of multiple comparisons, also employing Tukey, Dunnet, Williams and other, specialized contrasts.

I am afraid, that reproducing those capabilities of emmeans and multcomp in the **_parameters_** may seriously confuse R users. Already now people ask "which one should I use, emmeans or multcomp"? All the more so as the output across them both isn't 100% consistent, which sometimes makes an issue, especially in validated environments.

**Comment by strengejacke** [comment]
> Adding a third option may only increase the confusion.

In general, I would say, yes. But here I was thinking of adjusted p-values for `summary()`, not for estimated marginal means. So, I think there's a slight difference - not sure, though, whether adjusted p-values for summary-outputs is usually done or not. Maybe this feature isn't that necessary as I initially thought it would be.

**Comment by strengejacke** [comment]
Just saw this package... I think, actually I was having something like [this package](https://github.com/IndrajeetPatil/pairwiseComparisons) in mind (ping @IndrajeetPatil )

**Comment by strengejacke** [comment]
I've implemented simple usage of `p.adjust()`, I think this is sufficient for now.

**Comment by iago-pssjd** [comment]
Maybe related to this issue. It seems that `model_parameters` does not support `multcomp::glht` output:
```
> m1<- glmmTMB(am ~ disp + hp + (1|carb), data = mtcars)
> glht(m1, linfct = matrix(c(0,1,-1),nrow=1))

	 General Linear Hypotheses

Linear Hypotheses:
        Estimate
1 == 0 -0.008652

> model_parameters(glht(m1, linfct = matrix(c(0,1,-1),nrow=1)))
Error in cs[, column_index] : incorrect number of dimensions
```
Would be this a possible feature?

**Comment by strengejacke** [comment]
These objects don't follow the "typical" model output, so it's probably of lower priority. However, we might implement support for such objects, if it fits into the design/api. But I suggest opening a new issue for this, else it will be forgotten...
