### ISSUE TITLE
Option for exact p-values

### ISSUE THREAD

**Issue by wmmurrah** [easystats/parameters#143]
The parameters() function is very useful. It would be preferable to have the option of printing exact p-values. Then people who do not like to use p-values in a dichotomous way could make better decisions with the output. By only presenting whether the p-value is above or below a threshold, information is lost in the output.

**Comment by strengejacke** [comment]
Do you prefer exact p-values also for value < 0.001?

**Comment by DominiqueMakowski** [comment]
Hum good point. The initial inspiration here and in other places were the APA guidelines. That being said, I personally do think it makes sense to display exact p-values (well, maybe not below .001, because otherwise with the rounding there is the risk of seeing things like `p = 0.00`  As I've already seen in papers and dissertations). 

It all boils down to adding the option to [format_p](https://github.com/easystats/parameters/blob/master/R/format_p.R)... We could add an argument like `exact` that would trigger this precise display. Or we could expand the `digits` argument, already common in many places. If `digits == NA` (or NULL), we show such categories, otherwise, exact numbers up to n digits.

**Comment by mattansb** [comment]
Some journal require exact p-values, and then they want *exact* - like, `p = 3.891e-19`.
I think for 1.000 < p < 0.001 we should display the rounded p-value, and for p < 0.001 we can display `p < 0.001` or if `exact = TRUE` we can show the full p-value `p = 3.891e-19`.

**Comment by DominiqueMakowski** [comment]
> Some journal require exact p-values, and then they want exact - like, p = 3.891e-19.

![](https://media.giphy.com/media/1M9fmo1WAFVK0/giphy.gif)

**Comment by mattansb** [comment]
![](https://media0.giphy.com/media/jPAdK8Nfzzwt2/source.gif)

**Comment by strengejacke** [comment]
Or we could add a `scientific`-option, that will replace the p-values with more exact scientific notation, somethin like

``` r
library(parameters)
model <- lm(mpg ~ wt + cyl, data = mtcars)
model_parameters(model)
#> Parameter   | Coefficient |   SE |         95% CI |     t | df |      p
#> -----------------------------------------------------------------------
#> (Intercept) |       39.69 | 1.71 | [36.18, 43.19] | 23.14 | 29 | < .001
#> wt          |       -3.19 | 0.76 | [-4.74, -1.64] | -4.22 | 29 | < .001
#> cyl         |       -1.51 | 0.41 | [-2.36, -0.66] | -3.64 | 29 | < .01

sprintf("%.5e", coef(summary(model))[, 4])
#> [1] "3.04318e-20" "2.22020e-04" "1.06428e-03"
```

<sup>Created on 2019-10-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DominiqueMakowski** [comment]
or this through `digits = "scientific"` (why have many different arguments when you can have flexible easy to remember ones)

**Comment by strengejacke** [comment]
> or this through `digits = "scientific"` (why have many different arguments when you can have flexible easy to remember ones)

But that would mean that we don't have "< 0.05" no more.

**Comment by mattansb** [comment]
IMO p values should not just reflect the cutoffs, but should be the actual number (for cutoffs we can add a stars column...?).
Okay, that's it from me on this (:

**Comment by strengejacke** [comment]
@wmmurrah is this implementation sufficient?

**Comment by DominiqueMakowski** [comment]
> IMO p values should not just reflect the cutoffs, but should be the actual number (for cutoffs we can add a stars column...?).

I agree, but then APA and stuff. I wonder if they changed that in the 7th edition?

**Comment by DominiqueMakowski** [comment]
> But that would mean that we don't have "< 0.05" no more

digits = "thresholds" ?

**Comment by wmmurrah** [comment]
This is great!
