### ISSUE TITLE
Custom approach to PCA?

### ISSUE THREAD

**Issue by pdwaggoner** [easystats/parameters#149]
Hi @DominiqueMakowski @strengejacke @mattansb - great work on the `principal_components()` function! 

I wonder, though, if we should consider a manual/custom calculation of PCs, scores, loadings, etc. more in line with the easystats approach, rather than depending on the base R `prcomp` function? It's not too onerous to build out and calculate PCs and all of the other things we want from them. Here is a simple example using the USArrests data from some code a colleague and I use to teach PCA to our students here. Let me know whether you'd like to "customize" the PC calculation a bit building on this simple case, or whether you'd like to stick with using `prcomp` - I am totally fine with either approach.

```{R}
# quick munging
scaled_df <- USArrests %>%
  rownames_to_column(var = "State") %>%
  as_tibble() %>% 
  mutate_at(.vars = vars(-State), scale)

# First - calulate the covariance matrix
arrests_cov <- scaled_df %>%
    select(-State) %>%
    cov()

# Second - calculate and store evs
(arrests_eigen <- eigen(arrests_cov))

# Third - extract first two loadings
phi <- arrests_eigen$vectors[, 1:2]
phi <- -phi
row.names(phi) <- c("Murder", "Assault", "UrbanPop", "Rape")
colnames(phi) <- c("PC1", "PC2")

# Finally - Calculate Principal Components scores (for the first two as an example...
PC1 <- as.matrix(select_if(scaled_df, is.numeric)) %*% phi[,1]
PC2 <- as.matrix(select_if(scaled_df, is.numeric)) %*% phi[,2]

# If desired, create data frame with Principal Components scores
(PC <- tibble(
  State = scaled_df$State,
  PC1 = PC1[,1],
  PC2 = PC2[,1]
))

# Now, visualize scores
ggplot(PC, aes(PC1, PC2)) + 
  geom_vline(xintercept = 0, size = 2, color = "black", alpha = .5) +
  geom_hline(yintercept = 0, size = 2, color = "black", alpha = .5) +
  geom_point() +
  ggrepel::geom_text_repel(aes(label = State)) +
  labs(title = "First two principal components of USArrests",
       x = "First principal component",
       y = "Second principal component")

# Or, visualize biplot
phi_df <- (phi * 1.75) %>%
  as.data.frame %>%
  rownames_to_column(var = "variable")

ggplot(PC, aes(PC1, PC2)) + 
  geom_vline(xintercept = 0, size = 2, color = "black", alpha = .5) +
  geom_hline(yintercept = 0, size = 2, color = "black", alpha = .5) +
  geom_point() +
  ggrepel::geom_text_repel(aes(label = State)) +
  geom_segment(data = phi_df,
               aes(x = 0, y = 0,
                   xend = PC1,
                   yend = PC2),
               arrow = arrow(length = unit(0.03, "npc")),
               color = "purple") +
  ggrepel::geom_text_repel(data = phi_df,
                           aes(x = PC1, y = PC2, label = variable),
                           color = "purple") +
  labs(title = "First two principal components of USArrests",
       x = "First principal component",
       y = "Second principal component")
```

**Comment by strengejacke** [comment]
Can you explain how this idea came into your mind? Is there something (information, attributes) missing  from the `prcomp()` function? I'm curious about the pro's for using this approach instead of the "simpler" `prcomp()`.

**Comment by pdwaggoner** [comment]
I guess there aren't any overt benefits to this approach compared to the `prcomp` approach, other than it would be a custom function rather than a reformatting of an existing function. I think the trick with this decision, as well as underlying the whole easystats framework, is balancing innovation with not reinventing the wheel. What that balance is exactly, I am unsure. But I was thinking this kind of a custom approach would give us a bit more flexibility and fewer dependencies, thereby more overtly contributing to the statistical programming landscape. But again, its already been done via `prcomp`, so perhaps my suggestion is unnecessarily complicating things. Just a thought.

**Comment by DominiqueMakowski** [comment]
> mutate_at(.vars = vars(-State), scale)

@pdwaggoner What is that?! Using `scale()` instead of `effectsize::standardize()`? 

 ![](https://media.giphy.com/media/12rsiyXAc9XVyE/giphy.gif)

Aside from that, while it's certainly an interesting exercise to "reverse" engineer prcomp to potentially have more control over it, or be more explicit about what it does, I wonder too what would be the other benefits 🤔 (especially since `prcomp` is quite well optimised in terms of speed)

**Comment by pdwaggoner** [comment]
Ha! @DominiqueMakowski forgive me and the grave oversight... It was a moment of easystats-lapse. A moment of weakness. 

But fair point. Like @strengejacke noted, there aren't benefits that I can see other than what you also mentioned ("potentially have more control over it, or be more explicit about what it does"). So we can pass on this. Just wanted to float it out there

**Comment by strengejacke** [comment]
Closing this, because I think I would not like to spend resources maintaining this due to lazyness and lack of time ;-)
