### ISSUE TITLE
CRAN 0.3.0

### ISSUE THREAD

**Issue by strengejacke** [easystats/parameters#156]
Now that _effectsize_ has been built on Windows, we can go on with sending updates. Today I will submit sjPlot, then parameters and then see. I think there are no urgent issues in parameters or see that need to be addressed now, or?

**Comment by DominiqueMakowski** [comment]
I think it's ready to go!

**Comment by strengejacke** [comment]
But does anyone have a good idea why parameters fails on Travis Linux?

**Comment by mattansb** [comment]
I thin we should push out all the pkgs to align with the changes due to `effectsize` now existing - if we can.

**Comment by DominiqueMakowski** [comment]
> But does anyone have a good idea why parameters fails on Travis Linux?

Weird, but timeouts can be related to their system rather than us

**Comment by strengejacke** [comment]
True, but since I have activated Linux on pretty much all packages I maintain, it's weird tha Linux fails just for parameters due to timeout.

**Comment by strengejacke** [comment]
Fixing authorship, sending to win-builder now (latest submit will contain two bug fixes, so re-checking now), then re-submit.

**Comment by strengejacke** [comment]
ok, checks seem to pass, @DominiqueMakowski you should get an email now to confirm me as new maintainer.

**Comment by DominiqueMakowski** [comment]
confirmed

**Comment by strengejacke** [comment]
on its way to CRAN!
