### ISSUE TITLE
check "factor_analysis()"

### ISSUE THREAD

**Issue by strengejacke** [easystats/parameters#159]
See https://github.com/easystats/parameters/commit/48cd17b40a365d39c7feb65653c3cf3a497ee062#commitcomment-35761166

**Comment by DominiqueMakowski** [comment]
alright alright I'm on it 😅

**Comment by strengejacke** [comment]
I don't think we need to do this for the current submission, so we only have a vague draft of this function in 0.3.0, but maybe until the next release, you can try to check if that function makes sense or not...
