### ISSUE TITLE
mixed models parameters

### ISSUE THREAD

**Issue by strengejacke** [easystats/parameters#160]
This pkg might be interesting: https://github.com/melff/iimm

**Comment by DominiqueMakowski** [comment]
What does it do?

**Comment by strengejacke** [comment]
It offers (fast) alternative to kenward-roger approximations, and also easy implementation of sattherthwaite approx.

**Comment by DominiqueMakowski** [comment]
Seems useful indeed...

**Comment by strengejacke** [comment]
Maybe useful for glmm:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4458010/

**Comment by strengejacke** [comment]
Ok the "quick Sattherthwaite" (aka m-l-1) method is implemented now.

1) Name could be better, currently we have `p_value_ml1()` and `dof_ml1()`.
2) Although the code implementation should give the same results as proposed in https://github.com/easystats/parameters/issues/160#issue-527085340, sometime there are really strange results (i.e. very strange approximation). But maybe that's actually the point of the m-l-1 heuristic? Must read the paper(s) more in detail. Maybe it's indeed better working for models with small clusters only...

**Comment by strengejacke** [comment]
should actually be implemented now...
