### ISSUE TITLE
Skewness and Kurtosis SEs

### ISSUE THREAD

**Issue by mattansb** [easystats/parameters#166]
Here is a pretty good review of different SEs: [https://doi.org/10.3758/s13428-010-0044-x](https://doi.org/10.3758/s13428-010-0044-x).

I think it would be useful (to add an option) to) provide one / some of these (the ones that give the same results as SPSS?) in the `skewness` and `kurtosis` functions.

**Comment by DominiqueMakowski** [comment]
agree!

> (the ones that give the same results as SPSS?)

I'd say, rather the best ones ☺️

**Comment by mattansb** [comment]
I wouldn't know either way- care to have a go at it?

**Comment by Generalized** [comment]
By the way, the e1071::skewness() provides three types of the estimator. Default is the Minitab one. Those, who work in the Pharmaceutical industry heavily use the type 2 for compliance with their SAS-based colleagues. The skewness() could just call the e1071 or implement the 3 types. I don't recall when I used the type 1 (implemented in **_parameters_**) for the last time...

**Comment by strengejacke** [comment]
Do I understand those formulas correctly, i.e. the SE is always the same for different variables, if these variables are of same length? So the SE only depends on the `n`, not on the skewness-value?

**Comment by mattansb** [comment]
Looks like yes - these are SEs under H0 for testing (but would be inappropriate for CIs, which no one does anyway).

**Comment by strengejacke** [comment]
ok, so the authors recommend / suggest bootstrapped SE's as an alternative. Do we need to implement this?

**Comment by mattansb** [comment]
I don't think we have to - most (all?) will probably use the basic ones a
la SPSS...

--
Mattan S. Ben-Shachar, PhD student
Department of Psychology & Zlotowski Center for Neuroscience
Ben-Gurion University of the Negev
The Developmental ERP Lab

**Comment by DominiqueMakowski** [comment]
🤔 🤔 🤔 depends on how tedious it is to add it?

**Comment by strengejacke** [comment]
The basic ones are implemented (but commented out, as I think these are useless, because they're are the same for different skewness/kurtosis values). I would say we could use bootstrapped SE's, which shouldn't be too hard

**Comment by mattansb** [comment]
a good use for `requireNamespace`!

```R
skewness.numeric <- function(x, na.rm = TRUE, type = "2", bootstrap_iterations = NA, ...) {

  # ...

  if (!is.na(bootstrap_iterations)) {
    if (!requireNamespace("boot", quietly = TRUE)) {
      warning("Package 'boot' needed for bootstrapping SEs. Using parametric method.")
    }

    results <- boot::boot(data = x, R = bootstrap_iterations, ...,
                          statistic = function(.x) {
                            skewness.numeric(.x, na.rm = na.rm, type = type, bootstrap_iterations = NA, ...)
                          })

    .skewness_se <- sd(results$t)
  }
}
```

**Comment by strengejacke** [comment]
``` r
library(parameters)
for (i in iris[, 1:4]) {
  print(skewness(as.numeric(i), iterations = 1000))
  cat("\n")
}
#> Skewness |    SE |         95% CI
#> ---------------------------------
#> 0.315    | 0.134 | [0.053, 0.577]
#> 
#> Skewness |    SE |          95% CI
#> ----------------------------------
#> 0.319    | 0.174 | [-0.023, 0.660]
#> 
#> Skewness |    SE |           95% CI
#> -----------------------------------
#> -0.275   | 0.137 | [-0.543, -0.007]
#> 
#> Skewness |    SE |          95% CI
#> ----------------------------------
#> -0.103   | 0.122 | [-0.342, 0.136]
```

<sup>Created on 2020-03-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mattansb** [comment]
I think the "standard" methods should be available to users (I think ~SPSS~ new users would expect these, no?) - we can strongly recommend using the boot and cite the paper in the beginning of this thread?

I also suggest that both functions will always return SEs, and that they will be two column data frames instead of numerics with an attribute. This will also make the matrix / data.frame methods easier to implament.

@strengejacke If that okay with you, I'll get it done (:

**Comment by mattansb** [comment]
Will look like this:

``` r
library(parameters)

x <- rnorm(100)
skewness(x, iterations = 50)
#> Skewness |    SE
#> ----------------
#> 0.187    | 0.291
kurtosis(x, iterations = 50)
#> Kurtosis |    SE
#> ----------------
#> 0.346    | 0.379


x <- cbind(rnorm(100), rexp(100))
skewness(x, iterations = 50)
#> Parameter | Skewness |    SE
#> ----------------------------
#> X1        |   -0.113 | 0.243
#> X2        |    1.530 | 0.344
kurtosis(x, iterations = 50)
#> Parameter | Kurtosis |    SE
#> ----------------------------
#> X1        |    0.136 | 0.397
#> X2        |    2.850 | 1.561


x <- as.data.frame(x)
skewness(x, iterations = 50)
#> Parameter | Skewness |    SE
#> ----------------------------
#> V1        |   -0.113 | 0.250
#> V2        |    1.530 | 0.361
kurtosis(x, iterations = 50)
#> Parameter | Kurtosis |    SE
#> ----------------------------
#> V1        |    0.136 | 0.350
#> V2        |    2.850 | 1.649
```

I’ve removed CIs (never seen that before, and the assumed symmetry doesn't make sense to me),
but added a testing option

``` r
print(skewness(x), test = TRUE)
#> Parameter | Skewness |    SE |      z |      p
#> ----------------------------------------------
#> V1        |   -0.113 | 0.238 | -0.474 | 0.636 
#> V2        |    1.530 | 0.238 |  6.435 | < .001
print(kurtosis(x), test = TRUE)
#> Parameter | Kurtosis |    SE |     z |      p
#> ---------------------------------------------
#> V1        |    0.136 | 0.455 | 0.300 | 0.764 
#> V2        |    2.850 | 0.455 | 6.267 | < .001
```

<sup>Created on 2020-03-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
> @strengejacke If that okay with you, I'll get it done (:

Yes, feel free to modify. However, when changing the default return value (data frame with parameter and se), we need to check whether this probably breaks code. It would also be useful to just return a numeric vector, e.g. via an `as.numeric()` method, because for descriptive statistics, you probably just need the skewness/kurtosis, not SE.

**Comment by strengejacke** [comment]
> This will also make the matrix / data.frame methods easier to implament.

Sounds good!

**Comment by mattansb** [comment]
done and done
