### ISSUE TITLE
bootstrap aov object doesn't work

### ISSUE THREAD

**Issue by AmirDJV** [easystats/parameters#167]
Hi, 

When I run `parameters::parameters()` with `aov` (unlike with `lm`) it seems like it doesn't preform bootstrapping.  

``` r
model <- aov(qsec ~ gear, mtcars)

parameters(model, bootstrap = FALSE)
#> Parameter | Sum_Squares | df | Mean_Square |    F |     p
#> ---------------------------------------------------------
#> gear      |        4.48 |  1 |        4.48 | 1.42 | 0.243
#> Residuals |       94.51 | 30 |        3.15 |      |      
#>0.02 sec elapsed

parameters(model, bootstrap = TRUE,  iterations = 100000)
#> Parameter | Sum_Squares | df | Mean_Square |    F |     p
#> ---------------------------------------------------------
#> gear      |        4.48 |  1 |        4.48 | 1.42 | 0.243
#> Residuals |       94.51 | 30 |        3.15 |      |      
#>0.02 sec elapsed
```

**Comment by IndrajeetPatil** [comment]
The expected output here is bootstrapped *p*-values?

**Comment by mattansb** [comment]
The F statistic is not symmetrical - p values would have to be based on permutation tests, not bootstrapping (e.g. `lmperm` package).
As for estimates - would bootstrapped CIs for SS/MS of the effect be beneficial? Not sure...

**Comment by IndrajeetPatil** [comment]
Yeah, I don't see how bootstrapping can be useful here. 

Maybe in the context of CIs for effect sizes for `aov` objects I can see its value, but that's a completely different issue.
