### ISSUE TITLE
Package citation

### ISSUE THREAD

**Issue by AmirDJV** [easystats/parameters#171]
Hi, 

In order to cite this package, should I use the following citation? 

> Makowski D, Ben-Sachar M, Lüdecke D (2019). “Describe and understand your model’s parameters.” CRAN. R package, https://github.com/easystats/parameters.

Corresponding BibTeX entry:

>   @Article{,
>     title = {Describe and understand your model’s parameters},
>     author = {Dominique Makowski and Mattan S. Ben-Sachar and Daniel
>       Lüdecke},
>     journal = {CRAN},
>     year = {2019},
>     note = {R package},
>     url = {https://github.com/easystats/parameters},
>   }

**Comment by strengejacke** [comment]
Yes, we currently have no related publication, so that's how you currently can cite the package.
