### ISSUE TITLE
Citeable parameters

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#186]
Since parameters is becoming pretty mature, I think we can plan a submission (we need our yearly JOSS 😁)?

In the paper, we can show/discuss:

- Built on insight to support a large number of models/packages
- parameters description (specificities and difference with broom)
  - specific vs. standardized names
- parameters calculation
- plotting (e.g., of parameters)
- ...

----------------
Journals:

  - [JOSS](https://joss.theoj.org/) (IF = NA, H  = NA, SJR = NA)
  - [JORS](https://openresearchsoftware.metajnl.com/) (IF = NA, H = 2, SJR = NA)
  - [PeerJ Computer Science](https://peerj.com/computer-science/) (IF = NA, H = 10, SJR = 0.87)
  - [SoftwareX](https://www.journals.elsevier.com/softwarex/) (IF = NA, H =10, SJR = 4.54)
  - [Journal of Statistical Software](https://www.jstatsoft.org/index) (IF = NA, H = 115, SJR = 17.57)

**Comment by DominiqueMakowski** [comment]
Related note: @IndrajeetPatil you should add yourself to the DESCRIPTION 😉

**Comment by strengejacke** [comment]
> PeerJ only considers Research Articles and Literature Review Articles.

JOSS, JORS or SoftwareX look like approprioate target journals to me. JStatSoft rather aims at Software that is about some new statistical approach, while _parameters_ is more a "summary" package, not doing own / new statistics, I think.

**Comment by strengejacke** [comment]
SoftwareX has a fee of 500$, however, doesn't seem to be listed in our internal ranking, so this will be less attractive.

**Comment by DominiqueMakowski** [comment]
> SoftwareX has a fee of 500$

indeed 😅 

We all had a good experience with JOSS... unless we cant to change an try something new 😏

**Comment by IndrajeetPatil** [comment]
I vote for _JOSS_ as well!

**Comment by strengejacke** [comment]
Maybe I find some time to work on the paper, but JOSS has closed submissions for now...

**Comment by DominiqueMakowski** [comment]
- [x] Built on insight to support a large number of models/packages
- [x] plotting (e.g., of parameters)
- [ ] parameters description (specificities and difference with broom)
- [ ] specific vs. standardized names
- [ ] parameters calculation (bootstrapped, ...)
- [ ] ...
