### ISSUE TITLE
rescale design weights

### ISSUE THREAD

**Issue by strengejacke** [easystats/parameters#189]
I re-implemented `sjstats::scale_weights()` here: https://easystats.github.io/parameters/reference/rescale_weights.html

@DominiqueMakowski would you say this function makes sense in this package, or would you suggest moving it to another package?

**Comment by strengejacke** [comment]
_bump_

**Comment by DominiqueMakowski** [comment]
Yeah, I think it makes sense. Maybe I'd tweak the format so one doesn't have to cbind, i.e., it would return the whole dataframe with the two new columns added. (so one can use this function in a tidy pipeline `df %>% rescale_weights("groups", "probability") %>% whatever()`. Also, can the `cluster` argument [(should we rename to `group`? *cluster* being maybe more associated with clustering?] accept multiple values (a list of grouping columns when multiple random factors exist)?
