### ISSUE TITLE
Suggesting two small functions to support PCA

### ISSUE THREAD

**Issue by strengejacke** [easystats/parameters#196]
@DominiqueMakowski Suggestions/comments, also about function names?

`extract_scales()`: https://easystats.github.io/parameters/reference/extract_scales.html
`component_columns()`: https://easystats.github.io/parameters/reference/principal_components.html

**Comment by strengejacke** [comment]
@DominiqueMakowski  _bump_ (master of function names...)

**Comment by DominiqueMakowski** [comment]
`extract_scales` -> `get_scores`?
`component_columns` -> `variables_to_component`?

How does `extract_scales()` relate to `predict()`? Couldn't we add this as a *method* for `predict()`*? 
I.e., predict() for CFA, EFA or PCA returns the scores for each observation, created by running the variable score through the loadings (i.e., the scores take into account the loadings for each score). `extract_scales` seems to be the commonly used simplification of that (for questionnaire validations, survey etc), i.e., taking n amount of items that load the most (either by loading cutoff or number), and then computing their average (i.e., setting all remaining loadings as equal). Thus, it would make sense to have like `predict(pca, method="average", n_items=2)` (maybe we'd need to find some consistency with for instance [efa_to_cfa](https://easystats.github.io/parameters/reference/convert_efa_to_cfa.html)).

**Comment by strengejacke** [comment]
> extract_scales -> get_scores?

ok.

> component_columns -> variables_to_component?

Not sure. It really returns only the assignment of a component for each variables in the original data. Yes, it tells you how variables are related to components, but does that function name imply that? hm...

> How does extract_scales() relate to predict()?

Not sure, have not yet looked into detail into that function and thus have no idea what it does.

**Comment by DominiqueMakowski** [comment]
> It really returns only the assignment of a component for each variables in the original data.

True, true. `closest_component()`? Because as far as I understand it doesn't return the direct "assignment", but rather the component that is the most related to each variable?

**Comment by strengejacke** [comment]
> closest_component()? 

yes, that sounds good!
