### ISSUE TITLE
parameters:::.extract_parameters_mixed shuffling order of parameters

### ISSUE THREAD

**Issue by mikeypasek** [easystats/parameters#199]
Please see description of problem here: https://stackoverflow.com/questions/59888022/predictors-are-in-random-order-in-sjplot-using-tab-model-r-with-reproducible/59888688#59888688

It seems that parameters:::.extract_parameters_mixed is shuffling the order of parameters rather than extracting them in order, which appears to be an underlying bug.

Thanks!

**Comment by strengejacke** [comment]
I have posted an answer on SO. I think that issue has been solved in parameters 0.4.0. can you still reproduce that issue?

**Comment by mikeypasek** [comment]
I updated parameters to 0.4.1 and sjPlot from 2.8.1 to 2.8.2 and issue is resolved. Thank you!
