### ISSUE TITLE
Error: object ‘check_smoothness’ is not exported by 'namespace:parameters'

### ISSUE THREAD

**Issue by emilio-berti** [easystats/parameters#208]
Hi,

I am trying to use the estimate package, but when loading it I got the following error

```
library(estimate)
Error: package or namespace load failed for ‘estimate’:
 object ‘check_smoothness’ is not exported by 'namespace:parameters'
```
I believe it's a similar issue as in easystats/report#46 and easystats/report#59. I tried also the following:
```
devtools::install_github(c("easystats/insight",
                             "easystats/bayestestR",
                             "easystats/performance",
                             "easystats/parameters",
                             "easystats/correlation",
                             "easystats/estimate",
                             "easystats/see",
                             "easystats/report"), force = TRUE)
```
but the error persists. 

I am using R 3.6.1 in Debian 9 GNU/Linux and RStudio 1.1.463. The package was working fine last week, so I guess it's just a broken dependency from the last updates.

Cheers,
Emilio

**Comment by DominiqueMakowski** [comment]
@emilio-berti Thanks for asking, the function has been renamed as `smoothness()` (although TBH I don't really remember the rationale for that renaming). Try:

```r
install.packages(c("insight", "bayestestR", "parameters"))
parameters::smoothness(iris$Sepal.Length)
```

Also, note that the `estimate` has been renamed to [`modelbased`](https://github.com/easystats/modelbased) ☺️ Let us know if that works for you

**Comment by emilio-berti** [comment]
Hi Dominique,

aaaah, didn't notice the change of the name. The solution you proposed worked perfectly. Thanks a lot!

Cheers,
Emilio
