### ISSUE TITLE
model_parameters() or print() for DRR()?

### ISSUE THREAD

**Issue by strengejacke** [easystats/parameters#209]
@DominiqueMakowski your task, I don't really know what `DRR()` is doing. ;-)

**Comment by DominiqueMakowski** [comment]
Man, I have no memories whatsoever having implemented that 😅 

Isn't it supposed to be an internal method for `parameters_reduction()`?

**Comment by strengejacke** [comment]
😂 

quite well documented for an internal function... ;-)
