### ISSUE TITLE
Omega and Eta sq

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#22]
- [x] Add eta sq
- [x] Add epsilon sq
- [x] Add Cohen's F
- [x] Add CIs for eta-sq
- [x] Add CIs for partial eta-sq
- [x] Add CIs omega-sq
- [x] Add CIs partial omega-sq

Ressources:
- https://github.com/strengejacke/sjstats/blob/master/R/eta_sq.R
- https://strengejacke.github.io/sjstats/reference/eta_sq.html

**Comment by strengejacke** [comment]
The current return value is a bit confusing, maybe we should use a different example?

``` r
library(parameters)
df <- iris
df$Sepal.Big <- ifelse(df$Sepal.Width >= 3, "Yes", "No")

model <- aov(Sepal.Length ~ Sepal.Big, data = df)
omega_squared(model)
#> [1] 0.004038505          NA
```

<sup>Created on 2019-04-22 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by DominiqueMakowski** [comment]
definitely... 

I am not even sure if we should return a named vector or a list or a dataframe... What are your thoughts?

**Comment by strengejacke** [comment]
any news on this? The return value of omega squared is still confusing. I think the function is supposed to return a df, but actually returns an unnames vector.

Furthermore, results differ from what I implemented in _sjstats_, we should check this:

``` r
library(parameters)
library(sjstats)
data(iris)
df <- iris
df$Sepal.Big <- ifelse(df$Sepal.Width >= 3, "Yes", "No")

model <- aov(Sepal.Length ~ Sepal.Big + Error(Species), data = df)


omega_squared(model, partial = FALSE)
#> [1] -0.09544457          NA -0.43213914          NA

omega_sq(model, partial = FALSE)
#>        term omegasq stratum
#> 1 Sepal.Big   0.274 Species
#> 2 Residuals   0.339 Species
#> 3 Sepal.Big   0.044  Within


omega_squared(model, partial = TRUE)
#> [1] -0.001274216           NA -0.005795247           NA

omega_sq(model, partial = TRUE)
#>        term partial.omegasq stratum
#> 1 Sepal.Big           0.444 Species
#> 2 Residuals           0.497 Species
#> 3 Sepal.Big           0.114  Within
```

<sup>Created on 2019-05-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DominiqueMakowski** [comment]
I'll take a look, as this needs to be fixed before release.

**Comment by DominiqueMakowski** [comment]
I have deactivated for now the Omega squared for models with `Error`. I haven't found a clear formula on the internet to compute them and the implementation of sjstats is quite hard to trace down 😕

**Comment by strengejacke** [comment]
> and the implementation of sjstats is quite hard to trace down

I can work on a draft...

**Comment by DominiqueMakowski** [comment]
note: doc says that "partial" is default (in model_parameters) but NULL is default.

**Comment by strengejacke** [comment]
I'm not sure you have the correct formula for omeqa-squared. you use

```r
(params$Sum_Squares - params$df * values$Mean_Square_residuals) / (values$Sum_Squares_residuals + values$Mean_Square_residuals)
```

I think it should be

```r
(params$Sum_Squares - params$df * values$Mean_Square_residuals) / (values$Sum_Squares_total+ values$Mean_Square_residuals)
```

**Comment by DominiqueMakowski** [comment]
this is possible, omega squares were not double-checked (hence the previously noted discrepancies with sjstats)

**Comment by strengejacke** [comment]
I have tried to implement omeqa-squared for repeated-measure aov, but I'm not sure if any of the approaches in sjstats or parameters is right. technically, the implementation in parameters feels more correct. Looking at the results, the sjstats implementation makes more sense:

``` r
library(parameters)
library(sjstats)
#> 
#> Attaching package: 'sjstats'
#> The following object is masked from 'package:parameters':
#> 
#>     p_value

df <- iris
df$Sepal.Big <- ifelse(df$Sepal.Width >= 3, "Yes", "No")

model <- aov(Sepal.Length ~ Sepal.Big + Error(Species), data = df)

omega_squared(model)
#> $Species
#>     Group Parameter Omega_Sq_partial
#> 1 Species Sepal.Big      -0.06795358
#> 2 Species Residuals               NA
#> 
#> $Within
#>    Group Parameter Omega_Sq_partial
#> 3 Within Sepal.Big        0.1150255
#> 4 Within Residuals               NA

omega_sq(model)
#>        term omegasq stratum
#> 1 Sepal.Big   0.274 Species
#> 2 Residuals   0.339 Species
#> 3 Sepal.Big   0.044  Within
```

<sup>Created on 2019-08-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


Why the differences?
The _total_ sum of squares and the residual mean squares are calculated differently. In sjstats, I always use the _last row_ of the tidy output as residual row - however, for repeated measures aov, we have more than one row for residuals (one row for within and one for between). This is what I take into account in the parameters implementation, however, results look somewhat strange.

Maybe we should indeed not allow aovlist for now...

**Comment by DominiqueMakowski** [comment]
I have virtually never used omega squared, I just know that this was a feature people needed in my first lab. Maybe someone else would have a stronger opinion? @mattansb @humanfactors @pdwaggoner

**Comment by mattansb** [comment]
We use (and teach) partial eta square, which is also the common effect size I see in papers I read (very easy to approx for most tests: `(F * df1) / (F * df1 + df2)` as can be seen in many lmm papers), only rarely do I see any omegas...

**Comment by strengejacke** [comment]
I have added `ci()` for partial eta-squared... **however**, this requires some code taken from other packages.

@DominiqueMakowski Are you ok with this approach, i.e. copy/pasting code from MBESS and another package? Licence is ok, I think, you can also re-write that code from scratch, if you feel more comfortable with having own code.

``` r
library(parameters)
df <- iris
df$Sepal.Big <- ifelse(df$Sepal.Width >= 3, "Yes", "No")
model <- anova(lm(Sepal.Length ~ Sepal.Big * Species, data = df))

es <- eta_squared(model, partial = TRUE)

ci(es)
#>           Parameter Eta_Sq_partial  conf.low conf.high
#> 1         Sepal.Big    0.031140626 0.0000000 0.1043039
#> 2           Species    0.661771666 0.5707417 0.7211695
#> 3 Sepal.Big:Species    0.001289171 0.0000000 0.0177377
#> 4         Residuals             NA        NA        NA
```

<sup>Created on 2019-08-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DominiqueMakowski** [comment]
> I have added ci() for partial eta-squared

Great thanks!!

> this requires some code taken from other packages

I am okay, as long as the original implementation is credited in the docs ☺️

**Comment by strengejacke** [comment]
> I am okay, as long as the original implementation is credited in the docs

Not yet, but we should add a reference or so...

it's at least stated in the related R files:

https://github.com/easystats/parameters/blob/master/R/ci_partial_eta_squared.R
https://github.com/easystats/parameters/blob/master/R/confint_ncg.R

**Comment by strengejacke** [comment]
I _think_ we're done...

**Comment by strengejacke** [comment]
Feel free to do some code-clean-up / styling

**Comment by strengejacke** [comment]
Ok, you may need to add the citation to the docs
