### ISSUE TITLE
model_parameters() for MuMin average class

### ISSUE THREAD

**Issue by strengejacke** [easystats/parameters#234]
See https://github.com/strengejacke/sjPlot/issues/352#issuecomment-611827488

**Comment by vjjan91** [comment]
Sorry - I did not follow the comment you made in the previous git issue - What do you mean by tab_model follows parameters under the hood?

**Comment by vjjan91** [comment]
Could you provide an example of how it might work? / reproducible example? Currently struggling with this issue - https://stackoverflow.com/questions/61132941/plotting-interactions-from-a-model-averaging-object-of-a-logistic-regression-i
