### ISSUE TITLE
Vignettte demean: Bell/Fairbrother/Jones (2019), not (2018)

### ISSUE THREAD

**Issue by helix123** [easystats/parameters#235]
Paper by Bell/Fairbrother/Jones is 2019, not 2018, see https://link.springer.com/article/10.1007%2Fs11135-018-0802-x

Andrew Bell, Malcolm Fairbrother & Kelvyn Jones , "Fixed and random effects models: making an informed choice", Quality & Quantity volume 53, pages 1051–1074 (2019)

**Comment by strengejacke** [comment]
Ok, thanks! I was indeed referring to the preprint, I guess.
