### ISSUE TITLE
including `supported_models()` function in `parameters`?

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/parameters#237]
Since `parameters` forms a unified interface for extracting model info, I am wondering if we should re-export `supported_models()` function in `parameters` as well? 
At least for me personally, when I want to check if a model is supported in `easystats` system, my mind directly goes to check this in `parameters`, and not in `insight`:
https://easystats.github.io/insight/reference/is_model_supported.html

![image](https://user-images.githubusercontent.com/11330453/79199262-06c28800-7e35-11ea-8a57-fb3da31037e6.png)

**Comment by strengejacke** [comment]
The problem is that *insight* supports the most packages, while model support in other packages in decreasing, due to various difficulties in accessing specific model information (e.g. r2() in performance, or p_value() in parameters). Thus, `parameters::supported_models()` might be misleading.

**Comment by DominiqueMakowski** [comment]
eventually, we could have an argument in supported_models(package='parameters') printing the appropriate list of supported packages, but that seems like a lot of work to maintain for a feature that won't be used by many (I expect people to just try `parameters(mod)` and then see) ^^

**Comment by strengejacke** [comment]
we also have default methods for `p_value()`, `standard_error()` and `ci()` that try to access these information via various approaches, so it's likely that models are supported that we aren't even aware of.

**Comment by IndrajeetPatil** [comment]
Hmm, I see. Yeah, in that case, this will be too much of an effort with a little in the return. Let's keep the current structure then. 

Thanks for your thoughts and consideration of this issue.
