### ISSUE TITLE
examples for `model_parameters.rma` are broken

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/parameters#240]
https://easystats.github.io/parameters/reference/model_parameters.rma.html

![image](https://user-images.githubusercontent.com/11330453/79322152-b4ed3100-7f0c-11ea-9bea-d30b9b285fb2.png)

**Comment by strengejacke** [comment]
Can't reproduce. Also, no warnings / erros in CRAN check results: https://cran.r-project.org/web/checks/check_results_parameters.html

**Comment by IndrajeetPatil** [comment]
Maybe then the website needs to be rebuilt? 

That's why I didn't tag it as a bug but rather as an error in the documentation.

**Comment by strengejacke** [comment]
I see, you were referring to the website... That's a pkgdown issue, because pkgdown seems to deal differently with environments, so the data is not accessible.

**Comment by IndrajeetPatil** [comment]
Hmm, even if we ignore this as a `pkgdown` issue, the users learning about the package via reading documentation on the website might think that the function is broken and might skip using it. 

Is there any way to avoid this? If not, feel free to close this issue.

**Comment by strengejacke** [comment]
I think we can at least prevent examples from being rendered using `pkgdown::in_pkgdown()`, however, I don't no how to _not_ render examples?

**Comment by strengejacke** [comment]
I actually did that, however, this also prevent examples from being tested on CRAN (I think). But since we have tests for metafor, this shouldn't be a problem.

**Comment by strengejacke** [comment]
Ha! `<<--` does the trick. See updated website.
