### ISSUE TITLE
`model_parameters` doesn't work with `oneway.test`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/parameters#244]
``` r
mod <- oneway.test(extra ~ group, data = sleep)

broom::tidy(mod)
#> Multiple parameters; naming those columns num.df, denom.df
#> # A tibble: 1 x 5
#>   num.df den.df statistic p.value method                                        
#>    <dbl>  <dbl>     <dbl>   <dbl> <chr>                                         
#> 1      1   17.8      3.46  0.0794 One-way analysis of means (not assuming equal~

insight::is_model_supported(mod)
#> [1] TRUE

parameters::model_parameters(mod)
#> Error in `$<-.data.frame`(`*tmp*`, "df", value = c(`num df` = 1, `denom df` = 17.7764735161785: replacement has 2 rows, data has 1
```

<sup>Created on 2020-04-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by strengejacke** [comment]
closing in favor of #133 and https://github.com/easystats/insight/issues/43
That's actually of lower priority for me, in particular since these objects are no "models" (my personal focus). But of course, this does not mean that it should _not_ go into easystats - maybe someone can address this / make a PR? A start would be to implement the methods in _insight_.

**Comment by strengejacke** [comment]
(@DominiqueMakowski)

**Comment by DominiqueMakowski** [comment]
That's crazy, it's the first time I see this `oneway.test()` 🤯

I guess supporting this is not complicated, but one just needs to find a way of identifying this subclass in `insight` and in `model_parameters.htest()`

**Comment by strengejacke** [comment]
Yes, I think the biggest problem would be to extract useful information in a generic way (see our discussion here: https://github.com/easystats/insight/issues/43). We could of course "hardcode" our functions, but that's the least preferred way, imho.
