### ISSUE TITLE
reduce use of qnorm for CIs

### ISSUE THREAD

**Issue by mattansb** [easystats/parameters#256]
The idea is that `qnorm()` gives too narrow a CI compared to the proper `qt()`:

``` r

dat <- mtcars[1:10, ]
fit <- lm(mpg ~ cyl, dat)

parameters::model_parameters(fit, standardize = "refit")
#> Parameter   | Coefficient |   SE |         95% CI |     t | df |     p
#> ----------------------------------------------------------------------
#> (Intercept) |        0.00 | 0.17 | [-0.39,  0.39] |  0.00 |  8 | 1.000
#> cyl         |       -0.86 | 0.18 | [-1.28, -0.45] | -4.80 |  8 | 0.001

parameters::model_parameters(fit, standardize = "basic") # uses qnorm
#> Parameter   | Coefficient (std.) |   SE |         95% CI |     t | df |      p
#> ------------------------------------------------------------------------------
#> (Intercept) |               0.00 | 0.00 | [ 0.00,  0.00] | 14.31 |  8 | < .001
#> cyl         |              -0.86 | 0.18 | [-1.21, -0.51] | -4.80 |  8 | 0.001
```

Note that the second CI is more narrow.

These is a long term goal, as:
1. I suspect implementation is hard. 
2. When with larger df, the difference gets smaller and smaller.

For now, this issue can be kept open for any curious people...

---

- [x] `se_ml1` 
- [ ] `se_betwithin` 
- [x] `ci.effectsize_std_param`
- [x] `equivalence_test` 
- [x] `.ci_from_refit`

**Comment by strengejacke** [comment]
> ci.effectsize_std_param

This is now on your end as you plan to implement `ci` for `effectsize::standardize_parameters()`.

**Comment by mattansb** [comment]
I thought it would be best to just leave that here, so I don't have to export the `ci()` function in effectsize, and I would maintain it here ^_^

**Comment by mattansb** [comment]
In either case, to truly fix this, all methods would need access to the correct df, which I think falls under `parameters`. Best keep all the standard error, p value, df methods in one place.

**Comment by strengejacke** [comment]
Ah, I see. Got it.

**Comment by strengejacke** [comment]
``` r
dat <- mtcars[1:10, ]
fit <- lm(mpg ~ cyl, dat)
effectsize::standardize_parameters(fit, standardize = "basic", ci = .95)
#> Parameter   | Coefficient (std.) |         95% CI
#> -------------------------------------------------
#> (Intercept) |               0.00 | [-0.39,  0.39]
#> cyl         |              -0.86 | [-1.28, -0.45]
```

<sup>Created on 2020-04-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mattansb** [comment]
That's awesome!

**Comment by strengejacke** [comment]
Not sure, I think `equivalence_test()` already uses the best CIs, based of df and `qt()`. It calls `ci_wald()` with df = NULL, and then:

```r
  if (is.null(dof)) {
    # residual df
    dof <- degrees_of_freedom(model, method = "any")
    # make sure we have a value for degrees of freedom
    if (is.null(dof) || length(dof) == 0) dof <- Inf
  }
```

**Comment by mattansb** [comment]
I'm looking here: https://github.com/easystats/parameters/blob/62a0d968ad9542e29f5bf1f1290e489973f522a8/R/equivalence_test.R#L454
