### ISSUE TITLE
failing tests on CRAN `clang11` check

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/parameters#268]
Two tests are failing in additional CRAN checks:
https://www.stats.ox.ac.uk/pub/bdr/clang11/parameters.out

Better to fix now before we get an e-mail from Prof. Ripley about them :D

I am not sure though how to test this. I don't have access to a machine with this config nor do I know how to fake it on Docker.

P.S. Plus, there are also a couple of `WARNING`s to fix:
https://cran.r-project.org/web/checks/check_results_parameters.html

**Comment by strengejacke** [comment]
The warnings are new, and I think these are due to technical reasons on CRAN check side (not sure though, but I guess...).

**Comment by strengejacke** [comment]
seems to be resolved.
