### ISSUE TITLE
feature request: adding support for `BANOVA` models

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/parameters#282]
```r  
  library(rstan)
    #> Loading required package: StanHeaders
    #> Loading required package: ggplot2
    #> rstan (Version 2.21.2, GitRev: 2e1f913d3ca3)
    #> For execution on a local, multicore CPU with excess RAM we recommend calling
    #> options(mc.cores = parallel::detectCores()).
    #> To avoid recompilation of unchanged Stan programs, we recommend calling
    #> rstan_options(auto_write = TRUE)
    #> Do not specify '-march=native' in 'LOCAL_CPPFLAGS' or a Makevars file
    library(rjags)
    #> Loading required package: coda
    #> 
    #> Attaching package: 'coda'
    #> The following object is masked from 'package:rstan':
    #> 
    #>     traceplot
    #> Linked to JAGS 4.3.0
    #> Loaded modules: basemod,bugs
    library(BANOVA)
    data(colorad)
    set.seed(700)

    model <- BANOVA.model(model_name = 'Binomial')
    banova_fit <- BANOVA.build(model)
    #> Compiling...
    #> Compiled successfully

    traceback()
    #> No traceback available

    res <-
      BANOVA.run(
        y ~ typic,
        ~ color * blur,
        data = colorad,
        fit = banova_fit,
        id = 'id',
        num_trials = as.integer(16),
        iter = 1000,
        thin = 1,
        chains = 2,
        refresh = 0
      )
    #> Warning: level 2 numeric variables have been mean centered.
    #> 
    #> CHECKING DATA AND PREPROCESSING FOR MODEL 'Binomial' NOW.
    #> 
    #> COMPILING MODEL 'Binomial' NOW.
    #> 
    #> STARTING SAMPLER FOR MODEL 'Binomial' NOW.
    #> Constructing ANOVA/ANCOVA tables...
    #> Done.

    class(res)
    #> [1] "BANOVA"

    summary(res)$coef
    #>                                mean     SD Quantile0.025 Quantile0.975 p-value
    #> (Intercept)  :  (Intercept)  0.4971 0.0580        0.3827        0.6089 <0.0001
    #> (Intercept)  :  color1      -0.0087 0.1260       -0.2624        0.2292  0.9620
    #> (Intercept)  :  blur        -0.1715 0.0299       -0.2289       -0.1114 <0.0001
    #> (Intercept)  :  color1:blur  0.0412 0.0297       -0.0167        0.1002  0.1600
    #> typic1  :  (Intercept)       0.3008 0.0337        0.2361        0.3676 <0.0001
    #> typic1  :  color1           -0.0588 0.0741       -0.2039        0.0829  0.4260
    #> typic1  :  blur             -0.0767 0.0176       -0.1128       -0.0434 <0.0001
    #> typic1  :  color1:blur       0.0386 0.0174        0.0056        0.0726  0.0180
    #>                             Signif.codes
    #> (Intercept)  :  (Intercept)          ***
    #> (Intercept)  :  color1                  
    #> (Intercept)  :  blur                 ***
    #> (Intercept)  :  color1:blur             
    #> typic1  :  (Intercept)               ***
    #> typic1  :  color1                       
    #> typic1  :  blur                      ***
    #> typic1  :  color1:blur                 *
```
<sup>Created on 2020-08-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
<details>
<summary>
Session info
</summary>

    devtools::session_info()
    #> - Session info ---------------------------------------------------------------
    #>  setting  value                                             
    #>  version  R Under development (unstable) (2020-07-22 r78897)
    #>  os       Windows 10 x64                                    
    #>  system   x86_64, mingw32                                   
    #>  ui       RTerm                                             
    #>  language (EN)                                              
    #>  collate  English_United States.1252                        
    #>  ctype    English_United States.1252                        
    #>  tz       Europe/Berlin                                     
    #>  date     2020-08-09                                        
    #> 
    #> - Packages -------------------------------------------------------------------
    #>  package      * version    date       lib source                        
    #>  assertthat     0.2.1      2019-03-21 [1] CRAN (R 4.1.0)                
    #>  backports      1.1.8      2020-06-17 [1] CRAN (R 4.1.0)                
    #>  BANOVA       * 1.1.7      2020-05-04 [1] CRAN (R 4.1.0)                
    #>  callr          3.4.3      2020-03-28 [1] CRAN (R 4.1.0)                
    #>  cli            2.0.2      2020-02-28 [1] CRAN (R 4.1.0)                
    #>  coda         * 0.19-3     2019-07-05 [1] CRAN (R 4.1.0)                
    #>  codetools      0.2-16     2018-12-24 [2] CRAN (R 4.1.0)                
    #>  colorspace     1.4-1      2019-03-18 [1] CRAN (R 4.1.0)                
    #>  crayon         1.3.4      2017-09-16 [1] CRAN (R 4.1.0)                
    #>  curl           4.3        2019-12-02 [1] CRAN (R 4.1.0)                
    #>  desc           1.2.0      2018-05-01 [1] CRAN (R 4.1.0)                
    #>  devtools       2.3.1      2020-07-21 [1] CRAN (R 4.1.0)                
    #>  digest         0.6.25     2020-02-23 [1] CRAN (R 4.1.0)                
    #>  dplyr          1.0.1      2020-07-31 [1] CRAN (R 4.1.0)                
    #>  ellipsis       0.3.1      2020-05-15 [1] CRAN (R 4.1.0)                
    #>  evaluate       0.14       2019-05-28 [1] CRAN (R 4.1.0)                
    #>  fansi          0.4.1      2020-01-08 [1] CRAN (R 4.1.0)                
    #>  fs             1.5.0      2020-07-31 [1] CRAN (R 4.1.0)                
    #>  generics       0.0.2      2018-11-29 [1] CRAN (R 4.1.0)                
    #>  ggplot2      * 3.3.2      2020-06-19 [1] CRAN (R 4.1.0)                
    #>  glue           1.4.1      2020-05-13 [1] CRAN (R 4.1.0)                
    #>  gridExtra      2.3        2017-09-09 [1] CRAN (R 4.1.0)                
    #>  gtable         0.3.0      2019-03-25 [1] CRAN (R 4.1.0)                
    #>  highr          0.8        2019-03-20 [1] CRAN (R 4.1.0)                
    #>  htmltools      0.5.0      2020-06-16 [1] CRAN (R 4.1.0)                
    #>  inline         0.3.15     2018-05-18 [1] CRAN (R 4.1.0)                
    #>  jsonlite       1.7.0      2020-06-25 [1] CRAN (R 4.1.0)                
    #>  knitr          1.29       2020-06-23 [1] CRAN (R 4.1.0)                
    #>  lattice        0.20-41    2020-04-02 [2] CRAN (R 4.1.0)                
    #>  lifecycle      0.2.0      2020-03-06 [1] CRAN (R 4.1.0)                
    #>  loo            2.3.1      2020-07-14 [1] CRAN (R 4.1.0)                
    #>  magrittr       1.5        2014-11-22 [1] CRAN (R 4.1.0)                
    #>  matrixStats    0.56.0     2020-03-13 [1] CRAN (R 4.1.0)                
    #>  memoise        1.1.0      2017-04-21 [1] CRAN (R 4.1.0)                
    #>  munsell        0.5.0      2018-06-12 [1] CRAN (R 4.1.0)                
    #>  pillar         1.4.6      2020-07-10 [1] CRAN (R 4.1.0)                
    #>  pkgbuild       1.1.0      2020-07-13 [1] CRAN (R 4.1.0)                
    #>  pkgconfig      2.0.3      2019-09-22 [1] CRAN (R 4.1.0)                
    #>  pkgload        1.1.0      2020-05-29 [1] CRAN (R 4.1.0)                
    #>  prettyunits    1.1.1      2020-01-24 [1] CRAN (R 4.1.0)                
    #>  processx       3.4.3      2020-07-05 [1] CRAN (R 4.1.0)                
    #>  ps             1.3.3      2020-05-08 [1] CRAN (R 4.1.0)                
    #>  purrr          0.3.4      2020-04-17 [1] CRAN (R 4.1.0)                
    #>  R6             2.4.1      2019-11-12 [1] CRAN (R 4.1.0)                
    #>  Rcpp           1.0.5      2020-07-06 [1] CRAN (R 4.1.0)                
    #>  RcppParallel   5.0.2      2020-06-24 [1] CRAN (R 4.1.0)                
    #>  remotes        2.2.0.9000 2020-08-06 [1] Github (r-lib/remotes@5a546ad)
    #>  rjags        * 4-10       2019-11-06 [1] CRAN (R 4.1.0)                
    #>  rlang          0.4.7      2020-07-09 [1] CRAN (R 4.1.0)                
    #>  rmarkdown      2.3        2020-06-18 [1] CRAN (R 4.1.0)                
    #>  rprojroot      1.3-2      2018-01-03 [1] CRAN (R 4.1.0)                
    #>  rstan        * 2.21.2     2020-07-27 [1] CRAN (R 4.1.0)                
    #>  runjags        2.0.4-6    2019-12-17 [1] CRAN (R 4.1.0)                
    #>  scales         1.1.1      2020-05-11 [1] CRAN (R 4.1.0)                
    #>  sessioninfo    1.1.1      2018-11-05 [1] CRAN (R 4.1.0)                
    #>  StanHeaders  * 2.21.0-5   2020-06-09 [1] CRAN (R 4.1.0)                
    #>  stringi        1.4.6      2020-02-17 [1] CRAN (R 4.1.0)                
    #>  stringr        1.4.0      2019-02-10 [1] CRAN (R 4.1.0)                
    #>  testthat       2.3.2      2020-03-02 [1] CRAN (R 4.1.0)                
    #>  tibble         3.0.3      2020-07-10 [1] CRAN (R 4.1.0)                
    #>  tidyselect     1.1.0      2020-05-11 [1] CRAN (R 4.1.0)                
    #>  usethis        1.6.1.9001 2020-08-06 [1] Github (r-lib/usethis@51fcdb8)
    #>  V8             3.2.0      2020-06-19 [1] CRAN (R 4.1.0)                
    #>  vctrs          0.3.2      2020-07-15 [1] CRAN (R 4.1.0)                
    #>  withr          2.2.0      2020-04-20 [1] CRAN (R 4.1.0)                
    #>  xfun           0.16       2020-07-24 [1] CRAN (R 4.1.0)                
    #>  yaml           2.2.1      2020-02-01 [1] CRAN (R 4.1.0)                
    #> 
    #> [1] C:/Users/inp099/Documents/R/win-library/4.1
    #> [2] C:/Program Files/R/R-devel/library

</details>

**Comment by strengejacke** [comment]
Similar problem like here: https://github.com/easystats/insight/issues/161
