### ISSUE TITLE
Less dependencies

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#3]
purrr is used only in [one location](https://github.com/easystats/parameters/blob/6009e419b1eb44877aa7ecbe3625159fc8676b40/R/standardize.data.frame.R#L87), but my quick base solutions don't work, as they it seems that they do not preserve the method type (i.e., they for some reason transform factors into numerics).

For broom, this will require a bit more work... we can maybe keep it at first (to support many models), and then, progressively, replace it here and there until complete removal.

There is still the `dplyr` case... I think we could keep it for now, and discuss its keeping later once the package is a bit more in shape.

**Comment by DominiqueMakowski** [comment]
Decided to remove broom for now as it was easier than expected

**Comment by strengejacke** [comment]
I think we can close this issue, right?

**Comment by DominiqueMakowski** [comment]
I think so yes.
