### ISSUE TITLE
Conversion between effect sizes

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#30]
Add some functions to easily convert among [effect sizes](https://www.meta-analysis.com/downloads/Meta-analysis%20Converting%20among%20effect%20sizes.pdf).

Maybe prefix them with `convert_*` to unify them. Although verbose, it would very "readable" (e.g. `convert_odds_to_probs()`.

**Comment by strengejacke** [comment]
See also
https://github.com/strengejacke/esc

**Comment by DominiqueMakowski** [comment]
damn it! I got strengejacked again

**Comment by strengejacke** [comment]
Two things I like about the package:
1 it's in a CRAN task view
2 the diamond in the logo, diamonds are typical for meta analyses, is a tribute to a good old game.

**Comment by DominiqueMakowski** [comment]
Sure, let's leave it exists peacefully then ☺️ 

I might just add a conversion from r to d and vice versa, as I would like to add [Gignac's et al. 2016](https://easystats.github.io/report/articles/interpret_metrics.html#gignac2016effect) guidelines also for d interpretation in report.

**Comment by strengejacke** [comment]
I don't mind re-implementing effect size conversions in parameters. It's also a very simple script:
https://github.com/strengejacke/esc/blob/master/R/hedges_g.R

This is typically used in meta analysis, I'm not sure if there exist more sophisticated algorithms?

**Comment by DominiqueMakowski** [comment]
Hum looks like there is a discrepancy between what is written [here](https://www.meta-analysis.com/downloads/Meta-analysis%20Converting%20among%20effect%20sizes.pdf) and your [formuma](https://github.com/strengejacke/esc/blob/58cde568cb4494209739a3953ef9f40ec9c04366/R/hedges_g.R#L65):

If I read correctly, to convert from *d* to *r*, the authors of the book suggest:

`r <- d / (sqrt(d^2 + 4))`

instead of:

`sqrt(d^2 / (d^2 + 4))`

**Comment by strengejacke** [comment]
But where's the difference?

``` r
for (d in 1:10) {
  print(d / (sqrt(d^2 + 4)))
  print(sqrt(d^2 / (d^2 + 4))  )
}
#> [1] 0.4472136
#> [1] 0.4472136
#> [1] 0.7071068
#> [1] 0.7071068
#> [1] 0.8320503
#> [1] 0.8320503
#> [1] 0.8944272
#> [1] 0.8944272
#> [1] 0.9284767
#> [1] 0.9284767
#> [1] 0.9486833
#> [1] 0.9486833
#> [1] 0.9615239
#> [1] 0.9615239
#> [1] 0.9701425
#> [1] 0.9701425
#> [1] 0.9761871
#> [1] 0.9761871
#> [1] 0.9805807
#> [1] 0.9805807
```

<sup>Created on 2019-04-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by DominiqueMakowski** [comment]
I talked too fast :)

**Comment by strengejacke** [comment]
But in terms of performance, your proposal would be faster...

``` r
library(microbenchmark)
d <- 1:1e6
microbenchmark(
  d / (sqrt(d^2 + 4)),
  sqrt(d^2 / (d^2 + 4))
)
#> Unit: milliseconds
#>                 expr     min       lq     mean   median      uq     max
#>    d/(sqrt(d^2 + 4))  9.2665  9.47115 11.70689  9.68255 12.1576 44.8185
#>  sqrt(d^2/(d^2 + 4)) 11.4457 11.74510 14.40051 14.08495 15.7218 41.0248
```

... if it matters. ;-)

**Comment by DominiqueMakowski** [comment]
it's something 😋

**Comment by strengejacke** [comment]
Why did you close this issue? Have you implemented conversion functions?

**Comment by DominiqueMakowski** [comment]
I added simple conversion from d to r. but for the others I didn't want to overlap with `esc`... should we reopen this issue and think about (re)implementing some converters?

**Comment by strengejacke** [comment]
I don't mind, if it's not very urgent, we can leave it as it's now... I don't use converters anyway, because these conversions are really scary! I can't understand why meta-analysis are such a hype. ;-)
