### ISSUE TITLE
Required changes due to changes in `standardize_parameters`

### ISSUE THREAD

**Issue by mattansb** [easystats/parameters#301]
***For the next release round***
Changes in `effectsize::standardize_parameters()` - it now directly calls `model_parameters()` (there will not be any recursion)
https://github.com/easystats/effectsize/issues/129

These require 2 changes to `parameters`:

1. Remove / change `ci()` / `standard_error()` methods.
2. Change how standardized values are produced:

`standardize_parameters()` now has a method for `model_parameters()`:

``` r
library(effectsize)

model <- lme4::lmer(mpg ~ wt + (1 | gear), data = mtcars)
standardize_parameters(model, "basic")
#> Parameter   | Coefficient (std.) |         95% CI
#> -------------------------------------------------
#> (Intercept) |               0.00 | [ 0.00,  0.00]
#> wt          |              -0.82 | [-1.02, -0.62]
#> 
#> # Standardization method: Basic



pars <- parameters::model_parameters(model)
standardize_parameters(pars, "basic")
#> Parameter   | Coefficient (std.) |         95% CI
#> -------------------------------------------------
#> (Intercept) |               0.00 | [ 0.00,  0.00]
#> wt          |              -0.82 | [-1.02, -0.62]
#> 
#> # Standardization method: Basic
```

<sup>Created on 2020-09-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

So essentially, model parameters can look like this:

```R
model_parameters <- function(model, standardize = NULL, ...) {
  if (!is.null(standardize) && standardize == "refit") {
    model <- effectsize::standardize(model, ...)
    standardize <- NULL
  }
  
  
  ### DO ALL THE THINGS
  ### DO ALL THE THINGS
  ### DO ALL THE THINGS
  ### DO ALL THE THINGS
  
  
  if (!is.null(standardize)) {
    std_parms <- effectsize::standardize_parameters(out, method = standardize, ...)
    out<- merge(out, std_parms) # or something? replace the correct columns?
  }
}
```

**Comment by strengejacke** [comment]
What about SE? Still available as attributes, or as columns that are not printed by default?

**Comment by mattansb** [comment]
An attribute.

**Comment by strengejacke** [comment]
The more I think about this, I'm not sure if the recursion is actually resolved. `model_parameters()` still needs to call effectsize-functions, or does `effectsize::standardize_parameters()` no longer call `model_parameters()`?

**Comment by DominiqueMakowski** [comment]
well, recursions usually mean bad design decisions 😁 

I would it conceptually it makes sense to me that parameters only return parameters directly related to the passed model, whereas effectsize computes "additional" indices. And having the merge occur at a later stage (e.g., via `report_table()`, in line with report's goal to be mostly a combiner of easystats' parts). It would make the general pipeline cleaner imo, "you have `parmeters::parameters()` to get the parameters table, `effectsize::effectsize()` to get effect sizes, `performance::performance()` to get the performance table, and `report_table()` to put them together.

But no rush imo, we could start thinking about cleaning or not once a merger is actually existing and on cran (SOON ^^). We could also then make a pool to see whether people mostly use effectsize() independently, or within parameters(), etc., to get some data about easystats' patterns of usage.

**Comment by mattansb** [comment]
There is no longer a recursion problem.

Although `effectsize::standardize_parameters.default()` does use `parameters` (so `effectsize` *depends* on `parameters`),

`effectsize::standardize_parameters.parameters_model()` does not, and can be used by `parameters` at the end of the processing safely (and so `parameters *suggests* `effectsize`).

**Comment by strengejacke** [comment]
Does `effectsize::standardize_parameters.parameters_model()` work with different standardize-methods? (posthoc, refit, ...)?

**Comment by strengejacke** [comment]
> well, recursions usually mean bad design decisions 😁

It wasn't me who voted for moving `standardize()` to effectsize! 😬

**Comment by strengejacke** [comment]
> I would say it conceptually it makes sense to me that parameters only return parameters directly related to the passed model, whereas effectsize computes "additional" indices.

I still don't consider standardized parameters as a "real" effect-size (or: it's a non-pétit-deux measure), but rather a "basic" functionality in _parameters_ that _should_ be possible to compute with `model_parameters()`.

**Comment by strengejacke** [comment]
> `effectsize::standardize_parameters.parameters_model()` does not, and can be used by `parameters` at the end of the processing safely (and so `parameters *suggests* `effectsize`).

I'm not sure this will work, as the standardization of coefficients is done before the final object has the class `"parameters_model"`?

**Comment by mattansb** [comment]
> Does effectsize::standardize_parameters.parameters_model() work with different standardize-methods? (posthoc, refit, ...)?

Yes!

> I'm not sure this will work, as the standardization of coefficients is done before the final object has the class "parameters_model"? And also the required attributes you're relying on are all added at the end of the model_parameters() function.

Is it not possible to save the addition/replacement of standardized coefs to the very last step? It should be relatively straight forward: pass the table, get the standardized coefs, add / replace them in the table. Done.

**Comment by strengejacke** [comment]
We do the complete parameter processing first, then finally add all relevant attributes. Since we use `merge()` quite often for the first steps, attributes would get lost. So it's quite a hassle changing this order. But in either way, I can still do what you suggested in your initial post?

**Comment by mattansb** [comment]
What I mean to suggested in the original post is:
- If method "refit", do that **first**,
- If method is "posthoc" (etc), do it **last** (or at least after the `ci`, `obj_name`, `exponentiate` attributes and the `parameters_model` class have been set).

This last part can look like this:
```
if (!is.null(standardize)) {
  std_parms <- effectsize::standardize_parameters(out, method = standardize)
  icol1 <- c("Coefficient","CI_high","CI_low")[c("Coefficient","CI_high","CI_low") %in% colnames(out)]
  icol2 <- c("Std_Coefficient","CI_high","CI_low")[c("Std_Coefficient","CI_high","CI_low") %in% colnames(out)]
  out[icol1] <- std_parms[icol2]
  out$SE <- attr(std_parms, "standard_error")
}
```

Which keeps all the attributes of `out`.

---

Of course you can leave it as it is now and it will continue to work (if you do this, you need to pass `exponentiate` to `standardize_parameters(exponentiate = exponentiate)`), but since `standardize_parameters.default()` calls `parameters::model_parameters()` it is inefficient as it needs to reconstruct the `parameters_model` object when it does so. 


---

I can (try) make a PR with these changes if you'd like.

**Comment by strengejacke** [comment]
> Which keeps all the attributes of out.

The only problem is that all the attributes are added in a later step, not in the helper-function `.extract_parameters_*()`.

**Comment by mattansb** [comment]
I think I can still make this work.
I'll open a new branch and make a PR.
