### ISSUE TITLE
having consistent column names in output dataframes

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/parameters#304]
I don't think we should be renaming the coefficient column _only_ when the estimates are standardized because we are not doing something similar when we exponentiate them or use robust method to assess their significance. Since the user chooses to specify this argument, they are expected to be aware of this, so we don't need to indicate this with column name change.

What do you think?

```r
    set.seed(123)
    library(parameters)

    mod <- stats::lm(formula = Sepal.Length ~ Species, data = iris)

    # base
    model_parameters(mod) 
    #> Parameter            | Coefficient |   SE |       95% CI |     t |  df |      p
    #> -------------------------------------------------------------------------------
    #> (Intercept)          |        5.01 | 0.07 | [4.86, 5.15] | 68.76 | 147 | < .001
    #> Species [versicolor] |        0.93 | 0.10 | [0.73, 1.13] |  9.03 | 147 | < .001
    #> Species [virginica]  |        1.58 | 0.10 | [1.38, 1.79] | 15.37 | 147 | < .001

    # no change
    model_parameters(mod, exponentiate = TRUE)
    #> Parameter            | Coefficient |    SE |           95% CI |     t |  df |      p
    #> ------------------------------------------------------------------------------------
    #> (Intercept)          |      149.31 | 10.87 | [129.30, 172.41] | 68.76 | 147 | < .001
    #> Species [versicolor] |        2.53 |  0.26 | [  2.07,   3.11] |  9.03 | 147 | < .001
    #> Species [virginica]  |        4.86 |  0.50 | [  3.97,   5.96] | 15.37 | 147 | < .001

    # no change
    model_parameters(mod, robust = TRUE)
    #> Parameter            | Coefficient |   SE |       95% CI |     t |  df |      p
    #> -------------------------------------------------------------------------------
    #> (Intercept)          |        5.01 | 0.05 | [4.91, 5.11] | 99.41 | 147 | < .001
    #> Species [versicolor] |        0.93 | 0.09 | [0.75, 1.11] | 10.42 | 147 | < .001
    #> Species [virginica]  |        1.58 | 0.10 | [1.38, 1.79] | 15.23 | 147 | < .001

    # change
    model_parameters(mod, standardize = TRUE) 
    #> Parameter            | Coefficient (std.) |   SE |       95% CI |     t |  df |      p
    #> --------------------------------------------------------------------------------------
    #> (Intercept)          |               5.01 | 0.07 | [4.86, 5.15] | 68.76 | 147 | < .001
    #> Species [versicolor] |               0.93 | 0.10 | [0.73, 1.13] |  9.03 | 147 | < .001
    #> Species [virginica]  |               1.58 | 0.10 | [1.38, 1.78] | 15.37 | 147 | < .001
```
<sup>Created on 2020-09-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by mattansb** [comment]
ifaik `robust = TRUE` doesn't affect the coefficients, only the SE/CI.

I would argue the other way around though - when `exponentiate = TRUE` maybe it should be `Coefficient [exp]`?

There is a fine line to walk here between not being informative enough (looking at you `broom`) and having `df [S]` / `df [KR]` / `SE [robust]` / `95% CI [robust]` (but maybe these aren't such a bad idea...?)

**Comment by DominiqueMakowski** [comment]
Agreed with `Coefficient (exp.)` and by default being explicit, and then people can still use the name standardized function if they want something closer to broom

**Comment by IndrajeetPatil** [comment]
Okay, as long as we are internally consistent, I am fine with changing the column names.

So I will keep this open to remind us to rename the columns in question.

**Comment by strengejacke** [comment]
We indeed started with different column names for standardized and non-standardized, which was a rather "historical". We currently save some information as attributes, for instance in _see_, when plotting model parameters, the axis is labelled with "exp(estimates)" or so.

My question is, looking at all the places in the code where we need to do some changes so it works with another renamed column, should we really rename the column, or just change the print-method, so we check for attributes whether `exponentiate = TRUE` was used and just change the name of the column in the printed output?

**Comment by mattansb** [comment]
Taken to the extreme, should all user input be stored as column names / attributes? And if as attributes, should they be printed?
(Not just for `parameters`, also for `bayestestR`, `effectsize`, etc...)

**Comment by strengejacke** [comment]
For the print-method, we could also think about "context specific names", something like (code from sjPlot):

```r
    axis.title <- dplyr::case_when(
      is.null(transform) && fitfam$is_binomial ~ "Log-Odds",
      is.null(transform) && fitfam$is_ordinal ~ "Log-Odds",
      is.null(transform) && fitfam$is_multinomial ~ "Log-Odds",
      is.null(transform) && fitfam$is_categorical ~ "Log-Odds",
      is.null(transform) && fitfam$is_count ~ "Log-Mean",
      fitfam$is_count ~ "Incidence Rate Ratios",
      fitfam$is_ordinal ~ "Odds Ratios",
      fitfam$is_multinomial ~ "Odds Ratios",
      fitfam$is_categorical ~ "Odds Ratios",
      fitfam$is_binomial && !fitfam$is_logit ~ "Risk Ratios",
      fitfam$is_binomial ~ "Odds Ratios",
      TRUE ~ "Coefficient"
    )
```

But maybe OR, RR etc. instead of the long forms (but preserve "Log-...", because else not intuitive).

**Comment by strengejacke** [comment]
``` r
library("pscl")
#> Classes and Methods for R developed in the
#> Political Science Computational Laboratory
#> Department of Political Science
#> Stanford University
#> Simon Jackman
#> hurdle and zeroinfl functions by Achim Zeileis
library("parameters")

data("bioChemists")
m <- zeroinfl(art ~ fem + mar + kid5 + ment | kid5 + phd, data = bioChemists)

model_parameters(m)
#> # Fixed Effects component
#> 
#> Parameter     | Log-Mean |       SE |         95% CI |     z |      p
#> ---------------------------------------------------------------------
#> (Intercept)   |     0.56 |     0.07 | [ 0.43,  0.69] |  8.26 | < .001
#> fem [Women]   |    -0.23 |     0.06 | [-0.34, -0.11] | -3.91 | < .001
#> mar [Married] |     0.14 |     0.07 | [ 0.01,  0.27] |  2.07 | 0.038 
#> kid5          |    -0.17 |     0.05 | [-0.26, -0.07] | -3.43 | < .001
#> ment          |     0.02 | 2.12e-03 | [ 0.02,  0.03] | 10.05 | < .001
#> 
#> # Zero-Inflated component
#> 
#> Parameter   | Log-Odds |   SE |         95% CI |     z |     p
#> --------------------------------------------------------------
#> (Intercept) |    -0.93 | 0.43 | [-1.78, -0.08] | -2.14 | 0.032
#> kid5        |     0.05 | 0.22 | [-0.38,  0.47] |  0.21 | 0.831
#> phd         |    -0.25 | 0.14 | [-0.51,  0.02] | -1.84 | 0.065

model_parameters(m, exponentiate = TRUE)
#> # Fixed Effects component
#> 
#> Parameter     |  IRR |       SE |       95% CI |     z |      p
#> ---------------------------------------------------------------
#> (Intercept)   | 1.75 |     0.12 | [1.53, 2.00] |  8.26 | < .001
#> fem [Women]   | 0.79 |     0.05 | [0.71, 0.89] | -3.91 | < .001
#> mar [Married] | 1.15 |     0.08 | [1.01, 1.30] |  2.07 | 0.038 
#> kid5          | 0.85 |     0.04 | [0.77, 0.93] | -3.43 | < .001
#> ment          | 1.02 | 2.17e-03 | [1.02, 1.03] | 10.05 | < .001
#> 
#> # Zero-Inflated component
#> 
#> Parameter   | Odds Ratio |   SE |       95% CI |     z |     p
#> --------------------------------------------------------------
#> (Intercept) |       0.39 | 0.17 | [0.17, 0.92] | -2.14 | 0.032
#> kid5        |       1.05 | 0.23 | [0.69, 1.60] |  0.21 | 0.831
#> phd         |       0.78 | 0.11 | [0.60, 1.02] | -1.84 | 0.065
```

<sup>Created on 2020-09-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
May I raise all your attention to this post again: https://github.com/easystats/parameters/issues/304#issuecomment-696627556

How are, e.g., coefficients of `Gamma(link = "log")` called? Or `Gamma(link = "inverse")`? I mean "named" in the meaning of "Odds Ratios" etc.

**Comment by strengejacke** [comment]
@mattansb ?

**Comment by mattansb** [comment]
Not sure why you tagged me?

I think either option (actual column name, or just in the printing) is fine.. no strong opinion here (:

**Comment by strengejacke** [comment]
https://github.com/easystats/parameters/issues/304#issuecomment-696627556

**Comment by IndrajeetPatil** [comment]
> May I raise all your attention to this post again: [#304 (comment)](https://github.com/easystats/parameters/issues/304#issuecomment-696627556)
> 
> How are, e.g., coefficients of `Gamma(link = "log")` called? Or `Gamma(link = "inverse")`? I mean "named" in the meaning of "Odds Ratios" etc.

All the other names look good to me. 
But, unfortunately, I don’t have any idea about how this ought to be named.

**Comment by strengejacke** [comment]
@mattansb I would not change the column names, but for the print, the "type" of coefficient. For special models, I have no clear idea what the coefficients exactly represent (odds, irr, ...)

**Comment by IndrajeetPatil** [comment]
Is this something we should query on Twitter? 
Maybe there are experts there who can help us with this?

**Comment by strengejacke** [comment]
e.g. here: https://www.stata.com/statalist/archive/2011-09/msg00794.html

I.e., exp(coef) for Gamma(log) would be "mean ratio" (instead of odds ratio)

**Comment by mattansb** [comment]
Ah, well I also don't know all the types 😅 (the code from sjPlot looks good) - but as it's not saved in the column name itself, but as an attribute, this would also be easier to change in a later date if we want to update what we know.

**Comment by DominiqueMakowski** [comment]
Overall I think that another option to consider would be to keep the printed column name consistent with the dataframe's column name, and keep it the same (for instance, Coefficient). And then print below in blue as we do in many other places some details, like "Coefficients are expressed in log-odds ratio" etc.

This would imo avoid any confusion when users query the dataframe (i.e., they would search for Coefficient because it's what is written and would find it accordingly), still provide the information to the user and also suggest to developers that this information is included in the object as attribute (as opposed to hardcoded as a column name)

**Comment by strengejacke** [comment]
hm... no! 😬

**Comment by mattansb** [comment]
This goes against the "no generic names" guideline we have (unlike `broom`)...

**Comment by strengejacke** [comment]
Well, we actually do _not_ rename the column, but rather only change the output of `print()`, so we still have the generic `"Coefficient"` as column name, and only "log-odds" or "Odds Ratio" etc. in the console. But just related to the "visible result", yes, we aim at having `model_parameters()` "context-specific". So I would also keep the column headers in the output as we have it now (using Coefficient, or log-odds, or ...).

**Comment by DominiqueMakowski** [comment]
But that's the thing, here we're kinda in between, we have a stable column name (Coefficient) but it gets printed as if it was different it's quite confusing... Either we go full specificity and we rename it for real (and so at least it is consistent between the printing and the object) or we keep it as is (and print "Coefficient") but add the information below.

So far most of our printing changes have been fairly aesthetic (e.g., printing a column like 95% CI instead of CI_low and CI_high), but printing something else entirely (logodds instead of coefficient) is kinda strange

**Comment by strengejacke** [comment]
> So far most of our printing changes have been fairly aesthetic

CI -> three columns in data frame, one in output, with renamed column header
statistic and df -> two columns in data frame, one in output, with renamed column header
Component -> one column in data frame, no(!) in output (rather, separated tables)

I'm not sure changing the column header for "Coefficient" is the big thing that leads to master confusion here?

**Comment by DominiqueMakowski** [comment]
> I'm not sure changing the column header for "Coefficient" is the big thing that leads to master confusion here?

Accurate depiction of a regular easystats user trying to do `params$Log-Odds` 👍 

![](https://media.giphy.com/media/3jN3GziOKUEmI/giphy.gif) 

I think it's somewhat different than what we do with CI, stats(df) etc., and also I suspect coefficients are extracted more often than the `df` column.

I don't see the drawback of having a nice little informational sentence written in the easystasts' blue style. `emmeans` does something similar if I recall, printing the param type on the side, which is nice and clear I think.

And another reason is conceptual, when we transform `t` and `df_error` into `t(df)` or with the CI, we don't really change the meaning, we just present it differently. Whereas here we change the meaning, because even though the values in the column are log odds (or anything else, really), this is just their *type*, but it is still the coefficient column. The values are coefficients, which is the important thing, and then the fact that it is log odds or exponentiated values or whatnot is an additional clarifying piece of information, but it does not change the fact that they are coefficients. TLDR; keeping coefficient is philosophically right

**Comment by strengejacke** [comment]
But aesthetically speaking, "Log-Odds" (or ...) is shorter than "Coefficient", making the output more readable when having less wide columns. 🚀  But I see your point, though I'm still not sure if it's a big issue here... I expect *users* who don't care about / need column names, or *developers* / *coders*, who are able to realize the underlying structure of the object.

**Comment by mattansb** [comment]
Both options (don't change column name in printing + add blue row, and change column name in printing) sound fine to me.

(But NOT changing the actual column name! That would break all of `effectsize`!)

**Comment by strengejacke** [comment]
> (But NOT changing the actual column name! That would break all of effectsize!)

No, that would literally break all packages ;-)

**Comment by strengejacke** [comment]
@DominiqueMakowski If you have a nice looking, readable, compact and convincing solution for:

``` r
library(parameters)
suppressPackageStartupMessages(library(pscl))
data("bioChemists")
  
model <- zeroinfl(art ~ fem + mar + kid5 + ment | kid5 + phd, data = bioChemists)
model_parameters(model, exponentiate = TRUE)
#> # Fixed Effects 
#> 
#> Parameter     |  IRR |       SE |       95% CI |     z |      p
#> ---------------------------------------------------------------
#> (Intercept)   | 1.75 |     0.12 | [1.53, 2.00] |  8.26 | < .001
#> fem [Women]   | 0.79 |     0.05 | [0.71, 0.89] | -3.91 | < .001
#> mar [Married] | 1.15 |     0.08 | [1.01, 1.30] |  2.07 | 0.038 
#> kid5          | 0.85 |     0.04 | [0.77, 0.93] | -3.43 | < .001
#> ment          | 1.02 | 2.17e-03 | [1.02, 1.03] | 10.05 | < .001
#> 
#> # Zero-Inflated 
#> 
#> Parameter   | Odds Ratio |   SE |       95% CI |     z |     p
#> --------------------------------------------------------------
#> (Intercept) |       0.39 | 0.17 | [0.17, 0.92] | -2.14 | 0.032
#> kid5        |       1.05 | 0.23 | [0.69, 1.60] |  0.21 | 0.831
#> phd         |       0.78 | 0.11 | [0.60, 1.02] | -1.84 | 0.065
```

<sup>Created on 2020-10-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I'll add a blue line instead of changing column headers...

**Comment by strengejacke** [comment]
You have time until _effectsize_ is submitted to CRAN, because then _parameters_ will be submitted immediately afterwards as well... 😝

**Comment by mattansb** [comment]
I better submit soon then, to not give him a chance! 🤣

**Comment by strengejacke** [comment]
![aeb01108d342546c1970615ecd2da754](https://user-images.githubusercontent.com/26301769/96978797-0bbc6e80-151f-11eb-9756-9cdb154f71c8.gif)

**Comment by strengejacke** [comment]
Ok, @DominiqueMakowski almost missed the chance, I'm running checks and prepare submission...

**Comment by DominiqueMakowski** [comment]
> If you have a nice looking, readable, compact and convincing solution for:

I don't, you've won for this round 🏳️ 😞
