### ISSUE TITLE
Different methods for model parameters standardization

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#31]
Currently, model standardization does the full standardization, meaning that it actually directly standardizes the outcome and predictors (omitting the factors and binary variables) and then refit the model. 

While this is IMHO the most meaningful method to obtain standardized coefs (that can be interpreted, for numeric predictors, as how an increase of 1 SD in the predictor changes the SD of the outcome), it is also slow (necessitating to refit the model), which can be a problem, for instance in Bayesian analyses.

Although a posteriori standardization of parameters does not always make sense (especially for factors and interactions effects), it would be good to allow for different (and faster) standardization methods, such as the simple scaling of parameters based on the outcome's SD.

I am not sure what design would be the best, and several different methods exist.

Some references:

- Bring, J. (1994). How to standardize regression coefficients. The American Statistician, 48(3), 209-213.
- Menard, S. (2004). Six approaches to calculating standardized logistic regression coefficients. The American Statistician, 58(3), 218-223.
- Gelman, A. (2008). Scaling regression inputs by dividing by two standard deviations. Statistics in medicine, 27(15), 2865-2873.
- Schielzeth, H. (2010). Simple means to improve the interpretability of regression coefficients. Methods in Ecology and Evolution, 1(2), 103-113.
- Menard, S. (2011). Standards for standardized logistic regression coefficients. Social Forces, 89(4), 1409-1428.

**Comment by strengejacke** [comment]
I hardly dare to say it, but there is _of course_ also a function in sjstats:
https://github.com/strengejacke/sjstats/blob/master/R/std_b.R

The way how parameters are scaled is the "default" that is used in many statistical packages, so results are not unexpected. The function also includes the standardization from Gelman (by 2 SD), and for mixed models and stanreg objects.

**Comment by strengejacke** [comment]
But [as you can see](https://github.com/strengejacke/sjstats/commit/cc17e7d70e82f9e0084c0c49ef84aba610b23ad7), I'm removing a lot of functions in favor of the easystats packages, where they're much better findable.

**Comment by DominiqueMakowski** [comment]
This time I knew it was in sjstats ☺️ but nevertheless I think this is an important feature for parameters. 

Here's a brief overview (to be improved):

### Refit method

- Standardize data and refit
- Bring et al. (1994): This standardization is sometimes recommended to improve computational accuracy (see Neter, Wasserman, and Kutner, 1989).

### Full

- First, calculate the regression coefficients by using unstandardized variables and then
multiply them by the ratio between the standard deviation of the respective independent variable and the standard deviation of the dependent variable (Bring et al., 1994)
- Menard et al. 2011: For logistic models, `b*M = b(sX)R/slogit(Ŷ)` where b*M is the standardized logistic regression coefficient, b is the unstandardized logistic regression coefficient, sX is he standard deviation of the independent variable X, slogit(Ŷ) is the standard deviation of logit(Ŷ), that is, the standard deviation of the predicted values of logit(Y), and R is the correlation between the observed values of Y (either 0 or 1) and the predicted values of Y (predicted probabilities for each case).


### Partial

![image](https://user-images.githubusercontent.com/8875533/56350332-1e086e80-61fd-11e9-91c0-1a770b4bb2e7.png)

- Menard et al. 2011: For logistic models, Goodman (1972) describes a “standardized” coefficient that is really the normal distribution version of the Wald test statistic for logistic regression, b = b/SE(b), where b is the unstandardized (logit or logistic regression) coefficient and SE(b) is the standard error of that coefficient (Menard 2010)
- Menard et al. 2011: A second approach, suggested for logistic regression models by Menard (1995) and Agresti (1996), is to ignore the variance in logit(Y) and simply standardize the coefficients based on the variance in the predictors, using b = (b)(sX).


### 2 SD

- Gelman, A. (2008): For these reasons, we recommend the general practice of scaling numeric inputs by dividing by two standard deviations, which allows the coefficients to be interpreted in the same way as with binary inputs. (We leave binary inputs unscaled because their coefficients can already be interpreted directly.)
- Implemented [here](https://github.com/cran/arm/blob/master/R/standardize.R) (and sjstats)

**Comment by strengejacke** [comment]
We should definitely include such a function, and also offer different ways of standardizing, including model refit.

**Comment by pdwaggoner** [comment]
For whatever value it may have, I think standardization is a great idea. Most packages do these things (e.g., `car`, `MASS`, `scales` and even the `scale` function in base R). How are you thinking to go about incorporating these tests. Just trying to get a sense of how you guys develop and expand packages.

**Comment by strengejacke** [comment]
You mean the technical approach? First, writing a generic

```r
standardize_coefficients <- function(x, ...) {
  UseMethod("standardize_coefficients")
}
```

and then the related methods for objects, like `standardize_coefficients.lm` etc. I would start with what we have already done, so copying the code from _sjstats_. Then add step by step methods for other models / objects.

**Comment by DominiqueMakowski** [comment]
I gave it a try (on the dev branch).

I also added a small testing suite code to help to compare the new solutions and methods to other ones:

``` r
library(parameters)
library(insight)
library(dplyr)
library(sjstats)
library(MuMIn)
library(lm.beta)

data <- dplyr::mutate(iris, Group_Sepal.Width = ifelse(Sepal.Width > 3, "High", "Low"))
model <- lm(Sepal.Length ~ Species * Petal.Width * Sepal.Width + poly(Petal.Length, 2), data=data)

out <- insight::get_parameters(model)
for(method in c("refit", "full")){
  for(robust in c(FALSE, TRUE)){
    std <- data.frame(x = standardize_parameters(model, method=method, robust=robust)$estimate)
    names(std) <- paste0(method, "robust", robust)
    out <- cbind(out, std)
  }
}

out$MuMin <- MuMIn::std.coef(model, partial.sd=FALSE)[, 1]
out$sjstats <- c(NA, sjstats::std_beta(model)[, 2])
out$lm.beta <- lm.beta::lm.beta(model)$standardized.coefficients
knitr::kable(out, digits=2)
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;">parameter</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">refitrobustFALSE</th>
<th style="text-align: right;">refitrobustTRUE</th>
<th style="text-align: right;">fullrobustFALSE</th>
<th style="text-align: right;">fullrobustTRUE</th>
<th style="text-align: right;">MuMin</th>
<th style="text-align: right;">sjstats</th>
<th style="text-align: right;">lm.beta</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">3.71</td>
<td style="text-align: right;">1.01</td>
<td style="text-align: right;">0.89</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Speciesversicolor</td>
<td style="text-align: right;">-0.85</td>
<td style="text-align: right;">-0.86</td>
<td style="text-align: right;">-0.81</td>
<td style="text-align: right;">-1.03</td>
<td style="text-align: right;">-0.82</td>
<td style="text-align: right;">-0.49</td>
<td style="text-align: right;">-0.49</td>
<td style="text-align: right;">-0.49</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Speciesvirginica</td>
<td style="text-align: right;">-4.01</td>
<td style="text-align: right;">-1.34</td>
<td style="text-align: right;">-1.19</td>
<td style="text-align: right;">-4.84</td>
<td style="text-align: right;">-3.86</td>
<td style="text-align: right;">-2.29</td>
<td style="text-align: right;">-2.29</td>
<td style="text-align: right;">-2.29</td>
</tr>
<tr class="even">
<td style="text-align: left;">Petal.Width</td>
<td style="text-align: right;">2.31</td>
<td style="text-align: right;">0.40</td>
<td style="text-align: right;">0.47</td>
<td style="text-align: right;">2.13</td>
<td style="text-align: right;">2.31</td>
<td style="text-align: right;">2.13</td>
<td style="text-align: right;">2.13</td>
<td style="text-align: right;">2.13</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sepal.Width</td>
<td style="text-align: right;">0.80</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.42</td>
<td style="text-align: right;">0.34</td>
<td style="text-align: right;">0.42</td>
<td style="text-align: right;">0.42</td>
<td style="text-align: right;">0.42</td>
</tr>
<tr class="even">
<td style="text-align: left;">poly(Petal.Length, 2)1</td>
<td style="text-align: right;">14.67</td>
<td style="text-align: right;">17.72</td>
<td style="text-align: right;">14.13</td>
<td style="text-align: right;">17.72</td>
<td style="text-align: right;">14.13</td>
<td style="text-align: right;">1.45</td>
<td style="text-align: right;">1.45</td>
<td style="text-align: right;">1.45</td>
</tr>
<tr class="odd">
<td style="text-align: left;">poly(Petal.Length, 2)2</td>
<td style="text-align: right;">1.69</td>
<td style="text-align: right;">2.05</td>
<td style="text-align: right;">1.63</td>
<td style="text-align: right;">2.05</td>
<td style="text-align: right;">1.63</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">0.17</td>
</tr>
<tr class="even">
<td style="text-align: left;">Speciesversicolor:Petal.Width</td>
<td style="text-align: right;">-1.00</td>
<td style="text-align: right;">-1.00</td>
<td style="text-align: right;">-1.09</td>
<td style="text-align: right;">-0.92</td>
<td style="text-align: right;">-1.00</td>
<td style="text-align: right;">-0.77</td>
<td style="text-align: right;">-0.77</td>
<td style="text-align: right;">-0.77</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Speciesvirginica:Petal.Width</td>
<td style="text-align: right;">-0.05</td>
<td style="text-align: right;">-0.63</td>
<td style="text-align: right;">-0.68</td>
<td style="text-align: right;">-0.05</td>
<td style="text-align: right;">-0.05</td>
<td style="text-align: right;">-0.06</td>
<td style="text-align: right;">-0.06</td>
<td style="text-align: right;">-0.06</td>
</tr>
<tr class="even">
<td style="text-align: left;">Speciesversicolor:Sepal.Width</td>
<td style="text-align: right;">0.48</td>
<td style="text-align: right;">0.23</td>
<td style="text-align: right;">0.19</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.20</td>
<td style="text-align: right;">0.76</td>
<td style="text-align: right;">0.76</td>
<td style="text-align: right;">0.76</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Speciesvirginica:Sepal.Width</td>
<td style="text-align: right;">1.22</td>
<td style="text-align: right;">0.51</td>
<td style="text-align: right;">0.41</td>
<td style="text-align: right;">0.64</td>
<td style="text-align: right;">0.52</td>
<td style="text-align: right;">2.08</td>
<td style="text-align: right;">2.08</td>
<td style="text-align: right;">2.08</td>
</tr>
<tr class="even">
<td style="text-align: left;">Petal.Width:Sepal.Width</td>
<td style="text-align: right;">-0.62</td>
<td style="text-align: right;">-0.25</td>
<td style="text-align: right;">-0.27</td>
<td style="text-align: right;">-0.32</td>
<td style="text-align: right;">-0.26</td>
<td style="text-align: right;">-1.73</td>
<td style="text-align: right;">-1.73</td>
<td style="text-align: right;">-1.73</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Speciesversicolor:Petal.Width:Sepal.Width</td>
<td style="text-align: right;">-0.03</td>
<td style="text-align: right;">-0.01</td>
<td style="text-align: right;">-0.01</td>
<td style="text-align: right;">-0.01</td>
<td style="text-align: right;">-0.01</td>
<td style="text-align: right;">-0.06</td>
<td style="text-align: right;">-0.06</td>
<td style="text-align: right;">-0.06</td>
</tr>
<tr class="even">
<td style="text-align: left;">Speciesvirginica:Petal.Width:Sepal.Width</td>
<td style="text-align: right;">-0.21</td>
<td style="text-align: right;">-0.08</td>
<td style="text-align: right;">-0.09</td>
<td style="text-align: right;">-0.11</td>
<td style="text-align: right;">-0.09</td>
<td style="text-align: right;">-0.75</td>
<td style="text-align: right;">-0.75</td>
<td style="text-align: right;">-0.75</td>
</tr>
</tbody>
</table>

<sup>Created on 2019-04-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by DominiqueMakowski** [comment]
Currently, all "external" packages (sjstats MuMin and lm.beta) give the same results. Some of these results are far from the implemented methods.

**Comment by DominiqueMakowski** [comment]
Here's a clearer version with only the difference from refit (the baseline):
``` r
library(parameters)
library(insight)
library(dplyr)
library(sjstats)
library(MuMIn)
library(lm.beta)

data <- dplyr::mutate(iris, Group_Sepal.Width = ifelse(Sepal.Width > 3, "High", "Low"))
model <- lm(Sepal.Length ~ Species * Petal.Width * Sepal.Width + poly(Petal.Length, 2), data=data)

out <- standardize_parameters(model, method="refit", robust=FALSE)
robust_true <- standardize_parameters(model, method="refit", robust=FALSE)$estimate

out$full <- out$estimate - standardize_parameters(model, method="full", robust=FALSE)$estimate
out$full_robust <- robust_true - standardize_parameters(model, method="full", robust=FALSE)$estimate


# out$MuMin <- out$estimate - MuMIn::std.coef(model, partial.sd=FALSE)[, 1]
out$sjstats <- out$estimate - c(NA, sjstats::std_beta(model)[, 2])
out$lm.beta <- out$estimate - lm.beta::lm.beta(model)$standardized.coefficients
out <- dplyr::select(out, -estimate)
knitr::kable(out, digits=2)
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;">parameter</th>
<th style="text-align: right;">full</th>
<th style="text-align: right;">full_robust</th>
<th style="text-align: right;">sjstats</th>
<th style="text-align: right;">lm.beta</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1.01</td>
<td style="text-align: right;">1.01</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1.01</td>
</tr>
<tr class="even">
<td style="text-align: left;">Speciesversicolor</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">-0.37</td>
<td style="text-align: right;">-0.37</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Speciesvirginica</td>
<td style="text-align: right;">3.49</td>
<td style="text-align: right;">3.49</td>
<td style="text-align: right;">0.94</td>
<td style="text-align: right;">0.94</td>
</tr>
<tr class="even">
<td style="text-align: left;">Petal.Width</td>
<td style="text-align: right;">-1.73</td>
<td style="text-align: right;">-1.73</td>
<td style="text-align: right;">-1.73</td>
<td style="text-align: right;">-1.73</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sepal.Width</td>
<td style="text-align: right;">-0.39</td>
<td style="text-align: right;">-0.39</td>
<td style="text-align: right;">-0.39</td>
<td style="text-align: right;">-0.39</td>
</tr>
<tr class="even">
<td style="text-align: left;">poly(Petal.Length, 2)1</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">16.26</td>
<td style="text-align: right;">16.26</td>
</tr>
<tr class="odd">
<td style="text-align: left;">poly(Petal.Length, 2)2</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.88</td>
<td style="text-align: right;">1.88</td>
</tr>
<tr class="even">
<td style="text-align: left;">Speciesversicolor:Petal.Width</td>
<td style="text-align: right;">-0.08</td>
<td style="text-align: right;">-0.08</td>
<td style="text-align: right;">-0.23</td>
<td style="text-align: right;">-0.23</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Speciesvirginica:Petal.Width</td>
<td style="text-align: right;">-0.59</td>
<td style="text-align: right;">-0.59</td>
<td style="text-align: right;">-0.57</td>
<td style="text-align: right;">-0.57</td>
</tr>
<tr class="even">
<td style="text-align: left;">Speciesversicolor:Sepal.Width</td>
<td style="text-align: right;">-0.02</td>
<td style="text-align: right;">-0.02</td>
<td style="text-align: right;">-0.53</td>
<td style="text-align: right;">-0.53</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Speciesvirginica:Sepal.Width</td>
<td style="text-align: right;">-0.13</td>
<td style="text-align: right;">-0.13</td>
<td style="text-align: right;">-1.57</td>
<td style="text-align: right;">-1.57</td>
</tr>
<tr class="even">
<td style="text-align: left;">Petal.Width:Sepal.Width</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">1.49</td>
<td style="text-align: right;">1.49</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Speciesversicolor:Petal.Width:Sepal.Width</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">0.05</td>
</tr>
<tr class="even">
<td style="text-align: left;">Speciesvirginica:Petal.Width:Sepal.Width</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">0.66</td>
<td style="text-align: right;">0.66</td>
</tr>
</tbody>
</table>

<sup>Created on 2019-04-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by DominiqueMakowski** [comment]
Sorry for this compulsive editing, but it seems like the discrepancies are highly volatile, especially when factors are involed...

**Comment by strengejacke** [comment]
what is full and full_robust?

**Comment by DominiqueMakowski** [comment]
full is the "classic" solution (using SD of response and of predictor), but with particular (and exploratory) treatment of interactions and factors. robust scales by mad instead of SD

**Comment by DominiqueMakowski** [comment]
I think we have a clearer view now of the general design.
