### ISSUE TITLE
Instead of returning `NULL`, can we not return only the following important details that are already included in the `BayesFactor` object?

### ISSUE THREAD

**Issue by strengejacke** [easystats/parameters#317]
Instead of returning `NULL`, can we not return only the following important details that are already included in the `BayesFactor` object?

cc @mattansb 

``` r
# setup
set.seed(123)
library(BayesFactor)
#> Loading required package: coda
#> Loading required package: Matrix
#> ************
#> Welcome to BayesFactor 0.9.12-4.2. If you have questions, please contact Richard Morey (richarddmorey@gmail.com).
#> 
#> Type BFManual() to open the manual.
#> ************
data(raceDolls)

## Compute Bayes factor for independent binomial design, with
## columns as the fixed margin
bf <- contingencyTableBF(raceDolls, sampleType = "indepMulti", fixedMargin = "cols")

bf@bayesFactor
#>                        bf error                     time         code
#> Non-indep. (a=1) 0.596006     0 Tue Oct 13 23:42:07 2020 d23918ae6c6b

bf@denominator@type
#> [1] "independent multinomial"

bf@denominator@prior
#> $a
#> [1] 1
#> 
#> $fixedMargin
#> [1] "cols"
```

<sup>Created on 2020-10-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

_Originally posted by @IndrajeetPatil in https://github.com/easystats/insight/issue_comments/708026316_

**Comment by strengejacke** [comment]
(https://github.com/easystats/insight/issues/191)

**Comment by IndrajeetPatil** [comment]
I would also prefer if this is resolved before the next update round. 

As `easystats`'s house-expert on everything `BayesFactor`, what is your take on this @mattansb?

**Comment by strengejacke** [comment]
I don't know what meaningful parameters could be returned. A Bayes factor I would expect to be returned by `model_performance()` - what else is left here?

**Comment by IndrajeetPatil** [comment]
But that's the issue here, right? 
Currently, it doesn't even return that. It just returns `NULL`, which makes writing wrapper functions around it harder.

**Comment by mattansb** [comment]
Since:

``` r
x <- matrix(c(1,2,3,4,5,6), nrow = 3)*100
parameters::parameters(chisq.test(x))
#> Parameter1 | Chi2(2) |      p |  Method
#> ---------------------------------------
#> x          |   28.00 | < .001 | Pearson
```

<sup>Created on 2020-10-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


Why not just return the Bayes factor?

**Comment by strengejacke** [comment]
?

``` r
set.seed(123)
library(BayesFactor)
library(parameters)
data(raceDolls)
bf <- contingencyTableBF(raceDolls, sampleType = "indepMulti", fixedMargin = "cols")
model_parameters(bf)
#> BF  
#> ----
#> 1.81
```

<sup>Created on 2020-10-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by IndrajeetPatil** [comment]
Yeah, exactly! 

But did you see effectsize PR in which Mattan had tagged us?
I think that’s another option: to return Cramer’s V and its posteriors.

**Comment by mattansb** [comment]
(`effectsize()` does not return the posteriors themselves, only the summary from `bayestestR::describe_posterior()`)

**Comment by strengejacke** [comment]
@IndrajeetPatil Yeah, but that would open the pandora's box here, so that would be something for later, if at all...

**Comment by mattansb** [comment]
Agreed
