### ISSUE TITLE
supporting `verbose` argument for all methods

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/parameters#337]
For some models this argument is unsupported, which can result in an error. I think we should add this argument regardless of whether it is actually relevant for the method or not so that it is not passed to the regression function. 

``` r
library(lqmm)

set.seed(123)

M <- 50
n <- 10
test <- data.frame(x = runif(n*M,0,1), group = rep(1:M,each=n))
test$y <- 10*test$x + rep(rnorm(M, 0, 2), each = n) + rchisq(n*M, 3)
fit.lqmm <- lqmm(fixed = y ~ x, random = ~ 1, group = group,    
                 data = test, tau = 0.5, nK = 11, type = "normal")

parameters::model_parameters(fit.lqmm) 
#> Parameter   | Coefficient |   SE |        95% CI | t(49) |      p
#> -----------------------------------------------------------------
#> (Intercept) |        3.44 | 0.59 | [2.25,  4.64] |  5.79 | < .001
#> x           |        9.26 | 0.55 | [8.16, 10.36] | 16.95 | < .001

parameters::model_parameters(fit.lqmm, verbose = FALSE) 
#> Error in boot.lqmm(object, ...): unused argument (verbose = FALSE)
```

For instances, for a function like following, the function will work for some objects, while not for others because of `verbose` not being present for some methods:

```r
tidy_model_parameters <- function(model, ...) {
  parameters::model_parameters(model, verbose = FALSE, ...) %>%
    parameters::standardize_names(data = ., style = "broom") %>%
    as_tibble(.)
}
```

**Comment by strengejacke** [comment]
You may for now just add `verbose = TRUE` to all function definitions (`model_parameters.*()`) , even if the argument does nothing and will be ignored, just to make sure that errors like the one you mentioned don't occur.

**Comment by strengejacke** [comment]
I'm planning the next updates in the first half of December, just in case you'd like to have this feature for the next update.

**Comment by strengejacke** [comment]
Just in case you'd like to file a PR :-)

**Comment by IndrajeetPatil** [comment]
Working on it now!

**Comment by IndrajeetPatil** [comment]
Also, I am reformatting code to follow the one argument per line (if no. of arguments > 3) approach. I hope that's okay.
It significantly improves readability of the code.

![image](https://user-images.githubusercontent.com/11330453/99255600-73ab5f80-2814-11eb-8db6-eea1e7f04805.png)
