### ISSUE TITLE
model_parameters and p_value

### ISSUE THREAD

**Issue by strengejacke** [easystats/parameters#34]
we might (partially) extract the code from `p_value()` for the different models I added, to write related `model_parameters()` functions, and then just call model-parameters to get the p-values.

**Comment by DominiqueMakowski** [comment]
Although in the end, it would make more sense that the extraction/computation of the p-value is done in `p_value` and that `model_performance` simply calls `p_value`,`ci` and other subfunctions no?

**Comment by strengejacke** [comment]
Usually yes. But as most p-values are based on the extraction of many model parameters that are already computed in `model_parameters()`, I thought it might make sense to go this way.

But it actually depends on the amount of "overload" we have when we first compute `model_parameters()` and then to get p-values from those results for `p_value()`...

**Comment by DominiqueMakowski** [comment]
You're right

**Comment by DominiqueMakowski** [comment]
closing - the implementation has started
