### ISSUE TITLE
letting the user select effect size for chi-square tests

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/parameters#341]
I think we can follow here the same argument schema we used for `parameters::model_parameters.aov`.

Have two arguments for `parameters::model_parameters.htest` - both `NULL` by default and both not releavant for anything but chi-squared test - and then the user can select which argument to use: 
```r
cramer_v = NULL, 
phi = NULL, 
cohens_g = NULL, # relevant only for mcnemar.test
ci = NULL
```

What do you think?

Otherwise, the user can run into a scenario like this where you end up with two different `estimate` columns:

``` r
library(magrittr)
parameters::model_parameters(stats::chisq.test(table(mtcars$am, mtcars$cyl))) %>%
  parameters::standardize_names(., "broom")
#> Warning in stats::chisq.test(table(mtcars$am, mtcars$cyl)): Chi-squared
#> approximation may be incorrect
#>   statistic df  estimate cramers.conf.low cramers.conf.high  estimate
#> 1  8.740733  2 0.5226355        0.1118233         0.8455312 0.5226355
#>   phi.conf.low phi.conf.high    p.value
#> 1    0.1118233     0.8455312 0.01264661
```

<sup>Created on 2020-11-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by strengejacke** [comment]
does cohen's g work for mcnemar?

**Comment by strengejacke** [comment]
we could rename effect size columns like phi, cramers etc. into "coefficient", instead "estimate". @mattansb what do you think?

**Comment by mattansb** [comment]
Yeah, makes sense as they are a type of correlation coefficient.

**Comment by strengejacke** [comment]
Though I'm not sure what the broom convention is... I realize that our approach, being context specific, makes more sense.

**Comment by IndrajeetPatil** [comment]
But even if we rename it to `coefficient`, the same problem will persist since there will now be two columns called `coefficient`. 

I think we can retain the term `estimate`, but just give the users the flexibility to choose the effect size rather than providing all effect sizes available. The latter also has the value of being internally consistent since that's what we are doing with `aov` effect sizes.

**Comment by IndrajeetPatil** [comment]
> does cohen's g work for mcnemar?

It does work:

```r
library(effectsize)
Performance <- rbind(c(794, 86),
                     c(150, 570))
dimnames(Performance) <- list("1st Survey" = c("Approve", "Disapprove"),
                              "2nd Survey" = c("Approve", "Disapprove"))

cohens_g(Performance)
#> Cohen's g |       95% CI
#> ------------------------
#>      0.14 | [0.07, 0.19]
```

So we can also have `cohens_g = NULL` in `.htest` method and support that effect size for `mcnemar.test`.

**Comment by strengejacke** [comment]
But your example did not include any call to the `mcnemar.test()`.

**Comment by IndrajeetPatil** [comment]
I was just responding to your question about whether `cohens_g` works right now. 

What I am saying is, this is what we currently have and it would be nice to complete the table:

test | function | `model_parameters` | `effectsize` | combined output?
----- | --------- | --------------- | -------- | -----------
one-sample proportion test | `stats::chisq.test` | supported | supported | Yes
Pearson's chi-square test | `stats::chisq.test` | supported | supported | Yes
McNemar test | `stats::mcnemar.test` | supported | supported | No

**Comment by strengejacke** [comment]
My question was if `cohens_g()` works for _mcnemar-tests_, and it looks like it does _not_:

``` r
library(effectsize)
Performance <- rbind(c(794, 86),
                     c(150, 570))
dimnames(Performance) <- list("1st Survey" = c("Approve", "Disapprove"),
                              "2nd Survey" = c("Approve", "Disapprove"))

cohens_g(mcnemar.test(Performance))
#> Error in cohens_g(mcnemar.test(Performance)): if 'x' is not a matrix, 'y' must be given
```

<sup>Created on 2020-11-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Hence, I don't see a way how to support that effect size.

**Comment by IndrajeetPatil** [comment]
By that token, we shouldn't also be able to support Cramer's V for `stats::chisq.test`, but we do-

```er
library(effectsize)

cramers_v(stats::chisq.test(table(mtcars$am, mtcars$cyl)))
#> Error in stats::chisq.test(x, y, ...): 'list' object cannot be coerced to type 'double'
```

**Comment by strengejacke** [comment]
No, the difference is that `chisq.test()` contains enough information (element `$observed`) to compute effect sizes, while `mcnemar.test()` does not.

**Comment by strengejacke** [comment]
``` r
library(effectsize)
cramers_v(stats::chisq.test(table(mtcars$am, mtcars$cyl))$observed)
#> Cramer's V |       95% CI
#> -------------------------
#>       0.52 | [0.11, 0.85]
```

<sup>Created on 2020-11-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by IndrajeetPatil** [comment]
Ah, what a bummer! It's frustrating how inconsistent the `htest` objects are in terms of the details they contain.

**Comment by strengejacke** [comment]
Yes, indeed...
