### ISSUE TITLE
What does df_error mean?

### ISSUE THREAD

**Issue by iago-pssjd** [easystats/parameters#349]
If I print `model_parameters`  on a mixed logistic regression through `knitr::kable` I get
```r
library(lme4)
(gm1 <- glmer(cbind(incidence, size - incidence) ~ period + (1 | herd),
              data = cbpp, family = binomial)) # ?glmer example
kable(model_parameters(gm1))


|Parameter   | Coefficient|        SE|    CI_low|    CI_high|         z| df_error|         p|
|:-----------|-----------:|---------:|---------:|----------:|---------:|--------:|---------:|
|(Intercept) |   -1.398343| 0.2312140| -1.851514| -0.9451717| -6.047828|      Inf| 0.0000000|
|period2     |   -0.991925| 0.3031506| -1.586089| -0.3977606| -3.272053|      Inf| 0.0010677|
|period3     |   -1.128216| 0.3228302| -1.760952| -0.4954807| -3.494767|      Inf| 0.0004745|
|period4     |   -1.579745| 0.4220492| -2.406947| -0.7525443| -3.743037|      Inf| 0.0001818|
```
Looking for what `df_error =Inf` can mean I did not find any reference in the `model_parameters` documentation to `df_error`. Can you explain this?

Thank you!

**Comment by strengejacke** [comment]
See here: https://github.com/easystats/parameters/issues/140

We can add this to the docs.

**Comment by strengejacke** [comment]
Regarding your approach in printing the output to markdown: _insight 0.11.0_ was just updated on CRAN. After installation of _insight_ and the latest GitHub version of _parameters_, you can easily create tables in markdown, see [this vignette](https://easystats.github.io/parameters/articles/model_parameters_formatting.html), in particular [the last section](https://easystats.github.io/parameters/articles/model_parameters_formatting.html#formatting-the-parameters-table-in-markdown-1).

**Comment by iago-pssjd** [comment]
Thank you! These are great news.
