### ISSUE TITLE
Object-source

### ISSUE THREAD

**Issue by strengejacke** [easystats/parameters#35]
@DominiqueMakowski 

Where does the object `classify_distribution` in this line come from?

https://github.com/easystats/parameters/blob/62ccdca243e92d383c0bf997494abd5b6e5db6a1/R/find_distribution.R#L63

**Comment by DominiqueMakowski** [comment]
the model stored in `sysdata.R`, which is generated via [this](https://github.com/easystats/blog/pull/3)

**Comment by strengejacke** [comment]
Thanks!
