### ISSUE TITLE
feature request: supporting effect sizes for t-tests

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/parameters#354]
The same way we are using `effectsize` to return effect sizes for contingency table analysis and ANOVAs, we can also do the same for *t*-test.

``` r
mod <- stats::t.test(1:10, y = c(7:20))

parameters::model_parameters(mod)
#> Parameter1 | Parameter2 | Mean_Parameter1 | Mean_Parameter2 | Difference | t(21.98) |      p |          95% CI |                  Method
#> ----------------------------------------------------------------------------------------------------------------------------------------
#> 1:10       |    c(7:20) |            5.50 |           13.50 |      -8.00 |    -5.43 | < .001 | [-11.05, -4.95] | Welch Two Sample t-test

effectsize::effectsize(mod)
#>     d |         95% CI
#> ----------------------
#> -2.32 | [-3.38, -1.22]
```

<sup>Created on 2020-11-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This would mean that `parameters::model_parameters.htest` would gain two more arguments:

```r
  cohens_d = NULL,
  hedges_g = NULL,
```

**Comment by mattansb** [comment]
(Note that `effectsize()` here doesn't actually return Cohen's d, but rather some approximation of it - some general "standardized difference"...)

``` r
mtcars$am <- factor(mtcars$am)

effectsize::effectsize(t.test(mpg ~ am, data = mtcars))
#>     d |         95% CI
#> ----------------------
#> -1.76 | [-2.82, -0.67]

effectsize::cohens_d(mpg ~ am, data = mtcars)
#> Cohen's d |         95% CI
#> --------------------------
#>     -1.48 | [-2.27, -0.67]
```

<sup>Created on 2020-11-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
``` r
library(parameters)
heads <- rbinom(1, size = 100, prob = .5)
x <- c(A = 20, B = 15, C = 25)

colnames(model_parameters(cor.test(mtcars$mpg, mtcars$cyl))) # should be df_error
#> [1] "Parameter1" "Parameter2" "r"          "t"          "df_error"  
#> [6] "p"          "CI_low"     "CI_high"    "Method"

colnames(model_parameters(t.test(mtcars$mpg, mtcars$cyl))) # should be df_error
#>  [1] "Parameter1"      "Parameter2"      "Mean_Parameter1" "Mean_Parameter2"
#>  [5] "Difference"      "t"               "df_error"        "p"              
#>  [9] "CI_low"          "CI_high"         "Method"

colnames(model_parameters(oneway.test(mpg ~ cyl, data = mtcars)))
#> [1] "F"        "df"       "df_error" "p"        "Method"

colnames(model_parameters(chisq.test(x)))
#> [1] "Chi2"   "df"     "p"      "Method"

colnames(model_parameters(prop.test(heads, 100)))
#> [1] "Proportion" "CI_low"     "CI_high"    "Chi2"       "df"        
#> [6] "Null_value" "p"          "Method"

colnames(model_parameters(binom.test(c(682, 243), p = 3/4)))
#> [1] "Probability" "CI_low"      "CI_high"     "Success"     "Trials"     
#> [6] "Null_value"  "p"           "Method"
```

<sup>Created on 2020-11-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by IndrajeetPatil** [comment]
Wrong issue lol

**Comment by strengejacke** [comment]
Hedges' g doesn't work?!?

**Comment by strengejacke** [comment]
``` r
mod <- stats::t.test(1:10, y = c(7:20))
effectsize::hedges_g(mod)
#> Error: Cannot compute effect size for a non-numeric vector.
```

<sup>Created on 2020-11-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by IndrajeetPatil** [comment]
Yeah, that's true. `effectsize::effectsize` gives you some pre-determined effect sizes and that's it.

![image](https://user-images.githubusercontent.com/11330453/100519841-b49f5e80-319a-11eb-8268-b477937e178b.png)

cf. https://github.com/easystats/effectsize/issues/175#issuecomment-709309433

**Comment by strengejacke** [comment]
Ok, just curious why you mentioned to add `hedges_g` as argument.

**Comment by IndrajeetPatil** [comment]
Because I had forgotten about this whole thing. It's only when you mentioned it doesn't work that I thought of it.

But I am wondering if @mattansb would reconsider supporting all effect sizes available via `effectsize::effectsize` to make this possible.

**Comment by mattansb** [comment]
@IndrajeetPatil can you open a new issue on effectsize for supporting multiple indices for htest objects? I'll see what can be done...

**Comment by IndrajeetPatil** [comment]
This is now supported in `effectsize`, so we can support `hedges_g` argument in `model_parameters.htest`:

```r
mod <- stats::t.test(1:10, y = c(7:20))
effectsize::hedges_g(mod)
#> Hedges' g |         95% CI
#> --------------------------
#>     -2.12 | [-3.17, -1.15]
#> 
#> - Estimated using un-pooled SD.
#> - Bias corrected using Hedges and Olkin's method.
```

**Comment by mattansb** [comment]
Indra, do you get push notifications to changes I make in `effectsize` directly into your eyelids?

**Comment by strengejacke** [comment]
not working yet:

``` r
mtcars$am <- factor(mtcars$am)
m <- t.test(mpg ~ am, data = mtcars)
effectsize::effectsize(m, type = "hedges_g")
#> Warning in effectsize.htest(m, type = "hedges_g"): Unable to retrieve data from
#> htest object. Using t_to_d() approximation.
#>     d |         95% CI
#> ----------------------
#> -1.76 | [-2.82, -0.67]
```

<sup>Created on 2020-12-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mattansb** [comment]
Because the formula syntax doesn't work. Try passing vectors.

**Comment by strengejacke** [comment]
I'm a bit confused. When should I use the generic `effectsize()`, and when the specific functions? I just updated the code for `model_parameters.htest()`, so all call `effectsize::effectsize()` because, e.g. `effectsize::cramers_v(model$observed, ci = ci, adjust = cramers_v == "adjusted")` did no longer work for `chisq.test()`...?

**Comment by IndrajeetPatil** [comment]
Sorry, I jumped the gun here and thus the confusion. 

@strengejacke It doesn't yet work, because this commit is still in the `dev` branch:
https://github.com/easystats/effectsize/pull/250

**Comment by mattansb** [comment]
> I'm a bit confused. When should I use the generic effectsize(), and when the specific functions? I just updated the code for model_parameters.htest(), so all call effectsize::effectsize() because, e.g. effectsize::cramers_v(model$observed, ci = ci, adjust = cramers_v == "adjusted") did no longer work for chisq.test()...?

Passing any `htest` to `cohens_d()`, `cramers_v()` etc just passes them on to `effectsize.htest()`. So there shouldn't be a difference... (Now on `main`.)
