### ISSUE TITLE
Unify df names

### ISSUE THREAD

**Issue by mattansb** [easystats/parameters#355]
Based on https://github.com/easystats/parameters/issues/353#issuecomment-735138293,
I suggest renaming all `df` column names to `df` and `df_error` where applicable: 

``` r
library(parameters)

colnames(model_parameters(cor.test(mtcars$mpg, mtcars$cyl))) # should be df_error
#> [1] "Parameter1" "Parameter2" "r"          "t"          "df"        
#> [6] "p"          "CI_low"     "CI_high"    "Method"

colnames(model_parameters(t.test(mtcars$mpg, mtcars$cyl))) # should be df_error
#>  [1] "Parameter1"      "Parameter2"      "Mean_Parameter1" "Mean_Parameter2"
#>  [5] "Difference"      "t"               "df"              "p"              
#>  [9] "CI_low"          "CI_high"         "Method"

colnames(model_parameters(oneway.test(mpg ~ cyl, data = mtcars))) # should be df & df_error
#> [1] "F"        "df_num"   "df_denom" "p"        "Method"
```

<sup>Created on 2020-11-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

These are the only example I could think of, but there might be more...

**Comment by strengejacke** [comment]
``` r
library(parameters)
heads <- rbinom(1, size = 100, prob = .5)
x <- c(A = 20, B = 15, C = 25)

colnames(model_parameters(cor.test(mtcars$mpg, mtcars$cyl))) # should be df_error
#> [1] "Parameter1" "Parameter2" "r"          "t"          "df_error"  
#> [6] "p"          "CI_low"     "CI_high"    "Method"

colnames(model_parameters(t.test(mtcars$mpg, mtcars$cyl))) # should be df_error
#>  [1] "Parameter1"      "Parameter2"      "Mean_Parameter1" "Mean_Parameter2"
#>  [5] "Difference"      "t"               "df_error"        "p"              
#>  [9] "CI_low"          "CI_high"         "Method"

colnames(model_parameters(oneway.test(mpg ~ cyl, data = mtcars)))
#> [1] "F"        "df"       "df_error" "p"        "Method"

colnames(model_parameters(chisq.test(x)))
#> [1] "Chi2"   "df"     "p"      "Method"

colnames(model_parameters(prop.test(heads, 100)))
#> [1] "Proportion" "CI_low"     "CI_high"    "Chi2"       "df"        
#> [6] "Null_value" "p"          "Method"

colnames(model_parameters(binom.test(c(682, 243), p = 3/4)))
#> [1] "Probability" "CI_low"      "CI_high"     "Success"     "Trials"     
#> [6] "Null_value"  "p"           "Method"
```

<sup>Created on 2020-11-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by IndrajeetPatil** [comment]
Btw, this is going to be a breaking change and `CRAN`-revdep will complain about `statsExpressions` breaking. 

Just let them know that you have already informed the maintainer and a revision is on the way. (I've already made the necessary changes.)

**Comment by strengejacke** [comment]
@IndrajeetPatil it will also break "ggstatsplot". Have you prepared a fix as well?

**Comment by IndrajeetPatil** [comment]
Yepp, once `statsExpressions` is fixed, `ggstatsplot` won't have any problems.

**Comment by IndrajeetPatil** [comment]
I will also need `performance` to be on `CRAN` before I can submit `statsExpressios`. 

Do you plan to submit it to `CRAN` today as well?

**Comment by strengejacke** [comment]
_performance_ needs _parameters_ to be on CRAN first, so maybe one day after acceptance of _parameters_.

**Comment by strengejacke** [comment]
sorry, _performance_ requires _insight_, which is already in CRAN...

**Comment by IndrajeetPatil** [comment]
Cool, so maybe that can also be submitted today? 
No worries if you want to wait until tomorrow, but just wanted to see if this was a possibility.

**Comment by strengejacke** [comment]
There were too many hassles with the renaming of `df` to `df_error` for `cor.test()` stuff, so I decided to do this in a later update. Maybe you can prepare your packages so they work with both the current df-name and the future-df-name (df_error)?

**Comment by IndrajeetPatil** [comment]
Sounds good.

**Comment by iago-pssjd** [comment]
I detected this change after updating the package, since previously I manipulated the `df` column of `model_parameters.htest` in my code and then I got an error, so I believe it could be of help having this change reported to the `NEWS` of `0.10.0`.

**Comment by strengejacke** [comment]
sorry, indeed I missed adding that to the NEWS file. At least we added a section on labelling the df in the docs: https://easystats.github.io/parameters/reference/model_parameters.html

**Comment by strengejacke** [comment]
I think `insight::standardize_names()` should standardize df-columns, so you always get `df` as name.

**Comment by strengejacke** [comment]
Is there anything we have to take care of for this issue?

**Comment by IndrajeetPatil** [comment]
Nothing from my side.

**Comment by IndrajeetPatil** [comment]
So what did we ultimately decide?

Will we be renaming every instance of `df` to `df_error` (e.g., `chisq.test` below)? 

Like ripping a band-aid, better to do this in one release than to drag it out over multiple releases with numerous instance of breaking changes.

```r
library(parameters)

as.data.frame(model_parameters(cor.test(mtcars$wt, mtcars$mpg)))
#>   Parameter1 Parameter2          r   CI     CI_low    CI_high         t
#> 1  mtcars$wt mtcars$mpg -0.8676594 0.95 -0.9338264 -0.7440872 -9.559044
#>   df_error            p                               Method
#> 1       30 1.293959e-10 Pearson's product-moment correlation

as.data.frame(model_parameters(chisq.test(c(A = 20, B = 15, C = 25))))
#>   Chi2 df         p                                   Method
#> 1  2.5  2 0.2865048 Chi-squared test for given probabilities

as.data.frame(model_parameters(t.test(1:10, y = c(7:20))))
#>   Parameter1 Parameter2 Mean_Parameter1 Mean_Parameter2 Difference   CI
#> 1       1:10    c(7:20)             5.5            13.5         -8 0.95
#>     CI_low   CI_high        t df_error            p                  Method
#> 1 -11.0528 -4.947198 -5.43493 21.98221 1.855282e-05 Welch Two Sample t-test
```

**Comment by DominiqueMakowski** [comment]
I suppose so, though I wonder if there's any way of nicely printing it cos `df_error` is terrible!

**Comment by strengejacke** [comment]
`df_error` is usually printed as `df`, unless both `df` and `df_error` columns are available.

**Comment by mattansb** [comment]
In `chisq.test` the df is *not* a `df_error` - it is akin to the numerator df of the F statistic, which we denote simply as `df` (:

**Comment by IndrajeetPatil** [comment]
I see. :)

Okay, if there is already method to this madness, should we close this issue? 
I don't think there are any other changes to be made related to this, right?

**Comment by mattansb** [comment]
I think so
