### ISSUE TITLE
incorrect response column and avoiding warning message

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/parameters#356]
Comparing the `parameters` output here with `broom` shows that the `response` column in `parameters` is incorrect.

Additionally, it will be good to avoid the `warning` message.

``` r
# setup
set.seed(123)
library(magrittr)

# model (converting all numeric columns in data to z-scores)
mod <-
  stats::lm(
    formula = cbind(mpg, disp) ~ wt,
    data = effectsize::standardize(mtcars)
  )

parameters::model_parameters(mod) %>%
  parameters::standardize_names(., "broom")
#> Warning in merge.data.frame(parameters, std_err, by = merge_by): column names
#> 'Response.x', 'Response.y' are duplicated in the result
#> Warning in merge.data.frame(parameters, statistic, by = merge_by): column names
#> 'Response.x', 'Response.y' are duplicated in the result
#>          term      estimate  std.error   conf.low  conf.high response
#> 1 (Intercept)  8.052569e-17 0.08933891 -0.1824544  0.1824544      mpg
#> 2          wt -8.676594e-01 0.09076842 -1.0530332 -0.6822855      mpg
#> 3 (Intercept) -1.700398e-16 0.08933891 -0.1824544  0.1824544      mpg
#> 4          wt  8.879799e-01 0.09076842 -1.0530332 -0.6822855      mpg
#>       statistic df.error      p.value response.1
#> 1  9.013507e-16       30 1.000000e+00        mpg
#> 2 -9.559044e+00       30 1.293959e-10        mpg
#> 3  9.013507e-16       30 1.000000e+00        mpg
#> 4 -9.559044e+00       30 1.293959e-10        mpg
```

<sup>Created on 2020-12-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
The warning stems from the wrong processing of mlm-models. I thought we already did support those kinds of models, but it looks like there was still a bug...

**Comment by strengejacke** [comment]
```r
purrr::modify_if(.x = mtcars, .p = is.numeric, ~ {
      as.numeric(scale(.x))
    })
```

This is blasphemous and changes the status of this issue into "wontfix". Will be resolved first when you replace by `effectsize::standardize()`.

**Comment by IndrajeetPatil** [comment]
I have updated my `reprex`. The bug has nothing to do with whether `purrr` is used or `effectsize` to standardize.

**Comment by strengejacke** [comment]
> The bug has nothing to do with whether purrr is used or effectsize to standardize.

I know, but of course we're using _effectsize_ here, as it's more elegant and does all the "if numeric" stuff for you 😬

**Comment by strengejacke** [comment]
So why isn't his issue tagged by [this commit](https://github.com/easystats/parameters/commit/34dd345906a03a48479a61371de7f351cc8ec6a0) , and why isn't GitHub CI starting?

**Comment by strengejacke** [comment]
<sup>(I hope you realized the joke made [here](https://github.com/easystats/parameters/issues/356#issuecomment-738890860))</sup>

**Comment by IndrajeetPatil** [comment]
Yeah, of course 😉 

Force of habit to use tidyverse everywhere 😅

**Comment by DominiqueMakowski** [comment]
```r
purrr::modify_if(.x = mtcars, .p = is.numeric, ~ {
      as.numeric(scale(.x))
    })
```
Totally blasphemous indeed Indra should have a penalty of 24h of not being able to report any new bugs 😁
