### ISSUE TITLE
`exponentiate` standard errors: statistical motivation?

### ISSUE THREAD

**Issue by vincentarelbundock** [easystats/parameters#365]
Hi,

I'm trying to figure out the statistical motivation behind the treatment of standard errors when `exponentiate=TRUE`:

My vague recollection is that you can trivially exponentiate confidence intervals because quantiles are invariant under monotonic transformations, but that this not the case for standard errors or other such statistics. Is that correct? If so, why are we doing this?

```r
 params$SE <- params$Coefficient * params$SE
```

https://github.com/easystats/parameters/blob/master/R/utils_model_parameters.R#L142

**Comment by strengejacke** [comment]
>  If so, why are we doing this?

This is a common behaviour in other statistical packages (like Stata), but even for some R packages (like e.g. emmeans, I think).

**Comment by vincentarelbundock** [comment]
Thanks, you're right. I just checked against Stata 14. Sadly, the manual only states that "standard errors are similarly transformed", which seems like a weird explanation, but whatever.

**Comment by mattansb** [comment]
<sub>Just to note that emmeans uses to delta method, and does not simply transform the SEs 🙃</sub>

**Comment by strengejacke** [comment]
> Just to note that emmeans uses to delta method, and does not simply transform the SEs 🙃

True, I remember a discussion here related to emmeans approach of transforming SEs.

https://github.com/strengejacke/ggeffects/issues/151
