### ISSUE TITLE
feature request: adding methods for `WRS2` objects

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/parameters#367]
I will add these. 

Example of `WRS2` object:

``` r
set.seed(123)
library(WRS2)
t1way(libido ~ dose, data = viagra)
#> Call:
#> t1way(formula = libido ~ dose, data = viagra)
#> 
#> Test statistic: F = 3 
#> Degrees of freedom 1: 2 
#> Degrees of freedom 2: 4 
#> p-value: 0.16 
#> 
#> Explanatory measure of effect size: 0.79 
#> Bootstrap CI: [0.42; 1.33]
```

<sup>Created on 2020-12-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by IndrajeetPatil** [comment]
``` r
set.seed(123)
library(WRS2)
library(parameters)

mod <- t1way(libido ~ dose, data = viagra)

model_parameters(mod)
#> # A heteroscedastic one-way ANOVA for trimmed means
#> 
#> F    | df | df (error) |     p | Effsize |       95% CI |                                            Method
#> -----------------------------------------------------------------------------------------------------------
#> 3.00 |  2 |          4 | 0.160 |    0.79 | [0.42, 1.33] | A heteroscedastic one-way ANOVA for trimmed means
```

<sup>Created on 2020-12-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by strengejacke** [comment]
slightly revised the print method:

``` r
set.seed(123)
library(WRS2)
library(parameters)

mod <- t1way(libido ~ dose, data = viagra)

model_parameters(mod)
#> # A heteroscedastic one-way ANOVA for trimmed means
#> 
#> F    | df | df (error) |     p | Effsize |       95% CI
#> -------------------------------------------------------
#> 3.00 |  2 |          4 | 0.160 |    0.79 | [0.42, 1.33]
```

<sup>Created on 2020-12-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by IndrajeetPatil** [comment]
@strengejacke If there are two examples/models here, do you know why only the first one is rendered on the website? 
https://easystats.github.io/parameters/reference/model_parameters.t1way.html

<img width="895" alt="Screenshot 2020-12-23 at 16 36 01" src="https://user-images.githubusercontent.com/11330453/103013182-01c5e480-453d-11eb-97f1-ea1b3e2906ba.png">

**Comment by strengejacke** [comment]
Not sure, but for examples in if-statements, only the last one is rendered. Maybe there is a particular setting/option? But I'm not aware of it.

**Comment by IndrajeetPatil** [comment]
I see. 

In that case, I think we can retain only one example here. Otherwise, it's a bit of confusing output for the users of the website.

**Comment by mattansb** [comment]
If you warp the first one in `print()` it will also render.

--
Mattan S. Ben-Shachar, PhD student
Department of Psychology & Zlotowski Center for Neuroscience
Ben-Gurion University of the Negev
The Developmental ERP Lab

**Comment by strengejacke** [comment]
> If you warp the first one in `print()` it will also render.

Makes sense. We can try that.
