### ISSUE TITLE
supporting effect sizes for `htest` object from `stats::oneway.test` 

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/parameters#371]
Just like other `aov`-like objects, we can also support here returning effect size measures:

```r
# model
mod <- oneway.test(extra ~ group, data = sleep)

# omega-squared and partial omega-squared are going to be the same here
effectsize::effectsize(mod, type = "omega", partial = TRUE)
#> Warning: `var.equal = FALSE` - effect size is an approximation.
#> Omega2 |       90% CI
#> ---------------------
#>   0.11 | [0.00, 0.36]

# include in parameters?
parameters::model_parameters(mod, omega_squared = "partial")
#> F    | df | df_error |     p |                                                   Method
#> ---------------------------------------------------------------------------------------
#> 3.46 |  1 |    17.78 | 0.079 | One-way analysis of means (not assuming equal variances)
```

**Comment by mattansb** [comment]
(Note that `partial` is effectively ignored because this is a one-way between S model 😊)

**Comment by IndrajeetPatil** [comment]
Yepp, that's why added the comment ;)

> omega-squared and partial omega-squared are going to be the same here

**Comment by mattansb** [comment]
Missed that (:

**Comment by strengejacke** [comment]
``` r
mod <- oneway.test(extra ~ group, data = sleep)
parameters::model_parameters(mod, omega_squared = "partial")
#> Warning: `var.equal = FALSE` - effect size is an approximation.
#> F    | df | df (error) | Omega2 | Omega2 95% CI |     p |                                                   Method
#> ------------------------------------------------------------------------------------------------------------------
#> 3.46 |  1 |      17.78 |   0.11 |  [0.00, 0.41] | 0.079 | One-way analysis of means (not assuming equal variances)
```

<sup>Created on 2020-12-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by IndrajeetPatil** [comment]
Thanks! :)

But why are we supporting here _only_ `omega_squared`? Because `effectsize` also supports eta-squared for this object:

``` r
# model
mod <- oneway.test(extra ~ group, data = sleep)

# omega-squared and partial omega-squared are going to be the same here
effectsize::effectsize(mod, type = "eta", partial = TRUE)
#> Warning: `var.equal = FALSE` - effect size is an approximation.
#> Eta2 |       90% CI
#> -------------------
#> 0.16 | [0.00, 0.42]
```

Maybe we can also add `eta_squared = NULL` to `.add_effectsize_oneway`?

<sup>Created on 2020-12-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by strengejacke** [comment]
Ah okay, didn't know.

**Comment by strengejacke** [comment]
``` r
mod <- oneway.test(extra ~ group, data = sleep)
mp <- parameters::model_parameters(mod, omega_squared = TRUE, eta_squared = TRUE)
#> Warning: `var.equal = FALSE` - effect size is an approximation.

#> Warning: `var.equal = FALSE` - effect size is an approximation.
parameters::print_html(mp)
```



<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#yctuqoxndl .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#yctuqoxndl .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#yctuqoxndl .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#yctuqoxndl .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#yctuqoxndl .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#yctuqoxndl .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#yctuqoxndl .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#yctuqoxndl .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#yctuqoxndl .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#yctuqoxndl .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#yctuqoxndl .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#yctuqoxndl .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#yctuqoxndl .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#yctuqoxndl .gt_from_md > :first-child {
  margin-top: 0;
}

#yctuqoxndl .gt_from_md > :last-child {
  margin-bottom: 0;
}

#yctuqoxndl .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#yctuqoxndl .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#yctuqoxndl .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#yctuqoxndl .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#yctuqoxndl .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#yctuqoxndl .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#yctuqoxndl .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#yctuqoxndl .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#yctuqoxndl .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#yctuqoxndl .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#yctuqoxndl .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#yctuqoxndl .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#yctuqoxndl .gt_left {
  text-align: left;
}

#yctuqoxndl .gt_center {
  text-align: center;
}

#yctuqoxndl .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#yctuqoxndl .gt_font_normal {
  font-weight: normal;
}

#yctuqoxndl .gt_font_bold {
  font-weight: bold;
}

#yctuqoxndl .gt_font_italic {
  font-style: italic;
}

#yctuqoxndl .gt_super {
  font-size: 65%;
}

#yctuqoxndl .gt_footnote_marks {
  font-style: italic;
  font-size: 65%;
}
</style>

<div id="yctuqoxndl" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">

<table class="gt_table">

<thead class="gt_header">

<tr>

<th colspan="9" class="gt_heading gt_title gt_font_normal" style>

One-way analysis of means (not assuming equal variances)

</th>

</tr>

<tr>

<th colspan="9" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style>

</th>

</tr>

</thead>

<thead class="gt_col_headings">

<tr>

<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">

F

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

df

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

df (error)

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

Eta2

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

Eta2 95% CI

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

Omega2

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

Omega2 95% CI

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

p

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

Method

</th>

</tr>

</thead>

<tbody class="gt_table_body">

<tr>

<td class="gt_row gt_left">

3.46

</td>

<td class="gt_row gt_center">

1

</td>

<td class="gt_row gt_center">

17.78

</td>

<td class="gt_row gt_center">

0.16

</td>

<td class="gt_row gt_center">

(0.00, 0.46)

</td>

<td class="gt_row gt_center">

0.11

</td>

<td class="gt_row gt_center">

(0.00, 0.41)

</td>

<td class="gt_row gt_center">

0.079

</td>

<td class="gt_row gt_center">

One-way analysis of means (not assuming equal variances)

</td>

</tr>

</tbody>

<tfoot class="gt_sourcenotes">

</tfoot>

</table>

</div>



<sup>Created on 2020-12-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
# Plain Text

``` r
mod <- oneway.test(extra ~ group, data = sleep)
mp <- parameters::model_parameters(mod, omega_squared = TRUE, eta_squared = TRUE)

mp
#> # One-way analysis of means (not assuming equal variances)
#> 
#> F    | df | df (error) | Eta2 |  Eta2 95% CI | Omega2 | Omega2 95% CI |     p
#> -----------------------------------------------------------------------------
#> 3.46 |  1 |      17.78 | 0.16 | [0.00, 0.46] |   0.11 |  [0.00, 0.41] | 0.079
```

# HTML

``` r
parameters::print_html(mp)
```

<table class="gt_table">

<thead class="gt_header">

<tr>

<th colspan="8" class="gt_heading gt_title gt_font_normal" style>

One-way analysis of means (not assuming equal variances)

</th>

</tr>

<tr>

<th colspan="8" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style>

</th>

</tr>

</thead>

<thead class="gt_col_headings">

<tr>

<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">

F

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

df

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

df (error)

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

Eta2

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

Eta2 95% CI

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

Omega2

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

Omega2 95% CI

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

p

</th>

</tr>

</thead>

<tbody class="gt_table_body">

<tr>

<td class="gt_row gt_left">

3.46

</td>

<td class="gt_row gt_center">

1

</td>

<td class="gt_row gt_center">

17.78

</td>

<td class="gt_row gt_center">

0.16

</td>

<td class="gt_row gt_center">

(0.00, 0.46)

</td>

<td class="gt_row gt_center">

0.11

</td>

<td class="gt_row gt_center">

(0.00, 0.41)

</td>

<td class="gt_row gt_center">

0.079

</td>

</tr>

</tbody>

<tfoot class="gt_sourcenotes">

</tfoot>

</table>

# Markdown

``` r
parameters::print_md(mp)
```

<table>
<caption>One-way analysis of means (not assuming equal variances)</caption>
<thead>
<tr class="header">
<th style="text-align: left;">F</th>
<th style="text-align: center;">df</th>
<th style="text-align: center;">df (error)</th>
<th style="text-align: center;">Eta2</th>
<th style="text-align: center;">Eta2 95% CI</th>
<th style="text-align: center;">Omega2</th>
<th style="text-align: center;">Omega2 95% CI</th>
<th style="text-align: center;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">3.46</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">17.78</td>
<td style="text-align: center;">0.16</td>
<td style="text-align: center;">(0.00, 0.46)</td>
<td style="text-align: center;">0.11</td>
<td style="text-align: center;">(0.00, 0.41)</td>
<td style="text-align: center;">0.079</td>
</tr>
</tbody>
</table>

<sup>Created on 2020-12-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mattansb** [comment]
It also supports the (superior) epsilon squared (:

**Comment by strengejacke** [comment]
@IndrajeetPatil you may check if the `verbose` option works when adding effect sizes for the different htest-objects, and if not, ping @mattansb  (https://github.com/easystats/effectsize/issues/225)

**Comment by strengejacke** [comment]
Is there a partial Epsilon squared?

**Comment by mattansb** [comment]
In general yes, but for `oneway.test` the `partial` is effectively ignored because for one-way between-subject partial==non-partial.

**Comment by strengejacke** [comment]
``` r
mod <- oneway.test(extra ~ group, data = sleep)
parameters::model_parameters(mod, omega_squared = TRUE, eta_squared = TRUE, epsilon_squared = TRUE, verbose = FALSE)
#> Warning: `var.equal = FALSE` - effect size is an approximation.

#> Warning: `var.equal = FALSE` - effect size is an approximation.

#> Warning: `var.equal = FALSE` - effect size is an approximation.
#> # One-way analysis of means (not assuming equal variances)
#> 
#> F    | df | df (error) | Eta2 |  Eta2 95% CI | Omega2 | Omega2 95% CI | Epsilon2 | Epsilon2 95% CI |     p
#> ----------------------------------------------------------------------------------------------------------
#> 3.46 |  1 |      17.78 | 0.16 | [0.00, 0.46] |   0.11 |  [0.00, 0.41] |     0.12 |    [0.00, 0.41] | 0.079
```

<sup>Created on 2020-12-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

(@mattansb: `verbose` not working for `effectsize::effectsize()`)

**Comment by strengejacke** [comment]
> In general yes, but for `oneway.test` the `partial` is effectively ignored because for one-way between-subject partial==non-partial.

Ok, so the docs are correct:

> Logical, if TRUE, computes *partial* Omega, Eta or Epsilon squared as index of effect size. Only applies to objects from oneway.test().

**Comment by mattansb** [comment]
(Added verbose)

> Ok, so the docs are correct:
>> Logical, if TRUE, computes partial Omega, Eta or Epsilon squared as index of effect size. Only applies to objects from oneway.test().

But that is incorrect - not point in having the partial option here, as it does nothing.

**Comment by strengejacke** [comment]
We don't have the partial option here, but should I explicitly mention that it's a partial effect size?

**Comment by mattansb** [comment]
No, because it isn't ^_^

**Comment by mattansb** [comment]
Might be confusing... Maybe "returns the non-partial effect size (since there is nothing to partial out)"?

**Comment by IndrajeetPatil** [comment]
There is a bug here. Whenever `eta_squared` is not `NULL`, epsilon-squared is returned, even if `epsilon_squared = NULL`.

``` r
mod <- stats::oneway.test(extra ~ group, data = sleep)

parameters::model_parameters(mod, eta_squared = "partial")
#> Warning: `var.equal = FALSE` - effect size is an approximation.

#> Warning: `var.equal = FALSE` - effect size is an approximation.
#> # One-way analysis of means (not assuming equal variances)
#> 
#> F    | df | df (error) | Eta2 |  Eta2 95% CI | Epsilon2 | Epsilon2 95% CI |     p
#> ---------------------------------------------------------------------------------
#> 3.46 |  1 |      17.78 | 0.16 | [0.00, 0.46] |     0.12 |    [0.00, 0.41] | 0.079

parameters::model_parameters(mod, eta_squared = "partial", epsilon_squared = NULL)
#> Warning: `var.equal = FALSE` - effect size is an approximation.

#> Warning: `var.equal = FALSE` - effect size is an approximation.
#> # One-way analysis of means (not assuming equal variances)
#> 
#> F    | df | df (error) | Eta2 |  Eta2 95% CI | Epsilon2 | Epsilon2 95% CI |     p
#> ---------------------------------------------------------------------------------
#> 3.46 |  1 |      17.78 | 0.16 | [0.00, 0.46] |     0.12 |    [0.00, 0.41] | 0.079
```

<sup>Created on 2020-12-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                                             
#>  version  R Under development (unstable) (2020-12-16 r79643)
#>  os       Windows 10 x64                                    
#>  system   x86_64, mingw32                                   
#>  ui       RTerm                                             
#>  language (EN)                                              
#>  collate  English_United States.1252                        
#>  ctype    English_United States.1252                        
#>  tz       Europe/Berlin                                     
#>  date     2020-12-22                                        
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version    date       lib source                               
#>  assertthat    0.2.1      2019-03-21 [1] CRAN (R 4.1.0)                       
#>  backports     1.2.1      2020-12-09 [1] CRAN (R 4.1.0)                       
#>  bayestestR    0.8.0.1    2020-12-18 [1] Github (easystats/bayestestR@dbd3aa1)
#>  cli           2.2.0      2020-11-20 [1] CRAN (R 4.1.0)                       
#>  crayon        1.3.4      2017-09-16 [1] CRAN (R 4.1.0)                       
#>  digest        0.6.27     2020-10-24 [1] CRAN (R 4.1.0)                       
#>  effectsize    0.4.1.1    2020-12-21 [1] Github (easystats/effectsize@1f20820)
#>  ellipsis      0.3.1      2020-05-15 [1] CRAN (R 4.1.0)                       
#>  evaluate      0.14       2019-05-28 [1] CRAN (R 4.1.0)                       
#>  fansi         0.4.1      2020-01-08 [1] CRAN (R 4.1.0)                       
#>  fs            1.5.0      2020-07-31 [1] CRAN (R 4.1.0)                       
#>  glue          1.4.2      2020-08-27 [1] CRAN (R 4.1.0)                       
#>  highr         0.8        2019-03-20 [1] CRAN (R 4.1.0)                       
#>  htmltools     0.5.0      2020-06-16 [1] CRAN (R 4.1.0)                       
#>  insight       0.11.1.1   2020-12-22 [1] Github (easystats/insight@55f64e2)   
#>  knitr         1.30       2020-09-22 [1] CRAN (R 4.1.0)                       
#>  lifecycle     0.2.0      2020-03-06 [1] CRAN (R 4.1.0)                       
#>  magrittr      2.0.1      2020-11-17 [1] CRAN (R 4.1.0)                       
#>  parameters    0.10.1.1   2020-12-22 [1] local                                
#>  pillar        1.4.7      2020-11-20 [1] CRAN (R 4.1.0)                       
#>  pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 4.1.0)                       
#>  purrr         0.3.4      2020-04-17 [1] CRAN (R 4.1.0)                       
#>  reprex        0.3.0.9001 2020-08-15 [1] Github (tidyverse/reprex@23a3462)    
#>  rlang         0.4.9      2020-11-26 [1] CRAN (R 4.1.0)                       
#>  rmarkdown     2.6        2020-12-14 [1] CRAN (R 4.1.0)                       
#>  rstudioapi    0.13       2020-11-12 [1] CRAN (R 4.1.0)                       
#>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 4.1.0)                       
#>  stringi       1.5.3      2020-09-09 [1] CRAN (R 4.1.0)                       
#>  stringr       1.4.0      2019-02-10 [1] CRAN (R 4.1.0)                       
#>  styler        1.3.2.9000 2020-11-30 [1] Github (r-lib/styler@d5b8b0e)        
#>  tibble        3.0.4      2020-10-12 [1] CRAN (R 4.1.0)                       
#>  vctrs         0.3.6      2020-12-17 [1] CRAN (R 4.1.0)                       
#>  withr         2.3.0      2020-09-22 [1] CRAN (R 4.1.0)                       
#>  xfun          0.19       2020-10-30 [1] CRAN (R 4.1.0)                       
#>  yaml          2.2.1      2020-02-01 [1] CRAN (R 4.1.0)                       
#> 
#> [1] C:/Users/inp099/Documents/R/win-library/4.1
#> [2] C:/Program Files/R/R-devel/library
```

</details>
