### ISSUE TITLE
WRS2 methods don't seem to work inside function environments

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/parameters#374]
The pretty-printing related attributes seem to be causing some problems here:

``` r
foo <- function(data, x, y) {
  x <- rlang::ensym(x)
  y <- rlang::ensym(y)

  mod <- WRS2::t1way(rlang::new_formula({{ y }}, {{ x }}), data)

  parameters::model_parameters(mod)
}

foo(mtcars, cyl, wt)
#> Error in attr(params, "model_class") <- class(model): attempt to set an attribute on NULL
```

<sup>Created on 2020-12-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

Trace:

```r
Error in attr(params, "model_class") <- class(model) : 
  attempt to set an attribute on NULL 
4. .add_htest_parameters_attributes(parameters, model, ...) at methods_wrs2.R#19
3. model_parameters.t1way(mod) at 1_model_parameters.R#54
2. parameters::model_parameters(mod) 
1. foo(mtcars, cyl, wt) 
```

Should we be using ` .add_htest_parameters_attributes` here? Or should `WRS2` objects get their own ` .add_*` function?

**Comment by strengejacke** [comment]
Instead of model parameters, can you add this code line to the function:

```r
as.character(mod$call)
```

I assume this code fails...

**Comment by strengejacke** [comment]
Ok, the reason was that the above code returned `"WRS2::t1way"`, and you were looking for `"t1way"` only.
