### ISSUE TITLE
renaming different CI columns for t-test outputs

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/parameters#388]
It would be better here to rename `CI_low` and `CI_high` to `Difference_CI_low` and  `Difference_ CI_high`, resp., to make it more explicit what do these CIs correspond to, especially since the corresponding column is separated from them.

``` r
as.data.frame(parameters::model_parameters(
  t.test(1:10, y = c(7:20)),
  standardized_d = TRUE
))
#>   Parameter1 Parameter2 Mean_Parameter1 Mean_Parameter2 Difference        t
#> 1       1:10    c(7:20)             5.5            13.5         -8 -5.43493
#>   df_error   CI_low   CI_high Cohens_d  d_CI_low d_CI_high            p
#> 1 21.98221 -11.0528 -4.947198 -2.19089 -3.281465 -1.188038 1.855282e-05
#>                    Method
#> 1 Welch Two Sample t-test
```

<sup>Created on 2021-01-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by IndrajeetPatil** [comment]
Re-opening this until we reach a consensus about whether #389 was a good idea.

**Comment by DominiqueMakowski** [comment]
I think I'd prefer the paraemter's CI to be moved next to it, but I think it's okay if they are just named `CI`, as throughout easystats the main `CI_*` refers to the estimate

**Comment by DominiqueMakowski** [comment]
We can always add a note in the "return" section saying `The CI_low and CI_high columns (aggregated when printed in the console for visual convenience) refer to the intervals of the estimate` or something

**Comment by IndrajeetPatil** [comment]
Yeah, I agree that there should be consistency in terms of naming columns. I reverted all the changes I had made.

I just changed the order of the columns so that the CIs for difference are right next to it:

``` r
parameters::model_parameters(t.test(1:10, y = c(7:20)), hedges_g = TRUE)
#> # Welch Two Sample t-test
#> 
#> Parameter1 | Parameter2 | Mean_Parameter1 | Mean_Parameter2 | Difference |          95% CI | t(21.98) | Hedges_g |       g 95% CI |      p
#> ------------------------------------------------------------------------------------------------------------------------------------------
#> 1:10       |    c(7:20) |            5.50 |           13.50 |      -8.00 | [-11.05, -4.95] |    -5.43 |    -2.12 | [-3.17, -1.15] | < .001
```

<sup>Created on 2021-01-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
