### ISSUE TITLE
Warning: bad markup (extra space?) 

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#39]
I have these warnings during the checks:

```
Duration: 2m 12.9s

> checking whether package 'parameters' can be installed ... WARNING
  See below...

> checking Rd files ... WARNING
  prepare_Rd: bad markup (extra space?) at describe_distribution.Rd:13:131
  prepare_Rd: bad markup (extra space?) at model_parameters.stanreg.Rd:16:131
  prepare_Rd: bad markup (extra space?) at model_parameters.stanreg.Rd:24:135
  prepare_Rd: bad markup (extra space?) at model_parameters.stanreg.Rd:26:79
  prepare_Rd: bad markup (extra space?) at model_parameters.stanreg.Rd:30:161

0 errors v | 2 warnings x | 0 notes v
Error: R CMD check found WARNINGs
Execution halted

```

Asked on roxygen's repo: https://github.com/klutometis/roxygen/issues/866

**Comment by strengejacke** [comment]
Maybe, to also address this issue (https://github.com/easystats/performance/blob/master/README.md), we should simply copy/paste the docs?

**Comment by DominiqueMakowski** [comment]
Yes... but I am reluctant to do that because then we have to remember to changing the docs in parameters if we update it in bayestestR...

**Comment by DominiqueMakowski** [comment]
And I believe since `report`, `estimate` and all are gonna inherit from parameters... it quickly becomes a nightmare ^^

**Comment by strengejacke** [comment]
I removed all \href tags from the docs, put them into the references from bayestestR, and that seems to resolve this issue, though it's more a workaround than a proper solution.

**Comment by DominiqueMakowski** [comment]
Okay, let's do that for now and leave the issue open on roxygen
