### ISSUE TITLE
changes to frequentist equivalence_test()

### ISSUE THREAD

**Issue by mattansb** [easystats/parameters#405]
To be more consistent with the literature / logic / other packages of ***frequentist*** equivalence testing, I suggest the following:

1. Set default `rule = "classic"`. (As argued elsewhere, the Bayes-method does not comply with the frequentist logic...)
    (This is the default currently already in the `equivalence_test()` used in `effectsize`...)
2. There should be 2 p-values, not just one conditional on the result:
    - A p-value of the TOST (for rejecting H<sub>A</sub> =~ accepting the null)
    - A regular p-value (for rejecting the null). 
    - (Maybe *also* a p-value for rejecting the upper/lower limits of the ROPE? I don't think I've seen this done before...)

**Comment by strengejacke** [comment]
How do the first and third p-value differ? Currently, when H0 is rejected, the "null" to test against for the p-value is the upper or lower ROPE limit.

**Comment by mattansb** [comment]
They would compliment each other, really.

Here's an example using `emmeans`:

``` r
library(emmeans)


m <- lm(mpg ~ factor(am), mtcars)

(em_ <- emmeans(m, ~ am))
#>  am emmean   SE df lower.CL upper.CL
#>   0   17.1 1.12 30     14.9     19.4
#>   1   24.4 1.36 30     21.6     27.2
#> 
#> Confidence level used: 0.95

contrast(em_, "pairwise", delta = 6, side = 2) # TOST
#>  contrast estimate   SE df t.ratio p.value
#>  0 - 1       -7.24 1.76 30 0.706   0.7571 
#> 
#> Statistics are tests of equivalence with a threshold of 6 
#> P values are left-tailed

contrast(em_, "pairwise", null = 0, side = 2) # NHST
#>  contrast estimate   SE df t.ratio p.value
#>  0 - 1       -7.24 1.76 30 -4.106  0.0003

contrast(em_, "pairwise", null = 6, side = 1) # NHST to upper bound
#>  contrast estimate   SE df null t.ratio p.value
#>  0 - 1       -7.24 1.76 30    6 -7.507  1.0000 
#> 
#> P values are right-tailed
contrast(em_, "pairwise", null = -6, side = -1) # NHST to lower bound
#>  contrast estimate   SE df null t.ratio p.value
#>  0 - 1       -7.24 1.76 30   -6 -0.706  0.2429 
#> 
#> P values are left-tailed
```

<sup>Created on 2021-01-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by bwiernik** [comment]
This sort of headache is why I hate the equivalence testing framework... just use a confidence interval! 😜

The equivalence p value is the area of the (cumulative) confidence distribution that is outside of the region of equivalence. So, Σ(area < lower bound) + Σ(area > upper bound). 

For the example above:
```r
ggdist::pstudent_t(-6, 30, mu = -7.24, sigma = 1.76, lower.tail = TRUE) + 
  ggdist::pstudent_t(6, 30, mu = -7.24, sigma = 1.76, lower.tail = FALSE)
# [1] 0.7567365
```

When this proportion is < .05, then >95% of the confidence distribution lies within the equivalence bounds. Or, put more simply IMO, then the entirety of the 95% confidence interval is in the ROPE. 

This picture might be helpful.
![image](https://user-images.githubusercontent.com/4773225/118017594-cfb6f280-b324-11eb-8ea1-24d10efb4d86.png)

**Comment by bwiernik** [comment]
Or if you like terrible hand drawings
![image](https://user-images.githubusercontent.com/4773225/118029925-a00ee700-b332-11eb-83e3-d98962a8d564.png)

**Comment by strengejacke** [comment]
The docs aren't updated yet, but the p-value should now be the correct one.

**Comment by strengejacke** [comment]
``` r
m <- lm(mpg ~ factor(am), mtcars)
parameters::equivalence_test(m, range = c(-6, 6), p_value = TRUE)
#> # TOST-test for Practical Equivalence
#> 
#>   ROPE: [-6.00 6.00]
#> 
#>    Parameter       H0 inside ROPE        90% CI      p
#>  (Intercept) Rejected      0.00 % [15.24 19.06] > .999
#>       am [1] Rejected     29.21 % [ 4.25 10.24]  0.757
```

<sup>Created on 2021-09-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
Should we change it to 1 - p? Because p refers to H0 usually, and these p-values suggest a rather high compatibility with H0?

**Comment by mattansb** [comment]
No, this is how other software shows these p-values (also, on theory basis is makes sense to keep it like this - the test isn't to accept the null, it is to reject a different specification of a different null...)

**Comment by strengejacke** [comment]
Do we need adjustments for multiple testing?

**Comment by mattansb** [comment]
I don't this so - just like you normally don't adjust for multiple testing the t-tests in a regression table.

**Comment by bwiernik** [comment]
The null hypothesis here is "not equivalent", so a small p value is rejecting that and retaining equivalent.  

I agree that that's confusing, but I guess the idea is that small p is what folks are looking for.
