### ISSUE TITLE
is.na() applied to non-(list or vector) of type 'NULL' (R3.4)

### ISSUE THREAD

**Issue by mattansb** [easystats/parameters#417]
This error (https://github.com/easystats/effectsize/pull/283/checks?check_run_id=1825014756) on R3.4 is in:

```
 4. parameters:::model_parameters.default(...)
 5. parameters:::.model_parameters_generic(...)
 6. parameters:::.extract_parameters_generic(...)
 7. parameters:::.n_unique(parameters$Effects)
 9. stats:::na.omit.default(x)
```

**Comment by strengejacke** [comment]
Can you re-run tests and check if it works now?

**Comment by mattansb** [comment]
Yup, seems to work (though the tests on windows for R3.4 fail for some reason... https://github.com/easystats/effectsize/pull/286/checks?check_run_id=1847772798)
