### ISSUE TITLE
summary() method for model_parameters() 

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#419]
Looking at https://github.com/easystats/parameters/pull/418, I thought it could be nice to have a generic summay method that basically "assembles" all columns into one. 

Like it finds the parameter, the CI, the stat, the df, the p etc. and it returns a string like:

"parameters, 95%CI [x, y], t(df) = z, p < .005"

(there's already an implementation of such thing currently in [report_statistics](https://easystats.github.io/report/reference/report_statistics.html))

But it could be useful here in parameters as a `summary()` method to have more "compact" parameters, especially in the case of very wide tables. Thoughts?

**Comment by DominiqueMakowski** [comment]
Maybe the basis could go into insight, as it is in the same vein as `format_ci()`. Something like `format_indices()`? `format_parameters()`? `format_columns(..., summarize=TRUE)`?

**Comment by DominiqueMakowski** [comment]
@strengejacke @IndrajeetPatil @mattansb thoughts?

**Comment by mattansb** [comment]
What would the use can be?

Also, seems like something to go in `report`! A "make this table something I can copy into a word file" kind of function, no?

**Comment by DominiqueMakowski** [comment]
it's already in report, but it would be used in parameters::compare_performance to aggregate the params for each model into one column, and maybe it could be used in @IndrajeetPatil's packages to show on plots?

**Comment by DominiqueMakowski** [comment]
and @mattansb stop wanting to dump everything in report 😅 😅

**Comment by mattansb** [comment]
I only suggest report when it makes sense 🥺
(But I have a strong prior on `P(should be in report | Dom's idea)`)

Then yeah, maybe insight is better, to be used like the other format functions.

**Comment by strengejacke** [comment]
I have no clear idea at the moment how this could look like (and differ from what we have in report), so I have no definite opinion on this one.

**Comment by DominiqueMakowski** [comment]
> and differ from what we have in report

It would be a basis for it. Essentially the insight function could take an arbitrary data frame, that contains for instance a Beta, CI, CI_low/high and p columns, and would return a vector (i.e., a single column) of strings like "3.51, 95% CI [3.12, 3.98], p < .05", with options to control the included columns and the format. 

In compare performance you have for instance columns containing "3.42 [2.16, 4.54]" which could be created easily from the params dataframe using that insight function

**Comment by strengejacke** [comment]
(quick an dirty)

``` r
library(magrittr)
library(parameters)
m2 <- lm(Sepal.Length ~ Species * Petal.Length, data = iris)
out <- model_parameters(m2)
out %>% 
  format(ci_brackets = TRUE) %>% 
  apply(1, paste0, " (", colnames(out), ")", collapse = ", ")
#>                                                                                                                                                                                                         1 
#>                                                 "(Intercept) (Parameter), 4.21 (Coefficient), 0.41 (SE), [3.41, 5.02] (CI), 10.34 (CI_low), < .001 (CI_high), (Intercept) (t), 4.21 (df_error), 0.41 (p)" 
#>                                                                                                                                                                                                         2 
#>                           "Species [versicolor] (Parameter), -1.81 (Coefficient), 0.60 (SE), [-2.99, -0.62] (CI), -3.02 (CI_low), 0.003  (CI_high), Species [versicolor] (t), -1.81 (df_error), 0.60 (p)" 
#>                                                                                                                                                                                                         3 
#>                             "Species [virginica] (Parameter), -3.15 (Coefficient), 0.63 (SE), [-4.41, -1.90] (CI), -4.97 (CI_low), < .001 (CI_high), Species [virginica] (t), -3.15 (df_error), 0.63 (p)" 
#>                                                                                                                                                                                                         4 
#>                                           "Petal.Length (Parameter), 0.54 (Coefficient), 0.28 (SE), [-4.76e-03, 1.09] (CI), 1.96 (CI_low), 0.052  (CI_high), Petal.Length (t), 0.54 (df_error), 0.28 (p)" 
#>                                                                                                                                                                                                         5 
#> "Species [versicolor] * Petal.Length (Parameter), 0.29 (Coefficient), 0.30 (SE), [-0.30, 0.87] (CI), 0.97 (CI_low), 0.334  (CI_high), Species [versicolor] * Petal.Length (t), 0.29 (df_error), 0.30 (p)" 
#>                                                                                                                                                                                                         6 
#>   "Species [virginica] * Petal.Length (Parameter), 0.45 (Coefficient), 0.29 (SE), [-0.12, 1.03] (CI), 1.56 (CI_low), 0.120  (CI_high), Species [virginica] * Petal.Length (t), 0.45 (df_error), 0.29 (p)"
```

**Comment by DominiqueMakowski** [comment]
alright alright ☺️
