### ISSUE TITLE
should we remove `robust` argument for `merMod` objects for now?

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/parameters#427]
The `robust` argument currently doesn't work for `merMod` objects:

``` r
library(lme4)
#> Loading required package: Matrix
library(parameters)

mod <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy)

model_parameters(mod, robust = TRUE)
#> Error in UseMethod("estfun"): no applicable method for 'estfun' applied to an object of class "c('lmerMod', 'merMod')"
```

But we do expose it to users, which can be potentially confusing for them:

https://github.com/easystats/parameters/blob/e35cc42d5a2000ab94de06d714490323497931ec/R/methods_lme4.R#L106

**Comment by strengejacke** [comment]
It works:
https://easystats.github.io/parameters/articles/model_parameters_robust.html

**Comment by IndrajeetPatil** [comment]
Oh, then I am wondering if we should be including this in the user-facing examples.

**Comment by IndrajeetPatil** [comment]
Also, we need to fix this link: https://easystats.github.io/parameters/reference/model_parameters.cpglmm.html

**Comment by strengejacke** [comment]
I think the link-stuff is related to an issue in pkgdown. Not sure how to fix it, "internally" (i.e. from inside R) everything works as expected.

**Comment by IndrajeetPatil** [comment]
I think this should be sufficient.
