### ISSUE TITLE
consistent naming

### ISSUE THREAD

**Issue by strengejacke** [easystats/parameters#44]
not sure how we decide on this, but `model_parameters()` currently has following column names:

> Parameter      beta         SE    CI_low   CI_high         t            p   Std_beta

Do we want to harmonize this a bit?

**Comment by DominiqueMakowski** [comment]
Well I personally like the fact that the col names have the name of their stuff (i.e. beta when it's a beta, `t` when it's the t-value etc.). 

By harmonizing it, you mean in terms of lower/uppercase? Order of columns?

**Comment by strengejacke** [comment]
In this particular case I meant upper lower case, esp. beta in lower case, Std_beta in upper case

**Comment by DominiqueMakowski** [comment]
mmh. it is true that the "beta" has been bothering me for quite some time. Few alternatives:

- beta -> Beta (Std_Beta)
- beta -> Coefficient (Std_Coefficient)
- beta -> Slope (Std_Slope) 
- ... 

I am not a fan of the broomian "estimate" as it seems to generic, everything is an estimate of sorts *of something*, and what is of interest is the latter.

**Comment by DominiqueMakowski** [comment]
@strengejacke What is your opinion?

**Comment by strengejacke** [comment]
I'm a bit uncertain according b / beta, as these names are used differently in software and textbooks (some use "b" as unstandardized and "beta" as standardized, others use "beta" as unstandardized and "unstandardized beta" etc.). I would opt for coefficient (or Coefficient).

**Comment by strengejacke** [comment]
Here's an overview of bayestestR:

``` r
library(bayestestR)
library(magrittr)
model <- insight::download_model("stanreg_glm_2")
#> Registered S3 methods overwritten by 'ggplot2':
#>   method         from 
#>   [.quosures     rlang
#>   c.quosures     rlang
#>   print.quosures rlang
#> Registered S3 method overwritten by 'xts':
#>   method     from
#>   as.zoo.xts zoo


bayesfactor(model) %>% colnames()
#> Computation of Bayes factors: sampling priors, please wait...
#> [1] "Parameter" "BF"

ci(model) %>% colnames()
#> [1] "Parameter" "CI"        "CI_low"    "CI_high"

describe_posterior(model) %>% colnames()
#> Possible multicollinearity between cyl and wt (r = 0.7). This might lead to inappropriate results. See 'Details' in '?rope'.
#>  [1] "Parameter"          "Median"             "CI"                
#>  [4] "CI_low"             "CI_high"            "pd"                
#>  [7] "ROPE_CI"            "ROPE_low"           "ROPE_high"         
#> [10] "ROPE_Percentage"    "ESS"                "Rhat"              
#> [13] "Prior_Distribution" "Prior_Location"     "Prior_Scale"

describe_prior(model) %>% colnames()
#> [1] "Parameter"          "Prior_Distribution" "Prior_Location"    
#> [4] "Prior_Scale"

diagnostic_posterior(model) %>% colnames()
#> [1] "Parameter" "ESS"       "Rhat"      "MCSE"

effective_sample(model) %>% colnames()
#> [1] "Parameter" "ESS"

eequivalence_test(model) %>% colnames()
#> Error in eequivalence_test(model): could not find function "eequivalence_test"

estimate_density(model) %>% colnames()
#> [1] "Parameter" "x"         "y"

hdi(model) %>% colnames()
#> [1] "Parameter" "CI"        "CI_low"    "CI_high"

map_estimate(model) %>% colnames()
#> [1] "X.Intercept." "wt"           "cyl"

mcse(model) %>% colnames()
#> [1] "Parameter" "MCSE"

point_estimate(model) %>% colnames()
#> [1] "Parameter" "Median"

p_direction(model) %>% colnames()
#> [1] "Parameter" "pd"

p_map(model) %>% colnames()
#> [1] "Parameter" "p_MAP"

p_rope(model) %>% colnames()
#> [1] "Parameter" "p_ROPE"

rope(model) %>% colnames()
#> Possible multicollinearity between cyl and wt (r = 0.7). This might lead to inappropriate results. See 'Details' in '?rope'.
#> [1] "Parameter"       "CI"              "ROPE_low"        "ROPE_high"      
#> [5] "ROPE_Percentage"
```

<sup>Created on 2019-05-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
Maybe we can make a rule that if a _word_ is coming after `_`, it's lowercase? Like `CI_high`? That would mean we would change things like `ROPE_Percentage` into `ROPE_percentage`.

Furthermore, `pd`, `p_MAP` and `p_ROPE` are not consistent. What about `p_direction` (or keeping `pd`), `p_map` and `p_rope`?

**Comment by strengejacke** [comment]
* proper nouns: starting with upper case, followed by lower case (`Median`, `Rhat`, `Parameter`)
* abbreviations: all uppercase ( `ESS`, `MCSE`)
* two words: same rules as above, but separated with underscore. This would mean that `p_MAP` and `p_ROPE` are actually consistent, and so is `ROPE_Percentage`.

What about `p`? I would keep this as lower case, but what is the rule?

**Comment by DominiqueMakowski** [comment]
I think that my initial set of rules was loosely following this:

- Uppercase for the first letter of the column name except for specific conventions (the probability *p* is usually lowercase)
- uppercase for acronyms (e.g., like ROPE, MAP etc.)
- for the remaining words (percentage, high, etc.); lowercase

but indeed there are some inconsistencies there that need to be addressed.

**Comment by strengejacke** [comment]
I have revised the rules a bit, so they would match our naming scheme actually.

**Comment by DominiqueMakowski** [comment]
Thanks for pointing out the distinction between proper nouns and adjectives which indeed explains some of the exceptions

**Comment by strengejacke** [comment]
@pdwaggoner @mattansb We should decide on these conventions before submitting bayestestR, and then see that we will apply these consistent naming to all packages from bayestestR upwards, or what do you think?

Not sure, but I guess for _insight_, the ship has sailed...

**Comment by DominiqueMakowski** [comment]
I will hold bayestestR's submission until this is addressed :)

**Comment by strengejacke** [comment]
at least for bayestestR we don't have to change anything, I think. But it's good to have a consistent, logical naming convention that we apply to all our packages, and it's better to have it earlier than later ;-)

I'll check _performance_, and once we have decided on this, I will do the necessary revisions.

**Comment by DominiqueMakowski** [comment]
My only doubt is about the title case, should we apply title case to proper nouns and lower case to adjectives (as it is now) OR all nouns and adjectives in lower case *except* for the first letter (in which case `ROPE_Percentage` -> `ROPE_percentage` and `Std_Median` -> `Std_median`)

**Comment by strengejacke** [comment]
I'm not sure about this, either. My impression was that if you can formulate a "rule", it's easier to remember and to be consistent. So what would be the generic "rule" for your suggestion?

**Comment by mattansb** [comment]
I'm not sure I agree about "parameter" being a proper noun...
Generally I think nouns shouldn't be capitalized, unless due to convention (e.g. Rhat) - this would also mean not applying the (ugly) title case in most cases.
Agree with all other style suggestions.
(We're only talking about column / list item names, right? Not function names...)

**Comment by strengejacke** [comment]
> We're only talking about column / list item names, right?

yes.

**Comment by DominiqueMakowski** [comment]
I think in most cases the first letter of the name should be capitalised, because in the end (I am thinking of `report` here) these parameters tables should be almost publishable as is, and in a nicely formatted document the column names of tables are in general in title case :)

**Comment by DominiqueMakowski** [comment]
I usually try to stick with the APA guidelines, unless there is a good reason to do otherwise

**Comment by DominiqueMakowski** [comment]
Also, another question is the order; noun_adjective or adjective_nound. For instance, we have `R2_adjusted` and `Std_Median`. Should it be `Adjusted_R2` or `Median_std`.

On the one hand, it makes more sense in regards to sorting and visual segregation to start with the main thing and place the adjective after. On  the other hand, within the "organic" or "natural" approach to function design and naming that we try to have (i.e., that the code looks and reads like natural language), it makes sense to use the "natural" order  ("the standardized median" and the "adjusted r-squared") for naming...

**Comment by strengejacke** [comment]
I think most important is consistency with regards that you _know_ how column names are written, i.e. if you have a clear rule so you don't even need to manually check the column names before. 

Everything else (i.e. "visual output") is the jib of `print()`-methods, I would say.

**Comment by mattansb** [comment]
Agree that in most cases the first letter should be capitalized.

Word order: I think we should go with noun_adjective - first that "what", then more details about it. This would be less consistent with how these might be read aloud (in English), but would also be consistent with how these are visually reported (R<sup>2</sup><sub>Adj</sub>).

**Comment by strengejacke** [comment]
I personally had some trouble with these "strange" column names, being used to lower-case now for some time. But... I think it indeed makes sense to have the _common_ part as prefix, and that what varies is appended. So we have `ROPE`, `CI` and `R2` etc. first, then the verbs / adjectives. This makes sense from a "technical view" on the column names, though it's not human readable - but this is something  I would adapt in the print-methods (the human readable output).

**Comment by strengejacke** [comment]
or we use lower case for everything, and then have the noun_adjective pattern. That's what we should decide on. _If_ we use a mix of lower and upper case, we need a good "rule" / pattern.

**Comment by DominiqueMakowski** [comment]
We already have all lower case for functions 😁 

While I agree that we should favour consistency over beauty, as beauty can be dealt with in printing, we must not forget that many people are using rmarkdown in which dataframes are fed to `kables`. that's one of the reason for keeping up a high standard of "naturalness" also in the dataframes ☺️

**Comment by strengejacke** [comment]
Ok, please make your edits... :-)

**SUGGESTION**
* proper nouns: starting with upper case, followed by lower case (`Median`, `Rhat`, `Parameter`)
* abbreviations: all uppercase ( `ESS`, `MCSE`)
* adjectives / verbs: all lower case (like `high` or `low`)
* reserved words: as is (like `p`).
* two words: same rules as above, but separated with underscore. Noun goes first, followed by adjective / verb.

**Comment by DominiqueMakowski** [comment]
So do we change `ROPE_Percentage` to `ROPE_percentage`?

**Comment by strengejacke** [comment]
If you we don't have the "noun" rule (nouns in Uppercase), but only the variatonal part, then, yes. :-)

**Comment by strengejacke** [comment]
We may add "nouns" to (7) as well, if you delete (6)

**Comment by strengejacke** [comment]
According to (3): what is the "common" part and what the "varying" part?

"standardized_mean" and "standardized_median", or "mean_standardized" and "median_standardized"? This is indeed somewhat confusing. maybe we should stick with our "adjectives" after "nouns" rule here...

**Comment by pdwaggoner** [comment]
Sorry for being late - the time difference is a killer. But I read all of this, and these are good things to consider. Not sure if its too late to offer my opinion, but generally when I write functions or even just program in R, I keep everything lowercase and as meaningful and concise as possible, as this is the convention in R programming recently (see, e.g., http://adv-r.had.co.nz/Style.html). It also provides the benefit of inherent consistency, so we are aren't guessing and possibly messing up some things compared to other things. And further, I always use underscore (as we do in easystats). So for example, I like: 

* `rope_percent`
* `std_median`
* `ci_high`
* `ci_low`

And so on...

Just my opinion. Happy to go with whatever makes most sense. 

And whatever we decide, I don't think it would be too onerous to go back to `insight` and quickly update all function names to be in alignment with whatever conventions we decide and push it to CRAN as a minor release.

**Comment by strengejacke** [comment]
> function names

It's not about function names! We're just talking about _column names_ from data frames that are returned by the various methods.

**Comment by strengejacke** [comment]
> Sorry for being late - the time difference is a killer

Yes, sometime it feels like that ;-)

**Comment by pdwaggoner** [comment]
Ah touche. Thanks for the clarification. Its still early over here... ;) 

In that case, I think the programming convention for snake case is upper case first letter of the first word (regardless of proper or not) and then everything after the underscore is lower case. So, e.g.,

* `Rope_percent`
* `Std_median`

Not sure if this feels as good as `CI_low`, for example (compared to `Ci_low`), but it depends on whether we'd like to stick with convention or do our own thing. Anyway, there's my half-baked two cents. Apologies for missing the mark with my previous comment ;)
