### ISSUE TITLE
Bootstrapping method for model_parameters of `merMod` object

### ISSUE THREAD

**Issue by MikhaelManurung** [easystats/parameters#451]
Dear authors,

Thank you for making the package. It made my life so much easier!

I have a naive question: if I run `model_parameters` on my `merMod` object with `bootstrap=TRUE`, does this implement parametric bootstrap?

Thanks in advance. 

Best regards,
Mikhael

**Comment by strengejacke** [comment]
We use `lme4::bootMer()` to obtain bootstrapped parameters, and then summarize it via `bayestestR::describe_posterior()`. Thus the bootstrap method we have implemented is (semi)parametric.
