### ISSUE TITLE
Quartiles are not reported

### ISSUE THREAD

**Issue by kulbhushanchand** [easystats/parameters#452]
Quartiles are not reported as per the [documentation](https://easystats.github.io/parameters/reference/describe_distribution.html).
Looks like a bug. Can you kindly confirm?
Thanks

```
data(iris)
parameters::describe_distribution(iris, include_factors = TRUE, quartiles = TRUE)
```

![image](https://user-images.githubusercontent.com/17742733/112745082-615fe000-8fc3-11eb-86af-6013abed0982.png)

**Comment by strengejacke** [comment]
Are you using the CRAN version? The option for quartiles has been implemented recently, so you need to update from GitHub to use that feature.

**Comment by kulbhushanchand** [comment]
Yes, I am using CRAN `ver-0.12.0`.
As advised, updated to GitHub `ver-0.12.0.1` and the problem resolved.
Thanks for the help.

**Comment by strengejacke** [comment]
Great! A CRAN submission is scheduled for beginning/mid of April.
