### ISSUE TITLE
EFA to CFA doesn't work with bootstrapped psych::fa object

### ISSUE THREAD

**Issue by simonfelding** [easystats/parameters#471]
Hi! Thanks for the lovely packages! I really like how streamlined they are.

 
This is an example of the code that causes the problem:
```
library(psych)
library(easystats)
result <- fa(iris, n.iter=10)
efa_to_cfa(result)
```

Which leads to the error:
```
Error in UseMethod("convert_efa_to_cfa") : 
  no applicable method for 'convert_efa_to_cfa' applied to an object of class "c('psych', 'fa.ci')"
```

Expected result: Just ignore the CI.

I am running the latest github version of easystats.

**Comment by strengejacke** [comment]
@DominiqueMakowski Can you take a look? I think you implemented this function.

**Comment by DominiqueMakowski** [comment]
Should work now

``` r
library(psych)
library(parameters)

model <- fa(iris[1:4], n.iter=10)

efa_to_cfa(model)
#> # Latent variables
#> MR1 =~ Sepal.Length + Sepal.Width + Petal.Length + Petal.Width
```

<sup>Created on 2021-04-11 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>
