### ISSUE TITLE
new classes: sampleSelection

### ISSUE THREAD

**Issue by vincentarelbundock** [easystats/parameters#476]
``` r
library(sampleSelection)
library(parameters)
library(wooldridge) # for data
data(mroz)

mod <- selection(
  inlf ~ educ + kidslt6 + kidsge6, 
  wage ~ educ + exper + expersq,
  method = "2step",
  data = mroz)

k = parameters(mod)
str(k)
#>  NULL
```

The estimates are stored in `summary(x)$estimate`

This model includes results for a selection equation and an outcome equation, and we can find the indices using something like:

```r
ret$group <- NA_character_
ret$group[s$param$index$betaS] <- "Selection"
ret$group[s$param$index$betaO] <- "Outcome"
```

**Comment by strengejacke** [comment]
And I thought only @IndrajeetPatil was suggesting super-strange models... ;-)

**Comment by vincentarelbundock** [comment]
ha! I just released a new version of `modelsummary` and am getting emails with model requests. Honestly, I'm not sure how widespread these are because I don't use them myself, but I thought I'd drop them here just for the record :)

**Comment by vincentarelbundock** [comment]
Rockstar

**Comment by strengejacke** [comment]
There are some minor issues (correct DF, correct nobs,r2, ...) which I will fix now.

**Comment by strengejacke** [comment]
I'm not familiar with these models, there might be edge cases that do not yet work (e.g. "Tobit 5" models with a list of formulas). That's something that needs to be tested some day...

**Comment by strengejacke** [comment]
looks good:

```r
library(sampleSelection)
library(wooldridge) # for data
data(mroz)

mod1 <- selection(
  inlf ~ educ + kidslt6 + kidsge6, 
  wage ~ educ + exper + expersq,
  method = "2step",
  data = mroz)

mod2 <- selection(
  inlf ~ educ + kidslt6 + kidsge6, 
  wage ~ educ + exper + expersq,
  method = "ml",
  data = mroz)

modelsummary::modelsummary(list(mod1, mod2), group = component + term ~ model)
```

![image](https://user-images.githubusercontent.com/26301769/115671565-f055e300-a34a-11eb-9b0c-d06acafc5a91.png)

**Comment by strengejacke** [comment]
(there is a minor "sigma" issue I just realized...)
