### ISSUE TITLE
Linear Mixed Model Bootstrapped Confidence Intervals Question

### ISSUE THREAD

**Issue by delucalab** [easystats/parameters#478]
I recently ran a linear mixed effects model using lme4 after transforming data using log(1+x). Afterwards, I used emmeans to backtransform the data and get point estimates, confidence intervals, and contrasts. I noticed that some lower confidence intervals were negative which is theoretically impossible since the back transformed data is a proportion between 0 and 1. I was advised to generate bootstrapped confidence intervals instead and stumbled upon your package and the bootstrap_parameters function. Would this serve my purpose of ultimately getting bootstrapped backtransformed confidence intervals via emmeans and solve the negative lower CI bound issue?

**Comment by bwiernik** [comment]
Can you give a short reproducible example of what you are seeing with emmeans etc?

**Comment by delucalab** [comment]
Attaching the data and a .txt file with the code used and the outputs for reference. Let me know if you need anything else. Thanks for your help! I very much appreciate it!
[Code and Output.txt](https://github.com/easystats/parameters/files/6394141/Code.and.Output.txt)
[Reproducible Example.csv](https://github.com/easystats/parameters/files/6394143/Reproducible.Example.csv)

**Comment by strengejacke** [comment]
In linear models, the outcome is not bounded, so negative CI is possible. For outcomes which are proportions you should rather use a beta regression, see also http://htmlpreview.github.io/?https://github.com/strengejacke/mixed-models-snippets/blob/master/overview_modelling_packages.html

**Comment by bwiernik** [comment]
Or another potentially reasonable option would be a zero-inflated model--in these data, there appears to be a quite distinct difference between between have Outcome 0 and any other value.

```r
mod.tmb <- glmmTMB::glmmTMB(log(Outcome + .01) ~ Pred1*Pred2 + (1 | ID), 
														ziformula  = ~ Pred1*Pred2 + (1 | ID),
														data=data, REML=TRUE)
emmeans(data.tmb, ~ Pred1*Pred2, type="response", bias.adj = TRUE)
```

**Comment by delucalab** [comment]
Thanks! Just a couple follow up questions:

1. Beta-binomial seems to combine both of your suggestions. Would that be reasonable? If so, how do I determine which terms are relevant to include in the ziformula? Zero-inflated models are new to me.
2. Would a different transformation (ie logit), rather than log(x+1), work better when using a linear mixed model and prevent the negative CI I observed?

**Comment by strengejacke** [comment]
glmmTMB also allows beta-binomial or zero-inflated beta ("normal" beta regression excludes 0 and 1):

glmmTMB(ziformula, family=beta_family/betabinomial)

**Comment by strengejacke** [comment]
>  Would that be reasonable? 

I would say yes.

> If so, how do I determine which terms are relevant to include in the ziformula? Zero-inflated models are new to me.

That's indeed one of the big mysteries, and I haven't found any good tutorial/introduction on that, yet. If you're not certain, just copy the formula from the count-model.

> Would a different transformation (ie logit), rather than log(x+1), work better

I'm not sure, since you're trying to fulfill the model-assumptions by some crude transformations. If your response is bounded and a proportion, other model families than Gaussian are likely to fit better to the data.

**Comment by bwiernik** [comment]
Think of the zi formula as logistic regression model for "zero or not". Whatever predictors would be reasonable as a predictor of zero or not could be included. Often, using the same predictors as the main response model is reasonable. 

As for other transformations, you could use logit or add a smaller constant such as .01, but I wouldn't be confident in the behavior of those confidence bounds given that it's fairly ad hoc to assume a Gaussian response.

**Comment by delucalab** [comment]
Thank you so much! This is extremely helpful!

Last semi-related question:

When extracting marginal means, I have been using emmeans. How can I also extract the individual estimates that make up the group marginal mean? I want to ultimately be able to make a plot that displays model-adjusted individual responses as dots around the estimated marginal mean.

Thanks again for all your help! This is all new to me and I'm learning quite a bit.

**Comment by bwiernik** [comment]
predict() or get_predicted() will extract the predicted values for each point in the model. But I'm not sure what you mean by "model adjusted".

**Comment by strengejacke** [comment]
@delucalab I'm not quite sure what you exactly mean, but I'd recommend [ggeffects](http://strengejacke.github.io/ggeffects), in particular `ggemmeans()` to get same results as emmeans. There's a plot method that allows you to add individual data points (see [this vignette](https://strengejacke.github.io/ggeffects/articles/introduction_plotmethod.html)) or partial residuals (see [this vignette](https://strengejacke.github.io/ggeffects/articles/introduction_partial_residuals.html)). You could also calculate/plot marginal means by random effect groups (see [this vignette](https://strengejacke.github.io/ggeffects/articles/introduction_randomeffects.html)). Finally, the current GitHub version also allows you to add individual data points "collapsed" (i.e. averaged) over random effect groups (see [this issue](https://github.com/strengejacke/ggeffects/issues/187#issuecomment-825829721)). And there's a GitHub package that allows you to easily build your own ggplot-plots based on the results of ggeffects: https://github.com/mattansb/ggggeffects

**Comment by delucalab** [comment]
Thank you! This is very helpful! For my edification, what is the relationship between the individual estimates from predict() or get_predicted() and the marginal means from emmeans() or ggmmeans()? Is the marginal mean for a group just the average of the individual estimates or is it more complicated than that?

**Comment by strengejacke** [comment]
See [this vignette](https://strengejacke.github.io/ggeffects/articles/technical_differencepredictemmeans.html)

**Comment by delucalab** [comment]
Thank you! I had a look and may be confusing myself as this is all new to me (my apologies for the naivety). 

As an example: Let's say I have 50 subjects of nested data where I took a continuous measurement from healthy and lesioned tissue that is found within two distinct regions.  I run a mixed-model with predictors of interest including tissue type (ie healthy or lesion) and region and a random effect of subject ID. I then extract the individual-level estimates for each subject (I assume by using predict or get_predicted?) so that I have values for each subject in healthy tissue-region 1, healthy tissue-region 2, lesioned tissue-region 1, and lesioned tissue-region 2. If I then average the individual estimates across subjects for healthy tissue-region 1, healthy tissue-region 2, lesioned tissue-region 1, and lesioned tissue-region 2 will that ultimately equal the estimated marginal mean for each of those 4 groups of interest that would be calculated by emmeans or ggemmeans?

My apologies again for all the questions, I just want to wrap my head around the concepts.

**Comment by strengejacke** [comment]
I don't see why you need a mixed model here (i.e. why subject ID should be a random effect), unless you have multiple measurements from subjects (e.g., repeated over several timepoints, like every 3 months for 1 year).

**Comment by strengejacke** [comment]
>  will that ultimately equal the estimated marginal mean for each of those 4 groups of interest that would be calculated by emmeans or ggemmeans?

Both. `ggemmeans()` internally calls `emmeans()`, however, the returned object is a data frame, and this object has a nice ggplot2-plot method. However, `ggemmeans()` (and ggeffects in general) only aims at "predictions", while the emmeans package offers more functions (like contrasts or pairwise comparisons).

If you want to learn more about the concept of "marginal effects" in general, you may read [this vignette](https://strengejacke.github.io/ggeffects/articles/introduction_marginal_effects.html).

**Comment by delucalab** [comment]
> I don't see why you need a mixed model here (i.e. why subject ID should be a random effect), unless you have multiple measurements from subjects (e.g., repeated over several timepoints, like every 3 months for 1 year).

Each subject has the same outcome measured 4 times (lesion and non-lesion in two different regions) so I thought I should use a mixed model since the data is nested and correlated.

**Comment by delucalab** [comment]
> I don't see why you need a mixed model here (i.e. why subject ID should be a random effect), unless you have multiple measurements from subjects (e.g., repeated over several timepoints, like every 3 months for 1 year).

Gotcha I just wanted to confirm that the estimated marginal mean would equal the aggregate of individual level predictions by the model similar to how observed means are an aggregate of observed individual values.

**Comment by strengejacke** [comment]
>  I just wanted to confirm that the estimated marginal mean would equal the aggregate of individual level predictions by the model

I don't think these are not always identical, but close, I guess. But yes, estimated marginal means are "adjusted" means of your outcome by specific group-levels (adjusted for the possible bias of co-variates).

``` r
library(ggeffects)

# dummy data
data(iris)
set.seed(123)
iris$grp <- as.factor(sample(letters[1:5], 150, TRUE))

# model, with continuous and categorical predictors
m <- lm(Sepal.Width ~ grp + Sepal.Length + Species, data = iris)

# raw mean by Species
aggregate(iris$Sepal.Length, list(iris$Species), mean)
#>      Group.1     x
#> 1     setosa 5.006
#> 2 versicolor 5.936
#> 3  virginica 6.588

# or
sjstats::means_by_group(iris, Sepal.Length, Species)
#> 
#> # Grouped Means for Sepal.Length by Species
#> 
#> Category   | Mean |   N |   SD |   SE |      p
#> ----------------------------------------------
#> setosa     | 5.01 |  50 | 0.35 | 0.05 | < .001
#> versicolor | 5.94 |  50 | 0.52 | 0.07 |  0.121
#> virginica  | 6.59 |  50 | 0.64 | 0.09 | < .001
#> Total      | 5.84 | 150 | 0.83 | 0.07 |       
#> 
#> Anova: R2=0.619; adj.R2=0.614; F=119.265; p=0.000


# individual predictions per observation
iris$predictions <- predict(m)

# averaged individual predictions by Species
aggregate(iris$predictions, list(iris$Species), mean)
#>      Group.1     x
#> 1     setosa 3.428
#> 2 versicolor 2.770
#> 3  virginica 2.974

# predicted mean by Species, using "predict()"
ggpredict(m, "Species")
#> # Predicted values of Sepal.Width
#> 
#> Species    | Predicted |       95% CI
#> -------------------------------------
#> setosa     |      3.80 | [3.67, 3.94]
#> versicolor |      2.83 | [2.71, 2.96]
#> virginica  |      2.80 | [2.66, 2.95]
#> 
#> Adjusted for:
#> *          grp =    a
#> * Sepal.Length = 5.84

# predicted mean by Species, using "emmeans()"
ggemmeans(m, "Species")
#> # Predicted values of Sepal.Width
#> 
#> Species    | Predicted |       95% CI
#> -------------------------------------
#> setosa     |      3.71 | [3.60, 3.83]
#> versicolor |      2.74 | [2.66, 2.82]
#> virginica  |      2.71 | [2.61, 2.82]
#> 
#> Adjusted for:
#> * Sepal.Length = 5.84
```

<sup>Created on 2021-04-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
