### ISSUE TITLE
Measures of relative importance of parameters 

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#479]
Would be nice to implement or wrap around few methods to get relative importance measures, such as Shapley values or lmg (in the `relaimpo` package.

- Easy implementation of Shapley's values here (and example of lmg): https://datamotus.com/2019/12/20/Shapley-value-regression.html

```r
shap <- function(formula, var){
  ifelse(length(str_split(paste(formula)[3], pattern = "\\s\\+", simplify = T))!=1, 
      summary(lm(data=df, formula))$r.squared - 
      summary(lm(data=df, as.formula(gsub(paste0(paste(formula)[2], paste(formula)[1],
          paste(formula)[3]), pattern = paste0("\\+", var),replacement = ""))))$r.squared, 
      summary(lm(data=df, formula ))$r.squared -
      summary(lm(data=df, as.formula(paste0(paste(formula)[2],paste(formula)[1],1))))$r.squared
  )}
```

Using our R2 generics, we can easily get the most robust implementation of Shapley's values for regressions.

We could add that in a `check_importance()` function? Or `check_parameters()?`, that would provide parameters-level diagnostics metrics and things like that?

- Some intro: https://christophm.github.io/interpretable-ml-book/shapley.html

**Comment by bwiernik** [comment]
I'm a little leery here. There are many such "importance" metrics that differ in exactly what "importance" means, and which is appropriate needs to be carefully considered based on the research question. For example, lmg and dominance analysis can come to different conclusions because they conceptualize importance differently. There is also the issue that some methods for calculating importance, such as "relative weights analysis" are completely invalid.

**Comment by DominiqueMakowski** [comment]
> There are many such "importance" metrics that differ in exactly what "importance" means

Absolutely! But still, wouldn't it be useful to have them available? >e implement/support many not-recommended procedures already 😁 I agree that we cannot have a `check_importance()` that would return one single metric suggesting that "this is the perfect one trust it". But we could have separate functions `parameters_shapley(); parameters_lmg()` and a `check_importance(m, method=c("shapley", "lmg")`. Something similar to `model_performance()` mutatis mutandis

**Comment by vincentarelbundock** [comment]
Is this in-scope for `parameters` or `effectsize`?

**Comment by bwiernik** [comment]
It's implemented here https://github.com/easystats/parameters/pull/710
