### ISSUE TITLE
function names

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#48]
seeing how things develop, I wonder if it would make sense to have all parameters functions starting by parameters (similarly to performance). For example, parameters_standardization(), parameters_selection(), parameters_bootstrap(), parameters_marginal() etc.

**Comment by strengejacke** [comment]
Not sure, but I think in performance we did this for two reasons. First, to bundle functions according to their main tasks (check assumptions, performance, ...) And second, we can use abbreviations like `pcp`, to keep names at least a bit shorter.

If we would have only `parameters` as prefix, I would probably not prefix function names. Else, if we have different groups of functions, it makes sense.

**Comment by DominiqueMakowski** [comment]
So you would keep `standardize_parameters` and `bootstrap_parameters` and in the future `marginal_parameters` and... `select_parameters`?

**Comment by strengejacke** [comment]
Ah ok. We have two words anyway... Then maybe we should indeed use parameters first, this gives us more flexibility in the future.

**Comment by DominiqueMakowski** [comment]
👍
