### ISSUE TITLE
Bug in `random_parameters()` with component = "all"

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#481]
In the docs it says that `component` can be "all" and that it's the default, but actually the default is "conditional" and it fails if "all":

``` r
model <- lme4::lmer(Reaction ~ Days + (1 + Days  | Subject), data = lme4::sleepstudy)

parameters::random_parameters(model, component = "all")
#> Error in match.arg(component, choices = c("conditional", "zi", "zero_inflated")): 'arg' should be one of "conditional", "zi", "zero_inflated"
```

<sup>Created on 2021-05-04 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by bwiernik** [comment]
What is this function for?

**Comment by strengejacke** [comment]
For merMod, there shouldn't be a component argument, since there are no different components. @bwiernik The function prints a summary of RE variances (var/SD) (https://easystats.github.io/parameters/reference/random_parameters.html).
