### ISSUE TITLE
rotated_data doesn't work (and never did?)

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#487]
When cleaning the docs I stumbled on the `rotated_data()` function that doesn't work

``` r
pca <- parameters::principal_components(mtcars[, 1:5], n = 2, rotation = "varimax")
parameters::rotated_data(pca) 
#> Error in `$<-.data.frame`(`*tmp*`, ".parameters_merge_id", value = 1:32): replacement has 32 rows, data has 0
```

<sup>Created on 2021-05-09 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

It tries to access the `x` object stored in the results:

https://github.com/easystats/parameters/blob/b722711b5051ab9a017272458c9ea1057f3e6e6a/R/principal_components.R#L194

but AFAIK there's no such thing 🤔 
also the documentation for that function is a bit light, by reading it I wasn't too sure of what it's supposed to do and it what context it could be useful

**Comment by DominiqueMakowski** [comment]
> Simply remove it?

But surely it was added for a reason in the first place no? 😅

**Comment by bwiernik** [comment]
x appears that it should be the original data passed to principal_components

**Comment by DominiqueMakowski** [comment]
Yeah but maybe I would use it a lot... maybe it would be the most used function... If only we knew what it does haha

**Comment by strengejacke** [comment]
sadly, the most game-changer function in the world remained unrecognized and was removed from the packages due to the perforated brains of its developers.

**Comment by bwiernik** [comment]
The `x` object is supposed to be the principal component scores for the data set.
https://github.com/easystats/parameters/blob/b722711b5051ab9a017272458c9ea1057f3e6e6a/R/principal_components.R#L275

**Comment by bwiernik** [comment]
The issue here is that the structure of `stats::prcomp` and `psych::principal` objects is different. `stats::prcomp` calls the rotation matrix and rotated scores "rotation" and "x" whereas `psych::principal` calls these "rot.matrix" and "scores". What needs to happen here is either (1) consistently use `psych::principal`/`psych::fa` in these functions and adapt the wrapper functions to always use that API or (2) check for model classes in the wrapper functions and use the respective API as needed. In general, I would say to use the psych API consistently.

**Comment by DominiqueMakowski** [comment]
``` r
p <- psych::principal(mtcars, 3)
head(p$scores)
#>                          RC2        RC3         RC1
#> Mazda RX4          0.9216214  0.8933476 -0.27375081
#> Mazda RX4 Wag      0.8365475  0.6726814 -0.09841353
#> Datsun 710         0.6715640 -0.4744102 -0.74438413
#> Hornet 4 Drive    -0.9473444 -0.7637001 -0.77648311
#> Hornet Sportabout -0.8685878  1.0265816 -0.97921933
#> Valiant           -1.1952350 -1.0754145 -0.54199690

p <- prcomp(mtcars)
head(p$x)[, 1:3]
#>                           PC1       PC2       PC3
#> Mazda RX4          -79.596425  2.132241 -2.153336
#> Mazda RX4 Wag      -79.598570  2.147487 -2.215124
#> Datsun 710        -133.894096 -5.057570 -2.137950
#> Hornet 4 Drive       8.516559 44.985630  1.233763
#> Hornet Sportabout  128.686342 30.817402  3.343421
#> Valiant            -23.220146 35.106518 -3.259562
```

<sup>Created on 2021-05-12 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>


> principal component scores

Could we consider scores as the `predicted` scores and have a `get_predicted()` method in insight to retrieve it, and then here we just call `get_predicted` instead of digging in the object?

**Comment by bwiernik** [comment]
Yep, close enough and that’s accurate for factor analysis. That’s consistent with lavaan’s terminology.

**Comment by DominiqueMakowski** [comment]
``` r
pca <- parameters::principal_components(mtcars[, 1:5], n = 2, rotation = "varimax")
parameters::rotated_data(pca) 
#>     mpg cyl  disp  hp drat         RC1         RC2
#> 1  21.0   6 160.0 110 3.90 -0.23906186  0.38058456
#> 2  21.0   6 160.0 110 3.90 -0.23906186  0.38058456
#> 3  22.8   4 108.0  93 3.85 -0.87523403  0.30496365
#> 4  21.4   6 258.0 110 3.08 -0.83256507 -1.21853890
#> 5  18.7   8 360.0 175 3.15  0.37716377 -0.82007976
#> 6  18.1   6 225.0 105 2.76 -1.10127278 -1.86114104
#> 7  14.3   8 360.0 245 3.21  1.23453249 -0.26702364
#> 8  24.4   4 146.7  62 3.69 -1.30024506 -0.23007562
#> 9  22.8   4 140.8  95 3.92 -0.74129623  0.41446358
#> 10 19.2   6 167.6 123 3.92 -0.02461777  0.47612740
#> 11 17.8   6 167.6 123 3.92  0.02534454  0.45386195
#> 12 16.4   8 275.8 180 3.07  0.29853804 -0.88051969
#> 13 17.3   8 275.8 180 3.07  0.26641941 -0.86620618
#> 14 15.2   8 275.8 180 3.07  0.34136287 -0.89960437
#> 15 10.4   8 472.0 205 2.93  0.93247714 -1.25088059
#> 16 10.4   8 460.0 215 3.00  1.06844670 -1.03682781
#> 17 14.7   8 440.0 230 3.23  1.22799380 -0.41588998
#> 18 32.4   4  78.7  66 4.08 -1.30762202  0.71198099
#> 19 30.4   4  75.7  52 4.93 -0.60701035  2.14073148
#> 20 33.9   4  71.1  65 4.22 -1.25685030  0.99325379
#> 21 21.5   4 120.1  97 3.70 -0.90720118  0.02588588
#> 22 15.5   8 318.0 150 2.76 -0.15711335 -1.72688554
#> 23 15.2   8 304.0 150 3.15  0.18137850 -1.00150788
#> 24 13.3   8 350.0 245 3.73  1.72116683  0.68171810
#> 25 19.2   8 400.0 175 3.08  0.36060813 -0.98161661
#> 26 27.3   4  79.0  66 4.08 -1.12513535  0.63056351
#> 27 26.0   4 120.3  91 4.43 -0.46730967  1.39310467
#> 28 30.4   4  95.1 113 3.77 -1.05428733  0.43877634
#> 29 15.8   8 351.0 264 4.22  2.24906373  1.75900256
#> 30 19.7   6 145.0 175 3.62  0.13210722  0.33766027
#> 31 15.0   8 301.0 335 3.54  2.24244855  1.06973229
#> 32 21.4   4 121.0 109 4.11 -0.42316749  0.86380202
```

<sup>Created on 2021-05-12 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

Now that is has been fixed, it seems like it basically returns predicted scores + original data.

We could keep this function as an internal for now (because it looks like the matching of rows that it does could be annoying if we had to re-code it), and reassess later once we have a better overview of the whole prediction API (for instance, maybe we could store the matching data directly as an attribute in `get_predicted`? and assemble it in `estimate_prediction()` etc.)
