### ISSUE TITLE
Remove find_distribution

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#49]
After thinking about it, I think I'll remove find_distribution and the associated machine learning model.

First of all, because it's a bit out of scope. But the true reason is that I've been trying to wrap my head around it and it would probably need its own package to be done right. In fact, classifying distributions might be more interesting and relevant using a step-by-step process (or ensemble of models). 

For instance, a first model could try finding the "number of peaks" and discriminating between uniform, unimodal and multimodal distributions. Then, if the distribution is unimodal, it would try discriminating between symetric and non-symmetric (skewed) distributions. Depending on that, the next step would be to refine the classification (for symmetric distributions, segregating normal, Cauchy, t etc.) and for non-symmetric between beta gamma exp and whatnot. For multimodal distributions, it could use some form of mixture modelling.

Anyway, doing it right is beyond my abilities and the scope of this package :)

**Comment by strengejacke** [comment]
Hm, I just started to like that function after I discovered it. :-)

Maybe I implement it in sjstats until we find an own package for it.
