### ISSUE TITLE
Parameters for Bayesian models 

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#490]
``` r
library(rstanarm)

parameters::parameters(stan_glm(mpg ~ wt, data = mtcars, refresh = 0))
#> # Fixed effects
#> 
#> Parameter   | Median |         89% CI |   pd | % in ROPE |  Rhat |     ESS |                   Prior
#> ----------------------------------------------------------------------------------------------------
#> (Intercept) |  37.21 | [34.06, 40.33] | 100% |        0% | 1.000 | 3926.00 | Normal (20.09 +- 15.07)
#> wt          |  -5.32 | [-6.34, -4.47] | 100% |        0% | 1.000 | 3973.00 |  Normal (0.00 +- 15.40)
#> 
#> Using highest density intervals as credible intervals.
```

<sup>Created on 2021-05-12 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

For consistency with other models, we probably should return some index of dispersion (SD) by default. What do you think?

Also, we could print the CI-type message in yellow / blue instead of the warning-red so that it corresponds to an "hint" rather than a "something's wrong" warning

<sub>~Also for consistency we should change the default ci to .95 🙄~ </sub>

**Comment by bwiernik** [comment]
1) Consistency with which other models? lm and glm don't include sigma in this table. The question is whether sigma belongs here or in performance (or both?). Personally, I think all model parameters should be included in the output here (e.g., including cofficients, dispersion model, sigma, thresholds for ordinal models, etc.) and should include intervals if possible. It would be great if this were consistent across all models. 

2) Yes, I think we should use `message()` exclusively for problems--"warnings". In general, I try to avoid using `warning()` and use either `message()` or `error()` instead.

**Comment by DominiqueMakowski** [comment]
``` r
parameters::parameters(glm(mpg ~ wt, data = mtcars))
#> Parameter   | Coefficient |   SE |         95% CI | t(30) |      p
#> ------------------------------------------------------------------
#> (Intercept) |       37.29 | 1.88 | [33.61, 40.97] | 19.86 | < .001
#> wt          |       -5.34 | 0.56 | [-6.44, -4.25] | -9.56 | < .001
```

<sup>Created on 2021-05-13 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

In frequentist models we have parameters' SE, so I was thinking of having its equivalent for Bayesian models.

**Comment by strengejacke** [comment]
The CI-type message is actually a message, which you can turn of using `verbose`. We could also include the SD, however, my impression is that CIs are more usual than SD/SE when reporting summaries of Bayesian models... We should then probably omit one of the other columns, to prevent a too wide output.

**Comment by DominiqueMakowski** [comment]
> to prevent a too wide output.

On a side note, we could add a generic `summary()` method à-la-report that works on all parameters tables and return only the "critical" (though this is a hotly debated issue) columns

**Comment by strengejacke** [comment]
We have that already, `select = "minimal"` and `select = "short"` (https://easystats.github.io/parameters/reference/print.parameters_model.html)

**Comment by strengejacke** [comment]
But maybe we could indeed make `summary()` a shortcut for this.

**Comment by bwiernik** [comment]
Both brms and rstandarm include the SD across posterior draws in their output. I think this would be good to include in ours as well.

**Comment by strengejacke** [comment]
`dispersion` now defaults to `TRUE`, which reports the MAD. Should we also default to `"mean"`, to get the same output as for brms-summary?

**Comment by strengejacke** [comment]
``` r
library(parameters)
model <- lm(mpg ~ wt + cyl, data = mtcars)
model_parameters(model) |> summary()
#> Parameter   | Coefficient |         95% CI |      p
#> ---------------------------------------------------
#> (Intercept) |       39.69 | [36.18, 43.19] | < .001
#> wt          |       -3.19 | [-4.74, -1.64] | < .001
#> cyl         |       -1.51 | [-2.36, -0.66] | 0.001 
#> 
#> Model: mpg ~ wt + cyl (32 Observations)
#> Residual standard deviation: 2.568 (df = 29)
```

<sup>Created on 2021-05-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by strengejacke** [comment]
Can this be closed? If not, just re-open :-)

**Comment by DominiqueMakowski** [comment]
>  Should we also default to "mean", to get the same output as for brms-summary?

I'd be fine with keeping Median (as we kinda suggest that it's a better choice in our guidelines, which I still do agree with) and just adding the MAD

**Comment by mattansb** [comment]
I agree 👆🏻
