### ISSUE TITLE
check_sphericity in parameters and performance

### ISSUE THREAD

**Issue by strengejacke** [easystats/parameters#491]
@mattansb since you implemented this here (and @DominiqueMakowski in _parameters_), could you check whether we can merge these functions (and decide on a package where to put this function into):

https://easystats.github.io/performance/reference/check_sphericity.html
https://easystats.github.io/parameters/reference/check_sphericity.html

**Comment by mattansb** [comment]
Dom, can I got a head and make this change?

**Comment by mattansb** [comment]
@strengejacke Can I go a head and make this change?

**Comment by bwiernik** [comment]
Why not make the factor analysis one just the S3 method for data.frame?

**Comment by mattansb** [comment]
(If I understand correctly) doesn't Bartlett's test test for the presence of sphericity, whereas Mauchly’s test tests for the violation of sphericity?

They're also used in different contexts (mlm/rm vs EFA).

I guess we can have this as a method, but it feels weird to have two different tests with the same name :/

**Comment by strengejacke** [comment]
Ok, if anyone knows how to proceed, just make the related changes here in _parameters_.

**Comment by bwiernik** [comment]
I don't have strong preferences here. Both tests aren't very useful in my opinion--ANOVA sphericity test behavior is too erratic and sample size dependent. Bartlett test I've never understood the point--just fit a factor analysis model--if there's no covariance, you'll retain back p factors. 

The logic of the two tests is the same--test against a null hypothesis of spherical data. What differs is the decision rule--do you want to retain or reject the bill to proceed. ￼It makes sense to me to S3 them, but if we go with separate functions, I'd say `check_bartlett_sphericity()`.

**Comment by mattansb** [comment]
The problem is that `{parameters}` and `{performance}` don't import each other, so where would the `check_sphericity <- function(x, ...) UseMethod("check_sphericity")` function live without getting masking warnings when loading both packages? AFAIK we also can't reexport a function in a situation like this, no?

Trying over at #499

**Comment by DominiqueMakowski** [comment]
we can put them both in performance no? Since both are somewhat related to the quality / validity of some procedure

**Comment by DominiqueMakowski** [comment]
by S3 method you mean running bartlett for data.frames and the other for anovas?

**Comment by mattansb** [comment]
> we can put them both in performance no? Since both are somewhat related to the quality / validity of some procedure

Yes, but then users will get a masking warning when they load both packages. Do we care? (I think not - we have some of these between parameters and bayestestR...)

> by S3 method you mean running bartlett for data.frames and the other for anovas?

Yup.

**Comment by strengejacke** [comment]
> (I think not - we have some of these between parameters and bayestestR...)

Do we? I don't think there are functions that mask each other...

**Comment by mattansb** [comment]
Hmmm we use to, I think you or I fixed it recently ^^

**Comment by DominiqueMakowski** [comment]
> Yes, but then users will get a masking warning when they load both packages. 

How so? If the whole set of S3 is defined in performance and nothing stays in parameters what's the problem?

**Comment by mattansb** [comment]
Ah, but we want `check_sphericity.data.frame()` in `parameters` together with the other `check_factorstructure()` and `check_kmo()`, no?

**Comment by DominiqueMakowski** [comment]
we could put them in performance too... it's a breaking change true, but well... people should be `library(easystats)` anyway now that all packages are on CRAN :)

**Comment by mattansb** [comment]
I don't really think they *belong* in performance :/

If we're making a breaking change anyway, might as well just change the function name to `check_bartlett_sphericity()`, as @bwiernik suggested.

**Comment by IndrajeetPatil** [comment]
> If we're making a breaking change anyway, might as well just change the function name to check_bartlett_sphericity(), as @bwiernik suggested.

I'd vote for this option as well!

**Comment by strengejacke** [comment]
Hurry up, I want to submit today or tomorrow...

**Comment by strengejacke** [comment]
(any option except adding pkg dependencies is accepted)

**Comment by DominiqueMakowski** [comment]
Ok, that said I'd think I'd prefer `check_sphericity_bartlett()` so that users can start typing check_sph... and the autocompletion will do the rest. Also it goes with our logic of having subtypes specifiers at the end (so that "all" check_sphericity which is the supraordinal category are grouped together)

**Comment by DominiqueMakowski** [comment]
what's the status do I need to make a commit to rename the function or Mat you do it all at once?

**Comment by mattansb** [comment]
On it (:
