### ISSUE TITLE
add sampling related info in parameters for Bayesian models

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#5]
### Rstanarm 
- [x] Eff.Sample
- [x] Rhat 
- [ ] MCSE

### brms 
- [ ] Eff.Sample
- [ ] Rhat 
- [ ] MCSE

**Comment by strengejacke** [comment]
Where do you extract eff. sample size? We probably can make own functions out of it...

**Comment by DominiqueMakowski** [comment]
Currently [here](https://github.com/easystats/parameters/blob/79fce23e62c9699fd80b25babf303bab43ed6a6e/R/model_parameters.bayesian.R#L28). But this definitely needs to be reimplemented in a more autonomous and flexible way!

Do we want one function per index, like `rhat` and `effective_sample` or a general `diagnostic_posterior` (since we have `describe_posterior`)?

**Comment by strengejacke** [comment]
`diagnostic_posterior()` sounds also good to me.
