### ISSUE TITLE
BCa bootstrap confidence intervals

### ISSUE THREAD

**Issue by bwiernik** [easystats/parameters#503]
For models that support them, it would be nice to include BCa intervals in addition to the currently supported percentile intervals. For completeness, we might also want Studentized or Basic bootstrap, but I see less value in those.

**Comment by strengejacke** [comment]
``` r
library(boot)
library(parameters)

set.seed(2)
model <- lm(Sepal.Length ~ Species * Petal.Width, data = iris)
bootstrap_parameters(model)
#> # Fixed Effects
#> 
#> Parameter                     | Coefficient |        95% CI |      p
#> --------------------------------------------------------------------
#> (Intercept)                   |        4.78 | [ 4.50, 5.00] | < .001
#> Speciesversicolor             |       -0.72 | [-1.62, 0.08] | 0.094 
#> Speciesvirginica              |        0.50 | [-0.67, 1.65] | 0.415 
#> Petal.Width                   |        0.91 | [ 0.22, 1.97] | 0.039 
#> Speciesversicolor:Petal.Width |        0.50 | [-0.66, 1.52] | 0.393 
#> Speciesvirginica:Petal.Width  |       -0.27 | [-1.36, 0.67] | 0.545

bootstrap_parameters(model, ci_method = "bci")
#> # Fixed Effects
#> 
#> Parameter                     | Coefficient |        95% CI |      p
#> --------------------------------------------------------------------
#> (Intercept)                   |        4.78 | [ 4.51, 4.99] | < .001
#> Speciesversicolor             |       -0.77 | [-1.63, 0.03] | 0.079 
#> Speciesvirginica              |        0.49 | [-0.82, 1.66] | 0.447 
#> Petal.Width                   |        0.92 | [ 0.25, 2.03] | 0.029 
#> Speciesversicolor:Petal.Width |        0.52 | [-0.67, 1.48] | 0.345 
#> Speciesvirginica:Petal.Width  |       -0.25 | [-1.44, 0.61] | 0.550
```

<sup>Created on 2021-05-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by IndrajeetPatil** [comment]
😮 

Daniel is the _Flash_ of supporting feature requests! ⚡ 

![tenor](https://user-images.githubusercontent.com/11330453/119808313-47b81780-bee4-11eb-95b0-ffa4872ba773.gif)

**Comment by strengejacke** [comment]
Not sure how to adjust p-values, though.

**Comment by mattansb** [comment]
The current implantation is here:

https://github.com/easystats/parameters/blob/main/R/methods_base.R#L143-L157

But this method assumes translation equivariance: that shape of the sampling distribution is unaffected by the null being true or not.... Which is probably never really true anyway? A true p-value would require a permutation test... Otherwise, I would suggest dropping p-values entirely.

**Comment by bwiernik** [comment]
The approach I would use is to compute a wide range of confidence limits and interpolate at which limit the interval crosses zero. See e.g., https://www.stat.umn.edu/geyer/old/5601/examp/tests.html. This could be combined with `optim()` to find the precise limit if desired. This approach is consistent with the confidence distribution interpretation of p values.

**Comment by strengejacke** [comment]
> @strengejacke what's your thinking on calling the method `"bci"` instead of `"bcai"`?

Just the three letters. ;-) We may also rename it into `bcai()`. @DominiqueMakowski any preferences here?

**Comment by mattansb** [comment]
Interesting...

Here's my version (that uses the bootstrapped distribution we already have in the output):

``` r
p_value_distrib <- function(x, null = 0){
  get_ci <- function(alpha, d) {
    alpha <- ifelse(alpha > 1, 1, 
                    ifelse(alpha < 0, 0,
                           alpha))
    q <- quantile(c(d, null), probs = c(alpha/2, 1 - alpha/2))
    min(abs(q - null))
  }
  
  optim(0.5, fn = get_ci, d = x)[["par"]]
}

set.seed(444)
dat <- data.frame(x = rnorm(20),
                  y = rnorm(20))
m <- lm(y ~ x, dat)
b <- parameters::bootstrap_parameters(m)

parameters::model_parameters(m)$p[2]
#> [1] 0.1572755
b$p[2]
#> [1] 0.1308691
attr(b, "boot_samples")[[2]] |> p_value_distrib()
#> [1] 0.17
```

<sup>Created on 2021-05-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Does this make sense?

How would be support BCa and other methods this way?

**Comment by strengejacke** [comment]
> @strengejacke what's your thinking on calling the method `"bci"` instead of `"bcai"`?

you can now use both "bci" and "bcai", and `bcai()` was added as alias.
