### ISSUE TITLE
keep_iterations argument for model_parameters

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#521]
In the context of #520, I thought it'd be very convenient and useful to have a `keep_iterations` argument to model_parameters that would also return each iteration as separate columns (as `iter_1`, `iter_2`, etc., similarly to insight::get_predicted), for Bayesian or boostrapped models. This would allow to automatically reshape them with `bayestestR::reshape_iterations()`, which would be useful for plotting and such. I think this would just require to transpose the dataframe of iterations and merge it with the parameters table?

**Comment by strengejacke** [comment]
But we have bootstrap_model, which can be called directly?

**Comment by DominiqueMakowski** [comment]
Let me explain, currently these two return the same "type" of output:

``` r
library(rstanarm)

head(parameters::bootstrap_model(lm(Petal.Length ~ Sepal.Length, data=iris)))
#>   (Intercept) Sepal.Length
#> 1   -6.897673     1.822538
#> 2   -6.794865     1.802593
#> 3   -7.711458     1.975298
#> 4   -6.890940     1.828602
#> 5   -7.245136     1.891665
#> 6   -6.641201     1.782959
head(insight::get_parameters(stan_glm(Petal.Length ~ Sepal.Length, data=iris, refresh=0)))
#>   (Intercept) Sepal.Length
#> 1   -6.876114     1.792500
#> 2   -6.955083     1.814053
#> 3   -7.121851     1.848262
#> 4   -6.640905     1.764685
#> 5   -6.885221     1.810205
#> 6   -7.428681     1.912867
```

<sup>Created on 2021-06-06 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

i.e., a dataframe of iterations where each *col* is a parameter and iterations as presented as rows.

What I'm suggesting is to have:

``` r
m <- lm(Petal.Length ~ Sepal.Length, data=iris)
parameters::parameters(m, bootstrap = TRUE, keep_iterations = TRUE)
#> Parameter    | Coefficient |         95% CI |      p | iter_1 | iter_2 | iter_3 | iter_4 | ....
#> --------------------------------------------------------------------------------
#> (Intercept)  |       -7.16 | [-7.98, -6.35] | < .001 |   -7.16 | -7.16 | -7.16 |  ... | 
#> Sepal.Length |        1.87 | [ 1.74,  2.00] | < .001 |   1.87 |   1.87 |   1.87 |   ... | 
```

<sup>Created on 2021-06-06 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>


<sup>Created on 2021-06-06 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>


I.e., all iterations kept in the final parameters table as columns (one iteration *per column*)

**Comment by bwiernik** [comment]
Perhaps a list column that contains all of the iterations in one column might be better? What exactly is the use here?

**Comment by DominiqueMakowski** [comment]
It could be passed to `bayestestR::reshape_iterations()` to painlessly plot parameters on top of the posterior distribution it would be also used in `modelbased::estimate_grouplevel()` where posteriors are needed for BLUPs for instance). 

Having iterations as columns (albeit not really "printable") is a format that we use already quite a lot in easystats (and reshape_iterations was made to process specifically that kind of super-wide tables). Note that we also have `estimate_prediction(m, keep_iterations = TRUE)` (that also returns iterations as columns), so having the same argument in `model_parameters()` would be a consistent feature :)

**Comment by bwiernik** [comment]
Perhaps the function should return a plain data frame with just the iterations, no estimate/CI in that case?

**Comment by DominiqueMakowski** [comment]
I think both are good, otherwise people would just directly access the posteriors I think, + reshape_iterations is smart enough the keep all the rest intact so it's not a problem to have the iterations + other non-iterations

**Comment by strengejacke** [comment]
I would rather suggest adding a "to_wide" argument or similar to `bootstrap_model()`.

**Comment by DominiqueMakowski** [comment]
but it's crucial that it's in model_parameters so that all the filtering of parameters type groups effects etc., even down the road standardization etc. can work :) lemme give it a try

**Comment by DominiqueMakowski** [comment]
I added the option in describe_posterior, so it works from `parameters()`


``` r
library(rstanarm)
library(ggplot2)

model <- stan_glm(Sepal.Length ~ Species, data = iris, refresh = 0, iter = 500, chains = 2)

params <- parameters::parameters(model, keep_iterations = TRUE)
params <- bayestestR::reshape_iterations(params)

ggplot(params, aes(x = Parameter, y = Median)) + 
  geom_violin(aes(y = iter_value)) +
  geom_pointrange(aes(ymin = CI_low, ymax = CI_high))
```

![](https://i.imgur.com/5HY7E4M.png)

<sup>Created on 2021-06-07 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>
