### ISSUE TITLE
keep/except sounded like a good alternative for rows

### ISSUE THREAD

**Issue by strengejacke** [easystats/parameters#525]
> select/exclude usually refer to columns, while in this case, it refers to rows. This could be a reason against using select/exclude.

Yes this was my argument with thinking of easystats/datawizard#4, that we should have distinct names for rows and columns. For the latter we have select/exclude, so keep/except sounded like a good alternative for rows. 

I find `parameters(model, except = "Petal.*")` and `parameters(model, keep = "Sepal.*")` pretty neat. But then in order to avoid a breaking change we could keep `parameters` for now (as an alias for `keep`). 

The logic with two arguments is pretty straightforward, first, you keep all the parameters that match `keep`, and then you keep all parameters that negate (`!`) `except`.  So there is no conflict if the two are specified at the same time

_Originally posted by @DominiqueMakowski in https://github.com/easystats/parameters/issues/522#issuecomment-856493409_

**Comment by strengejacke** [comment]
@DominiqueMakowski @bwiernik moving the discussion over here. I think `keep` and `except` might indeed be a good counterpart of `select` and `exclude` for rows (parameters).

**Comment by strengejacke** [comment]
Maybe instead of `except`, we find a better name?
- drop
- omit
- neglect
- discard

**Comment by DominiqueMakowski** [comment]
It's true that except is bit too similar to exclude

drop could work yeah

**Comment by DominiqueMakowski** [comment]
omit too tho `na.omit` ^^

**Comment by strengejacke** [comment]
I would vote for what sounds more like "natural language", and that should probably decided by a native speaker ^^

**Comment by DominiqueMakowski** [comment]
I agree and like this line of thinking ^^, but with this logic we could say that for instance we "omit" a few rows from the printing, but when we actually discard them from the output (and the object has less rows), "throwing away" is actually more appropriate, even tho less peaceful 🧘‍♂️

**Comment by bwiernik** [comment]
Drop sounds a lot more natural to me.

**Comment by strengejacke** [comment]
What about the current implementation? Can we close this issue?

**Comment by bwiernik** [comment]
Looks good to Me
