### ISSUE TITLE
check_factorstructure: improve name and print

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#54]
- I am slowly adding a new set of features in parameters around dimensionality reduction (including support for PCA / FA etc.)
- In this context, I added the two popular tests for checking if the data is suitable for FA
- I would like to have a master function that returns the output of these two checks "at once"
- A function simply running these two checks gives an ugly collated output
- how to improve it?

_Originally posted by @DominiqueMakowski in https://github.com/easystats/parameters/pull/52_

**Comment by DominiqueMakowski** [comment]
to all: I don't like the current name `check_factorstructure`, any suggestions?

**Comment by DominiqueMakowski** [comment]
@strengejacke any thoughts on a better name?

**Comment by strengejacke** [comment]
never-ever ask me for naming something... I have this discussion with a friend of mine since the beginning of our C64-time in the late 80's / early 90's, and he said I simply can't find good names. ;-)

**Comment by DominiqueMakowski** [comment]
I'll leave it as is, even though it's not da best
