### ISSUE TITLE
n_clusters plot minor

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#544]
https://twitter.com/rfunctionaday/status/1410083237834153992?s=20

**rfunctionaday** reminds me of functions that I forgot about 😅 don't know who's behind it but they know their stuff!

anyway this made me thing to change the y axis title to "Consensus between methods" which might be cleared than "agreement", waddaya think?

**Comment by IndrajeetPatil** [comment]
>  change the y axis title to "Consensus between methods" which might be clearer than "agreement"

Yes, I like it!

BTW, are you surprised that the methods seem to agree that the solution is 2, and not 3. 
We know _a priori_ that there are 3 penguin species in that dataset, and so I am surprised what is throwing off the algorithms?

**Comment by bwiernik** [comment]
Two of the species are really similar on most characteristics. Way more distance between their average centroid and the third than between their two centroids. Actually a really nice example of the limitations of clustering algorithms.
