### ISSUE TITLE
Add df method to footer for mixed models

### ISSUE THREAD

**Issue by mattansb** [easystats/parameters#545]
``` r
m <- lme4::lmer(mpg ~ hp * factor(cyl) + (hp | gear), data = mtcars)
#> boundary (singular) fit: see ?isSingular

parameters::model_parameters(m)
#> # Fixed Effects
#> 
#> Parameter    | Coefficient |   SE |               95% CI | t(22) |      p
#> -------------------------------------------------------------------------
#> (Intercept)  |       39.44 | 4.86 | [   29.92,    48.96] |  8.12 | < .001
#> hp           |       -0.15 | 0.05 | [   -0.24,    -0.06] | -3.26 | 0.001 
#> cyl [6]      |       -9.58 | 7.12 | [  -23.53,     4.38] | -1.35 | 0.179 
#> cyl [8]      |      -15.20 | 5.75 | [  -26.47,    -3.94] | -2.64 | 0.008 
#> hp * cyl [6] |        0.07 | 0.06 | [   -0.05,     0.20] |  1.14 | 0.252 
#> hp * cyl [8] |        0.11 | 0.05 | [    0.02,     0.20] |  2.35 | 0.019 
#> 
#> # Random Effects
#> 
#> Parameter            | Coefficient
#> ----------------------------------
#> SD (Intercept: gear) |        4.39
#> SD (hp: gear)        |    5.01e-03
#> Cor (Intercept~gear) |       -1.00
#> SD (Residual)        |        2.69

parameters::model_parameters(m, df_method = "s")
#> # Fixed Effects
#> 
#> Parameter    | Coefficient |   SE |               95% CI |     t |    df |     p
#> --------------------------------------------------------------------------------
#> (Intercept)  |       39.44 | 4.86 | [   29.92,    48.96] |  8.12 |  3.36 | 0.003
#> hp           |       -0.15 | 0.05 | [   -0.24,    -0.06] | -3.26 | 21.27 | 0.004
#> cyl [6]      |       -9.58 | 7.12 | [  -23.53,     4.38] | -1.35 | 25.13 | 0.191
#> cyl [8]      |      -15.20 | 5.75 | [  -26.47,    -3.94] | -2.64 | 25.76 | 0.014
#> hp * cyl [6] |        0.07 | 0.06 | [   -0.05,     0.20] |  1.14 | 24.79 | 0.263
#> hp * cyl [8] |        0.11 | 0.05 | [    0.02,     0.20] |  2.35 | 22.43 | 0.028
#> 
#> # Random Effects
#> 
#> Parameter            | Coefficient
#> ----------------------------------
#> SD (Intercept: gear) |        4.39
#> SD (hp: gear)        |    5.01e-03
#> Cor (Intercept~gear) |       -1.00
#> SD (Residual)        |        2.69
```

<sup>Created on 2021-07-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by bwiernik** [comment]
How are we deciding on df/p by default? lmer rather explicitly doesn't choose an approximation for the denominator df (a decision I personally agree with; I cite the Bates listserv post about it often)

**Comment by mattansb** [comment]
I think the default is to use `df.residual()`?

`?model_parameters.merMod` say default is Wald,
but `?degrees_of_freedom` sat Wald is `Inf`.... Which is def not the case.

**Comment by bwiernik** [comment]
Hmm. Yeah, the df column definitely indicates some sort of KR or Satthertwaite approximation is being used, not a Wald approximation.

I don't really care for that. Each of the possible df approximations has fairly common conditions where they fail catastrophically. I'd feel a lot more comfortable giving profile likelihood/bootstrap CIs and either no p value (maybe with an explanatory message), Wald p values (with a cautionary message), or a p value estimated from likelihood/bootstrap (I've been wondering about this option for a while now). I think df approximations really need to be an explicit affirmative choice. The 'mindless' loading of lmerTest and its defaults is a big problem with common mixed effects practice in R in my view.

**Comment by mattansb** [comment]
> The 'mindless' loading of lmerTest and its defaults is a big problem with common mixed effects practice in R in my view.

![](https://media3.giphy.com/media/Q80mPk0CLu6AJRe9tV/giphy.gif)

**Comment by bwiernik** [comment]
![image](https://user-images.githubusercontent.com/4773225/124069162-b7508380-da09-11eb-9e75-46e2150d9d70.png)

**Comment by strengejacke** [comment]
> I think the default is to use `df.residual()`?
> 
> `?model_parameters.merMod` say default is Wald,
> but `?degrees_of_freedom` sat Wald is `Inf`.... Which is def not the case.

> For models of class lmerMod, when df_method = "wald", residual degrees of freedom are returned.
_(source: https://easystats.github.io/parameters/reference/model_parameters.merMod.html)_

**Comment by strengejacke** [comment]
I think there was an issue with the `ci()` method, which was not based on the residual df. I hope this is fixed now. To be clear:
when we have df (like t(22) in @mattansb example), computation of both CI and p-values is based on those df:


CI

```r
stats::qt(.975,  df = 22)
```

p-value:

```r
2 * stats::pt(<t-value>, df = 22, lower.tail = FALSE)
```

**Comment by DominiqueMakowski** [comment]
> I'd feel a lot more comfortable giving profile likelihood/bootstrap CIs and either no p value (maybe with an explanatory message)

We should definitely return p-values by default, their removal by Bates from lme4 (although fully justified) led to many users doing even weirder approximations. Down the line it also led to the development of interesting stuff like lmerTest and other packages, but still, the "how to get p-value from lme4" is probably one of the most googled questions for beginners. Moreover, it seems like even Doug changed his mind as his neo-lme4 Julia package returns p-values by default...  
Bootstrapped CI/p would be nice, but I think that, by default, faster solutions should be preferred. It's purely a personal feeling, but when I'm exploring a new package, or a new tool, or even starting some analysis, I want my functions to "work" and work "fast", just to get a sense of things. And then once everything is "set" then I can start fine-tuning the options for more accurate / correct - and computationally heavy - procedures.

**Comment by bwiernik** [comment]
If we give a p value then, my preference would be to follow glmmTMB and Julia MixedModel's behavior and use a normal Wald/Inf df p value, with some text suggesting alternatives
