### ISSUE TITLE
A generic method for printing tables?

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#55]
Started rework on `principal_components`. TODO:

- [ ] Improve print method (@strengejacke maybe we should think about adding a `print_table` method in insight to easily return nicely formatted tables (with separation lines), such as the ones in `report`?)

_Originally posted by @DominiqueMakowski in https://github.com/easystats/parameters/pull/52#issuecomment-504284527_

**Comment by strengejacke** [comment]
I would like to address this after versoin 0.4.0, because there are some crucial time issues (CRAN requested insight-update to fix the check issues, I'll be on vacation soon, ...).
