### ISSUE TITLE
Add CIs to random SD parameters?

### ISSUE THREAD

**Issue by mattansb** [easystats/parameters#559]
``` r
data(mtcars)
m1 <- lme4::lmer(mpg ~ wt + (wt | gear), data = mtcars)
parameters::model_parameters(m1)
#> # Fixed Effects
#> 
#> Parameter   | Coefficient |   SE |         95% CI | t(26) |      p
#> ------------------------------------------------------------------
#> (Intercept) |       37.21 | 4.72 | [27.95, 46.46] |  7.88 | < .001
#> wt          |       -5.67 | 1.39 | [-8.39, -2.96] | -4.09 | < .001
#> 
#> # Random Effects
#> 
#> Parameter            | Coefficient
#> ----------------------------------
#> SD (Intercept: gear) |        7.53
#> SD (wt: gear)        |        2.17
#> Cor (Intercept~gear) |       -0.99
#> SD (Residual)        |        2.55
```

Random effects are returned as point estiamtes, but we can get CIs:

``` r
confint(m1, "theta_") # method = "profile"
#>              2.5 %    97.5 %
#> .sig01  0.72773270 19.119626
#> .sig02 -1.00000000  1.000000
#> .sig03  0.09615637  5.492692
#> .sigma  2.00959518  3.386455
```

The order and the rownames are weird, but we can deal with that.

Same for `glmmTMB`:

``` r
m2 <- glmmTMB::glmmTMB(mpg ~ wt + (wt | gear), data = mtcars)
#> Warning in fitTMB(TMBStruc): Model convergence problem; singular convergence
#> (7). See vignette('troubleshooting')

confint(m2, "theta_") # method = "wald"
#>                          2.5 %    97.5 %  Estimate
#> Std.Dev.(Intercept)  1.9536916 16.564466  5.688748
#> Std.Dev.wt           0.5047694  4.887851  1.570744
#> Cor.wt.(Intercept)  -1.0000000  1.000000 -1.000000
confint(m2, "sigma")
#>          2.5 %   97.5 % Estimate
#> sigma 1.967945 3.303373 2.549678
```

<sup>Created on 2021-07-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by bwiernik** [comment]
Yes please. I'd like to also be consistent and add sigma to the lm and glm parameters output

**Comment by mattansb** [comment]
Sigma is a variance parameter, yes. But not all mixed models have it, because it's actually a distributional parameter... So I think we should finally decide what to do with it, along with the rest of the distributional parameters. Hmmm...

**Comment by bwiernik** [comment]
I think that any estimated parameter should be reported with a CI in parameters. We could also be general and just report them always with NAs or em dashes if fixed

**Comment by strengejacke** [comment]
One problem I see is computation time of profiled CIs for larger models. We have changed the default of `model_parameters()` to also return random effects now. If we want to add CIs as well by default, this will slow down the function.

**Comment by strengejacke** [comment]
Two examples here: the "summary" would take 2 to 6 seconds longer (on a quite fast machine) to display:

``` r
library(lme4)
#> Loading required package: Matrix
fm1 <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy)

tictoc::tic()
confint(fm1, "theta_")
#> Computing profile confidence intervals ...
#>             2.5 %     97.5 %
#> .sig01 14.3814182 37.7159953
#> .sig02 -0.4815008  0.6849863
#> .sig03  3.8011641  8.7533808
#> .sigma 22.8982669 28.8579965
tictoc::toc()
#> 1.99 sec elapsed


data("cbpp")
cbpp$obs <- 1:nrow(cbpp)
gm1 <- glmer(cbind(incidence, size - incidence) ~ period + (1 | herd) +  (1|obs),
             family = binomial, 
             data = cbpp)

tictoc::tic()
confint(gm1, "theta_")
#> Computing profile confidence intervals ...
#>            2.5 %    97.5 %
#> .sig01 0.4198668 1.3703842
#> .sig02 0.0000000 0.8737183
tictoc::toc()
#> 5.11 sec elapsed
```

<sup>Created on 2021-07-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by strengejacke** [comment]
I think this could be relevant for @vincentarelbundock as well, as he maintains the _modelsummary_ package. Vincent, what is your opinion / suggestion on this topic?

**Comment by bwiernik** [comment]
How about we add some text like `Set ci_method = "profile" or "boot" to obtain intervals for random effects parameters.` when a df-based or Wald method is used and there is no closed form interval for the random effects/dispersion/distribution parameters?

(Or whatever the argument name is.)

**Comment by vincentarelbundock** [comment]
Thanks for the ping.

I'm not sure I have a very strong opinion on this. Obviously, it's great if we can get the CI. But I do think that computation is a major issue. Given your benchmark, someone with a slow laptop might easily spend an extra 10 seconds per model. If they're trying to summarize 6 models in `modelsummary`, then that's an extra minute of computation. This is not terrible if you expect it and know the table you want, but *a lot* of people will think `R` is hanging if they have to wait a minute for a simple thing like extracting results.

So if at all possible, I'd say that expensive computations should be available but not default.

**Comment by bwiernik** [comment]
Reporting profile or boot CIs only when requested and omitting CIs for random effects otherwise is consistent with what broom.mixed does. 

I suggest we go with that and add a footnote to the print method about how to get random effects CIs if they are NA. 

For lm models, the PL CI for sigma has an analytic solution. For glmmTMB, it provides normal theory intervals for log(SD) when Wald intervals are requested, which seem to work pretty well in most cases.

**Comment by mattansb** [comment]
> I suggest we go with that and add a footnote to the print method about how to get random effects CIs if they are NA.

👍

**Comment by mattansb** [comment]
For `lme4`, setting `oldNames = FALSE` gives more informative names:

``` r
data(mtcars)
m1 <- lme4::lmer(mpg ~ wt + (wt | gear), data = mtcars)

confint(m1, "theta_", oldNames = FALSE) # method = "profile"
#>                               2.5 %    97.5 %
#> sd_(Intercept)|gear      0.72773270 19.119626
#> cor_wt.(Intercept)|gear -1.00000000  1.000000
#> sd_wt|gear               0.09615637  5.492692
#> sigma                    2.00959518  3.386455
```

<sup>Created on 2021-07-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by strengejacke** [comment]
``` r
data(mtcars)
m1 <- lme4::lmer(mpg ~ wt + (wt | gear), data = mtcars)

parameters::model_parameters(m1)
#> # Fixed Effects
#> 
#> Parameter   | Coefficient |   SE |         95% CI | t(26) |      p
#> ------------------------------------------------------------------
#> (Intercept) |       37.21 | 4.72 | [27.50, 46.91] |  7.88 | < .001
#> wt          |       -5.67 | 1.39 | [-8.52, -2.83] | -4.09 | < .001
#> 
#> # Random Effects
#> 
#> Parameter            | Coefficient
#> ----------------------------------
#> SD (Intercept: gear) |        7.53
#> SD (wt: gear)        |        2.17
#> Cor (Intercept~gear) |       -0.99
#> SD (Residual)        |        2.55
#> 
#> Using residual degrees of freedom for CI/p-values.

parameters::model_parameters(m1, df_method = "profile")
#> Computing profile confidence intervals ...
#> # Fixed Effects
#> 
#> Parameter   | Coefficient |   SE |         95% CI | t(26) |      p
#> ------------------------------------------------------------------
#> (Intercept) |       37.21 | 4.72 | [26.21, 47.52] |  7.88 | < .001
#> wt          |       -5.67 | 1.39 | [-8.70, -2.58] | -4.09 | < .001
#> 
#> # Random Effects
#> 
#> Parameter            | Coefficient |         95% CI
#> ---------------------------------------------------
#> SD (Intercept: gear) |        7.53 | [ 0.73, 19.12]
#> SD (wt: gear)        |        2.17 | [ 0.10,  5.49]
#> Cor (Intercept~gear) |       -0.99 | [-1.00,  1.00]
#> SD (Residual)        |        2.55 | [ 2.01,  3.39]
#> 
#> Showing profiled confidence intervals.
```

<sup>Created on 2021-07-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by mattansb** [comment]
Love it!
Should this perhaps be controlled by a separate argument? I don't think this is related to df per se.
Perhaps `random_ci` with `random_ci = NULL` as default?

**Comment by strengejacke** [comment]
This is an older discussion, trying to have just one argument for df/ci. In most cases, this works, since computation of CI is based on DF. In this particular case (or boot), it does not... :-/

**Comment by mattansb** [comment]
Then.... I think it's time to split those........ Sorry mate

**Comment by mattansb** [comment]
You can do:
```R
model_parameters <- function(model, df_method = NULL, ci_method = df_method , ...) {
}
```

**Comment by bwiernik** [comment]
Personally, I don't think we need two arguments, but the argument should be called 'ci_method'. Renaming is easy to make backwards compatible when the function has ...

**Comment by strengejacke** [comment]
Maybe that's the best compromise...

**Comment by bwiernik** [comment]
I think that that is an accurate way to put it

**Comment by mattansb** [comment]
> but the argument should be called 'ci_method'

But isn't not only used for CI, but also for the p-value... :/

**Comment by strengejacke** [comment]
closing in favor of #570

**Comment by strengejacke** [comment]
re-opening, to have it more focused here.
