### ISSUE TITLE
n_factors: improvements

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#56]
Hi @SachaEpskamp ☺️ 

Some (long) [time ago](https://github.com/neuropsychology/psycho.R/issues/29), upon your review of the psycho package, you mentioned about adding other methods, such as EGA, in the `n_factors` function that aims at aggregating a lot of methods together.

I recently updated, re-implemented and hopefully improved this function (see [here a small demo](https://easystats.github.io/parameters/articles/n_factors.html)) in this package. I added the [EGA methods using the EGAnet package](https://github.com/easystats/parameters/blob/31ef27361fd7a3074a7c8d2a0b0d4518d36fec2b/R/n_factors.R#L366). 

The implementation is rather simple, but the package fails quite often (I didn't manage to run the `bootEGA` from the example). I am not sure whether it is a bug or related to the provided data.

Anyway, I was hoping you could tell us what you think of this function; does the implementation, looks reasonable to you? Are you aware of any other methods/procedures that we could add to it? Do not hesitate to share any thoughts and comments :) Thanks

**Comment by SachaEpskamp** [comment]
Hi Dominique,

Wow this looks very nice! I'll send this to Hudson too! I don't know of other methods myself.

Best, Sacha

**Comment by hfgolino** [comment]
Hi @DominiqueMakowski , thanks for pointing out the bug. We fixed the bootEGA function, and updated the EGAnet package on GitHub.

Great package, by the way. Maybe we should talk via email sometime soon (hfg9s@virginia.edu).

Cheers,

Hudson

**Comment by DominiqueMakowski** [comment]
@hfgolino, sure, and please do not hesitate to share your thoughts on how we can improve our support for EGAnet to make its use more correct and relevant in our wrapper function to estimate the number of components.

Currently, it is wrapped in this small function:

https://github.com/easystats/parameters/blob/31ef27361fd7a3074a7c8d2a0b0d4518d36fec2b/R/n_factors.R#L369-L380

Does that look alright? (note the suppression of messages and warnings since I did not find any argument to silent the routine)
