### ISSUE TITLE
move `check_heterogeneity()` to `performance` package

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/parameters#562]
As discussed on Twitter, this function will be called `check_heterogeneity_bias()` once it moves to `performance`. 

@strengejacke I will make this change once you give me a green signal. 
I will also run `revdepcheck` to see if this causes any breakage. Unlikely, but better to check.

**Comment by IndrajeetPatil** [comment]
I am also wondering: 
Since we _are_ making this breaking change, we should also just move `check_multimodal` function to `performance`?
This way all `check_*` functions will be in a single place.

**Comment by bwiernik** [comment]
Yes.

**Comment by strengejacke** [comment]
I'd say yes.

**Comment by IndrajeetPatil** [comment]
Cool, on it!

**Comment by IndrajeetPatil** [comment]
@mattansb This change means that `performance` will move from `Suggests` to `Imports`. Hope that's okay with you.

https://github.com/easystats/effectsize/blob/148678bbc1dfa8c97698c85e8f0e13f99fc04bb7/R/standardize_info.R#L365

**Comment by mattansb** [comment]
Hmmmm why are you letting *me* know?

**Comment by IndrajeetPatil** [comment]
Because you are maintaining `effectsize` 😅

**Comment by mattansb** [comment]
Ohhhhh okay (: lol
Can make those changes over on effectsize too?

**Comment by IndrajeetPatil** [comment]
Yepp, will do.

**Comment by IndrajeetPatil** [comment]
We also have these in `parameters`, but I guess it's too late for them to be moved to `performance` as well?

<img width="1142" alt="Screenshot 2021-07-20 at 08 45 07" src="https://user-images.githubusercontent.com/11330453/126274456-e9ee206a-6712-4b3f-b035-222cb8186366.png">

**Comment by mattansb** [comment]
These are data related checks, so I'd say if we were to move them - to datawizard?

**Comment by IndrajeetPatil** [comment]
Ideally, that would be the case. But, I guess, we don't want to do that because the users have come to expect all `check_*` functions to be located in _performance_ package.

We can, of course, have them in _datawizard_ and re-export them, but we are also not too keen on re-exporting.

**Comment by bwiernik** [comment]
I agree that check_* functions should be in performance. check_clusterstructure can be interpreted as a check of a factor analysis model, so I think it fits
