### ISSUE TITLE
How to include test statistic for `anova(rms::orm())` & incorrect `anova.rms` type label

### ISSUE THREAD

**Issue by krassowski** [easystats/parameters#577]
Hi, thanks for the awesome package. I do not see test statistic (`Chi.Square`) for `anova` from `rms::orm`. How can I get it to show up? Please see the reproducer below:

```R
formula = mpg ~ cyl + disp + hp + drat
ordinary_fit = stats::lm(formula, data=mtcars)
ordinal_fit = rms::orm(formula, data=mtcars)

anova_ordinary = anova(ordinary_fit)
anova_ordinal = anova(ordinal_fit)
```

1. Statistics are given for both when using base `data.frame`:

```R
data.frame(anova_ordinary)
```

> ```
>           Df     Sum.Sq    Mean.Sq   F.value       Pr..F.
> cyl        1 817.712952 817.712952 90.151396 4.266410e-10
> disp       1  37.593953  37.593953  4.144666 5.168658e-02
> hp         1   9.370929   9.370929  1.033128 3.184472e-01
> drat       1  16.467435  16.467435  1.815505 1.890485e-01
> Residuals 27 244.901918   9.070441        NA           NA
> ```

```R
data.frame(anova_ordinal)
```

> ```
>       Chi.Square d.f.            P
> cyl    3.1313543    1 7.679992e-02
> disp   3.1403222    1 7.637872e-02
> hp     3.1221605    1 7.723432e-02
> drat   0.8732411    1 3.500596e-01
> TOTAL 27.1877148    4 1.821515e-05
> ```

2. Statistics are present for ordinary but missing for ordinal when using `parameters`:

```R
parameters::parameters(anova_ordinary)
```

> ```
> Parameter | Sum_Squares | df | Mean_Square |     F |      p
> -----------------------------------------------------------
> cyl       |      817.71 |  1 |      817.71 | 90.15 | < .001
> disp      |       37.59 |  1 |       37.59 |  4.14 | 0.052 
> hp        |        9.37 |  1 |        9.37 |  1.03 | 0.318 
> drat      |       16.47 |  1 |       16.47 |  1.82 | 0.189 
> Residuals |      244.90 | 27 |        9.07 |       |       
> 
> Anova Table (Type 1 tests)
> ```

```R
parameters::parameters(anova_ordinal)
```

> ```
> # Fixed Effects
> 
> Parameter | df |      p
> -----------------------
> cyl       |  1 | 0.077 
> disp      |  1 | 0.076 
> hp        |  1 | 0.077 
> drat      |  1 | 0.350 
> Total     |  4 | < .001
> 
> Anova Table (Type 1 tests)
> ```

**Comment by krassowski** [comment]
Also, the output seems states "Anova Table (Type 1 tests)" but `rms` uses type 2 according to:

https://github.com/harrelfe/rms/issues/60#issuecomment-373434171

Can you please confirm whether the footer is incorrect, or whether you recompute it to return type 1 results?

**Comment by krassowski** [comment]
I am now confident that the type is incorrect for `rms` models:

```R
formula = mpg ~ cyl + disp + hp + drat
ordinary_fit_base = stats::lm(formula, data=mtcars)
ordinary_fit = rms::ols(formula, data=mtcars)

anova_ordinary_base_type_1 = anova(ordinary_fit_base)
anova_ordinary_base_type_2 = car::Anova(ordinary_fit_base, type="II")
anova_ordinary_rms = anova(ordinary_fit)
```

#### Using the default `print` method

```R
anova_ordinary_base_type_1
```

> ```
> Analysis of Variance Table
> 
> Response: mpg
>           Df Sum Sq Mean Sq F value    Pr(>F)    
> cyl        1 817.71  817.71 90.1514 4.266e-10 ***
> disp       1  37.59   37.59  4.1447   0.05169 .  
> hp         1   9.37    9.37  1.0331   0.31845    
> drat       1  16.47   16.47  1.8155   0.18905    
> Residuals 27 244.90    9.07                      
> ---
> Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
> ```

```R
anova_ordinary_base_type_2
```

> ```
> Anova Table (Type II tests)
> 
> Response: mpg
>            Sum Sq Df F value Pr(>F)
> cyl         8.444  1  0.9309 0.3432
> disp       14.765  1  1.6279 0.2129
> hp         19.613  1  2.1623 0.1530
> drat       16.467  1  1.8155 0.1890
> Residuals 244.902 27               
> ```

```R
anova_ordinary_rms
```

> ```
>                 Analysis of Variance          Response: mpg 
> 
>  Factor     d.f. Partial SS MS         F     P     
>  cyl         1     8.443983   8.443983  0.93 0.3432
>  disp        1    14.765422  14.765422  1.63 0.2129
>  hp          1    19.613259  19.613259  2.16 0.1530
>  drat        1    16.467435  16.467435  1.82 0.1890
>  REGRESSION  4   881.145269 220.286317 24.29 <.0001
>  ERROR      27   244.901918   9.070441             
> ```


#### Using `parameters`

Correct:

```R
parameters::parameters(anova_ordinary_base_type_1)
```

> ```
> Parameter | Sum_Squares | df | Mean_Square |     F |      p
> -----------------------------------------------------------
> cyl       |      817.71 |  1 |      817.71 | 90.15 | < .001
> disp      |       37.59 |  1 |       37.59 |  4.14 | 0.052 
> hp        |        9.37 |  1 |        9.37 |  1.03 | 0.318 
> drat      |       16.47 |  1 |       16.47 |  1.82 | 0.189 
> Residuals |      244.90 | 27 |        9.07 |       |       
> 
> Anova Table (Type 1 tests)
> ```

Correct:

```R
parameters::parameters(anova_ordinary_base_type_2)
```

> ```
> Parameter | Sum_Squares | df | Mean_Square |    F |     p
> ---------------------------------------------------------
> cyl       |        8.44 |  1 |        8.44 | 0.93 | 0.343
> disp      |       14.77 |  1 |       14.77 | 1.63 | 0.213
> hp        |       19.61 |  1 |       19.61 | 2.16 | 0.153
> drat      |       16.47 |  1 |       16.47 | 1.82 | 0.189
> Residuals |      244.90 | 27 |        9.07 |      |      
> 
> Anova Table (Type 2 tests)
> ```

**Incorrect** (should be `Type 2 tests`):

```R
parameters::parameters(anova_ordinary_rms)
```

> ```
> # Fixed Effects
> 
> Parameter | Sum_Squares_Partial | df | Mean_Square |     F |      p
> -------------------------------------------------------------------
> cyl       |                8.44 |  1 |        8.44 |  0.93 | 0.343 
> disp      |               14.77 |  1 |       14.77 |  1.63 | 0.213 
> hp        |               19.61 |  1 |       19.61 |  2.16 | 0.153 
> drat      |               16.47 |  1 |       16.47 |  1.82 | 0.189 
> Total     |              881.15 |  4 |      220.29 | 24.29 | < .001
> Residuals |              244.90 | 27 |        9.07 |       |       
> 
> Anova Table (Type 1 tests)
> ```

**Comment by mattansb** [comment]
The label is incorrect.
Unfortunately the anova object returned by `rms:::anova.rms` does not include the "type" information, and the object class is `c("anova", "data.frame")` so there is no way to now where it's from - and `parameters` defaults to "type = 1" when this information is not available.

Perhaps you can open an issue over at `rms` to add this information in the header attribute.

**Comment by krassowski** [comment]
Thanks for the reply! I understand that this is tricky to fix without an action on `rms` side. I opened the issue over at https://github.com/harrelfe/rms/issues/105 and renamed the issue for visibility. What about the inclusion of `Chi.Square` in the `parameters` result?

**Comment by strengejacke** [comment]
``` r
library(parameters)
formula = mpg ~ cyl + disp + hp + drat

rms::ols(formula, data = mtcars) |> 
  anova() |> 
  model_parameters()
#> # Fixed Effects
#> 
#> Parameter | Sum_Squares_Partial | df | Mean_Square |     F |      p
#> -------------------------------------------------------------------
#> cyl       |                8.44 |  1 |        8.44 |  0.93 | 0.343 
#> disp      |               14.77 |  1 |       14.77 |  1.63 | 0.213 
#> hp        |               19.61 |  1 |       19.61 |  2.16 | 0.153 
#> drat      |               16.47 |  1 |       16.47 |  1.82 | 0.189 
#> Total     |              881.15 |  4 |      220.29 | 24.29 | < .001
#> Residuals |              244.90 | 27 |        9.07 |       |       
#> 
#> Anova Table (Type 2 tests)

rms::orm(formula, data = mtcars) |> 
  anova() |> 
  model_parameters()
#> # Fixed Effects
#> 
#> Parameter |  Chi2 | df |      p
#> -------------------------------
#> cyl       |  3.13 |  1 | 0.077 
#> disp      |  3.14 |  1 | 0.076 
#> hp        |  3.12 |  1 | 0.077 
#> drat      |  0.87 |  1 | 0.350 
#> Total     | 27.19 |  4 | < .001
#> 
#> Anova Table (Type 2 tests)
```

<sup>Created on 2022-05-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
