### ISSUE TITLE
moving all the `check_*` functions to `{performance}`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/parameters#581]
> we've moved all the check_* functions to {performance} even when they didn't really have anything to do with evaluating fit or model adequacy

A few still remain, and we need to decide if we want to make this breaking change (moving them to `{performance}`) for the next release itself:

![image](https://user-images.githubusercontent.com/11330453/128997405-5e781475-00c4-4d14-a9c4-3083b38c98f6.png)

_Originally posted by @IndrajeetPatil in https://github.com/easystats/parameters/issues/578#issuecomment-896623862_

**Comment by bwiernik** [comment]
I say yes. I would argue that all of these are about checking model adequacy for the factor/cluster models

**Comment by DominiqueMakowski** [comment]
Let's wait for the next release cycle before making any more movements since there was quite a lot of new stuff in this one already

**Comment by IndrajeetPatil** [comment]
This might be a matter of personal taste, but I, as a user, find it much more annoying if every consecutive release has a breaking change than a single one since it means more work for me. While a single release with many breaking changes means I just need to adjust once. 

That said, if we plan to also release `{easystats}` during this cycle, then this whole discussion is moot.

**Comment by bwiernik** [comment]
I would agree--I would prefer to have all of the movement of functions happen in one cycle.

**Comment by mattansb** [comment]
Same.

**Comment by strengejacke** [comment]
Since some of these changes not only affect "internal" packages, I prefer a rather "smooth" transition with the classic life-cycle (deprecation, defunct, ...), to avoid updating multiple packages within 2 weeks, which also might require "re-updating" some of the former packages they depend on.

**Comment by IndrajeetPatil** [comment]
Should we already add deprecation messages to these functions?

**Comment by IndrajeetPatil** [comment]
So many of these issues can be avoided just by getting the meta-package on CRAN. I am no longer sure what we are waiting for.

I have seen so many other meta-packages (fastverse, healthyverse, etc.) that have effortlessly made it to CRAN without having to justify much. I think we really need to try again soon.

**Comment by IndrajeetPatil** [comment]
Now that the meta-package is on CRAN, we can do this.

**Comment by IndrajeetPatil** [comment]
*bump*

**Comment by strengejacke** [comment]
We could start importing/re-exporting in _performance_ and later copy to _performance_ (and re-export in _parameters_), deprecate and remove.

**Comment by strengejacke** [comment]
Where are these functions used across _eaystats_? Maybe we can even (re)move then now? Maybe open a PR where these functions are removed and start a revdep check on that branch?
