### ISSUE TITLE
model_parameters not working with lme4

### ISSUE THREAD

**Issue by jasonmoy28** [easystats/parameters#585]
# Replication: 
`fit = lme4::lmer(data = lme4::cake, formula = 'angle ~ temperature + (temperature|recipe)')`
`parameters::model_parameters(fit)`

The code throws an error of: 
`Error in rbind(deparse.level, ...) : numbers of columns of arguments do not match`

**Comment by bwiernik** [comment]
What happens if you don't put your formula in quotes?

**Comment by IndrajeetPatil** [comment]
I _think_ this is a duplicate of https://github.com/easystats/parameters/issues/523 and should be fixed in the development version on GitHub.

**Comment by strengejacke** [comment]
yes, looks like it. Can you please try following installation steps to update your packages, and then try your example again?

```r
install.packages("insight", repos = "https://easystats.r-universe.dev")
install.packages("datawizard", repos = "https://easystats.r-universe.dev")
install.packages("parameters", repos = "https://easystats.r-universe.dev")
```

**Comment by jasonmoy28** [comment]
Yes. The development version works. Any timeline on when to publish them on CRAN? I understand it's none of your problems. But my package depends on these packages, so would like to learn more about the timeline. Thanks!
