### ISSUE TITLE
`plot()` for `cluster_analysis()` doesn't work.

### ISSUE THREAD

**Issue by strengejacke** [easystats/parameters#596]
@DominiqueMakowski Can you please check https://github.com/easystats/parameters/commit/e9c26492e426757332f6acf770db93a8197d3f5e?

The plot-examples fail:

``` r
library(parameters)
rez <- cluster_analysis(iris[1:4], n = 3, method = "hkmeans")
plot(rez)
#> Error in xy.coords(x, y, xlabel, ylabel, log): 'x' is a list, but does not have components 'x' and 'y'
```

<sup>Created on 2021-09-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by DominiqueMakowski** [comment]
Let me see

**Comment by DominiqueMakowski** [comment]
``` r
library(parameters)
rez <- cluster_analysis(iris[1:4], n = 3, method = "hkmeans")
plot(rez)
```

![](https://i.imgur.com/KZLEqAP.png)

<sup>Created on 2021-09-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

it works for me 🤔

**Comment by strengejacke** [comment]
Maybe not with CRAN versions? Maybe we should remove the plot-stuff from the examples.

**Comment by IndrajeetPatil** [comment]
Speaking of examples that don't run, I am guessing this failure is temporary and will resolve itself once `{performance}` update is on CRAN?
https://easystats.github.io/see/reference/print.see_performance_pp_check.html

![image](https://user-images.githubusercontent.com/11330453/133882709-3418dd6b-2b4e-49b9-91d5-3e75dc303848.png)

**Comment by DominiqueMakowski** [comment]
> Maybe not with CRAN versions? Maybe we should remove the plot-stuff from the examples.

But we didn't change anything for some time here? could it be some stuff related to the re-re-re-re-moving of plot.visualization_matrix? also @bwiernik

**Comment by bwiernik** [comment]
@IndrajeetPatil yes.

**Comment by bwiernik** [comment]
@DominiqueMakowski My guess is that this would be fixed once the NextMethod() dispatch is added
