### ISSUE TITLE
chi square: chisq? chi_square? chi_sq? chi2?

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#61]
How to name the column of the chi² parameter?

**Comment by strengejacke** [comment]
According to our [guideline](https://github.com/easystats/easystats#convention-of-code-style) I would say:

- `chisq`
- `Chi_squared` / `chi_squared` (not sure if (6) applies for capital letter)

**Comment by DominiqueMakowski** [comment]
Although we have `R2` for the R-squared. But I agree that `Chi2` would be weird. Chi_squared seems okay...

**Comment by DominiqueMakowski** [comment]
In fact, `Chisq` might be a better option since they can be additional associated indices (`Chisq_DoF`, `Chisq_p`).
