### ISSUE TITLE
improving summary output for `BFBayesFactor` objects

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/parameters#620]
We should include the name of the frequentist effect size estimate in the `Parameter` column:

For example:

# current behavior

``` r
library(BayesFactor)
library(parameters)

ttestBF(mtcars$wt, mu = 3) |> parameters() |> as.data.frame()
#>     CI     CI_low   CI_high  Parameter     Median     pd ROPE_Percentage
#> 1 0.95 -0.5512066 0.1682628 Difference -0.2039748 0.8745       0.2365167
#> 2 0.95 -0.1729238 0.5331445       <NA>         NA     NA              NA
#>   Prior_Distribution Prior_Location Prior_Scale        BF  Cohens_d
#> 1             cauchy              0   0.7071068 0.3868518        NA
#> 2               <NA>             NA          NA        NA 0.1977558
#>            Method
#> 1 Bayesian t-test
#> 2 Bayesian t-test
```

<sup>Created on 2021-10-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

# expected behavior

``` r
library(BayesFactor)
library(parameters)

ttestBF(mtcars$wt, mu = 3) |> parameters() |> as.data.frame()
#>     CI     CI_low   CI_high  Parameter     Median     pd ROPE_Percentage
#> 1 0.95 -0.5512066 0.1682628 Difference -0.2039748 0.8745       0.2365167
#> 2 0.95 -0.1729238 0.5331445 Cohens_d  0.1977558     NA              NA
#>   Prior_Distribution Prior_Location Prior_Scale        BF  
#> 1             cauchy              0   0.7071068 0.3868518       
#> 2               <NA>             NA          NA        NA 
#>            Method
#> 1 Bayesian t-test
#> 2 Bayesian t-test
```

The same for output from contingency table analysis where we return Cramer's *V*, Phi, etc...

**Comment by mattansb** [comment]
I think the change should be made here, to have `BFBayesFactor` and `htest` methods produce similar tables:

One row for estimate + effect size:

``` r
t.test(mtcars$wt, mu = 3) |> 
  parameters::model_parameters(standardized_d = TRUE)
#> One Sample t-test
#> 
#> Parameter |   mu | Difference |       95% CI | t(31) | Cohen's d |      d 95% CI |     p
#> ----------------------------------------------------------------------------------------
#> mtcars$wt | 3.00 |       0.22 | [2.86, 3.57] |  1.26 |      0.22 | [-0.13, 0.58] | 0.218
#> 
#> Alternative hypothesis: true mean is not equal to 3
```

Two rows for estimate + effect size:
``` r
BayesFactor::ttestBF(mtcars$wt, mu = 3) |> 
  parameters::model_parameters(test = NULL, priors = FALSE)
#> Bayesian t-test
#> 
#> 95% CI        |  Parameter | Median |    BF | Cohen's d
#> -------------------------------------------------------
#> [-0.56, 0.15] | Difference |  -0.20 | 0.387 |          
#> [-0.13, 0.56] |            |        |       |      0.20
#> 
#> Uncertainty intervals (highest-density) and p values (two-tailed) computed
#>   using a MCMC distribution approximation.
```

<sup>Created on 2021-10-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by IndrajeetPatil** [comment]
I would personally vote for _One row for estimate + effect size_, **if and only if** we also make the behavior of `model_parameters()` for `BFBayesFactor` objects similar to that for `htest`:  return frequentist effect sizes **only when the user asks for them**.

So, for example, the following would return only Median + CI columns:

```r
BayesFactor::ttestBF(mtcars$wt, mu = 3) |> 
  parameters::model_parameters()
```

While, this would return Median + CI **and** Cohen's d + CI columns:

```r
BayesFactor::ttestBF(mtcars$wt, mu = 3) |> 
  parameters::model_parameters(standardized_d = TRUE)
```

**Comment by IndrajeetPatil** [comment]
Can we please fix this soon? I haven't been able to work on my package for these two weeks because of this issue.

The GitHub `{effectsize}` breaks `{statsExpressions}`, so the next update will also need to inform CRAN about that 🙈 

I am really looking forward to the `1.0.0` release 😅

**Comment by IndrajeetPatil** [comment]
Since the outputs have changed since then and this issue has got too murky, I am closing it in favor of the cleaner #630 issue.
