### ISSUE TITLE
introducing `n_Obs` column to `htest` summary outputs

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/parameters#621]
I am wondering if it will be a good idea to add a column to the summary outputs for `htest` objects containing sample size or number of observations information. 

Although this might be straightforward for some tests, it's not so for others. Or at least I can't think of a straightforward way to extract this information in certain contexts.

``` r
# t-test ----------------------

mod1 <- t.test(mtcars$wt, mu = 3)
mod1$parameter[[1]] + 1
#> [1] 32

# but what about when var.equal = FALSE for two-sample test?
mod2 <- t.test(formula = wt ~ am, data = mtcars)
mod2$parameter[[1]] # sample size no longer parameter + 1
#> [1] 29.23352

# chi-squared test ------------

mod3 <- chisq.test(table(mtcars$am, mtcars$cyl))
#> Warning in chisq.test(table(mtcars$am, mtcars$cyl)): Chi-squared approximation
#> may be incorrect
sum(mod3$observed)
#> [1] 32

mod4 <- chisq.test(table(mtcars$cyl))
sum(mod4$observed)
#> [1] 32

# correlation ------------------

# no need, correlation package does this already
dplyr::select(mtcars, wt, mpg, drat) |>
  correlation::correlation() |>
  as.data.frame()
#>   Parameter1 Parameter2          r   CI     CI_low    CI_high         t
#> 1         wt        mpg -0.8676594 0.95 -0.9338264 -0.7440872 -9.559044
#> 2         wt       drat -0.7124406 0.95 -0.8499795 -0.4839784 -5.560807
#> 3        mpg       drat  0.6811719 0.95  0.4360484  0.8322010  5.096042
#>   df_error            p              Method n_Obs
#> 1       30 3.881876e-10 Pearson correlation    32
#> 2       30 9.568520e-06 Pearson correlation    32
#> 3       30 1.776240e-05 Pearson correlation    32

# etc.
```

<sup>Created on 2021-10-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by vincentarelbundock** [comment]
FWIW, I don't think `nobs` is a parameter or something we estimate, so it should be out of scope for this package.

**Comment by bwiernik** [comment]
htest objects are such a mess, and there are too many cases where guesses would be wrong, that I think we don't do this

**Comment by vincentarelbundock** [comment]
Cool. Will close now to clean the repo up a bit, but @IndrajeetPatil should of course feel free to re-open if he has strong views or an implementation in mind.

**Comment by iago-pssjd** [comment]
I believe it would be a great idea, even not only that, but including the whole observed table for a chi-squared test , like in `summarytools::ctable` (https://cran.r-project.org/web/packages/summarytools/vignettes/introduction.html#chi-square-%F0%9D%9B%982-odds-ratio-and-risk-ratio) or in `compareGroups::createTable` (https://cran.r-project.org/web/packages/compareGroups/vignettes/compareGroups_vignette.html#odds-ratios-and-hazard-ratios)

**Comment by rempsyc** [comment]
Should be doable yeah
