### ISSUE TITLE
Catch up with `{effectsize}` changes

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/parameters#638]
With the [devel effectsize](https://github.com/easystats/effectsize/issues/400#issuecomment-986476229), the aov effect sizes are not being returned correctly (`Omega2_CI_low` is missing, e.g.): 

``` r
model <- aov(wt ~ cyl + Error(gear), data = mtcars)

effectsize::omega_squared(model, partial = TRUE, ci = .9)
#> Warning: Some CIs could not be estimated due to non-finite F, df, or df_error
#> values.
#> # Effect Size for ANOVA (Type I)
#> 
#> Group  | Parameter | Omega2 (partial) |       90% CI
#> ----------------------------------------------------
#> gear   |       cyl |             1.00 | [    , 1.00]
#> Within |       cyl |             0.47 | [0.30, 1.00]
#> 
#> - One-sided CIs: upper bound fixed at (1).

parameters::model_parameters(
  model,
  omega_squared = "partial",
  ci = .9
)
#> Warning: Some CIs could not be estimated due to non-finite F, df, or df_error
#> values.
#> Warning in params[[es]][valid_rows] <- fx[[es]]: number of items to replace is
#> not a multiple of replacement length
#> Warning in params[[ci_low]][valid_rows] <- fx$CI_low: number of items to replace
#> is not a multiple of replacement length
#> Warning in params[[ci_high]][valid_rows] <- fx$CI_high: number of items to
#> replace is not a multiple of replacement length
#> # gear
#> 
#> Parameter | Sum_Squares | df | Mean_Square
#> ------------------------------------------
#> cyl       |       10.10 |  1 |       10.10
#> 
#> # Within
#> 
#> Parameter | Sum_Squares | df | Mean_Square |     F |      p | Omega2 (partial) | Omega2_CI_high
#> -----------------------------------------------------------------------------------------------
#> cyl       |        9.61 |  1 |        9.61 | 27.94 | < .001 |             1.00 |           1.00
#> Residuals |        9.97 | 29 |        0.34 |       |        |                  |               
#> 
#> Anova Table (Type 1 tests)
```

<sup>Created on 2021-12-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mattansb** [comment]
This should be relatively easy

``` r
model <- aov(wt ~ cyl + Error(gear), data = mtcars)

omega <- effectsize::omega_squared(model)
#> Warning: Some CIs could not be estimated due to non-finite F, df, or df_error
#> values.

pars <- parameters::model_parameters(model)


merge(pars, omega, by = c("Group", "Parameter")) |> 
  insight::format_table() |> 
  insight::export_table()
#> Group  | Parameter | Sum_Squares | df | Mean_Square |     F |      p | Omega2 (partial) |       95% CI
#> ------------------------------------------------------------------------------------------------------
#> gear   |       cyl |       10.10 |  1 |       10.10 |       |        |             1.00 | [    , 1.00]
#> Within |       cyl |        9.61 |  1 |        9.61 | 27.94 | < .001 |             0.47 | [0.25, 1.00]
```

<sup>Created on 2021-12-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>


(Maybe see also https://easystats.github.io/effectsize/articles/effectsize_API.html)

**Comment by strengejacke** [comment]
should work now, will wait for checks. Tests may need to rely on new _effectsize_ version, I'll fix that before submission.

**Comment by strengejacke** [comment]
Maybe we should drop including effect sizes in _parameters_ for now. The amount of issues is quite impressing (or depressing): https://github.com/easystats/parameters/runs/4703123991?check_suite_focus=true

**Comment by mattansb** [comment]
We can return effect sizes conditional on a non-cran version of effectsize. Should be easy to do with `insight::check_if_installed(minimum_version = ...)`.
Then tests can also be run conditionally with `testthat::skip_if_not_installed("effectsize", minimum_version = ...)`.

**Comment by strengejacke** [comment]
Problem is that I need to restrict to the current cran version, not newer.

**Comment by strengejacke** [comment]
(or in other words: effect sizes (or their CIs?) for `model_parameters()` does not work with the latest _effectsize_.

**Comment by mattansb** [comment]
Can you elaborate? Where are these failures happening? There shouldn't be any breaking changes between CRAN and GH versions of {effectsize} other than what we have pointed out above (ANOVA effect sizes).

**Comment by strengejacke** [comment]
I think the code that no longer works is here:

https://github.com/easystats/parameters/blob/b93d2ce31f53c3b2e036bec1cd490421214534ea/R/methods_aov.R#L534-L555

(the original code that also no longer works is commented out below). I'm not sure how to fix this, because simple `merge()` doesn't seem to work.

**Comment by strengejacke** [comment]
The main issue seems to be that CIs for effect sizes can't be added, effect sizes w/o CI seems to work.

**Comment by mattansb** [comment]
So the issue is only for ANOVA effect sizes, right?
I'll take a look.

**Comment by strengejacke** [comment]
CIs for Anova effect sizes. And these tests fail:
https://github.com/easystats/parameters/blob/main/tests/testthat/test-model_parameters.aov_es_ci.R
