### ISSUE TITLE
`model_parameters.merMod` is very slow

### ISSUE THREAD

**Issue by vincentarelbundock** [easystats/parameters#644]
The `parameters` function is extremely slow when applied to a model produced by the `lme4::lmer` function. In this example, `broom.mixed` is basically instantaneous but `parameters` quite slow. Adding more random effects units (e.g., 10000) makes things much worse; `parameters` often seems to hang indefinitely and is unuseable.

``` r
library(lme4)
library(tictoc)
library(broom.mixed)
library(parameters)

N <- 1e6
dat <- data.frame(
    x = rnorm(N),
    y = rnorm(N),
    k = sample(1:50, N, replace = TRUE),
    m = sample(1:1000, N, replace = TRUE))
mod <- lmer(y ~ x + (1 | k) + (1 | m), data = dat)

tic()
tidy(mod)
```

    ## # A tibble: 5 × 6
    ##   effect   group    term             estimate std.error statistic
    ##   <chr>    <chr>    <chr>               <dbl>     <dbl>     <dbl>
    ## 1 fixed    <NA>     (Intercept)      0.000787  0.00128      0.616
    ## 2 fixed    <NA>     x               -0.000741  0.000998    -0.743
    ## 3 ran_pars m        sd__(Intercept)  0.00369  NA           NA    
    ## 4 ran_pars k        sd__(Intercept)  0.00557  NA           NA    
    ## 5 ran_pars Residual sd__Observation  0.998    NA           NA

``` r
toc()
```

    ## 0.179 sec elapsed

``` r
tic()
parameters(mod)
```

    ## # Fixed Effects
    ## 
    ## Parameter   | Coefficient |       SE |        95% CI | t(999995) |     p
    ## ------------------------------------------------------------------------
    ## (Intercept) |    7.87e-04 | 1.28e-03 | [ 0.00, 0.00] |      0.62 | 0.538
    ## x           |   -7.41e-04 | 9.98e-04 | [ 0.00, 0.00] |     -0.74 | 0.457
    ## 
    ## # Random Effects
    ## 
    ## Parameter         | Coefficient
    ## -------------------------------
    ## SD (Intercept: m) |    3.69e-03
    ## SD (Intercept: k) |    5.57e-03
    ## SD (Residual)     |        1.00

    ## 
    ## Uncertainty intervals (equal-tailed) and p values (two-tailed) computed using a
    ##   Wald t-distribution approximation.

``` r
toc()
```

    ## 10.908 sec elapsed

Here is a screenshot of some profiling:

![profile](https://user-images.githubusercontent.com/987057/148595977-a52965c2-b6fe-460e-8be3-b3443d912aff.jpg)

**Comment by bwiernik** [comment]
The issue here is that profile likelihood CIs for the random effects components are slow when the number of units or effects is large

**Comment by bwiernik** [comment]
We could check to see how many effects need to be profiled and then disable CIs by default with a message if it is large?

**Comment by strengejacke** [comment]
looks like the bottle neck here is `ranef.merMod()`? Will check and profile on my machine, too. But strange then why `tidy()` is so much faster then?

**Comment by bwiernik** [comment]
tidy() doesn't compute CIs by default?

**Comment by vincentarelbundock** [comment]
> tidy() doesn't compute CIs by default?

No, the `conf.int` argument is `FALSE` by default: https://github.com/bbolker/broom.mixed/blob/master/R/lme4_tidiers.R#L130

> looks like the bottle neck here is `ranef.merMod()`? Will check and profile on my machine, too. But strange then why `tidy()` is so much faster then?

One thing to note is that we call `get_variance` 3 times in a row here: https://github.com/easystats/parameters/blob/main/R/extract_random_variances.R#L123

This means we end up calling `ranef` 3 times, whereas `broom.mixed::tidy.merMod` only calls it once, and only if the user explicitly changes the default value of the `effects` argument: https://github.com/bbolker/broom.mixed/blob/master/R/lme4_tidiers.R#L287

**Comment by strengejacke** [comment]
I think I'll rewrite/re-implement a `get_variance()` equivalent in _parameters_. `get_variance()` is useful for ICC and R2, but for "simple" estimates and SD, it's probably too much overload. I think we will gain quite some speed improvements going a different approach here by not using `get_variance()`. Will open a PR

**Comment by strengejacke** [comment]
See #645

**Comment by strengejacke** [comment]
ok, the issue with extracting random variances is solved right now. What remains is that retrieving the data using `get_data()` (which is needed for parameter formatting) takes quite a lot of time:

``` r
library(tictoc)
library(parameters)
library(broom.mixed)
library(lme4)
#> Loading required package: Matrix

N <- 1e6
dat <- data.frame(
  x = rnorm(N),
  y = rnorm(N),
  k = sample(1:50, N, replace = TRUE),
  m = sample(1:1000, N, replace = TRUE))
mod <- lmer(y ~ x + (1 | k) + (1 | m), data = dat)
#> boundary (singular) fit: see ?isSingular

tic()
tidy(mod)
#> # A tibble: 5 x 6
#>   effect   group    term             estimate std.error statistic
#>   <chr>    <chr>    <chr>               <dbl>     <dbl>     <dbl>
#> 1 fixed    <NA>     (Intercept)     -0.000584   0.00106    -0.550
#> 2 fixed    <NA>     x               -0.000320   0.00100    -0.320
#> 3 ran_pars m        sd__(Intercept)  0         NA          NA    
#> 4 ran_pars k        sd__(Intercept)  0.00252   NA          NA    
#> 5 ran_pars Residual sd__Observation  1.00      NA          NA
toc()
#> 0.15 sec elapsed


tic()
x1 <- model_parameters(mod)
toc()
#> 6.65 sec elapsed


tic()
x2 <- insight::get_data(mod)
toc()
#> 6.74 sec elapsed
```

<sup>Created on 2022-01-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>


I'm thinking about a way to make this optional...

**Comment by strengejacke** [comment]
``` r
library(tictoc)
library(parameters)
library(broom.mixed)
library(lme4)
#> Loading required package: Matrix

N <- 1e6
dat <- data.frame(
  x = rnorm(N),
  y = rnorm(N),
  k = sample(1:50, N, replace = TRUE),
  m = sample(1:1000, N, replace = TRUE))
mod <- lmer(y ~ x + (1 | k) + (1 | m), data = dat)

tic()
tidy(mod)
#> # A tibble: 5 x 6
#>   effect   group    term             estimate std.error statistic
#>   <chr>    <chr>    <chr>               <dbl>     <dbl>     <dbl>
#> 1 fixed    <NA>     (Intercept)      0.000956  0.00115      0.829
#> 2 fixed    <NA>     x               -0.000775  0.000999    -0.775
#> 3 ran_pars m        sd__(Intercept)  0.00618  NA           NA    
#> 4 ran_pars k        sd__(Intercept)  0.00381  NA           NA    
#> 5 ran_pars Residual sd__Observation  1.00     NA           NA
toc()
#> 0.16 sec elapsed


tic()
x1 <- model_parameters(mod)
toc()
#> 6.67 sec elapsed


tic()
x1 <- model_parameters(mod, pretty_names = FALSE)
toc()
#> 0.2 sec elapsed
```

<sup>Created on 2022-01-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by vincentarelbundock** [comment]
Wonderful! Thanks @strengejacke !

An additional good news is that the `rowSums` trick I implemented in
`insight` yesterday seems to help a lot. With your branch of
`parameters` and the `main` branch of `insight` I get this (I doubt my laptop is 6x faster than yours):

``` r
library(parameters)
library(lme4)
library(insight)
library(tictoc)

N <- 1e6
dat <- data.frame(
  x = rnorm(N),
  y = rnorm(N),
  k = sample(1:50, N, replace = TRUE),
  m = sample(1:1000, N, replace = TRUE))
mod <- lmer(y ~ x + (1 | k) + (1 | m), data = dat)

tic()
k <- get_data(mod)
toc()
```

    ## 0.089 sec elapsed

``` r
tic()
k <- model_parameters(mod)
toc()
```

    ## 1.658 sec elapsed

**Comment by strengejacke** [comment]
@vincentarelbundock I added an option where `pretty_names` is passed down to `.add_model_parameters_attributes()` (which will skip calling `format_parameters()`, which called `parameters_type()`, which in turn called the - for large samples - time-consuming `get_data()`). I hope that passing this via the dots doesn't interfere with any other functions where dots are passed. Or I could add this as official argument for `model_parameters()` (I didn't do this yet because of laziness - I wanted to quickly test if it works in general, and it seems so, thus I could add this as "user visible" argument - what do you think?)

**Comment by strengejacke** [comment]
> An additional good news is that the `rowSums` trick I implemented in `insight` yesterday

Unfortunately, this is not in the CRAN version I submitted some days before. :-(
But with the next release cycle, pretty names are much faster to retrieve then. :-)

**Comment by strengejacke** [comment]
I just installed the latest main from insight, indeed your commit fixed the bottle neck:

``` r
library(tictoc)
library(parameters)
library(broom.mixed)
library(lme4)
#> Loading required package: Matrix

N <- 1e6
dat <- data.frame(
  x = rnorm(N),
  y = rnorm(N),
  k = sample(1:50, N, replace = TRUE),
  m = sample(1:1000, N, replace = TRUE))
mod <- lmer(y ~ x + (1 | k) + (1 | m), data = dat)
#> boundary (singular) fit: see ?isSingular

tic()
tidy(mod)
#> # A tibble: 5 x 6
#>   effect   group    term            estimate std.error statistic
#>   <chr>    <chr>    <chr>              <dbl>     <dbl>     <dbl>
#> 1 fixed    <NA>     (Intercept)      0.00151   0.00102      1.48
#> 2 fixed    <NA>     x                0.00113   0.00100      1.13
#> 3 ran_pars m        sd__(Intercept)  0.00638  NA           NA   
#> 4 ran_pars k        sd__(Intercept)  0        NA           NA   
#> 5 ran_pars Residual sd__Observation  1.00     NA           NA
toc()
#> 0.14 sec elapsed


tic()
x1 <- model_parameters(mod)
toc()
#> 0.42 sec elapsed


tic()
x1 <- model_parameters(mod, pretty_names = FALSE)
toc()
#> 0.23 sec elapsed
```

<sup>Created on 2022-01-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
@vincentarelbundock Have you submitted _modelbased_ to CRAN already? If yes, ok... If not, we/you could temporarily rely on using `pretty_names = FALSE`, and once your fix in _insight_ is on CRAN, just use the normal call to `model_parameters()` w/o `pretty_names = FALSE`.

**Comment by vincentarelbundock** [comment]
I wasn't really planning to release a new version of `modelsummary` now, since I have not implemented new features in the past few weeks (focus on `marginaleffects`). Honestly, I think I can just tell users to install the devel version of insight, and the problem will fix itself eventually anyway, when the new version of `insight` is out (I will then require the most recent).

The `pretty_names=FALSE` idea is nice, but I think we should probably keep things as is for now. I'll try some larger `lmer` models, but I think that as long as they take less than 10s to process with `model_parameters`, we're in an acceptable range.

**Comment by strengejacke** [comment]
Sorry, I confused _marginaleffects_ with _modelsummary_ - the first needs to be updated, not the latter...

**Comment by vincentarelbundock** [comment]
Yes, I submitted that already...
