### ISSUE TITLE
add generic plot method for parameters

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#65]
As a classic horizontal barplot?

**Comment by pdwaggoner** [comment]
Do you mean something as simple as this, or am I under thinking this?

``` R
library(ggplot2)

attach(mtcars)

ggplot(mpg, aes(cyl)) + 
  geom_bar() +
  coord_flip()
```

**Comment by DominiqueMakowski** [comment]
More like this ☺️:

``` r
library(ggplot2)
library(dplyr)
library(parameters)

model <- lm(Sepal.Length ~ ., data=iris)
params <- model_parameters(model)


params %>% 
  mutate(Parameter = forcats::fct_rev(Parameter)) %>% 
  ggplot(aes(x=Parameter, y=Coefficient, fill=Coefficient)) +
  geom_bar(stat="identity") +
  coord_flip() +
  scale_fill_gradient2(high = "#4CAF50", mid="#FFF9C4", low="#E91E63") +
  see::theme_modern()
```

![](https://i.imgur.com/3KRSGDE.png)

<sup>Created on 2019-06-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by pdwaggoner** [comment]
So that would be a yes, I am under-thinking...? ;) this looks great.

**Comment by DominiqueMakowski** [comment]
Additional features would include: 1) adding error bars for CIs, 2) possibility of showing the standardized coefficients if available

**Comment by pdwaggoner** [comment]
Cool, maybe something like this?

```R
library(ggplot2)
library(dplyr)
devtools::install_github("easystats/parameters")
library(parameters)

model <- lm(Sepal.Length ~ ., data=iris)
params <- model_parameters(model)

params %>% 
  mutate(Parameter = forcats::fct_rev(Parameter)) %>% 
  group_by(Parameter) %>% 
  ggplot(aes(x=Parameter, y=Coefficient, fill=Coefficient)) +
  geom_bar(stat="identity") +
  geom_errorbar(aes(ymin = params$CI_low, 
                    ymax = params$CI_high),
                width=0.1) +
  coord_flip() +
  scale_fill_gradient2(high = "#4CAF50", mid="#FFF9C4", low="#E91E63") +
  see::theme_modern()
```

And we typically don't standardize coefficients in my world, so I should probably leave that to someone more capable, so I don't break things.

**Comment by strengejacke** [comment]
"Never use more dimensions than your data" - thus, a point-estimate should simply be a point. And then I would add error bars / CI to the plot, so you end up having [forest plots](https://strengejacke.github.io/sjPlot/articles/plot_model_estimates.html).

**Comment by DominiqueMakowski** [comment]
@strengejacke as you are updating see, do you think this can be added in?

**Comment by strengejacke** [comment]
We have different structures for Bayes and Frq:

```r
> str(x)
Classes ‘parameters_model’, ‘see_parameters_model’ and 'data.frame':	3 obs. of  12 variables:
 $ Parameter         : chr  "(Intercept)" "Speciesversicolor" "Speciesvirginica"
 $ Median            : num  5.009 0.923 1.576
 $ CI_low            : num  4.9 0.76 1.41
 $ CI_high           : num  5.12 1.08 1.74
 $ pd                : num  1 1 1
 $ ROPE_Percentage   : num  0 0 0
 $ ESS               : num  3259 3262 3098
 $ Rhat              : num  1 1 1
 $ Prior_Distribution: chr  "normal" "normal" "normal"
 $ Prior_Location    : num  0 0 0
 $ Prior_Scale       : num  8.28 2.07 2.07
 $ Std_Median        : num  0 1.12 1.9
 - attr(*, "clean_names")= chr  "(Intercept)" "Species (versicolor)" "Species (virginica)"
 - attr(*, "ci")= num 0.89
> str(x2)
Classes ‘parameters_model’, ‘see_parameters_model’ and 'data.frame':	3 obs. of  9 variables:
 $ Parameter      : chr  "(Intercept)" "wt" "cyl"
 $ Coefficient    : num  39.69 -3.19 -1.51
 $ SE             : num  1.715 0.757 0.415
 $ CI_low         : num  36.18 -4.74 -2.36
 $ CI_high        : num  43.19 -1.64 -0.66
 $ t              : num  23.14 -4.22 -3.64
 $ df_residual    : int  29 29 29
 $ p              : num  3.04e-20 2.22e-04 1.06e-03
 $ Std_Coefficient: num  4.90e-17 -5.18e-01 -4.47e-01
 - attr(*, "clean_names")= chr  "(Intercept)" "wt" "cyl"
 - attr(*, "ci")= num 0.95
```

Would you suggest adding different class-attributes for plotting? Or should the plot-method in _see_ check which information is available and manage the plotting stuff then?

**Comment by DominiqueMakowski** [comment]
I would say in the data_plot, we find the point estimate col:
`estimate <- names(x)[names(x) %in% c("Coefficient", "Median", "Mean", "MAP")][1]`

Then we check if there a `CI_low` and `CI_high` col, which becomes `ymin` and `ymax`

Then plot

Does that make sense?

**Comment by strengejacke** [comment]
> Does that make sense?

yes.

**Comment by strengejacke** [comment]
can't we close this? we have a `plot()` method now in _see_, at least in its first stage.

``` r
library(parameters)

model <- lm(Sepal.Length ~ ., data=iris)
params <- model_parameters(model)
plot(params)
```

![](https://i.imgur.com/H8K2p8L.png)

<sup>Created on 2019-08-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DominiqueMakowski** [comment]
we should add this in the README
