### ISSUE TITLE
Join model results tables

### ISSUE THREAD

**Issue by gorkang** [easystats/parameters#657]
There is any way to combine two model results tables using the `model_parameters() %>% display()` method?

I am used to `sjPlot::tab_model(model1, model2)`, but I am not sure how to do it with the parameters package.

Thanks!

Below  a reproducible exaple.

``` r
suppressPackageStartupMessages(library(dplyr))
library(parameters)
library(sjPlot)
  
model1 <- lm(mpg~cyl, data=mtcars)
model2 <- lm(mpg~cyl + wt, data=mtcars)
```

### Show 1 table

``` r
# Show 1 table
sjPlot::tab_model(model1)
```

<table style="border-collapse:collapse; border:none;">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
mpg
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimates
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
p
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
(Intercept)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
37.88
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
33.65 – 42.12
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>\<0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
cyl
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-2.88
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-3.53 – -2.22
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>\<0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">
32
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
R<sup>2</sup> / R<sup>2</sup> adjusted
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
0.726 / 0.717
</td>
</tr>
</table>

### Join two tables

``` r
sjPlot::tab_model(model1, model2)
```

<table style="border-collapse:collapse; border:none;">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
mpg
</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
mpg
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimates
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
p
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimates
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  col7">
p
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
(Intercept)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
37.88
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
33.65 – 42.12
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>\<0.001</strong>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
39.69
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
36.18 – 43.19
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7">
<strong>\<0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
cyl
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-2.88
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-3.53 – -2.22
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>\<0.001</strong>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-1.51
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-2.36 – -0.66
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7">
<strong>0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
wt
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-3.19
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-4.74 – -1.64
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7">
<strong>\<0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">
32
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">
32
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
R<sup>2</sup> / R<sup>2</sup> adjusted
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
0.726 / 0.717
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
0.830 / 0.819
</td>
</tr>
</table>

### Show 1 table

``` r

model_parameters(model1, summary = TRUE) %>% display(format = "md")
```

| Parameter   | Coefficient |  SE  |     95% CI     | t(30) |    p    |
|:------------|:-----------:|:----:|:--------------:|:-----:|:-------:|
| (Intercept) |    37.88    | 2.07 | (33.65, 42.12) | 18.27 | \< .001 |
| cyl         |    -2.88    | 0.32 | (-3.53, -2.22) | -8.92 | \< .001 |

### Join two tables

``` r
model_parameters(model1, model2, summary = TRUE) %>% display(format = "md")
#> Warning in se * fac: longer object length is not a multiple of shorter object
#> length
#> Warning in params$Estimate - se * fac: longer object length is not a multiple of
#> shorter object length
#> Warning in se * fac: longer object length is not a multiple of shorter object
#> length
#> Warning in params$Estimate + se * fac: longer object length is not a multiple of
#> shorter object length
#> Error: Sorry, `model_parameters()` failed with the following error (possible class 'lm'
#>   not supported):
#> 
#>   replacement has 2 rows, data has 3
```

<sup>Created on 2022-02-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
We have [`compare_parameters()`](https://easystats.github.io/parameters/reference/compare_parameters.html), which does this, however, printing options are somewhat limited.

Indeed, packages like _sjPlot_ rely on _parameters_, and take over the more sophisticated table outputs. You may also want to look at @vincentarelbundock fantastic [_modelsummary_](https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html) package, which also relies on _parameters_ as work horse.

[_gtsummary_](https://www.danieldsjoberg.com/gtsummary/) is also a good options, but I'm not that familiar with most other packages.

**Comment by IndrajeetPatil** [comment]
Here is a reprex with _parameters_ option:

``` r
library(parameters)

model1 <- lm(mpg ~ cyl, data = mtcars)
model2 <- lm(mpg ~ cyl + wt, data = mtcars)

compare_parameters(model1, model2)
#> Parameter    |               model1 |               model2
#> ----------------------------------------------------------
#> (Intercept)  | 37.88 (33.65, 42.12) | 39.69 (36.18, 43.19)
#> cyl          | -2.88 (-3.53, -2.22) | -1.51 (-2.36, -0.66)
#> wt           |                      | -3.19 (-4.74, -1.64)
#> ----------------------------------------------------------
#> Observations |                   32 |                   32
```

<sup>Created on 2022-02-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by gorkang** [comment]
Thanks for the prompt response and for the code example!

Just in case it's useful to someone, below the code with gtsummary to merge regression tables including some model stats.

Thanks again!

```
suppressPackageStartupMessages(library(dplyr))
library(gtsummary)
  
model1 <- lm(mpg ~ cyl, data = mtcars)
model2 <- lm(mpg ~ cyl + wt, data = mtcars)
  
t1 = tbl_regression(model1, intercept = TRUE) %>% 
       add_n() %>% 
       add_glance_table(include = c("r.squared", "adj.r.squared", "nobs"))

t2 = tbl_regression(model2, intercept = TRUE) %>% 
       add_n() %>% 
       add_glance_table(include = c("r.squared", "adj.r.squared", "nobs"))

gtsummary::tbl_merge(list(t1, t2)) 

```

Indeed {gtsummary} is a great option
