### ISSUE TITLE
Refactor `standard_error_robust`

### ISSUE THREAD

**Issue by vincentarelbundock** [easystats/parameters#658]
This is a follow-up to: https://github.com/easystats/insight/issues/505

@strengejacke and I agree to attempt a refactor with the following features:

1. `vcov_estimation`, `vcov_type` and `vcov_args` (also for backwards-compatibility. This calls something like `do.call(vcov_fun, c(list(x = x, type = vcov_type), vcov_args))`
2. If we `vcov_type` is `NULL, we might have `type`in the list of`vcov_args`and then just call`do.call(vcov_fun, c(list(x = x), vcov_args))`
3. We also want `vcov_estimation` to be "HC3" or similar, to simplify
4. We also want to check dots if some valid `vcov_args` are passed through dots, and then add them to `vcov_args`
5. We also want to "ignore" `robust`, and if `vcov_estimation` is not NULL, we internally set `robust = TRUE`.

I've been working on this, and it turns out it's not easy to *just* do that. I would like to propose two additional pieces of refactor: 

6. `standard_error()` gets new `vcov_estimation` and `vcov_args` arguments and it supersedes `standard_error_robust()`
7. `vcov_estimation` also accepts matrices and functions.

The last point would eventually allow us to make things somewhat faster, because currently `p_value_robust`, `standard_error_robust` and co. all repeat the same computation several times. Plus, we could do something like this:

```
standard_error(mod, vcov_estimation = "vcovHC")
standard_error(mod, vcov_estimation = "HC3")
standard_error(mod, vcov_estimation = sandwich::vcovHC)
standard_error(mod, vcov_estimation = sandwich::vcovHC(mod))
```

What do you think?

**Comment by bwiernik** [comment]
I like it. I am wondering if it would be best to just have the argument for the function/matrix and then one `vcov_args()` rather than pulling out type separately?

**Comment by vincentarelbundock** [comment]
> I like it. I am wondering if it would be best to just have the argument for the function/matrix and then one `vcov_args()` rather than pulling out type separately?

Yes, that's the idea. You can do:

```r
standard_error(mod, vcov_estimation = sandwich::vcovHC, vcov_args = list(type = "HC3"))
```

But we also allow short string "shortcuts" for the most common values:

```r
standard_error(mod, vcov_estimation = "HC3")
```

**Comment by bwiernik** [comment]
So we don't need the `vcov_type` argument then?

**Comment by vincentarelbundock** [comment]
Right, it would be dropped, with some guardrails for backward compatibility.

**Comment by IndrajeetPatil** [comment]
Incredible work. Indeed, thanks a lot, Vincent!
