### ISSUE TITLE
Accept multiple models in model_parameters (compare_parameters)

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#66]
An interesting feature would be to allow multiple models, from which the parameters could be compared. Will have to figure out printing of a single input first.

**Comment by strengejacke** [comment]
Should be possible with insight::print_parameters()

**Comment by DominiqueMakowski** [comment]
Think it would be more consistent to add this feature in a `compare_parameters` function

**Comment by strengejacke** [comment]
Yes, I only meant the basis is there to have such a function. It could look like [tab_model()](https://strengejacke.github.io/sjPlot/articles/tab_model_estimates.html#more-than-one-model).

**Comment by humanfactors** [comment]
I'm going to address this tomorrow at work. I just compiled a relatively large table of model coefficients for a revise and resubmit. I made extensive use of sjPlot::tab_dfl() (and edge, funnily enough) to convert my data. Manually pulling parts from model_parameters().

Also @strengejacke you'll be please to know a reviewer specifically asked me for a "strengejacke" style lme4 output. No joke, provided me links to your blog and all.

**Comment by strengejacke** [comment]
Honestly, that reviewer wasn't me!

**Comment by strengejacke** [comment]
I think the output is now in shape to easily address this issue. Would you suggest appending rows, or binding as columns, and include all columns?

**Comment by DominiqueMakowski** [comment]
I think the most readable/useful is bind them as columns, because if someone wanted to bind as rows, they might as well run multiple model_parameters().  

The issue that arises then is, bind the *tables* together, or bind col by col? I think that binding the tables is more in line with a traditional APA reporting, so we might want to stick with that?

And also, the table will prolly quickly become too wide. Not sure if there's any way we can deal with this on our side tho. Maybe by default. We can also separate the issue and here deal with the binding of the model_parameters tables, and then in `report` implement a `compare_reports` or something like that that would run `compare_performance` and `compare_parameters` and chop some columns etc. to make it "reportable"

**Comment by DominiqueMakowski** [comment]
we should think about this someday, it'd be fairly cool feature to have :)

**Comment by strengejacke** [comment]
I'm thinking about this for some days actually. The basic computation is fairly easy, I'd say, however, the print methods (i.e. `insight::export_table()`) is more complicated, because we have to add a header line that spans several columns.

**Comment by DominiqueMakowski** [comment]
indeed indeed, maybe at first we could call external tables creators packages? Though I'm not sure they do it for the console printing, but at least it looks nice in MD

**Comment by mattansb** [comment]
From the [`weighted_posteriors()`](https://easystats.github.io/bayestestR/reference/weighted_posteriors.html) docs, relevant here too:

> Note that across models some parameters might play different roles. For example, the parameter A plays a different role in the model Y ~ A + B (where it is a main effect) than it does in the model Y ~ A + B + A:B (where it is a simple effect). In many cases centering of predictors (mean subtracting for continuous variables, and effects coding via contr.sum or orthonormal coding via contr.bayes for factors) can reduce this issue. In any case you should be mindful of this issue.

**Comment by strengejacke** [comment]
@mattansb don't complicate things before we even started ;-)
The _modelsummary_ package and _sjPlot_ both allow showing multiple models, though sjPlot is rather "fixed". _modelsummary_ seems to be quite flexible, the question is, whether we want (and can) utilize that package?

**Comment by strengejacke** [comment]
I have looked into the code from _modelsummary_ some time ago, looks like the gt package we already use in `insight::export_table()` is quite flexible. The console printing should be rather easy, too. Not sure about markdown tables, though.

**Comment by mattansb** [comment]
> @mattansb don't complicate things before we even started ;-)

But that's *my jobbbbbbbbb*

**Comment by strengejacke** [comment]
> > @mattansb don't complicate things before we even started ;-)
> 
> But that's _my jobbbbbbbbb_

![image](https://user-images.githubusercontent.com/26301769/106863260-883b1d80-66c8-11eb-82b4-55738d02ddf9.png)
