### ISSUE TITLE
skewness is no longer exported

### ISSUE THREAD

**Issue by mmoisse** [easystats/parameters#662]
In the latest version of parameters the `skewness` function is no longer exported, while in previous version it was.

**Comment by IndrajeetPatil** [comment]
Hi, Sorry about this trouble.

This function has now been moved to _datawizard_ package, which is also on CRAN:
https://easystats.github.io/datawizard/reference/skewness.html

**Comment by strengejacke** [comment]
I'm not sure, but I think it should be there:

https://github.com/easystats/parameters/blob/main/R/reexports.R

**Comment by IndrajeetPatil** [comment]
It's not:

``` r
library(parameters)

"skewness" %in% getNamespaceExports("parameters")
#> [1] FALSE
```

<sup>Created on 2022-02-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

Because `#' @export` is missing here:

https://github.com/easystats/parameters/blob/21f943c694399ea1e47a0680864d596172f198de/R/reexports.R#L37-L39

**Comment by strengejacke** [comment]
ok, that was not intended. It _should_ have been re-exported.
