### ISSUE TITLE
robust vignette - unaffected statistic?

### ISSUE THREAD

**Issue by mattansb** [easystats/parameters#664]
I guess this is more of a question, but "*t*-statistic associated with it remain unchanged" - this is not true in the examples given.
Is the mistake in the text or in the results? @strengejacke @vincentarelbundock 

https://github.com/easystats/parameters/blob/2b38c8cc58b57a128b8856a3ea53ada6b5daf4c8/vignettes/model_parameters_robust.Rmd#L96-L97

https://github.com/easystats/parameters/blob/2b38c8cc58b57a128b8856a3ea53ada6b5daf4c8/vignettes/model_parameters_robust.Rmd#L234-L235

(Great vignette!)

**Comment by strengejacke** [comment]
Where are you referring to?

**Comment by strengejacke** [comment]
I don't see any examples where t changes

**Comment by mattansb** [comment]
e.g., first example

![image](https://user-images.githubusercontent.com/35330040/155473363-22266f44-dd7b-4dbf-a3f4-6cd3b1843a0f.png)

**Comment by strengejacke** [comment]
Ah, I was looking at the DF ^^

**Comment by strengejacke** [comment]
I'm not sure against which packages we can check? (maybe Stata?)

Despite other packages giving different estimates, t is always coef/se:

``` r
library(parameters)
data(cars)
model <- lm(dist ~ speed, data = cars)

model_parameters(model)
#> Parameter   | Coefficient |   SE |          95% CI | t(48) |      p
#> -------------------------------------------------------------------
#> (Intercept) |      -17.58 | 6.76 | [-31.17, -3.99] | -2.60 | 0.012 
#> speed       |        3.93 | 0.42 | [  3.10,  4.77] |  9.46 | < .001
#> 
#> Uncertainty intervals (equal-tailed) and p values (two-tailed) computed using a
#>   Wald t-distribution approximation.

p <- robustbase::lmrob(dist ~ speed, data = cars) |> parameters()
p
#> # Fixed Effects
#> 
#> Parameter   | Coefficient |   SE |          95% CI | t(48) |      p
#> -------------------------------------------------------------------
#> (Intercept) |      -15.51 | 5.18 | [-25.92, -5.11] | -3.00 | 0.004 
#> speed       |        3.67 | 0.42 | [  2.83,  4.50] |  8.82 | < .001
#> 
#> Uncertainty intervals (equal-tailed) and p values (two-tailed) computed using a
#>   Wald t-distribution approximation.

p$Coefficient / p$SE
#> [1] -2.997781  8.818567

p <- robust::lmRob(dist ~ speed, data = cars) |> parameters()
p
#> # Fixed Effects
#> 
#> Parameter   | Coefficient |   SE |         95% CI | t(48) |      p
#> ------------------------------------------------------------------
#> (Intercept) |      -15.16 | 8.14 | [-31.53, 1.20] | -1.86 | 0.069 
#> speed       |        3.61 | 0.51 | [  2.57, 4.64] |  7.02 | < .001
#> 
#> Uncertainty intervals (equal-tailed) and p values (two-tailed) computed using a
#>   Wald t-distribution approximation.

p$Coefficient / p$SE
#> [1] -1.863262  7.016600
```

<sup>Created on 2022-02-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by vincentarelbundock** [comment]
This looks like a mistake in the text of the vignette. t stats are (and should be) affected when we use a robust vcov.

**Comment by mattansb** [comment]
Thanks, yes, it makes a ton more sense that t should change.
