### ISSUE TITLE
Performance issues with `{parameters}`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/parameters#677]
Our workhorse function is painfully slow compared to its alternative `broom::tidy()`. 

Although we provide some additional details, the performance penalty of x 20 (!) is not going to be worth for most developers to recoup the costs involved in either switching from `{broom}` or for choosing `{parameters}` over `{broom}`.

``` r
m <- stats::lm(wt ~ mpg, data = mtcars)

parameters::parameters(m) |> as.data.frame()
#>     Parameter Coefficient         SE   CI     CI_low    CI_high         t
#> 1 (Intercept)    6.047255 0.30869072 0.95  5.4168245  6.6776856 19.590012
#> 2         mpg   -0.140862 0.01473599 0.95 -0.1709569 -0.1107671 -9.559044
#>   df_error            p
#> 1       30 1.203667e-18
#> 2       30 1.293959e-10

broom::tidy(m, conf.int = TRUE)
#> # A tibble: 2 x 7
#>   term        estimate std.error statistic  p.value conf.low conf.high
#>   <chr>          <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>
#> 1 (Intercept)    6.05     0.309      19.6  1.20e-18    5.42      6.68 
#> 2 mpg           -0.141    0.0147     -9.56 1.29e-10   -0.171    -0.111

bench::mark(
  parameters::parameters(m),
  broom::tidy(m, conf.int = TRUE),
  check = FALSE,
  iterations = 100
)
#> # A tibble: 2 x 6
#>   expression                           min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>                      <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 parameters::parameters(m)        112.7ms 120.54ms      8.27    96.8KB     3.89
#> 2 broom::tidy(m, conf.int = TRUE)    4.9ms   5.78ms    168.        83KB     3.43
```

<sup>Created on 2022-03-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

Profiler report:

``` r
library(profvis)

profvis(
  {
    parameters::parameters(stats::lm(wt ~ mpg, data = mtcars))
  }
)
```

![image](https://user-images.githubusercontent.com/11330453/158652392-11486b3a-725f-4c40-96a3-53d3e1c48ab6.png)

This is currently low priority, but something we should definitely focus on after stable release.

**Comment by strengejacke** [comment]
I think we can / should try to reduce the many calls to `insight::model_info()`.

**Comment by DominiqueMakowski** [comment]
I was just thinking that yesterday when I was using model_info(model)$is_bayesian, maybe we should export some of the checks (is_bayesian, is_mixed) that we use quite a lot to use them directly instead of calling model_info

**Comment by strengejacke** [comment]
Can we set remotes to a PR directly in parameters? I.e. remotes insight/PR537?

**Comment by strengejacke** [comment]
btw, on speed improvement is call `model_info(no_terms = TRUE)`.

**Comment by IndrajeetPatil** [comment]
> Can we set remotes to a PR directly in parameters? I.e. remotes insight/PR537?

Maybe try?

```r
Remotes:
  easystats/insight@performance_model_info
```

**Comment by strengejacke** [comment]
![yoda-quotes-31981-4179042-971708](https://user-images.githubusercontent.com/26301769/158770812-296f4fdd-18a0-4895-ae6d-50fd8aa251c3.jpg)

**Comment by strengejacke** [comment]
Current time on PR: 
mean = 781.1us
median = 832.35us

Time on master
mean = 12.96ms
median = 13.7ms

**Comment by IndrajeetPatil** [comment]
![DcauJusticeLeagueUnlimitedGIF](https://user-images.githubusercontent.com/11330453/158771754-8a6af4b2-d167-4078-a812-fcde5db23692.gif)

**Comment by strengejacke** [comment]
> I was just thinking that yesterday when I was using model_info(model)$is_bayesian, maybe we should export some of the checks (is_bayesian, is_mixed) that we use quite a lot to use them directly instead of calling model_info

See my comment here (this is already possible, but a hidden feature)
> btw, on speed improvement is call model_info(no_terms = TRUE).

**Comment by strengejacke** [comment]
Ok, we already have some improvements now:

``` r
m <- stats::lm(wt ~ mpg, data = mtcars)

parameters::parameters(m) |> as.data.frame()
#>     Parameter Coefficient         SE   CI     CI_low    CI_high         t
#> 1 (Intercept)    6.047255 0.30869072 0.95  5.4168245  6.6776856 19.590012
#> 2         mpg   -0.140862 0.01473599 0.95 -0.1709569 -0.1107671 -9.559044
#>   df_error            p
#> 1       30 1.203667e-18
#> 2       30 1.293959e-10

broom::tidy(m, conf.int = TRUE)
#> # A tibble: 2 x 7
#>   term        estimate std.error statistic  p.value conf.low conf.high
#>   <chr>          <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>
#> 1 (Intercept)    6.05     0.309      19.6  1.20e-18    5.42      6.68 
#> 2 mpg           -0.141    0.0147     -9.56 1.29e-10   -0.171    -0.111

bench::mark(
  parameters::parameters(m),
  broom::tidy(m, conf.int = TRUE),
  check = FALSE,
  iterations = 100
)
#> # A tibble: 2 x 6
#>   expression                           min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>                      <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 parameters::parameters(m)        59.47ms  61.85ms      15.9    62.4KB     1.57
#> 2 broom::tidy(m, conf.int = TRUE)   5.44ms   5.73ms     169.       83KB     3.45
```

<sup>Created on 2022-03-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by IndrajeetPatil** [comment]
That's a remarkable improvement, Daniel! Thanks for looking into this so quickly.

**Comment by strengejacke** [comment]
We have some overhead that broom can avoid, we will not get very close to broom, I guess. But this is due to the many more features we have, also including the formatting of parameter names.

**Comment by IndrajeetPatil** [comment]
We should definitely not be compromising on functionality to get equivalent performance, but should try to avoid unnecessary overhead costs.

Feel free to close this issue.

**Comment by strengejacke** [comment]
@DominiqueMakowski Do you remember why we return model terms in `model_info()`? This is something that requires "more" time (and the reason why I added the undocumented `no_terms` argument), but honestly, I never use `model_info()` to look at model terms/variables.

**Comment by strengejacke** [comment]
The most time-consuming stuff are the regex-things, so wherever possible, we should use `grepl(..., fixed = TRUE)` or similar.

**Comment by strengejacke** [comment]
Getting closer :-)

``` r
m <- stats::lm(wt ~ mpg, data = mtcars)
bench::mark(
  parameters::parameters(m),
  broom::tidy(m, conf.int = TRUE),
  check = FALSE,
  iterations = 100
)
#> # A tibble: 2 x 6
#>   expression                           min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>                      <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 parameters::parameters(m)        42.58ms  44.58ms      22.1   76.69MB     1.92
#> 2 broom::tidy(m, conf.int = TRUE)   5.33ms   5.63ms     172.     9.54MB     3.51
```

<sup>Created on 2022-03-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
I just saw that I added a 2nd hidden argument; `model_parameters(pretty_names = FALSE)`:

``` r
m <- stats::lm(wt ~ mpg, data = mtcars)

bench::mark(
  parameters::parameters(m, pretty_names = FALSE),
  broom::tidy(m, conf.int = TRUE),
  check = FALSE,
  iterations = 100
)
#> # A tibble: 2 x 6
#>   expression                                           min   median `itr/sec`
#>   <bch:expr>                                      <bch:tm> <bch:tm>     <dbl>
#> 1 parameters::parameters(m, pretty_names = FALSE)  12.81ms  13.41ms      70.8
#> 2 broom::tidy(m, conf.int = TRUE)                   5.36ms   5.59ms     172. 
#> # ... with 2 more variables: mem_alloc <bch:byt>, `gc/sec` <dbl>
```

@vincentarelbundock This might be of interest for you, too! If you're just interested in the returned data frame and don't use the formatted parameter strings, simply set `pretty_names = FALSE` to increase performance.

@IndrajeetPatil I think we can close this. We have now a 10fold speed improvement, there's hardly much more we can do...

**Comment by IndrajeetPatil** [comment]
Woohoo!!

**Comment by vincentarelbundock** [comment]
Thanks, this looks amazing\!

There might be ways to make the name clean up faster in general. For instance, the other day I noticed that literally 2/3 of the full compute time of `marginaleffects()` was spent in `insight::clean_names()`, which is a massive loop over a bunch of regexes. Simple things like using `|` instead of looping might help here and over there as well:

``` r
x <- "y"
fast <- function(x) {
    regex <- paste(letters, collapse = "|")
    grepl(regex, x)
}

slow <- function(x) {
    out <- FALSE
    for (i in letters) {
        if (isFALSE(out)) {
            out <- grepl(i, x)
        }
    }
    out
}

bench::mark(fast(x), slow(x))
#> # A tibble: 2 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 fast(x)        30µs   33.3µs    24776.    2.19KB     2.48
#> 2 slow(x)       164µs  175.2µs     5329.   59.05KB    12.6
```

<sup>Created on 2022-03-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by DominiqueMakowski** [comment]
Impressive improvements @strengejacke !

> Do you remember why we return model terms in model_info()

absolutely not 😕

**Comment by strengejacke** [comment]
@vincentarelbundock For a simple example (`y ~ offset(logOff) + x`), `clean_names()` is now down from 6.7ms to 1.5ms. I think in this particular case, we cannot merge the pattern with `|`... But you're right, whenever we find places where we can improve or replace/avoid regex, we should do it.

**Comment by strengejacke** [comment]
> Impressive improvements @strengejacke !
> 
> > Do you remember why we return model terms in model_info()
> 
> absolutely not 😕

Is it safe to remove the model terms from the return value of `model_inof()`? 😱

**Comment by DominiqueMakowski** [comment]
just sayin' but @IndrajeetPatil is the king of looking up instances of stuff throughout the 'verse 👀

**Comment by IndrajeetPatil** [comment]
We don't use `model_info$model_terms` list anywhere outside _insight_, so should be safe to get rid of:

https://github.com/search?q=org%3Aeasystats+model_terms&type=code

**Comment by mattansb** [comment]
A bit late to the party, but... 

> I think we can / should try to reduce the many calls to insight::model_info().

We can have functions "secretly" accept `model_info` passed to them:

```R
foo <- function(model, ...) {
  
  if (is.null(model_info <- match.call()$model_info) {
    model_info <- insight::model_info(model)
  }
  
  ....
  
}



main_foo <- function(model) {
  model_info <- insight::model_info(model)
  
  ....
  
  
  foo(model, model_info = model_info)  
  
  ....
}

```
