### ISSUE TITLE
Navigation bar on homepage is getting too crowded

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/parameters#679]
Current look:

![image](https://user-images.githubusercontent.com/11330453/159116368-564289c2-e174-4aac-8e86-42b20b79e7b0.png)

Instead of creating a separate navigation item for each group, we can have just one but group the drop-down menu instead.
What do you think? 

For example, this is what the articles' menu in [_ggstatsplot_](https://indrajeetpatil.github.io/ggstatsplot/) looks like:

![image](https://user-images.githubusercontent.com/11330453/159116438-dc6fc7fb-71cc-4442-8219-7f5d1c9a9aab.png)

**Comment by strengejacke** [comment]
![picard_make_it_so](https://user-images.githubusercontent.com/26301769/159275475-824e82e5-af42-4cf7-8bdf-ef60b85a4890.jpg)

**Comment by IndrajeetPatil** [comment]
@strengejacke Can you see if the new organization looks okay to you?

**Comment by strengejacke** [comment]
cool, looks good!
