### ISSUE TITLE
Extension of support to new packages

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#68]
## Regressions
- [ ] brms

## Machine learning
- [ ] ...

## Others (SEM, ...)
- [x] FactoMineR
- [ ] blavaan
- [ ] psychonetrics

**Comment by strengejacke** [comment]
Can you revise this issue a bit? brms is supported, so can be removed, and maybe we should have a more clear list of model types we want to add?

**Comment by strengejacke** [comment]
I think we should add explicit packages as new issue where needed.
