### ISSUE TITLE
Supporting F test to compare two variances

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/parameters#680]
Another `htest` object to support 🥵 

Will be needed to resolve [this](https://github.com/easystats/report/issues/238).

``` r
x <- rnorm(50, mean = 0, sd = 2)
y <- rnorm(30, mean = 1, sd = 1)
m <- var.test(x, y)  

parameters::parameters(m)
#> Error in `$<-.data.frame`(`*tmp*`, "df_error", value = c(`num df` = 49L, : replacement has 2 rows, data has 1
```

<sup>Created on 2022-03-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by strengejacke** [comment]
Just checked, mostly supported by _insight_. Only unclear what `model_info()` should return, probably `$is_ftest`? (ping @mattansb )

**Comment by mattansb** [comment]
Yeah, it is an F test, and htest... Maybe you can be generous and also call it a linear test, or a t-test (it does not assume equal means.... which are thus modeled) 🤷‍♂️

**Comment by mattansb** [comment]
Technically, is also Gaussian.

**Comment by bwiernik** [comment]
For an effect size, the SD ratio, with Normal CI computed using theta = log(sd1i/sd2i) + 1/(2*(n1i-1)) - 1/(2*(n2i-1)) and SE  = sqrt(1/(2*(n1i-1)) + 1/(2*(n2i-1))), then backtransformed with with exp()

**Comment by mattansb** [comment]
What's wrong with the default CI?

``` r
vt <- var.test(mpg ~ am, mtcars)

df <- vt$parameter
theta <- log(vt$estimate) + 1/(2*df[1]) - 1/(2*df[2])
SE <- sqrt(1/(2*df[1]) + 1/(2*df[2]))

exp(theta + c(-1, 1) * 1.96 * SE)
#> [1] 0.2274423 0.6390019

vt$conf.int
#> [1] 0.1243721 1.0703429
#> attr(,"conf.level")
#> [1] 0.95
```

<sup>Created on 2022-03-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
