### ISSUE TITLE
Get rid of "Registered S3 method overwritten" warning

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/parameters#687]
``` r
library(datawizard)
library(parameters)
#> Registered S3 method overwritten by 'parameters':
#>   method                         from      
#>   format.parameters_distribution datawizard
```

<sup>Created on 2022-03-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
Since the main function is now in _datawizard_, the `format()` method should be there, too. Once _datawizard_ is on CRAN, we can remove it here.

**Comment by strengejacke** [comment]
And indeed, already done: https://github.com/easystats/parameters/commit/63f7a0ae39fb5de947630537c87b31cd7ed47359
