### ISSUE TITLE
`model_parameters()` should return `NULL` for data frames

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/parameters#689]
# Current behavior

This is really unexpected behaviour for me.

``` r
library(parameters)

parameters(iris)
#> Warning: Identical densities found along different segments of the distribution,
#> choosing rightmost.

#> Warning: Identical densities found along different segments of the distribution,
#> choosing rightmost.
#> # Fixed Effects
#> 
#> Parameter    | Median |       95% CI |   pd | % in ROPE
#> -------------------------------------------------------
#> Sepal.Length |   5.80 | [4.60, 7.70] | 100% |        0%
#> Sepal.Width  |   3.00 | [2.20, 3.90] | 100% |        0%
#> Petal.Length |   4.35 | [1.00, 6.10] | 100% |        0%
#> Petal.Width  |   1.30 | [0.10, 2.30] | 100% |     3.47%
#> 
#> Uncertainty intervals (highest-density) and p-values (two-tailed) computed
#>   using a MCMC distribution approximation.
```

<sup>Created on 2022-04-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

# Comparison with broom

Compare with:

``` r
library(broom)

tidy(iris)
#> Warning: Data frame tidiers are deprecated and will be removed in an upcoming
#> release of broom.
#> Warning: `data_frame()` was deprecated in tibble 1.1.0.
#> Please use `tibble()` instead.
#> This warning is displayed once every 8 hours.
#> Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.
#> Warning in mean.default(X[[i]], ...): argument is not numeric or logical:
#> returning NA
#> Error in var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm = na.rm): Calling var(x) on a factor x is defunct.
#>   Use something like 'all(duplicated(x)[-1L])' to test for a constant vector.
```

<sup>Created on 2022-04-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

# Example code

I would argue that data frame objects and its cousins should be returned untouched by `model_parameters()` since they are not regression model objects. We already have `datawizard::describe_distribution()` that handles data frame summaries.

```r
parameters.data.frame <- function(x) {
  x
}

parameters.tbl_df <- parameters.data.frame 
parameters.tbl <- parameters.data.frame 
parameters.data.table <- parameters.data.frame 
```

**Comment by strengejacke** [comment]
We treat data frames as posterior samples, so I'd rather opt for checking the data frame format (completely numeric), and maybe warn. And clearly write this in the docs. @DominiqueMakowski

**Comment by IndrajeetPatil** [comment]
But why?! Why are we treating data frames as posterior samples? 

If data frames are needed for some internal data structures, we can just add an additional class, no? And treat them as posterior samples.

**Comment by strengejacke** [comment]
> But why?

![data_good_question](https://user-images.githubusercontent.com/26301769/161250217-d7adff19-707a-4596-8ec5-52bf782e78c1.jpg)


``` r
m <- insight::download_model("brms_1")
parameters::model_parameters(as.data.frame(m))
#> # Fixed Effects
#> 
#> Parameter   | Median |           95% CI |     pd | % in ROPE
#> ------------------------------------------------------------
#> b_Intercept |  39.68 | [ 36.27,  43.34] |   100% |        0%
#> b_wt        |  -3.20 | [ -4.70,  -1.57] | 99.95% |        0%
#> b_cyl       |  -1.49 | [ -2.38,  -0.68] | 99.95% |        0%
#> sigma       |   2.63 | [  1.99,   3.39] |   100% |        0%
#> lp__        | -79.73 | [-83.11, -77.99] |   100% |        0%
#> 
#> Uncertainty intervals (highest-density) and p-values (two-tailed) computed
#>   using a MCMC distribution approximation.
```

<sup>Created on 2022-04-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by IndrajeetPatil** [comment]
But that's a brms model, and`model_parameters()` generic doesn't use `data.frame` method to deal with it, as can be seen from the dispatch here:

``` r
library(brms)
brms_1 <- brm(mpg ~ wt + cyl, data = mtcars)

library(sloop)
s3_dispatch(model_parameters(brms_1))
#>    model_parameters.brmsfit
#>    model_parameters.default
```

<sup>Created on 2022-04-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
Yes, I know. Ask @DominiqueMakowski, I think it has a historical reason, based in bayestestR.

**Comment by DominiqueMakowski** [comment]
Yes, a long long time ago bayestestR was meant to work only with posterior samples in the form of dataframes, and this would have been used by parameters to be used with models.

That said, retuning dataframes untouched is not the most what I would expect, I would basically expect a summary table (`as.data.frame(report(df)))`. We could steal that from `report`

**Comment by IndrajeetPatil** [comment]
> retuning dataframes untouched is not what I would expect,

Why not? `model_parameters()` documentation says:

> Compute and extract model parameters

A data frame (like `iris`) is neither a regression **model** nor does it have **parameters**. 
Transforming it in any sort of way is encouraging [off label](https://www.tidyverse.org/blog/2021/06/off-label-uses-in-ggplot2/) usage for this function. 

> you're asking the "summary parameters" of the variables

But we have a function for that: `datawizard::describe_distribution()`, which does have a `data.frame` method.

> We could steal that from report (as.data.frame(report(df)))

But this makes sense in _report_ package. When I call `report(iris)`, I am expecting to see something other than what I entered because this is completely within the function scope and docs make that perfectly clear.

**Comment by DominiqueMakowski** [comment]
fair enough, although parameters could also call describe_distribution(), afaik only few people would run parameters on a dataframe "by mistake" and it should do something rather then silently doing nothing no?

**Comment by IndrajeetPatil** [comment]
> only few people would run parameters on a dataframe "by mistake"

This happens every day in my `ggcoefstats()` function because it accepts both data frames and regression model objects and plots them. It's a big headache for me to always make sure that the entered object is a regression model object before I pass it on to `model_parameters()`.

>  it should do something rather then silently doing nothing no?

Not necessarily. We can add a warning, so if it is indeed a mistake, the user knows.

```r
parameters.data.frame <- function(x, verbose = TRUE, ...) {
  if (verbose) {
    warning("A `data.frame` object is not a valid regression model object. Did you enter it accidentally?")
  }

  x
}

```

**Comment by IndrajeetPatil** [comment]
I am going to take the silence as a reluctant nod, and make a PR. 😅

**Comment by strengejacke** [comment]
Two things: _why_ is there a need to remove the data frame method? Does it any harm? And: _bayestestR_ has a data frame method for everything as well, for consistency we probably need to remove that as well - however, in _bayestestR_, all posteriors are coerced to data frames and mostly passed to the data frame method.

**Comment by IndrajeetPatil** [comment]
> Does it any harm?

Not to us, but we are making life difficult for developers who write wrappers around these functions.

The problem is that anyone who writes wrappers around `parameters()` needs to currently sanitize their inputs. 

Let's say I want to write a function called `sjplot()` (sounds familiar), which is supposed to work **only** with regression model objects. Naively, I'd expect `parameters()` doesn't accept `data.frame` objects, but surprisingly, not only it does, it also returns some output. 

So, the developer of `sjplot()` now needs to check that the entered object is not a `data.frame` object and only then pass it to my function. Otherwise, the function returns nonsensical output:

``` r
library(sjPlot)
sjplot(iris)
#> Warning in RColorBrewer::brewer.pal(n, pal): n too large, allowed maximum for palette Paired is 12
#> Returning the palette you asked for with that many colors
```

![](https://i.imgur.com/1qKZ9qN.png)

<sup>Created on 2022-04-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

All developers would thankful if we made their lives easier by not accepting objects which are not regression model objects.

This way, they don't need to write additional functions to sanitize inputs:

``` r
library(marginaleffects)
marginaleffects(iris)
#> Error in sanity_model_supported_class(model): Models of class "data.frame" are not supported.
```

<sup>Created on 2022-04-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by bwiernik** [comment]
I agree with Indra. I think we can split the difference and make the current behavior available with an `as_draws` argument. 

@IndrajeetPatil Why do you say that the data frame should be returned as is, rather than returning NULL or an error?

**Comment by strengejacke** [comment]
Yes, returning it as is would contradict your argumentation that developers need to sanitize the input. If we return the data frame, while a model object is expected, this will cause problems. I'd suggest better return `NULL`.

**Comment by IndrajeetPatil** [comment]
> @IndrajeetPatil Why do you say that the data frame should be returned as is, rather than returning NULL or an error?

That was my initial thinking. I am also happy with returning `NULL`. 

> I'd suggest better return NULL.

Agreed!

**Comment by IndrajeetPatil** [comment]
Revised code from my initial comment:

```r
parameters.data.frame <- function(x, verbose = TRUE, ...) {
  if (verbose) {
    warning("A `data.frame` object is not a valid regression model object. Did you enter it accidentally?")
  }

  NULL
}

parameters.tbl_df <- parameters.data.frame 
parameters.tbl <- parameters.data.frame 
parameters.data.table <- parameters.data.frame 
```

**Comment by IndrajeetPatil** [comment]
> bayestestR has a data frame method for everything as well, for consistency we probably need to remove that as well - however, in bayestestR, all posteriors are coerced to data frames and mostly passed to the data frame method

Hmm, that makes this a bit messy. We first need to make this change in _bayestestR_, and then we can handle it in _parameters_.

**Comment by strengejacke** [comment]
closed in #690

**Comment by mattansb** [comment]
We should definitely *not* remove the df methods in bayestestR! They are what make the whole package work + super easy to expand to new models and methods...

(I personally make custom posterior estimates all the time and pass them as dfs to bayestestR functions, it is sooooo easy to use this way.)

**Comment by strengejacke** [comment]
Yes, I think so, too. it's literally part of the bayestestR DNA to have those data frame methods
