### ISSUE TITLE
Add `sort` parameter to `model_parameters()`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/parameters#696]
It will internally use `sort_parameters()` (https://github.com/easystats/parameters/pull/695).

Implementation sketch:

```r
model_parameters(x, sort = "none", ...) {
  ... # code to tidy parameters
  out <- sort_parameters(out, sort = sort)
  ... # add classes and return
}
```

**Comment by vincentarelbundock** [comment]
This is a cool idea indeed, but I’d just note that our output object is already “just a data.frame”, so we can use all the existing tooling to sort:

``` r
library(dplyr)
library(parameters)

mod <- lm(mpg ~ factor(cyl) + hp + am, mtcars)
parameters(mod) |> arrange(desc(Parameter))
#> Parameter   | Coefficient |   SE |         95% CI | t(27) |      p
#> ------------------------------------------------------------------
#> hp          |       -0.04 | 0.01 | [-0.07, -0.01] | -3.04 | 0.005 
#> cyl [8]     |       -3.53 | 2.50 | [-8.67,  1.60] | -1.41 | 0.169 
#> cyl [6]     |       -3.92 | 1.54 | [-7.08, -0.77] | -2.55 | 0.017 
#> am          |        4.16 | 1.26 | [ 1.58,  6.74] |  3.31 | 0.003 
#> (Intercept) |       27.30 | 1.42 | [24.37, 30.22] | 19.17 | < .001
#> 
#> Uncertainty intervals (equal-tailed) and p-values (two-tailed)
#>   computed using a Wald t-distribution approximation.
```

It’s nice to add feature, but we have to be mindful of feature creep. Sprawling packages can become very hard to maintain in the long run.

**Comment by bwiernik** [comment]
Yeah, I don't really see a need for this to be in the function rather than done in two stages

**Comment by vincentarelbundock** [comment]
Looks like this was already implemented: https://easystats.github.io/parameters/reference/sort_parameters.html

Personally, I would deprecate this function, but I understand if that's too drastic. At least we should close this issue.

**Comment by IndrajeetPatil** [comment]
Please don't. 

I implemented the helper function because it is helpful in the context of (at the least) both _ggstatsplot_ and _sjPlot_ visualizations.

As for the current issue of adding this as an argument, I have no strong opinions. I created it only because Daniel had commented on my PR that that might be a nice addition.

**Comment by vincentarelbundock** [comment]
Thanks a lot for explaining @IndrajeetPatil
