### ISSUE TITLE
Typo in Roxygen Documentation

### ISSUE THREAD

**Issue by Buedenbender** [easystats/parameters#698]
Hi, 

just a minor typo in the documentation (roxygen) of [R/check_factorstructure.R](https://github.com/easystats/parameters/blob/HEAD/R/check_factorstructure.R) in Line 57, which I found on the pkdown side: [here](https://easystats.github.io/parameters/reference/check_kmo.html)

> Kaiser (1975) suggested that KMO > .9 were (...)

However, the reference list does not contain a source for Kaiser (1975). I guess it is supposed to refer to `Kaiser 1974` Little Jiffy Mark IV article, right?

**Comment by strengejacke** [comment]
Good catch, thanks!
