### ISSUE TITLE
model_parameters for subcomponents (random, ...)

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#7]
@strengejacke As you can see, it differs from broom by giving more flexibility, computing more things, and also being less "generic" (e.g. the colnames directly refers to what they represent, i.e., Mean, Median, instead of "estimate"). This last point is both a bad thing (from a programming perspective, as you need to adapt to the input), but I believe a good thing for users (improved clarity and explicitness). Especially, it was designed this way for straightforward future compatibility with report (which will paste colnames and values into textual report). Hence the presence of title, upper and lower cases; although it is not conventional for programming, it is usually the way we format the tables for reporting in papers...

What do you think of the current design direction?

**Comment by strengejacke** [comment]
I think it's a problem which is difficult to solve, if at all... There's a discussion at the stan-forum how to name columns in broom, as Bayes models have no "confidence intervals". I think, we can use names that refer to what they represent, but maybe we can add a "converter", either as function or as argument, which then returns standardized column names. That would be best, so package developers may prefer the standardized names, while user would rather use the other naming style.

**Comment by DominiqueMakowski** [comment]
having with a converter triggered by a "generic=TRUE" argument is indeed a good idea, and seems relatively easy (although tedious) to implement, as it can be just a big list of renaming...

I was enquiring a more general feeling, are you a bit more convinced about the existence and purpose of this package (and the potential issue of a too-strong resemblance with broom/broom.mixed) 😅

**Comment by strengejacke** [comment]
I don't mind the overlap to broom(.mixed), especially if we keep dependencies and requirements at a minimum level. One thing why I hesitate to use broom.mixed is the version requirement R >= 3.5. For ggeffects, I moved the effects-package from imports to suggest, because I got several feedback that users coudln't use ggeffects anymore because they could not install R 3.5 (I think people should not underestimate that many users are subject to the IT administration when it comes to installing software, and this is not done every two months, so many users still might be using R < 3.5).

**Comment by strengejacke** [comment]
I think we indeed need a broom-alternative that also covers mixed models and Bayesian models, but this will be a tough work.

- Annoying part: implementation of many (but easy to do) models
- Difficult task: Cleaning from different model parts like ZI or random effects from ZI
- Very difficult task: Handle edge cases from brms and rstanarm.

I think, we should either return a list for each component (conditional, random, ...) or have additional columns for this information.

**Comment by DominiqueMakowski** [comment]
it's definitely on the roadmap :)

for frequentist models, it would also benefit from the computation of p values.

what about keeping `model_parameters`  for returning the "conditional" parameters. Rather than having an argument controlling the stuff to return (`what="random"`), I think it could be worth having another function, `model_random`? `model_otherparameters` (jk)? That would return the additional parameters (random, zi, gam's smooth, sigma...)... Or maybe we should make separate functions for each of these subtypes?

**Comment by strengejacke** [comment]
We could do both, a generic `model_parameters` with an argument (similar to _insight_, with `components = c("all", "zi", "conditional"...)`, and the related standalone-functions.

I think we can start with the standalone functions and then think about a generic function or adding an argument to `model_parameters()` later, as we for now need the "subfunctions" first anyway.

**Comment by DominiqueMakowski** [comment]
Agreed

**Comment by strengejacke** [comment]
Just wanted to say: I think `model_parameters()` is really a game changer, especially since our package comes with minimum dependencies. But in the end, we actually need to make it work for (almost) all model-classes that are supported by _insight_ - or even a bit more...

**Comment by DominiqueMakowski** [comment]
yes yes... The key part is to have the subcomponents working and supporting these classes (in particular CIs and p values), then the rest will (hopefully) be a piece of cake 🤞

Maybe this will need the addition of other functions, such as `dof` or `get/find_statistic` (for retrieving/computing the statistic and its name F, z, t etc.)

This + some cool new features (clever standardization, marginal parameters or such) could make `parameters` and his big brother `performance` very useful package

**Comment by strengejacke** [comment]
closing in favor of #113
