### ISSUE TITLE
Coefficient -> Beta

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#70]
Since a CRAN release is close, I wanted to have your opinion about something:

We decided [here](https://github.com/easystats/parameters/issues/44) to change from `beta` (lowercase) to `Coefficient` (for the column name of the parameters table).

However, since we usually try to stick to the APA norms, and that they recommend using the beta symbol to report slopes, I wondered if we should change it to `Beta` (title case for consistency).

Thoughts?

**Comment by DominiqueMakowski** [comment]
Daniel mentioned:

> I'm a bit uncertain according b / beta, as these names are used differently in software and textbooks (some use "b" as unstandardized and "beta" as standardized, others use "beta" as unstandardized and "unstandardized beta" etc.).

So I wonder the extent to which we are certain that APA's guidelines (I don't have the book) suggest using the beta symbol for regression slopes.

**Comment by DominiqueMakowski** [comment]
@pdwaggoner @mattansb @humanfactors

**Comment by mattansb** [comment]
My first thought here was "there are model parameters that are not slopes", but it seems that `model_parameters` only returns slopes:
``` r
library(rstanarm)
model <- stan_glm(mpg ~ cyl, mtcars, family = gaussian())

head(as.data.frame(model))
#>   (Intercept)       cyl    sigma
#> 1    39.32217 -3.130616 3.366686
#> 2    38.68716 -2.933902 3.339297
#> 3    37.38322 -2.676346 3.081585
#> 4    38.36550 -3.068607 3.340693
#> 5    43.30647 -3.668781 3.932849
#> 6    43.15878 -3.619783 3.860538

parameters::model_parameters(model) # where is sigma?
#>     Parameter   Median CI    CI_low   CI_high  pd ROPE_CI   ROPE_low
#> 1 (Intercept) 37.86467 90 34.142294 41.335485 100      89 -0.6026948
#> 2         cyl -2.86977 90 -3.413836 -2.292818 100      89 -0.6026948
#>   ROPE_high ROPE_Percentage Effective_Sample      Rhat Prior_Distribution
#> 1 0.6026948               0         3393.088 0.9993293             normal
#> 2 0.6026948               0         3338.302 0.9992868             normal
#>   Prior_Location Prior_Scale
#> 1              0   60.269481
#> 2              0    8.436748
```

In either case, I would probably stick with `Coefficient` (also `sigma` would be a coefficient - of variation), as `Beta` might be confused with "standardized coefficient".

**Comment by humanfactors** [comment]
As a general point, from reading the thread, I don't actually agree that column names should be captialised. I would far more frequently need to call `df$Coefficient` than I would be exporting to a perfect tabular dataframe for export. My opinion is that I don't see a clear rule for dataframe outputs _across_ easyverse, so I think lowercase should be preferred. However, looking at the previous thread please do keep in mind it's just my perspective!

-----

Putting aside that discussion, however, I think `Coefficient` is fine. APA 6th Edition specifies to use B (sample coefficient) or β (population level) for the actual table

> "Clearly label the type of regression (e.g., hierarchical) and type of regression coefficients (raw or standardized) being reported (see Tables 5 . 1 2 and 5 . 1 3 ) . For hierarchical and other sequential regressions, be sure to provide the increments of change (see section 4.44 ) ." (APA, p. 141)

![image](https://user-images.githubusercontent.com/16096044/60701256-c214d280-9f2d-11e9-92b0-dc97335ed2e3.png)

-----

However to add to Matt's point, we should avoid the term "slope" as in a standard `lm` we do see the intercept being assigned a coefficient.

![image](https://user-images.githubusercontent.com/16096044/60701549-b675db80-9f2e-11e9-8c68-0f040d7f3050.png)

**Comment by pdwaggoner** [comment]
Personally, I like `Coefficient`, as this captures a wide array of values fitted by and reported from a model object (e.g., slope, intercept, rfx, etc). And in my field(s), we never use the term "slope". Its always either beta or coefficient. And as parameters from a fit model object _include_ the intercept and beta(s), I think `Coefficient` makes most sense here.

**Comment by DominiqueMakowski** [comment]
The matter is settled then. We'll see then in `report` how to deal with this for inline reporting
