### ISSUE TITLE
Matrix object in `cluster_analysis()`

### ISSUE THREAD

**Issue by strengejacke** [easystats/parameters#700]
The cluster_analysis() function accepts a matrix as the first argument, but without warning/error fails to complete the analysis. The requirement that the first argument should be a data frame is documented, but it would be helpful if there was either a warning or an effort to convert a matrix to a data frame in order to complete the analysis.

``` r
library(parameters)
data(iris)
iris.dat <- iris[c(1:15, 51:65, 101:115), -5]
iris.dat.km <- cluster_analysis(iris.dat, n = 4, method = "kmeans")
predict(iris.dat.km)
#>  [1] 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 2 2 1 4 4 2 1 4 1 1 4 1 4 4 2 4 2 4 2 2 1 2
#> [39] 4 2 2 4 2 4 4

iris.mat <- as.matrix(iris.dat)
iris.mat.km <- cluster_analysis(iris.mat, n = 4, method = "kmeans")
predict(iris.mat.km)
#>  [1] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
#> [26] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
```

<sup>Created on 2022-04-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by bwiernik** [comment]
Coercing to a data frame is a good idea. 

One thing we should check for both matrices and data frames is if the input is square. That would usually indicate it's a correlation, covariance, or distance matrix, which would need to be handled specially

**Comment by strengejacke** [comment]
What kind of special handling would we need?

**Comment by bwiernik** [comment]
Just that it needs to be treated as a covariance matrix and not a data matrix

**Comment by strengejacke** [comment]
You mean reshaping?

**Comment by bwiernik** [comment]
No. For example, kmeans() can only take a data matrix, not a distance matrix, so we need to fail or give a warning if we think it's a distance or covariance matrix. hclust() only takes a distance matrix, so we need to not re-compute the distance matrix from the data if we already have one. Etc. For each cluster function, we need to appropriately handle data vs covariance vs distance matrices. 

Also, the second condition here is always true. lower.tri() returns logical values for matrix positions, not the values themselves. We want either isSymmetric() or identical(round(x[lower.tri(x)], 10), round(x[upper.tri(x)], 10))

```r

if (nrow(x) == ncol(x) && identical(lower.tri(x), upper.tri(x))) {
    ## TODO: special handling
    warning(insight::format_message("Input data seems to be a correlation, covariance or similar matrix."), call. = FALSE)
  }
```
