### ISSUE TITLE
Inconstancy in `p_value.numeric()`?

### ISSUE THREAD

**Issue by mattansb** [easystats/parameters#703]
Shouldn't these return the same value?
``` r
parameters:::p_value.numeric(c(1,1,1))
#> [1] 1
parameters:::p_value.numeric(-c(1,1,1))
#> [1] 0.25
```

<sup>Created on 2022-05-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
I'm not sure who wrote/revised the numeric-method, but the commented code in `p_value.numeric()` returns the correct result:

``` r
testp <- function(x) {
  k_lt0 <- sum(x <= 0)
  k_gt0 <- sum(x >= 0)
  k <- 2 * min(k_lt0, k_gt0)
  N <- length(x)
  (k + 1) / (N + 1)
}
testp(c(1,1,1))
#> [1] 0.25
testp(-c(1,1,1))
#> [1] 0.25
```

<sup>Created on 2022-05-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mattansb** [comment]
I commented out the code https://github.com/easystats/parameters/commit/ce229656b9653472b8ee1047a36cd880bc9de1c7,

but it was you who broke the my new code https://github.com/easystats/parameters/commit/98bc44f313cbfaa73755e5b191640b326fe1556f 😅

I think the function should be:

``` r
p_value.numeric <- function(model, null = 0, ...) {
  x <- model
  xM <- mean(x)
  # browser()
  x0 <- x - xM
  k <- sum(abs(x0) > abs(xM - null))
  N <- length(x)
  (k + 1) / (N + 1)
}

x <- rnorm(100, mean = 1.5)

hist(x)
```

![](https://i.imgur.com/AmSs4ez.png)

``` r
p_value.numeric(x)
#> [1] 0.2079208
p_value.numeric(-x) # should be same
#> [1] 0.2079208

p_value.numeric(x, null = 1) # should be larger
#> [1] 0.6633663

p_value.numeric(-x, null = 1) # should be smaller
#> [1] 0.00990099
p_value.numeric(x, null = -1) # should be same
#> [1] 0.00990099
```

<sup>Created on 2022-05-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
