### ISSUE TITLE
Change `standardize_parameters()` output's class(es)

### ISSUE THREAD

**Issue by mattansb** [easystats/parameters#704]
@strengejacke `standardize_parameters()` returns a class `c("effectsize_std_params", "effectsize_table", "see_effectsize_table", "data.frame")` - please make sure to change these to the proper classes with methods maintained in `parameters` (:

**Comment by strengejacke** [comment]
Should we aim at having it as close as possible as it is now implemented in _effectsize_? There are plenty of `effectsize_table` methods, and I'm not sure if we need all of them in _parameters_. So we could preserve some attributes, to allow calls to `equivalence_test.effectsize_table()` or `interpret.effectsize_table()`.

**Comment by mattansb** [comment]
I guess you could keep those then (so much for reducing circular dependency 😅)..

But the format+printing methods should be moved here, I think, else users without `effectsize` will get an ugly data frame.

**Comment by bwiernik** [comment]
I am strongly in favor of anything to reduce circular dependencies. Where does the generic for equivalence_test() live?

**Comment by strengejacke** [comment]
In _bayestestR_, I think.

**Comment by strengejacke** [comment]
Ok, output class is now `parameters_standardized`. @mattansb I think the class `effectsize_std_params` is no longer used, can you check _effectsize_ if you have any methods that could be removed, to clean up the code?

**Comment by mattansb** [comment]
Will do, thanks!
