### ISSUE TITLE
CRAN submission

### ISSUE THREAD

**Issue by strengejacke** [easystats/parameters#713]
@vincentarelbundock There are some issues with _marginaleffects_: https://win-builder.r-project.org/5QXJ3SX1YRVP/00check.log

```
 == Failed tests ================================================================
  -- Failure (test-marginaleffects.R:9:5): model_parameters - marginaleffects (frequentist) --
  dim(parameters(model)) (`actual`) not equal to c(3, 10) (`expected`).
  
    `actual`: 3 14
  `expected`: 3 10
  -- Failure (test-marginaleffects.R:16:5): model_parameters - marginaleffects (frequentist) --
  dim(parameters(model)) (`actual`) not equal to c(3, 15) (`expected`).
  
    `actual`: 3 14
  `expected`: 3 15
```

I would have assumed this is due to not testing against the devel-version, but GitHub actions don't do this, either? Should I condition these tests on a higher version of _marginaleffects_, or only run them on GitHub?

**Comment by vincentarelbundock** [comment]
I just pushed a minor commit testing only the number of rows, and not the columns, as those are more likely to change.

I also opened a new issue to address stuff for next release: https://github.com/easystats/parameters/issues/714

**Comment by strengejacke** [comment]
```
Package: MCM
Check: examples
New result: ERROR
  Running examples in ‘MCM-Ex.R’ failed
  The error most likely occurred in:
  
  > base::assign(".ptime", proc.time(), pos = "CheckExEnv")
  > ### Name: mcm_lmer
  > ### Title: Estimate and Test Inter-generational Mobility Effect with
  > ###   Longitudinal Data
  > ### Aliases: mcm_lmer
  > 
  > ### ** Examples
  > 
  > library(MCM)
  > library(lme4)
  Loading required package: Matrix
  > data("sim_datlmer")
  > fit_mcm_lmer <- mcm_lmer(yij ~ origin*destination*age +
  +                            (1|id), data = sim_datlmer,
  +                          origin = "origin",
  +                          destination = "destination",
  +                          time = "age")
  Warning: extra argument(s) ‘origin’, ‘destination’, ‘time’ disregarded
  Error in asMethod(object) : 
    Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 102
  Calls: mcm_lmer ... .extract_parameters_mixed -> <Anonymous> -> get_statistic.default
  Execution halted
```

**Comment by IndrajeetPatil** [comment]
@strengejacke Do you not update [CRAN comments file](https://github.com/easystats/parameters/blob/main/cran-comments.md) for each submission?

I think we can save ourselves a lot of headache during submission by already declaring expected breakages found during our own reverse dependency check.

**Comment by strengejacke** [comment]
I used to add the comments into the comment-field during submission, but since I got (automatic) emails with requests to reply-to-all and explain, I stopped adding comments, as this step seemed to be redundant.
