### ISSUE TITLE
Remove Bayesian CI warning from website

### ISSUE THREAD

**Issue by vincentarelbundock** [easystats/parameters#719]
The very first thing that people see when they visit the website or README is a warning about bayesian credible intervals.

It's been there for 9 months already. Feels like bad marketing. Can we remove it? 

If we think that this will lead users astray, we should raise an error in R instead.

**Comment by IndrajeetPatil** [comment]
I agree that we should get rid of it from the README.

**Comment by strengejacke** [comment]
![picard_make_it_so](https://user-images.githubusercontent.com/26301769/171009851-d3e2ebce-133f-4ee4-a4fc-5b47ef2f9185.jpg)

**Comment by vincentarelbundock** [comment]
049a86c2
