### ISSUE TITLE
`footer` does not work with `display`

### ISSUE THREAD

**Issue by iago-pssjd** [easystats/parameters#721]
I would expect that

> For markdown-formatted tables, table footers, due to the limitation in markdown rendering, are actually just a new text line under the table.

However, it does not appear even a text line:
```r
model <- lm(mpg ~ wt + cyl, data = mtcars)
mp <- model_parameters(model)
display(mp, format = "markdown", footer = "Somethng")


|Parameter   | Coefficient |   SE |         95% CI | t(29) |      p |
|:-----------|:-----------:|:----:|:--------------:|:-----:|:------:|
|(Intercept) |       39.69 | 1.71 | (36.18, 43.19) | 23.14 | < .001 |
|wt          |       -3.19 | 0.76 | (-4.74, -1.64) | -4.22 | < .001 |
|cyl         |       -1.51 | 0.41 | (-2.36, -0.66) | -3.64 | 0.001  |
```
(Same with `format = "html"`)

**Comment by etiennebacher** [comment]
@iago-pssjd It should work now (note that for HTML output, you also need to reinstall insight from github)

**Comment by iago-pssjd** [comment]
@etiennebacher Great!
Thanks!
