### ISSUE TITLE
bootstrap_parameters no longer works with glmmTMB

### ISSUE THREAD

**Issue by plants-22** [easystats/parameters#739]
I was running the following code inside a for loop on glmmTMB mixed models. I was working fine in the previous parameters version. 

boot_out <- bootstrap_parameters(model = all_model_objects[[h]][[new_AIC$model[[h]]]],
                                   iterations = nBoot, parallel = "multicore", n_cpus = 6)

Now I get the following error: 

Error in eval(expr, p) : 
  trying to get slot "call" from an object (class "glmmTMB") that is not an S4 object 

The glmmTMB objects are S3 objects. It seems parameters thinks they're meant to something else. Help!

**Comment by strengejacke** [comment]
Do you have a small reproducible example?

**Comment by strengejacke** [comment]
Seems like an issue in `lme4::bootMer()`, not _parameters_:

``` r
library(glmmTMB)

m1 <- glmmTMB(
  count ~ mined + (1 | site),
  zi =  ~ mined,
  family = poisson,
  data = Salamanders
)

boot_fun <- function(model) {
  lme4::fixef(model)[[1]]
}

lme4::bootMer(m1, boot_fun)
#> Error in eval(expr, p): trying to get slot "call" from an object (class "glmmTMB") that is not an S4 object
```

<sup>Created on 2022-07-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by plants-22** [comment]
Yes, do you need the data files and code? I just upgraded R to v4.2.1 and installed the previous parameters 0.17.0. I still have the problem so might not be the bootstrap_parameters function

**Comment by strengejacke** [comment]
Yes, see my comment above. Seems like an issue in `lme4::bootMer()` or maybe something in _glmmTMB_ has changed. I opened an issue (https://github.com/glmmTMB/glmmTMB/issues/836), maybe we find a solution to this problem.

**Comment by plants-22** [comment]
Thank you!

**Comment by bwiernik** [comment]
It should work again with version 1.1-30 now on CRAN https://cran.r-project.org/web/packages/lme4/index.html

**Comment by plants-22** [comment]
Excellent! Thank you all, it works now!
