### ISSUE TITLE
degrees of freedom: DoF or df?

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#74]
I've seen a trend (also in other languages such as Julia) toward naming degrees of freedom `dof` instead of `df` (my guess is that it's to avoid confusion with `dataframe`). However, in APA tables it's usually reported as `df`. 

Should we rename the column to `df`?

**Comment by strengejacke** [comment]
I think `df` is a common abbreviation for degrees of freedom. Maybe it's often avoided because of the function `df()` and the often used abbreviation df for data frame.

However, `dof` also works. :-D

**Comment by mattansb** [comment]
I think that since we are discussing a column's *name*, there's no reason it would be confused with an object of the same name. I support `df`.
(Also, if the name contains what *type* of df it is (e.g. `df_resid`), even less of a chance for confusion).
(Also2, this shouldn't matter for printing 😊, à la #73)

**Comment by pdwaggoner** [comment]
Agreed @mattansb - well said.

**Comment by DominiqueMakowski** [comment]
> this shouldn't matter for printing 

Although there should be a consistency between the name in the df and what is printed, if it's printed `df` it would be super weird and inconsistent to keep it as `dof` in the dataframe.

I honestly have no preference between `df` and `dof`, at the same time I'd like to stay close with APA and at the same time I've seen DoF used in recent software... hence I am not taking part in the vote 😅

**Comment by DominiqueMakowski** [comment]
@mattansb -> df
@pdwaggoner -> (df?)
@strengejacke -> ?
@humanfactors -> ?

**Comment by DominiqueMakowski** [comment]
I have a prior that the vote will be in favour of `df` :)

**Comment by IndrajeetPatil** [comment]
I will vote in favor of `df` as well.
