### ISSUE TITLE
Provide better error message when the `model` argument is missing

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/parameters#758]
The following bit is unnecessary: 

> "Sorry, `model_parameters()` failed with the following error (possible class '"

``` r
parameters::parameters()
#> Error in paste0("Sorry, `model_parameters()` failed with the following error (possible class '", : argument "model" is missing, with no default

performance::performance()
#> Error in insight::is_model(model): argument "model" is missing, with no default
```

The alternative is to do something like this, but I have no idea when this will be the intended behaviour.

```r
broom::tidy()
#> # A tibble: 0 × 0

broom::glance()
#> # A tibble: 0 × 0
```

<sup>Created on 2022-08-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
I'd say we stop (error), but a more informative error message.
