### ISSUE TITLE
missing GEE -> missing HAC/HAR robust SE for GEE [enhancement]

### ISSUE THREAD

**Issue by DexterGlass** [easystats/parameters#762]
GEE is heteroskedasticity consistent but not robust, and neither autocorrelation  (ac)robust nor  ac consistent estimator.

parameters uses clubSandwich. clubSandwich has vcovHAC().
 vcovHAC is heteroskedasticity consistent and autocorrelation consistent.

**Comment by strengejacke** [comment]
tagging @vincentarelbundock

**Comment by vincentarelbundock** [comment]
Thanks for the tag. I can look into this eventually.

@DexterGlass would you be able to give me a minimal working example of a GEE model using publicly available data (something like the builtin `mtcars` dataset).

Thanks!

**Comment by DexterGlass** [comment]
`r<-na.exclude(airquality)
overdisp<-(mean(r$Solar.R)/var(r$Solar.R))^(-1)
overdisp
#we have overdispersion so set scale not fixed in poisson family.
install.packages(gee)
library(gee)
fitted<-gee(Solar.R~Wind+Temp+Ozone,id=r$Month,corstr = "AR-M",scale.fix=F,family="poisson",data=r,maxiter = 1000,Mv=1)
#fit AR(1) working correlation form
#data is clustered by month
#response is a count variable
summary(fitted)
`

**Comment by DexterGlass** [comment]
`
r<-na.exclude(airquality)
overdisp<-(mean(r$Solar.R)/var(r$Solar.R))^(-1)
overdisp
#we have overdispersion so set scale not fixed in poisson family.
install.packages(gee)
library(gee)
fitted<-gee(Solar.R~Wind+Temp+Ozone,id=r$Month,corstr = "AR-M",scale.fix=F,family="poisson",data=r,maxiter = 1000,Mv=1)
#fit AR(1) working correlation form
#data is clustered by month
#response is a count variable
summary(fitted)

`

**Comment by DexterGlass** [comment]
`

install.packages(geepack)
library(geepack)
fit2<-geeglm(Solar.R~Wind+Temp+Ozone,id=r$Month,corstr = "ar1",family="poisson",data=r)
summary(fit2)
#second version of gee allows nested fixed-effects model-comparison and supports unevenly spaced timepoints 

`

**Comment by vincentarelbundock** [comment]
Like in the other thread, it looks like the `vcov*` functions in `sandwich` and `clubSandwich` do not work here.

If you can show me a working example where the functions from one of these two packages produce a valid variance-covariance matrix, then I can re-open the issue and make sure that `parameters` supports the `vcov` argument for these models.
