### ISSUE TITLE
Missing Support for glmmPQL for penalized quasilikelihood glmm [enhancement request]

### ISSUE THREAD

**Issue by DexterGlass** [easystats/parameters#764]
Error: Unable to extract a variance-covariance matrix for
  model object of class `glmmPQL`. Different values of
  the `vcov` argument trigger calls to the `sandwich` or
  `clubSandwich` packages in order to extract the matrix
  (see `?insight::get_varcov`). Your model or the
  requested estimation type may not be supported by one
  or both of those packages, or you were missing one or
  more required arguments in `vcov_args` (like
  `cluster`).

``` r
library(parameters)
library(MASS)
library(nlme)
 f<-glmmPQL(y ~ trt + I(week > 2), random = ~ 1 | ID,
                family = binomial, data = bacteria)
mp <- model_parameters(f, vcov = "vcovHAC")
```

**Comment by strengejacke** [comment]
@vincentarelbundock I'm just tagging you for all vcov-stuff, just in case you can contribute. Not meant to assign you to doing this ;-)

**Comment by vincentarelbundock** [comment]
These issues are interesting to me, so tags are great.

This type of model is not supported by `sandwich::vcovHAC`, so we will not be able to add support in `parameters`. As the error message says, we do not implement covariance computation ourselves, and only delegate to `sandwich` and `clubSandwich`.

``` r
library(MASS)
library(nlme)
library(sandwich)
f <- glmmPQL(y ~ trt + I(week > 2),
     random = ~ 1 | ID,
     family = binomial, data = bacteria
 )
sandwich::vcovHAC(f)
#> Error in UseMethod("estfun"): no applicable method for 'estfun' applied to an object of class "c('glmmPQL', 'lme')"
```
