### ISSUE TITLE
Fix test failure on older R versions

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/parameters#772]
```r
══ Failed tests ════════════════════════════════════════════════════════════════
── Error (test-dominance_analysis.R:49:3): (code run outside of `test_that()`) ──
Error in `sapply(sets, isa, "formula")`: object 'isa' not found
Backtrace:
    ▆
 1. └─parameters::dominance_analysis(...) at test-dominance_analysis.R:49:2
 2.   └─base::sapply(sets, isa, "formula") at parameters/R/dominance_analysis.R:193:4
 3.     └─base::match.fun(FUN)

[ FAIL 1 | WARN 1 | SKIP 17 | PASS 1152 ]
```

**Comment by strengejacke** [comment]
`isa` is a base R function, but maybe introduced in a later R version?

**Comment by IndrajeetPatil** [comment]
Yeah, we can probably just skip this test on older versions. 

Or backport the needed function.

**Comment by strengejacke** [comment]
I replaced with `inherits` (see https://stackoverflow.com/questions/73146762/how-to-solve-the-following-error-running-rmcorr-in-r-error-in-isaparticipant), should work, I think.

**Comment by vincentarelbundock** [comment]
`isa` was introduced in 4.1. We should probably not use it.

https://hughjonesd.shinyapps.io/rcheology/

**Comment by IndrajeetPatil** [comment]
Where has this Shiny app been all my life?!

Thanks, @vincentarelbundock. That's a lifesaver.

**Comment by vincentarelbundock** [comment]
It's fantastic, isn't it?!

**Comment by strengejacke** [comment]
indeed, I always end up googling using various search terms like "isa first introduced R version" etc. and nothing helpful comes up.

**Comment by strengejacke** [comment]
old-release pass, so should be fixed now.
