### ISSUE TITLE
Unable to suppress table footer

### ISSUE THREAD

**Issue by jmgirard** [easystats/parameters#775]
May be related to easystats/insight#457 

How do I get rid of the "Anova Table (Type 1 tests)" line and other similar after-table text?

``` r
fit <- aov(Petal.Length ~ Species, data = iris)
parameters::model_parameters(fit) |> insight::print_md(caption = NULL)
```

| Parameter | Sum_Squares | df  | Mean_Square |    F    |    p    |
|:----------|:-----------:|:---:|:-----------:|:-------:|:-------:|
| Species   |   437.10    |  2  |   218.55    | 1180.16 | \< .001 |
| Residuals |    27.22    | 147 |    0.19     |         |         |

Anova Table (Type 1 tests)

``` r
parameters::model_parameters(fit) |> insight::print_md(caption = "")
```

| Parameter | Sum_Squares | df  | Mean_Square |    F    |    p    |
|:----------|:-----------:|:---:|:-----------:|:-------:|:-------:|
| Species   |   437.10    |  2  |   218.55    | 1180.16 | \< .001 |
| Residuals |    27.22    | 147 |    0.19     |         |         |

Anova Table (Type 1 tests)

``` r
parameters::model_parameters(fit) |> insight::print_md(footer = NULL)
```

| Parameter | Sum_Squares | df  | Mean_Square |    F    |    p    |
|:----------|:-----------:|:---:|:-----------:|:-------:|:-------:|
| Species   |   437.10    |  2  |   218.55    | 1180.16 | \< .001 |
| Residuals |    27.22    | 147 |    0.19     |         |         |

Anova Table (Type 1 tests)

``` r
parameters::model_parameters(fit) |> insight::print_md(footer = "")
```

| Parameter | Sum_Squares | df  | Mean_Square |    F    |    p    |
|:----------|:-----------:|:---:|:-----------:|:-------:|:-------:|
| Species   |   437.10    |  2  |   218.55    | 1180.16 | \< .001 |
| Residuals |    27.22    | 147 |    0.19     |         |         |

Anova Table (Type 1 tests)

<sup>Created on 2022-09-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
``` r
fit <- aov(Petal.Length ~ Species, data = iris)

# no caption
parameters::model_parameters(fit) |> print()
#> Parameter | Sum_Squares |  df | Mean_Square |       F |      p
#> --------------------------------------------------------------
#> Species   |      437.10 |   2 |      218.55 | 1180.16 | < .001
#> Residuals |       27.22 | 147 |        0.19 |         |       
#> 
#> Anova Table (Type 1 tests)

# add caption
parameters::model_parameters(fit) |> print(caption = "test")
#> test
#> 
#> Parameter | Sum_Squares |  df | Mean_Square |       F |      p
#> --------------------------------------------------------------
#> Species   |      437.10 |   2 |      218.55 | 1180.16 | < .001
#> Residuals |       27.22 | 147 |        0.19 |         |       
#> 
#> Anova Table (Type 1 tests)
```

<sup>Created on 2022-09-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
``` r
library(parameters)
fit <- aov(Petal.Length ~ Species, data = iris)

parameters::model_parameters(fit) |> print(footer = "")
#> Parameter | Sum_Squares |  df | Mean_Square |       F |      p
#> --------------------------------------------------------------
#> Species   |      437.10 |   2 |      218.55 | 1180.16 | < .001
#> Residuals |       27.22 | 147 |        0.19 |         |

parameters::model_parameters(fit) |> print_md(footer = "")
```

| Parameter | Sum_Squares | df  | Mean_Square |    F    |    p    |
|:----------|:-----------:|:---:|:-----------:|:-------:|:-------:|
| Species   |   437.10    |  2  |   218.55    | 1180.16 | \< .001 |
| Residuals |    27.22    | 147 |    0.19     |         |         |

<sup>Created on 2022-09-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
ok, I harmonized the `footer` argument between `print()` and `print_md()`. In a few hours, _parameters 0.18.2.9_ should be on R universe, and you (or your students) can install the latest updates via `easystats::install_latest()`.
