### ISSUE TITLE
Should we remove % in ROPE from default tables?

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#778]
It's just a thought that occurred to me now I haven't given it much thiking myself, but given the complexity of specifying default ROPE bounds, I wonder if we should have the %ROPE by default 

https://github.com/easystats/parameters/blob/15f7313e40a6b0f15f933fcd4fe5582b0b4ada15/R/methods_brms.R#L9

**Comment by bwiernik** [comment]
Yes I think so. 

I would also say we should make the rope % default be 1.00 so that it gives the % of the whole posterior in the rope

**Comment by DominiqueMakowski** [comment]
agreed

**Comment by strengejacke** [comment]
Isn't this also a _bayestestR_ issue?

**Comment by strengejacke** [comment]
closed in #781
