### ISSUE TITLE
Several potential improvements with Bayes Factors

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#788]
A few improvements I noted when asking for BFs

``` r
m <- brms::brm(mpg ~ wt, data=mtcars, prior = brms::set_prior("normal(0, 1)", class = "b"), refresh=0)
#> Compiling Stan program...
#> Start sampling
param <- parameters::parameters(m, test=c("pd", "BF"))
#> Warning: Bayes factors might not be precise.
#> For precise Bayes factors, sampling at least 40,000 posterior samples is recommended.

param
#> # Fixed effects
#> 
#> Parameter   | Median |         95% CI |   pd |  Rhat |     ESS |       BF
#> -------------------------------------------------------------------------
#> (Intercept) |  32.36 | [27.92, 36.09] | 100% | 0.999 | 2053.00 | 1.01e+08
#> wt          |  -3.83 | [-4.91, -2.49] | 100% | 0.999 | 2084.00 | 2.92e+03
#> 
#> # Fixed effects sigma
#> 
#> Parameter | Median |       95% CI |   pd |  Rhat |     ESS |       BF
#> ---------------------------------------------------------------------
#> sigma     |   3.44 | [2.63, 4.81] | 100% | 1.001 | 2018.00 | 4.32e+09
#> 
#> Uncertainty intervals (equal-tailed) and p-values (two-tailed) computed
#>   using a MCMC distribution approximation.
```
- [ ] the BF position is at the end, but it'd be better to put if after pd by default (to have all test scores grouped together)

Now, strange things happen when I tried to relocate it using datawizard (@IndrajeetPatil):

```
datawizard::data_relocate(param, "pd", before = "BF")
#> Error in seq.default(1, where - 1): 'to' must be a finite number
```

It got me to scratch my head for a bit before remembering that the name is `log_BF` (how come we didn't name it `BF_log` 🤔?). 

- [x] Point is, we should add a more informative error message when the column name doesn't exist.
- [x] ~We should pretty print `log(BF)` or `BF(log)` or `BF-log`, because I completely forgot about that...~

Then:

```
datawizard::data_relocate(param, "pd", before = -1)
#> # Fixed effects
#> 
#> Parameter   | Median |         95% CI |  Rhat |   pd |     ESS |       BF
#> -------------------------------------------------------------------------
#> (Intercept) |  32.36 | [27.92, 36.09] | 0.999 | 100% | 2053.00 | 1.01e+08
#> wt          |  -3.83 | [-4.91, -2.49] | 0.999 | 100% | 2084.00 | 2.92e+03
#> 
#> # Fixed effects sigma
#> 
#> Parameter | Median |       95% CI |  Rhat |   pd |     ESS |       BF
#> ---------------------------------------------------------------------
#> sigma     |   3.44 | [2.63, 4.81] | 1.001 | 100% | 2018.00 | 4.32e+09
#> 
#> Uncertainty intervals (equal-tailed) and p-values (two-tailed) computed
#>   using a MCMC distribution approximation.
```

<sup>Created on 2022-10-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Weirdly, this doesn't place "pd" before the last one, but two... which got me scratching my head again:

until I did `as.data.frame(param)`:
```

    Parameter   Component Median   CI CI_low CI_high pd log_BF Rhat  ESS
1 b_Intercept conditional  32.37 0.95  27.90   36.10  1   27.6    1 2556
2        b_wt conditional  -3.82 0.95  -4.93   -2.48  1   10.2    1 2481
3       sigma       sigma   3.45 0.95   2.64    4.87  1   17.3    1 2547
```

Which revealed that the order was specific to the pretty printing.

Now related to the BF (for bayestestR); 

- it says in the docs of `bf_models()` "se as.numeric() to extract the non-log Bayes factors; see examples), that prints nicely.", fair enough, but it would be nice to have an argument to be able to get non-log BFs from `parameters()`. 
- Also, I wonder what sentence could we add in the docs to explain why we return log BFs by default (@mattansb) ?
- Finally, in the interpretation section of the docs (of `bf_models()`), it says "A Bayes factor greater than 1 can be interpreted as evidence against the null..." Should we adjust this and specify here the distinction between raw and log BFs etc.

**Comment by mattansb** [comment]
We return log(BF) to maintain precision which is lost exp(log_BF) which was mostly important for `bayestestR::bayesfactor_models()`, and we made the change for all BFs to be consistant.

We named the column `log_BF` and not `BF_log` so that people wouldn't extract the column thinking its a BF by mistake:

``` r
d <- data.frame(BF_log = c(-3, 0, 4))

d$BF # OOPS!
#> [1] -3  0  4
```

As for printing, it always prints the BF (not log BF):

```R
m <- brms::brm(mpg ~ wt, 
  data = mtcars, 
  prior = brms::set_prior("normal(0, 1)", class = "b"), 
  backend = "cmdstanr",
  refresh = 0
)

param <- parameters::parameters(m, test = "BF")
```

The `log_BF` column has the log(BF)

```R
param$log_BF
#> [1] 23.059774  8.328669 19.753161
```

But when printing, we are looking at the BF

```R
exp(param$log_BF)
#> [1] 1.034505e+10 4.140901e+03 3.790433e+08

param
#> # Fixed effects 
#> 
#> Parameter   | Median |         95% CI |  Rhat |     ESS |       BF
#> ------------------------------------------------------------------
#> (Intercept) |  32.35 | [27.58, 36.14] | 1.000 | 2419.00 | 1.03e+10
#> wt          |  -3.81 | [-4.93, -2.37] | 1.000 | 2436.00 | 4.14e+03
#> 
#> # Fixed effects sigma
#> 
#> Parameter | Median |       95% CI |  Rhat |     ESS |       BF
#> --------------------------------------------------------------
#> sigma     |   3.46 | [2.66, 4.79] | 1.000 | 2176.00 | 3.79e+08
#> 
#> Uncertainty intervals (equal-tailed) and p-values (two-tailed) computed using a MCMC distribution approximation.

```

**Comment by DominiqueMakowski** [comment]
Aaaah riiight yes thanks a lot I'm all clear now :)

**Comment by IndrajeetPatil** [comment]
They don't call him an expert for no reason ;)

**Comment by strengejacke** [comment]
@DominiqueMakowski Help is coming (https://github.com/easystats/datawizard/pull/286):

``` r
out <- data.frame(
  Parameter = "Test",
  Median = 0.5,
  CI_low = 0.4,
  CI_high = 0.6,
  pd = .97,
  Rhat = .99,
  ESS = 1000,
  log_BF = 3
)

# close match
datawizard::data_relocate(out, "pd", before = "BF")
#> Error: The column passed to `before` wasn't found. Did you mean "log_BF"?

# close multiple matches
datawizard::data_relocate(out, "pd", before = "CIl")
#> Error: The column passed to `before` wasn't found. Did you mean one of "CI_low"
#>   or "CI_high"?

# not even close
datawizard::data_relocate(out, "pd", before = "xyz")
#> Error: The column passed to `before` wasn't found. Possibly mispelled.
```

<sup>Created on 2022-10-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
I'm not sure this works well when we ignore case:

``` r
colnames(iris)
#> [1] "Sepal.Length" "Sepal.Width"  "Petal.Length" "Petal.Width"  "Species"
p <- sprintf("(%s){~%i}", "Spela", 2)
grep(pattern = p, x = colnames(iris), ignore.case = FALSE)
#> [1] 1 2 5


colnames(iris)
#> [1] "Sepal.Length" "Sepal.Width"  "Petal.Length" "Petal.Width"  "Species"
p <- sprintf("(%s){~%i}", tolower("Spela"), 2)
grep(pattern = p, x = tolower(colnames(iris)), ignore.case = FALSE)
#> [1] 1 2 3 4 5
```

<sup>Created on 2022-10-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
Well, it depends:

``` r
out <- data.frame(
  Parameter = "Test",
  Median = 0.5,
  CI_low = 0.4,
  CI_high = 0.6,
  pd = .97,
  Rhat = .99,
  ESS = 1000,
  log_BF = 3
)

p <- sprintf("(%s){~%i}", "BF", 1)
grep(pattern = p, x = colnames(out), ignore.case = FALSE)
#> [1] 8

p <- sprintf("(%s){~%i}", tolower("BF"), 1)
grep(pattern = p, x = colnames(out), ignore.case = TRUE)
#> [1] 8



p <- sprintf("(%s){~%i}", "CIl", 1)
grep(pattern = p, x = colnames(out), ignore.case = FALSE)
#> [1] 3 4

p <- sprintf("(%s){~%i}", tolower("CIl"), 1)
grep(pattern = p, x = colnames(out), ignore.case = TRUE)
#> [1] 3 4



p <- sprintf("(%s){~%i}", "Spela", 2)
grep(pattern = p, x = colnames(iris), ignore.case = FALSE)
#> [1] 1 2 5

p <- sprintf("(%s){~%i}", "Spela", 2)
grep(pattern = p, x = colnames(iris), ignore.case = TRUE)
#> [1] 1 2 3 4 5
```

<sup>Created on 2022-10-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

For `Spela`, there are more matches because of the lower "p" in the pattern and colnames `Petal.Width` and `Petal.Length`.

**Comment by strengejacke** [comment]
> the BF position is at the end, but it'd be better to put if after pd by default (to have all test scores grouped together)

Currently, in `insight::standardize_column_order.parameters_model()`, BFs are assigned to the group of "p-values", hence they are put at the end. We could change this, what do you think? We can then close this issue after deciding on this one.

**Comment by mattansb** [comment]
What group is `pd` assigned to?

**Comment by strengejacke** [comment]
Uncertainty: https://github.com/easystats/insight/blob/main/R/standardize_column_order.R

Maybe this assignment is just a rather quick'n'dirty one for now, we probably should revisit it again.

**Comment by bwiernik** [comment]
> "pd", "ROPE_CI", "ROPE_low", "ROPE_high", "ROPE_Percentage", "Rhat", "ESS",

I think pd and the ROPE values should go into the p value group. Rhat and ESS should go in the other details group with Alternative and N
