### ISSUE TITLE
`model_parameters`: very slow `deparse` when called from `do.call`

### ISSUE THREAD

**Issue by vincentarelbundock** [easystats/parameters#798]
It seems important to be able to use `parameters` programmatically because it is a “backend” package used by other packages. Unfortunately, it is currently *much* slower when we use `do.call` than when we call `model_parameters` directly. This is because of the many `deparse(substitute(model))` calls in most `model_parameters` functions. Example:

``` r
library(tictoc)
library(parameters)

mtcars_big <- do.call("rbind", lapply(1:10000,  \(x) mtcars))

reg <- lm(mpg ~ cyl, data = mtcars_big)

tic()
tmp <- model_parameters(model = reg)
toc()
#> 0.051 sec elapsed

fun <- model_parameters
arg <- list(model = reg)

tic()
tmp <- do.call("fun", arg)
toc()
#> 2.728 sec elapsed
```

One option, would be to change this:

``` r
attr(out, "object_name") <- deparse(substitute(model), width.cutoff = 500)
```

To something like this:

``` r
modsub <- substitute(model)
if (is.name(modsub)) attr(out, "object_name") <- deparse(modsub, width.cutoff = 500)
```

However, there are lots and lots of these calls throughout the package.

Another option would be to enhance the `insight::safe_deparse` function, perhaps with a `name_only` argument. But that would require changes in two packages.

Yet another option would be to define:

``` r
safe_deparse_substitute <- function(x) {
  xsub <- substitute(x)
  if (is.name(xsub)) {
    out <- insight::safe_deparse(xsub)
  } else {
    out <- NULL
  }
  return(out)
}
```

Would that work in practice? Not sure…

What do you think?

**Comment by vincentarelbundock** [comment]
FYI, I just did a simple test and the `safe_deparse_substitute` function appears to work. So that's one reasonable-seeming option.

**Comment by vincentarelbundock** [comment]
Another note: this scales in the size of the model, because we try to convert the whole model object (including large data) into a string, which is obviously a very long string when the dataset is large.

**Comment by bwiernik** [comment]
Yeah a more efficient approach than do.call() seem like it would be great here

**Comment by strengejacke** [comment]
Are there any alternatives to `substitute()`? Like `quote()` or something, or something how we get the call inside the function?

**Comment by strengejacke** [comment]
Can you install latest _insight_ and _parameters_ from GitHub main and then re-run your benchmarks? These versions should be available soon from r-universe, and can be easily installed for user with `easystats::install_latest()`.

**Comment by strengejacke** [comment]
``` r
library(parameters)
mtcars_big <- do.call("rbind", lapply(1:10000,  \(x) mtcars))

reg <- lm(mpg ~ cyl, data = mtcars_big)
fun <- model_parameters
arg <- list(model = reg)

microbenchmark::microbenchmark(
  tmp <- model_parameters(model = reg),
  tmp <- do.call("fun", arg),
  times = 50
)
#> Unit: milliseconds
#>                                  expr     min       lq     mean   median
#>  tmp <- model_parameters(model = reg) 88.1542 106.4424 117.2343 114.2844
#>            tmp <- do.call("fun", arg) 86.2261 109.9457 115.0649 114.0678
#>        uq      max neval cld
#>  123.5720 249.4902    50   a
#>  120.3787 135.2663    50   a
```

<sup>Created on 2022-10-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by vincentarelbundock** [comment]
This is fantastic! Thanks so much.

And good catch on the `substitute(model)` location.
