### ISSUE TITLE
Potential Misspecification of Mixed Models Random Effects Standard Deviation

### ISSUE THREAD

**Issue by benediktclaus** [easystats/parameters#800]
When estimating a mixed model with `lme4` and extracting group-wise random effects estimates, `model_parameters()` includes a column for the standard error _SE_.

``` r
library(parameters)
library(lme4)
#> Lade nötiges Paket: Matrix

data(mtcars)
model <- lmer(mpg ~ wt + (wt | gear), data = mtcars)
model_parameters(model, effects = "random", group_level = TRUE)
#> # Random Effects
#> 
#> Parameter       | Coefficient |   SE |          95% CI
#> ------------------------------------------------------
#> (Intercept) [3] |       -7.60 | 2.78 | [-13.06, -2.15]
#> (Intercept) [4] |        5.84 | 2.55 | [  0.84, 10.84]
#> (Intercept) [5] |        1.76 | 3.31 | [ -4.72,  8.25]
#> wt [3]          |        2.21 | 0.73 | [  0.77,  3.64]
#> wt [4]          |       -1.54 | 0.84 | [ -3.19,  0.11]
#> wt [5]          |       -0.67 | 1.03 | [ -2.68,  1.35]
#> 
#> Uncertainty intervals (equal-tailed) and p-values (two-tailed) computed
#>   using a Wald t-distribution approximation.
```

<sup>Created on 2022-10-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I dug a little deeper into that issue and discovered that these values are obtained with `lme4`'s function `ranef()`. In the [documentation of that function](https://rdrr.io/cran/lme4/man/ranef.html) it says that the measure of dispersion is the "conditional standard deviation" (condsd). Should this be renamed?

**Comment by bbolker** [comment]
I think it depends on how picky you're being. Doug Bates would certainly never call them standard errors. I guess the question would be how liable people are to do things like start calculating p-values (which I would **not** recommend). How hard would it be to add an additional note (below the note about Wald intervals) to mention the fact that the SE and CI columns represent the conditional SD and the quantiles of the conditional distribution?

**Comment by bwiernik** [comment]
These are standard errors in that they reflect the uncertainty in the estimated random effect. The conditional variance-covariance matrix of the random effects is analogous to the variance-covariance matrix of a set of regression coefficients. 

The phrasing as the "conditional SD" reflects Doug Bates' philosophical position that these are _predictions_, not _estimates_. But the interpretation is the same. Notice that glmmTMB calls them SEs, and brms and company call them "Estimated Error". 

For consistency and ease of use by users, we should keep the SE label

**Comment by strengejacke** [comment]
I just realized that we still show a note about p-values, which actually only refers to the fixed effects part. The CIs for the random effects are actually based on normal-distribution (i.e. `qnorm(.975) * SE`), as stated in the documentation.

**Comment by benediktclaus** [comment]
Great, thanks for the clarification!
