### ISSUE TITLE
Separate CI footnotes for fixed and random components

### ISSUE THREAD

**Issue by bwiernik** [easystats/parameters#801]
I just realized that we still show a note about p-values, which actually only refers to the fixed effects part. The CIs for the random effects are actually based on normal-distribution (i.e. `qnorm(.975) * SE`), as stated in the documentation.

__Originally posted by @strengejacke in https://github.com/easystats/parameters/issues/800#issuecomment-1276258642__

**Comment by strengejacke** [comment]
Is (partly) done in this commit: https://github.com/easystats/parameters/commit/c973a602813da021b22af0e17f46a18681271aa6
