### ISSUE TITLE
applying parameters to models fitted with jags

### ISSUE THREAD

**Issue by NielsSkovgaard-Olsen** [easystats/parameters#819]
Hi!

I can see from the following page that data.frames of posterior draws and mcmc.lists are supported by model_parameters();

https://easystats.github.io/parameters/reference/model_parameters.stanreg.html

However, when I try to apply parameters() to models fitted with either R2jags or runjags, I keep receiving error messages.

To illustrate, suppose **jags1** is an object of the class **run.jags**, then neither of the commands below works:

`model_parameters(jags1, as_draws = TRUE, verbose = TRUE)`

Calculating summary statistics...
Note: The monitored variable 'p2' appears to be non-stochastic; it will
not be included in the convergence diagnostic
Note: The monitored variables 'p1', 'S2S4_mean_diff' and
'S3S4_mean_diff' appear to be stochastic in one chain but
non-stochastic in another chain; they will not be included in the
convergence diagnostic
Calculating the Gelman-Rubin statistic for 3372 variables....
Note: Unable to calculate the multivariate psrf

Error message:
"Error: Sorry, `model_parameters()` failed with the following error (possible
  class `runjags` not supported):

  $ operator is invalid for atomic vectors"

`model_parameters(jags1, as_draws = FALSE, verbose = TRUE)`

Calculating summary statistics...
Note: The monitored variable 'p2' appears to be non-stochastic; it will
not be included in the convergence diagnostic
Note: The monitored variables 'p1', 'S2S4_mean_diff' and
'S3S4_mean_diff' appear to be stochastic in one chain but
non-stochastic in another chain; they will not be included in the
convergence diagnostic
Calculating the Gelman-Rubin statistic for 3372 variables....
Note: Unable to calculate the multivariate psrf
Error: Sorry, `model_parameters()` failed with the following error (possible
  class `runjags` not supported):

  $ operator is invalid for atomic vectors

`m <- model_parameters(jags1, as_draws = FALSE, verbose = TRUE)`

Calculating summary statistics...
Note: The monitored variable 'p2' appears to be non-stochastic; it will
not be included in the convergence diagnostic
Note: The monitored variables 'p1', 'S2S4_mean_diff' and
'S3S4_mean_diff' appear to be stochastic in one chain but
non-stochastic in another chain; they will not be included in the
convergence diagnostic
Calculating the Gelman-Rubin statistic for 3372 variables....
Note: Unable to calculate the multivariate psrf

Error message:
"Error: Sorry, `model_parameters()` failed with the following error (possible
  class `runjags` not supported):

  $ operator is invalid for atomic vectors"

```
jags2.mcmc <- as.mcmc(jags1)
model_parameters(jags2.mcmc, as_draws = FALSE, verbose = TRUE)
```

NULL
Warning message:
A `data.frame` object is no valid regression model object and cannot be
  used with `model_parameters()`.

`model_parameters(jags2.mcmc, as_draws = TRUE, verbose = TRUE)`
Error: Objects of class `mcmc` are not yet supported.

```
jags2.mcmc.list <- as.mcmc.list(jags1)
model_parameters(jags2.mcmc.list, as_draws = FALSE, verbose = TRUE)
```

NULL
Warning message:
A `data.frame` object is no valid regression model object and cannot be
  used with `model_parameters()`.

`model_parameters(jags2.mcmc.list, as_draws = TRUE, verbose = TRUE)`
Error: Objects of class `mcmc.list` are not yet supported.

Thanks in advance!

**Comment by IndrajeetPatil** [comment]
Hi, thanks for reporting.

Currently, JAGS models aren't supported because none of us have much experience working with them (cf. https://github.com/easystats/insight/issues/161).

You can check out [broom.mixed](https://cran.r-project.org/web/packages/broom.mixed/index.html) package, which does support the models you are using.
