### ISSUE TITLE
Feature request - ability to save printed output of model_parameters to dataframe

### ISSUE THREAD

**Issue by rbcavanaugh** [easystats/parameters#829]
Hi - 

Thanks for a great package. I would love to be able to save the (printed) output of functions like model_parameters() to a tibble/dataframe so I can do things like put it right in a word document using flexible and never have to manually touch my tables before manuscript submission. At the moment, I manually format each table, but the print method of model_parameters is nearly perfect. Is there a way to save the output to a dataframe? Apologies if this is the wrong place for this sort of question/request. Example:

![image](https://user-images.githubusercontent.com/46727239/211960650-cc87b975-af87-4cb4-bbf2-57a81413c2e0.png)

**Comment by vincentarelbundock** [comment]
Have you tried this?

```r
as.data.frame(model_parameters(model))
```

**Comment by vincentarelbundock** [comment]
Yeah, `format_table()` is very cool, but you might be better off with a dedicated package for that. Maybe `modelsummary` or `sjPlot`:

https://vincentarelbundock.github.io/modelsummary/

https://strengejacke.github.io/sjPlot/

Both use `parameters` under the hood to extract information from model objects, but they offer a ton more options to customize the look and structure, and can also save tables directly to Microsoft Word files if that is your ultimate target.

**Comment by DominiqueMakowski** [comment]
Take a look at [export_table()](https://easystats.github.io/insight/articles/export.html) as well to export it in markdown

**Comment by mattansb** [comment]
The `format()` function does just this:

``` r
library(parameters)
#> Warning: package 'parameters' was built under R version 4.2.2

m <- lm(mpg ~ factor(cyl), mtcars)

(pars <- model_parameters(m))
#> Parameter   | Coefficient |   SE |          95% CI | t(29) |      p
#> -------------------------------------------------------------------
#> (Intercept) |       26.66 | 0.97 | [ 24.68, 28.65] | 27.44 | < .001
#> cyl [6]     |       -6.92 | 1.56 | [-10.11, -3.73] | -4.44 | < .001
#> cyl [8]     |      -11.56 | 1.30 | [-14.22, -8.91] | -8.90 | < .001
#> 
#> Uncertainty intervals (equal-tailed) and p-values (two-tailed) computed
#>   using a Wald t-distribution approximation.

format(pars)
#>     Parameter Coefficient   SE        95% CI t(29)      p
#> 1 (Intercept)       26.66 0.97  24.68, 28.65 27.44 < .001
#> 2     cyl [6]       -6.92 1.56 -10.11, -3.73 -4.44 < .001
#> 3     cyl [8]      -11.56 1.30 -14.22, -8.91 -8.90 < .001
```

<sup>Created on 2023-01-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
There are two vignettes for formatting (https://easystats.github.io/parameters/articles/model_parameters_formatting.html) and printing (https://easystats.github.io/parameters/articles/model_parameters_print.html). If you don't need automated reports (rmarkdown), I usually export to HTML and then copy/paste to Word. You can do this with:

```r
model_parameters() |> print_html()
```

This also works for those tables described in the vignette and is the easiest way to get formatted tables. More flexible and comprehensive in terms of summary tables is the _modelsummary_ package, which, afaik, also directly exports tables to word documents. I bet if you try out _modelsummary_ or some of _parameter_'s HTML printing options, you'll get what you want.

[https://vincentarelbundock.github.io/modelsummary/index.html](this vignette) also mentions some more packages at the bottom.

**Comment by rbcavanaugh** [comment]
Hugely helpful thanks. I'm really trying to avoid any manual copy-paste so that my research pipeline is fully reproducible (the journals I typically submit to want APA-formatted word docs). I missed some of the other functions in the parameters vignette that I think complete the pipeline for me - creating an empty word doc with the correct styles and adding tables via flextable from a correctly formatted tibble does the trick.

**Comment by rbcavanaugh** [comment]
> The `format()` function does just this:
> 
> ```r
> library(parameters)
> #> Warning: package 'parameters' was built under R version 4.2.2
> 
> m <- lm(mpg ~ factor(cyl), mtcars)
> 
> (pars <- model_parameters(m))
> #> Parameter   | Coefficient |   SE |          95% CI | t(29) |      p
> #> -------------------------------------------------------------------
> #> (Intercept) |       26.66 | 0.97 | [ 24.68, 28.65] | 27.44 | < .001
> #> cyl [6]     |       -6.92 | 1.56 | [-10.11, -3.73] | -4.44 | < .001
> #> cyl [8]     |      -11.56 | 1.30 | [-14.22, -8.91] | -8.90 | < .001
> #> 
> #> Uncertainty intervals (equal-tailed) and p-values (two-tailed) computed
> #>   using a Wald t-distribution approximation.
> 
> format(pars)
> #>     Parameter Coefficient   SE        95% CI t(29)      p
> #> 1 (Intercept)       26.66 0.97  24.68, 28.65 27.44 < .001
> #> 2     cyl [6]       -6.92 1.56 -10.11, -3.73 -4.44 < .001
> #> 3     cyl [8]      -11.56 1.30 -14.22, -8.91 -8.90 < .001
> ```
> 
> Created on 2023-01-12 with [reprex v2.0.2](https://reprex.tidyverse.org)

Thank you this is just what I was looking for! Thanks everyone else for the suggestions as well.
