### ISSUE TITLE
Omega squared and eta squared for repeated measures ANOVAs

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#84]
ressources:
- https://rdrr.io/github/doomlab/MOTE/man/omega.partial.SS.rm.html
- https://www.aggieerin.com/shiny-server/tests/omegaprmss.html
- https://www.researchgate.net/post/How_can_I_calculate_the_effect_size_in_a_repeated_measures_ANOVA

**Comment by mattansb** [comment]
generally:
```
pes = Fval * df1 / (Fval * df1 + df2)
# or
pes = tval^2 / (tval^2 + df2)
```
This is mathematically true for any anova / regression analysis, but it is also used in LMM (etc) as an 
approximated effect size (with a reference to *Rosenthal, R., & Rosnow, R. L. (2008). Essentials of behavioral research: Methods and data analysis.*).
**Note** that this is only for *partial* eta square.

---
While I'm at it, can `.ci_partial_eta_squared` be exported?

**Comment by DominiqueMakowski** [comment]
while you're at it, do you wanna give a hand in implementing the support of rm Anovas lol?

Id say it feels simpler to provide it with the eta 2 rather than exporting this particular internal no?

**Comment by mattansb** [comment]
> while you're at it, do you wanna give a hand in implementing the support of rm Anovas 😁 ?

Not really 😅... but maybe something like this? (super ugly.....)
```R
eta_squared.aovlist <- function(model, partial = TRUE, ci = NULL, iterations = 1000) {
  if (isFALSE(partial))
    warning("Currently only supports partial eta squared for repeated-measures ANOVAs.")
  
  res <- .extract_parameters_anova(model)
  x <- split(res,res$Group)
  x <- lapply(x, function(df) {
    df$df2 <- df$df[df$Parameter=="Residuals"]
    df$Eta_Sq_partial <- df$`F` * df$df / (df$`F` * df$df + df$df2)
    df
  })
  x <- do.call(rbind,x)
  rownames(x) <- NULL
  x[,c("Parameter","Eta_Sq_partial")]
}
```

Need to add support here for `ci`, not sure how to go about that...

It could be good to export `.ci_partial_eta_squared` for use with unsupported models etc...

**Comment by DominiqueMakowski** [comment]
> for use with unsupported models

"unsupported models"? what are you talking about 😅 

It's better to focus for V2 on extending the support (all packages are *in the end* supposed to support all models supported by insight (hence the existence of insight ^^)) than to externalize some pieces :)

As for the code, do add it! Some ugly, untested code is always better than no code imo it increases the motivation to improve when there is a basis compared starting from scratch

**Comment by mattansb** [comment]
``` r
library(parameters)


iris$Sepal.Big <- ifelse(iris$Sepal.Width >= 3, "Yes", "No")
model <- aov(Sepal.Length ~ Sepal.Big + Error(Species), data = iris)

eta_squared(model, ci = 0.95)
#>   Parameter Eta_Sq_partial    CI_low   CI_high
#> 1 Sepal.Big      0.4472423 0.0000000 0.7502341
#> 2 Residuals             NA        NA        NA
#> 3 Sepal.Big      0.1217329 0.0394255 0.2230279
#> 4 Residuals             NA        NA        NA



library(lme4)
#> Loading required package: Matrix
model <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy)

eta_squared(model, ci = 0.95)
#>   Parameter Eta_Sq_partial    CI_low  CI_high
#> 1      Days      0.7295385 0.4238465 0.832514
```

<sup>Created on 2019-08-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

![](https://media.tenor.com/images/c4ce38cc366f3fb597ac142ef78c019f/tenor.gif)

**Comment by DominiqueMakowski** [comment]
![](https://media.giphy.com/media/ZOStzpF9H5syI/giphy.gif)

**Comment by DominiqueMakowski** [comment]
Does this work when you run it on anova(themixedmodel)?

**Comment by mattansb** [comment]
Hmmm not sure. Will check tomorrow - if so, will somewhat de-uglify my
super ugly code (: will update.

--
Mattan S. Ben-Shachar, PhD student
Department of Psychology & Zlotowski Center for Neuroscience
Ben-Gurion University of the Negev
The Developmental ERP Lab

**Comment by mattansb** [comment]
It does not work with `anova(themixedmodel)` - not sure why though :/

**Comment by DominiqueMakowski** [comment]
closing in favour of #110
