### ISSUE TITLE
parameters(): `performance=TRUE` arg as alias for `summary`

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#898]
I find the name `summary` slightly confusing and sub-accurate. Maybe to be more explicit and in line with our package structure, we could `performance` as an alias? `parameters(m, summary=FALSE, performance=summary)` 

That would make the call `parameters(m, performance=TRUE)` more obvious that it calls the performance package features?

**Comment by bwiernik** [comment]
What does performance/summary actually do?

**Comment by strengejacke** [comment]
Since we're approaching stable releases, we should decide on this soon.

**Comment by DominiqueMakowski** [comment]
assuming the current `summary` gives model info, and *not* performance indices, then I'd rename as `info=TRUE` (the idea is that this kind of its related to `model_info()`, and have a separate `performance` arg eventually). If the current summary does also output performance indices, then I stand by my `performance=TRUE`

**Comment by strengejacke** [comment]
I think including performance-measures is something we should actually do here:
https://github.com/easystats/report/issues/65

I think we can rename into `info` or `model_info`.

**Comment by DominiqueMakowski** [comment]
> I think including performance-measures is something we should actually do here

100% agreed 

> I think we can rename into info

I think `info` (or `add_info` / `include_info`) is good enough
