### ISSUE TITLE
Coloured coefs

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#9]
The more I am thinking about it the more I think it would be awesome having a coloured parameters table, in particular, green/red for the estimate depending on the direction... it would become much more readable, 

@strengejacke you mentioned that such colour printing inspired by crayon was easy to implement... do you have any code snippet/example so I could experiment with it?

**Comment by strengejacke** [comment]
First, we need to check if the console supports colored output. We could probably use the code from crayon:

```r
supports_color <- function () 
{
  enabled <- getOption("crayon.enabled")
  if (!is.null(enabled)) {
    return(isTRUE(enabled))
  }
  if (rstudio_with_ansi_support() && sink.number() == 0) {
    return(TRUE)
  }
  if (!isatty(stdout())) {
    return(FALSE)
  }
  if (os_type() == "windows") {
    if (Sys.getenv("ConEmuANSI") == "ON") {
      return(TRUE)
    }
    if (Sys.getenv("CMDER_ROOT") != "") {
      return(TRUE)
    }
    return(FALSE)
  }
  if (inside_emacs() && !is.na(emacs_version()[1]) && emacs_version()[1] >= 
    23) {
    return(TRUE)
  }
  if ("COLORTERM" %in% names(Sys.getenv())) {
    return(TRUE)
  }
  if (Sys.getenv("TERM") == "dumb") {
    return(FALSE)
  }
  grepl("^screen|^xterm|^vt100|color|ansi|cygwin|linux", Sys.getenv("TERM"), 
    ignore.case = TRUE, perl = TRUE)
}

rstudio_with_ansi_support <- function () 
{
  if (Sys.getenv("RSTUDIO", "") == "") 
    return(FALSE)
  if ((cols <- Sys.getenv("RSTUDIO_CONSOLE_COLOR", "")) != 
    "" && !is.na(as.numeric(cols))) {
    return(TRUE)
  }
  requireNamespace("rstudioapi", quietly = TRUE) && rstudioapi::isAvailable() && 
    rstudioapi::hasFun("getConsoleHasColor")
}
```

If `supports_color()` is `TRUE`, then we need to surround the strings with the color codes. The following examples are take the string `easystats`:

blue:
`"\033[34measystats\033[39m"`

red:
`"\033[31measystats\033[39m"`

green:
`"\033[32measystats\033[39m"`

cyan:
`"\033[36measystats\033[39m"`

magenta:
`"\033[35measystats\033[39m"`

yellow:
`"\033[33measystats\033[39m"`

silver (grey):
`"\033[90measystats\033[39m"`

**Comment by strengejacke** [comment]
A function could look like this:

```r
cat_green <- function(x) {
  if (supports_color())
    x <- paste0("\033[32m", x, "\033[39m")
  x
}

**Comment by strengejacke** [comment]
Important is that this output is only coloured when it's called with `cat()`, so we might do some effort for our print-methods (or maybe it's quite easy...?)

**Comment by DominiqueMakowski** [comment]
Mmh... Then maybe leave it for report and implement in it a generic wrapper function that nicely displays the parameters table. It would avoid cluttering these packages with display related utils

**Comment by DominiqueMakowski** [comment]
![image](https://user-images.githubusercontent.com/8875533/52645225-4df47680-2f1b-11e9-8de5-7f842d83a6c1.png)


It's working 🎉 🎊

**Comment by strengejacke** [comment]
Nice! :-)
