### ISSUE TITLE
feature request: generalized eta and omega squared

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/parameters#91]
In addition to the currently implemented partial eta and omega squared, can we also support generalized versions (which are recommended for meta-analysis reporting)?

https://www.frontiersin.org/articles/10.3389/fpsyg.2013.00863/full

![image](https://user-images.githubusercontent.com/11330453/62974295-e47bf480-bde5-11e9-8152-dac4a2d2b426.png)

**Comment by DominiqueMakowski** [comment]
Sounds like a good idea, maybe @strengejacke already has some SJdrafts somewhere for that ☺️

@IndrajeetPatil would you like to give it a try?

**Comment by strengejacke** [comment]
No, unfortunately nothing related to the generalized versions (unless it's in my [esc-package](https://strengejacke.github.io/esc/), which is about effect sizes in meta-analysis.

**Comment by DominiqueMakowski** [comment]
adjusted partial eta 2:

https://twitter.com/ev_fedorenko/status/1172576676070526976?s=19

**Comment by DominiqueMakowski** [comment]
closing in favour of #110
