### ISSUE TITLE
Warn (in model_parameters) when argument is not supported by method?

### ISSUE THREAD

**Issue by LukasWallrich** [easystats/parameters#930]
I am aware that this is difficult with `...`, but I spent a lot of time today figuring out why robust standard errors worked beautifully for `lm` but then did not work as expected for `metafor` or `mira` objects. I suggested in #929 that it would be great if they could work for `mira` and would say the same for meta-analyses - but more importantly, should there be warning when arguments that sometimes work for model_parameters are passed and then not used?

As I understand the purpose of `parameters` it aims to provide a consistent interface across models - so it would seem essential that users notice easily when that interface is no longer consistent?

**Comment by strengejacke** [comment]
Thanks, informative message is now printed. This certainly applies to other models as well, we may add these warnings by and by, when found.
