### ISSUE TITLE
Parameters standardization of lme4 models: something weird is going on

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#95]
Within the standardization vignette, comparison of methods:

## No random effect

```r
model <- lm(Sepal.Length ~ Petal.Width + Group_Sepal.Width, data=data)
comparison(model)
```` 
|Parameter            | full| classic| sjstats|lm.beta |MuMIn |
|:--------------------|----:|-------:|-------:|:-------|:-----|
|(Intercept)          | 0.13|    0.13|      NA|Error   |Error |
|Petal.Width          | 0.05|    0.05|    0.05|Error   |Error |
|Group_Sepal.WidthLow | 0.00|   -0.14|   -0.14|Error   |Error |

## stan_lmer (Bayesian)

```r
model <- stan_lmer(Sepal.Length ~ Petal.Width + Group_Sepal.Width + (1|Species), data=data)
comparison(model)
```` 
|Parameter            |  full| classic| sjstats|lm.beta |MuMIn |
|:--------------------|-----:|-------:|-------:|:-------|:-----|
|(Intercept)          |  0.15|    0.15|      NA|Error   |Error |
|Petal.Width          | -0.01|   -0.01|    0.00|Error   |Error |
|Group_Sepal.WidthLow |  0.00|   -0.14|   -0.14|Error   |Error |

## lmer (lme4)

```r
model <- lme4::lmer(Sepal.Length ~ Petal.Length + Group_Sepal.Width + (1|Species), data=data)
comparison(model)
```
|Parameter            |  full| classic| sjstats|lm.beta | MuMIn|
|:--------------------|-----:|-------:|-------:|:-------|-----:|
|(Intercept)          |  0.15|    0.15|      NA|Error   |  0.15|
|Petal.Length         |  2.25|    2.25|    0.00|Error   |  0.00|
|Group_Sepal.WidthLow | -1.27|   -0.77|   -0.14|Error   | -0.14|

This is the only case where parameters performs much more worse than the others... And it seems specific to lme4... I have no idea why

**Comment by DominiqueMakowski** [comment]
For factors or numerics only, it works as expected:

> model <- lme4::lmer(Sepal.Length ~ Petal.Length + (1|Species), data=data)
> knitr::kable(comparison(model), digits=2)


|Parameter    | full| classic| sjstats|lm.beta | MuMIn|
|:------------|----:|-------:|-------:|:-------|-----:|
|(Intercept)  |    0|       0|      NA|Error   |     0|
|Petal.Length |    0|       0|       0|Error   |     0|
> model <- lme4::lmer(Sepal.Length ~ Group_Sepal.Width + (1|Species), data=data)
> knitr::kable(comparison(model), digits=2)


|Parameter            | full| classic| sjstats|lm.beta | MuMIn|
|:--------------------|----:|-------:|-------:|:-------|-----:|
|(Intercept)          |  0.3|    0.30|      NA|Error   |  0.30|
|Group_Sepal.WidthLow |  0.0|   -0.27|   -0.27|Error   | -0.27|

**Comment by DominiqueMakowski** [comment]
There is also a discrepancy between the classic method and sjstats, which should not be there. What sjstats do with lme4's interactions?

**Comment by strengejacke** [comment]
What is `Group_Petal.Width`?

**Comment by strengejacke** [comment]
I get different values for sjstats with lme4-model:

``` r
library(sjstats)
library(lme4)
#> Loading required package: Matrix

data <- iris
data$Group_Sepal.Width <- as.factor(ifelse(data$Sepal.Width > 3, "High", "Low"))
data$Binary_Sepal.Width <- as.factor(ifelse(data$Sepal.Width > 3, 1, 0))
m <- lme4::lmer(Sepal.Length ~ Petal.Length + Group_Sepal.Width + (1|Species), data=data)

sjstats::std_beta(m)
#>                   term std.estimate  std.error   conf.low   conf.high
#> 1         Petal.Length    1.7708471 0.13547093  1.5053289  2.03636521
#> 2 Group_Sepal.WidthLow   -0.1354434 0.04105623 -0.2159121 -0.05497465
```

<sup>Created on 2019-08-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DominiqueMakowski** [comment]
In the above it represents the difference with parameters' standardize "refit" method

```r
library(parameters)
library(sjstats)
library(lm.beta)
library(MuMIn)

comparison <- function(model, robust=FALSE){
  out <- parameters_standardize(model, method="refit", robust=robust)[1:2]
  
  out$full <- tryCatch({
    out[, 2] - parameters_standardize(model, method="full", robust=robust)[, 2]
}, error = function(error_condition) {
    "Error"
})
  out$classic <- tryCatch({
    out[, 2] - parameters_standardize(model, method="classic", robust=robust)[, 2]
}, error = function(error_condition) {
    "Error"
})
  out$sjstats <- tryCatch({
    if(insight::model_info(model)$is_bayesian){
      out[, 2] - c(NA, bayestestR::describe_posterior(as.data.frame(sjstats::std_beta(model)))[, 2])
    } else{
      out[, 2] - c(NA, sjstats::std_beta(model)[, 2])
    }
}, error = function(error_condition) {
    "Error"
})
  
  out$lm.beta <- tryCatch({
    out[, 2] - lm.beta::lm.beta(model)$standardized.coefficients
}, error = function(error_condition) {
    "Error"
}, warning = function(warning_condition) {
  "Error"
})
  
  out$MuMIn <- tryCatch({
    out[, 2] - MuMIn::std.coef(model, partial.sd=FALSE)[, 1]
}, error = function(error_condition) {
    "Error"
})

  out[, 2] <- NULL
  return(out)
}
```

**Comment by strengejacke** [comment]
Why is `standardize.data.frame()` called six times per standardization?

**Comment by DominiqueMakowski** [comment]
I don't know...

**Comment by strengejacke** [comment]
I think you have to revise this line:

https://github.com/easystats/parameters/blob/bb5cd8e72a7380dca2ed791a6b54c05055c78151/R/standardize.data.frame.R#L149

`x[select]` returns a df, not a vector/factor.

**Comment by DominiqueMakowski** [comment]
not sure, cause select can be a vector

**Comment by strengejacke** [comment]
ok, I think you're right... Maybe it's the way `update()` works for merMod-objects?

``` r
library(lme4)
#> Loading required package: Matrix

d <- iris
d$Group_Sepal.Width <- as.factor(ifelse(d$Sepal.Width > 3, "High", "Low"))
d$Binary_Sepal.Width <- as.factor(ifelse(d$Sepal.Width > 3, 1, 0))
m1 <- lme4::lmer(Sepal.Length ~ Petal.Length + Group_Sepal.Width + (1|Species), data=d)
m2 <- lm(Sepal.Length ~ Petal.Length + Group_Sepal.Width, data=d)

xx <- function(x) {
  print("huh")
  parameters::standardize(x)
}

stats::update(m1, data = xx(d))
#> [1] "huh"
#> [1] "huh"
#> [1] "huh"
#> [1] "huh"
#> Linear mixed model fit by REML ['lmerMod']
#> Formula: Sepal.Length ~ Petal.Length + Group_Sepal.Width + (1 | Species)
#>    Data: xx(d)
#> REML criterion at convergence: 167.1947
#> Random effects:
#>  Groups   Name        Std.Dev.
#>  Species  (Intercept) 1.0755  
#>  Residual             0.3962  
#> Number of obs: 150, groups:  Species, 3
#> Fixed Effects:
#>          (Intercept)          Petal.Length  Group_Sepal.WidthLow  
#>               0.1502                1.7708               -0.2715

stats::update(m2, data = xx(d))
#> [1] "huh"
#> 
#> Call:
#> lm(formula = Sepal.Length ~ Petal.Length + Group_Sepal.Width, 
#>     data = xx(d))
#> 
#> Coefficients:
#>          (Intercept)          Petal.Length  Group_Sepal.WidthLow  
#>               0.2598                0.9703               -0.4695
```

<sup>Created on 2019-08-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DominiqueMakowski** [comment]
I think I was unclear, what bugs me is that there is a big difference between parameters' classic method and sjstats only for lme4 models with interactions (parameters' classic method was supposed to emulate the one ob lm.beta or sjstats, which it does for *all* other models):

``` r
data <- dplyr::mutate(iris, Group_Sepal.Width = ifelse(Sepal.Width > 3, "A", "B"))

# Gold standard
parameters::parameters_standardize(lme4::lmer(Sepal.Length ~ Petal.Length + Group_Sepal.Width + (1|Species), data=data), method = "refit")
#>            Parameter Std_Coefficient
#> 1        (Intercept)       0.1502474
#> 2       Petal.Length       1.7708471
#> 3 Group_Sepal.WidthB      -0.2715314

# Sjstats' method
sjstats::std_beta(lme4::lmer(Sepal.Length ~ Petal.Length + Group_Sepal.Width + (1|Species), data=data))
#>                 term std.estimate  std.error   conf.low   conf.high
#> 1       Petal.Length    1.7708471 0.13547093  1.5053289  2.03636521
#> 2 Group_Sepal.WidthB   -0.1354434 0.04105623 -0.2159121 -0.05497465
# parameters' "classic" method, suposedly the same as sjstats
parameters::parameters_standardize(lme4::lmer(Sepal.Length ~ Petal.Length + Group_Sepal.Width + (1|Species), data=data), method = "classic")
#>            Parameter Std_Coefficient
#> 1        (Intercept)       0.0000000
#> 2 Group_Sepal.WidthB      -0.4793340
#> 3       Petal.Length       0.5003808
```

<sup>Created on 2019-08-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Which is even worse is that parameters' full method, which performs better than the alternatives for every other method, performs much worse for these models (lme4 with interactions), in comparison with the refit method (representing the "true" values). And I don't understand why

**Comment by strengejacke** [comment]
Yes, I know what you were meaning. I was just saying that it might be related to the multiple calls to `update()`. When I debugged, I got completely different data passed to `standardize.data.frame()` than what was expected. The data contained 7 columns, though it should only contain four columns.

**Comment by DominiqueMakowski** [comment]
mmmh right, but in the classic or full methods (of parameters), standardize.data.frame() should not be called as it doesn't standardize the data, but simply the parameter's coefficients 😕

**Comment by strengejacke** [comment]
But isn't the df method automatically called, because you pass the model data to `standardize()`?

**Comment by strengejacke** [comment]
I mean this line: `data` is a data frame, so `standardize.data.frame()` is always called for models, no matter what the `method`-arg is.

https://github.com/easystats/parameters/blob/bb5cd8e72a7380dca2ed791a6b54c05055c78151/R/standardize.models.R#L27

**Comment by DominiqueMakowski** [comment]
but `parameters_standardize` should not call standardize if method is not refit :confused:

**Comment by strengejacke** [comment]
ah, ok... we were talking about different methods then. 🤣

**Comment by strengejacke** [comment]
Ok, now that I know what we're talking about, debugging is easier... Maybe the issue come from the fact that `model_parameter()` and `parameters_type()` switch the coefficient order?

``` r
library(lme4)
#> Loading required package: Matrix
library(parameters)

d <- iris
d$Group_Sepal.Width <- as.factor(ifelse(d$Sepal.Width > 3, "High", "Low"))
d$Binary_Sepal.Width <- as.factor(ifelse(d$Sepal.Width > 3, 1, 0))
m1 <- lme4::lmer(Sepal.Length ~ Petal.Length + Group_Sepal.Width + (1|Species), data=d)

str(model_parameters(m1, standardize = F))
#> Classes 'parameters_model', 'see_parameters_model' and 'data.frame': 3 obs. of  7 variables:
#>  $ Parameter  : chr  "(Intercept)" "Group_Sepal.WidthLow" "Petal.Length"
#>  $ Coefficient: num  2.846 -0.225 0.831
#>  $ SE         : num  0.5727 0.0682 0.0635
#>  $ CI_low     : num  -2.732 0.216 -0.797
#>  $ CI_high    : num  8.424 -0.666 2.459
#>  $ t          : num  4.97 -3.3 13.07
#>  $ p          : num  6.71e-07 9.70e-04 4.77e-39
#>  - attr(*, "pretty_names")= Named chr  "(Intercept)" "Petal.Length" "Group_Sepal.Width (Low)"
#>   ..- attr(*, "names")= chr  "(Intercept)" "Petal.Length" "Group_Sepal.WidthLow"
#>  - attr(*, "ci")= num 0.95

str(parameters_type(m1))
#> 'data.frame':    3 obs. of  11 variables:
#>  $ Parameter          : chr  "(Intercept)" "Petal.Length" "Group_Sepal.WidthLow"
#>  $ Type               : chr  "intercept" "numeric" "factor"
#>  $ Term               : chr  "(Intercept)" "Petal.Length" "Group_Sepal.WidthLow"
#>  $ Variable           : chr  NA "Petal.Length" "Group_Sepal.Width"
#>  $ Level              : chr  NA NA "Low"
#>  $ Secondary_Parameter: chr  NA NA NA
#>  $ Secondary_Type     : logi  NA NA NA
#>  $ Secondary_Term     : logi  NA NA NA
#>  $ Secondary_Variable : logi  NA NA NA
#>  $ Secondary_Level    : logi  NA NA NA
#>  $ Tertiary_Parameter : logi  NA NA NA
```

<sup>Created on 2019-08-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
Yes, that's definitely the source. The SD for Petal.Length is calculated, but the coefficient from Group_Sepal.WidthLow is used for multiplication.

**Comment by strengejacke** [comment]
Might be fixed, but definitely needs some more thourrough checks with more complex models (more predictors).

**Comment by strengejacke** [comment]
Have I already mentioned the debug-feature in RStudio? 😁

**Comment by DominiqueMakowski** [comment]
Thanks for diving into that, in fact the bug was in model_parameters.merMod, (lost order due to merging), so good thing this is fixed before CRAN

**Comment by strengejacke** [comment]
Can we close this issue?
