### ISSUE TITLE
maybe we _do_ need to rename the `effectsize_type` argument to avoid partial matching after all

### ISSUE THREAD

**Issue by strengejacke** [easystats/parameters#978]
> @strengejacke maybe we _do_ need to rename the `effectsize_type` argument to avoid partial matching after all (https://github.com/easystats/effectsize/issues/639)...

What would be a good name for this argument? (reminder, it is passed to `effectsize(..., type)`) (which is only a valid argument for anova objects, htest objects and `BFBayesFactor` objects - ignored for all other...).

_Originally posted by @mattansb in https://github.com/easystats/parameters/issues/975#issuecomment-2147145046_

**Comment by strengejacke** [comment]
Maybe `type`?

**Comment by mattansb** [comment]
Seems too vague given the context `model_parameters(..., type = )`.

Can we abbreviate? `model_parameters(..., es_type = )` (similar to the `ci_method` argument)

**Comment by strengejacke** [comment]
yes, sounds good.

**Comment by strengejacke** [comment]
Mattan, that would mean that you need to prepare an update for _effectsize_ when _parameters_ is submitted.

**Comment by mattansb** [comment]
I'm ready (:
