### ISSUE TITLE
 [Proposal] Adding support for glmtoolbox::glmgee models

### ISSUE THREAD

**Issue by adrianolszewski** [easystats/parameters#981]
Hi!
Currently the glmtoolbox package is clearly superior for GEE estimation over the geepack one (which seems abandoned, with many issues left unfixed). But while geepack is fully supported by insight, glmtoolbox is not.

When I just passed a single model to parameters::model_parameters, I got the following message:
```
Error: Sorry, `model_parameters()` failed with the following error (possible class `glmgee` not supported):
The entered object is not a model object.
```

Would it be possible to add such support for the glmgee class (and maybe other from the glmtoolbox package)? As I said before, geepack is likely abandoned, full of bugs (crashing the entire R session), while glmtoolbox is much richer in handy tools, better documented and actively maintained.

**Comment by strengejacke** [comment]
xref: https://github.com/easystats/insight/issues/894

**Comment by strengejacke** [comment]
Is included in https://github.com/easystats/parameters/pull/977
But requires current GitHub version from _insight_, or better, once [this PR](https://github.com/easystats/insight/pull/895) is merged, it should also work in _parameters_.

**Comment by adrianolszewski** [comment]
Works perfectly, **thank you**!
