### ISSUE TITLE
remove parameters::format_table and replace by insight::format_table

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/parameters#99]
Should we go ahead and remove all instances of parameters::format_table?

**Comment by strengejacke** [comment]
I would wait for final CRAN acceptance before removing anything. It's now implemented in insight, which was updated on 24th July, so next update would be ~ end Sep/beginning Oct. Thus, I think we can remove it from the next update in _parameters_.

**Comment by DominiqueMakowski** [comment]
right. BTW, still waiting for a reply from CRAN for parameters.

**Comment by strengejacke** [comment]
insight was submitted to CRAN (required because I need to update two other packages due to changes in _tidyr_), so I have already addressed this issue. I hope you can hold out the failing travis, because insight 0.5.0 is not yet on the CRAN servers ;-)
