### ISSUE TITLE
vcovHC providing different SEs + p-values for parameters compared to coeftest when estimating a glm() model

### ISSUE THREAD

**Issue by dpmoriarity** [easystats/parameters#990]
I am re-opening this here, since this discrepancy was different than what my OP yesterday was about, figured that might help others with the same query find this easier.

The coeftest is giving different SEs and p-values than the parameters function using the vcov specification for gamma regression using glm(). Notably, this does not apply when an lm() model is used

head(iris)
test<-glm(Sepal.Length~Petal.Length+Species+Sepal.Width+Petal.Width, family = Gamma(link="log"),
          data = iris)

coeftest(test, vcov = vcovHC(test)) 

parameters(test, vcov = vcovHC(test)) #different pvalues and SEs

test2<-lm(Sepal.Length~Petal.Length+Species+Sepal.Width+Petal.Width, 
          data = iris)

coeftest(test2, vcov = vcovHC(test2)) #matches

parameters(test2, vcov = vcovHC(test2))

**Comment by strengejacke** [comment]
See https://strengejacke.github.io/sjPlot/articles/tab_model_robust.html for `tab_model()` and https://easystats.github.io/parameters/articles/model_parameters_robust.html for `model_parameters()`.

**Comment by dpmoriarity** [comment]
yes, I looked through them and tried several of the options they described and all have the same discrepancy (see below) for one alternative with more arguments but the same results. I apologize if I'm being dense, it just seemed like something to bring up here since I've seen prior threads about interactions with sandwich on this Github. But happy to have this closed if it's definitely user error and I will find a consult!

test<-glm(Sepal.Length~Petal.Length+Species+Sepal.Width+Petal.Width, family = Gamma(link="log"),
          data = iris)
          
coeftest(test, vcov = vcovHC(test, type="HC3"))
parameters(test, vcov = "HC3")#different pvalues and SEs
tab_model(test,  vcov.fun = "HC",vcov.args= list(type="HC3"),show.se = TRUE)#different pvalues and SEs

**Comment by dpmoriarity** [comment]
disregard, I'm now realizing the difference is in the coeftest functionality. sorry for the hassle, have 2 braincells left between this move and finding a flood in the basement on our arrival 

Enjoy the rest of your week!
